-- workouts_ampliacion.sql
-- 20 workouts nuevos para Blumm — pegar en SQL editor de Supabase

BEGIN;

INSERT INTO workouts (
  id, display_order, workout_type, emoji, name, description,
  duration_min, intensity, est_calories,
  phases, fitness_levels, equipment, goals, good_for, avoid_for,
  exercises, tips
) VALUES

-- ─── YOGA ────────────────────────────────────────────────────────────────────

('yoga_energizante_40', 21, 'yoga', '🌟',
 '{"es":"Yoga energizante","en":"Energizing yoga","fr":"Yoga énergisant","it":"Yoga energizzante"}',
 '{"es":"Secuencias dinámicas para activar el cuerpo y elevar la energía","en":"Dynamic sequences to activate the body and boost energy"}',
 40, 'medium', 130,
 ARRAY['follicular','ovulatory'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['energy','tone','lose_weight'],
 ARRAY['fatigue','pcos','hypothyroid','depression'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Saludo al sol A (3 rondas)"},{"dur":"3 min c/lado","name":"Guerrero I y II"},{"dur":"2 min c/lado","name":"Postura del triángulo"},{"dur":"3 min","name":"Perro boca abajo con pedaleo"},{"dur":"2 min","name":"Barco (Navasana)"},{"dur":"5 min","name":"Savasana"}],"en":[{"dur":"5 min","name":"Sun salutation A (3 rounds)"},{"dur":"3 min/side","name":"Warrior I and II"},{"dur":"2 min/side","name":"Triangle pose"},{"dur":"3 min","name":"Downward dog with pedaling"},{"dur":"2 min","name":"Boat pose (Navasana)"},{"dur":"5 min","name":"Savasana"}]}',
 '{"es":["Sincroniza el movimiento con la respiración","Muévete con intención, no con prisa","Hidratate bien antes y después"],"en":["Sync movement with breath","Move with intention, not speed","Hydrate well before and after"]}'),

('yoga_luteal_35', 22, 'yoga', '🌙',
 '{"es":"Yoga fase lútea","en":"Luteal phase yoga","fr":"Yoga phase lutéale","it":"Yoga fase luteale"}',
 '{"es":"Posturas suaves y restauradoras para acompañar la fase lútea y calmar el sistema nervioso","en":"Gentle restorative poses to support the luteal phase and calm the nervous system"}',
 35, 'low', 90,
 ARRAY['luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['reduce_symptoms','energy','stress'],
 ARRAY['pmdd','endometriosis','adenomyosis','anxiety','pms'],
 ARRAY[]::text[],
 '{"es":[{"dur":"4 min","name":"Postura del gato-vaca (Cat-Cow)"},{"dur":"3 min c/lado","name":"Media luna reclinada"},{"dur":"5 min","name":"Paloma suave"},{"dur":"4 min","name":"Torsión reclinada"},{"dur":"4 min","name":"Mariposa reclinada"},{"dur":"8 min","name":"Savasana con bolster"}],"en":[{"dur":"4 min","name":"Cat-cow flow"},{"dur":"3 min/side","name":"Reclined half moon"},{"dur":"5 min","name":"Gentle pigeon pose"},{"dur":"4 min","name":"Reclined spinal twist"},{"dur":"4 min","name":"Reclined butterfly"},{"dur":"8 min","name":"Supported savasana"}]}',
 '{"es":["Evita las inversiones en fase lútea tardía","Respira lento: 5 seg inhalación, 7 espiración","Si tienes retención usa música suave de fondo"],"en":["Avoid inversions in late luteal phase","Breathe slowly: 5s inhale, 7s exhale","Play soft background music if you feel bloated"]}'),

('yin_yoga_45', 23, 'yoga', '🕯️',
 '{"es":"Yin yoga","en":"Yin yoga","fr":"Yin yoga","it":"Yin yoga"}',
 '{"es":"Posturas pasivas de larga duración para soltar tejido conectivo y calmar el sistema nervioso","en":"Long-held passive poses to release connective tissue and calm the nervous system"}',
 45, 'low', 80,
 ARRAY['menstrual','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['reduce_symptoms','stress','rehab'],
 ARRAY['endometriosis','pmdd','adenomyosis','fibromyalgia','anxiety','chronic_pain'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Mariposa (Baddha Konasana)"},{"dur":"5 min c/lado","name":"Dragón (estiramiento psoas)"},{"dur":"5 min c/lado","name":"Cuadrado (variación paloma)"},{"dur":"5 min","name":"Oruga (flexión sentada)"},{"dur":"5 min","name":"Torsión supina c/lado"},{"dur":"5 min","name":"Savasana profunda"}],"en":[{"dur":"5 min","name":"Butterfly (Baddha Konasana)"},{"dur":"5 min/side","name":"Dragon (psoas stretch)"},{"dur":"5 min/side","name":"Square pose (pigeon variation)"},{"dur":"5 min","name":"Caterpillar (seated forward fold)"},{"dur":"5 min","name":"Supine twist each side"},{"dur":"5 min","name":"Deep savasana"}]}',
 '{"es":["Aguanta el discomfort sin llegar al dolor","No entres y salgas de las posturas con prisa","El yin trabaja con tejido conectivo, no con músculo"],"en":["Stay in discomfort without reaching pain","Enter and exit poses slowly","Yin targets connective tissue, not muscle"]}'),

('yoga_hormonal_40', 24, 'yoga', '🌸',
 '{"es":"Yoga hormonal","en":"Hormonal yoga","fr":"Yoga hormonal","it":"Yoga ormonale"}',
 '{"es":"Secuencia diseñada para estimular el sistema endocrino y equilibrar hormonas naturalmente","en":"Sequence designed to stimulate the endocrine system and naturally balance hormones"}',
 40, 'low', 100,
 ARRAY['luteal','menstrual','follicular'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['reduce_symptoms','energy','balance'],
 ARRAY['pcos','hypothyroid','endometriosis','pmdd','amenorrhea'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Respiración kapalabhati suave (10 rondas)"},{"dur":"5 min","name":"Torsión abdominal sentada"},{"dur":"5 min","name":"Cobra (Bhujangasana)"},{"dur":"5 min c/lado","name":"Guerrero III con giro"},{"dur":"5 min","name":"Puente de hombros (Setu Bandhasana)"},{"dur":"5 min","name":"Pez (Matsyasana)"},{"dur":"5 min","name":"Savasana con visualización"}],"en":[{"dur":"5 min","name":"Gentle kapalabhati breathing (10 rounds)"},{"dur":"5 min","name":"Seated abdominal twist"},{"dur":"5 min","name":"Cobra (Bhujangasana)"},{"dur":"5 min/side","name":"Warrior III with twist"},{"dur":"5 min","name":"Bridge pose (Setu Bandhasana)"},{"dur":"5 min","name":"Fish pose (Matsyasana)"},{"dur":"5 min","name":"Savasana with visualization"}]}',
 '{"es":["Practica en ayunas o 2h después de comer","Constancia diaria durante 3 meses para ver cambios hormonales","Consulta a tu médico si tienes SOP severo o tiroides medicada"],"en":["Practice fasted or 2h after eating","Daily consistency for 3 months to see hormonal changes","Consult your doctor if you have severe PCOS or medicated thyroid"]}'),

-- ─── PILATES ─────────────────────────────────────────────────────────────────

('pilates_suelo_40', 25, 'pilates', '🎯',
 '{"es":"Pilates de suelo","en":"Mat pilates","fr":"Pilates au sol","it":"Pilates a terra"}',
 '{"es":"Trabajo de core, control y alineación en esterilla para todas las fases del ciclo","en":"Core work, control and alignment on the mat for all cycle phases"}',
 40, 'medium', 140,
 ARRAY['follicular','ovulatory','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['tone','posture','rehab'],
 ARRAY['back_pain','diastasis','pcos','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"3 min","name":"Respiración lateral y activación de core"},{"dur":"5 min","name":"Cien (The Hundred)"},{"dur":"5 min","name":"Rolling like a ball"},{"dur":"5 min c/lado","name":"Serie de pierna única"},{"dur":"5 min","name":"Tijeras y bicicleta"},{"dur":"4 min","name":"Side kick series"},{"dur":"3 min","name":"Natación (Swimming)"}],"en":[{"dur":"3 min","name":"Lateral breathing and core activation"},{"dur":"5 min","name":"The Hundred"},{"dur":"5 min","name":"Rolling like a ball"},{"dur":"5 min/side","name":"Single leg series"},{"dur":"5 min","name":"Scissors and bicycle"},{"dur":"4 min","name":"Side kick series"},{"dur":"3 min","name":"Swimming"}]}',
 '{"es":["Activa el suelo pélvico antes de cada ejercicio","Mantén la columna neutra salvo que el ejercicio exija lo contrario","Calidad de movimiento por encima de cantidad"],"en":["Activate the pelvic floor before each exercise","Keep neutral spine unless the movement requires otherwise","Quality over quantity in every rep"]}'),

('pilates_postparto_30', 26, 'pilates', '🤱',
 '{"es":"Pilates postparto","en":"Postnatal pilates","fr":"Pilates postnatal","it":"Pilates postnatale"}',
 '{"es":"Recuperación progresiva del suelo pélvico y el core tras el parto","en":"Progressive recovery of pelvic floor and core after childbirth"}',
 30, 'low', 90,
 ARRAY['menstrual','follicular','luteal'],
 ARRAY['sedentary','occasional','regular'],
 ARRAY['home'],
 ARRAY['rehab','tone','energy'],
 ARRAY['postpartum','diastasis','back_pain','incontinence'],
 ARRAY['pregnant'],
 '{"es":[{"dur":"5 min","name":"Respiración diafragmática y suelo pélvico"},{"dur":"5 min","name":"Puente de glúteos con kegel"},{"dur":"5 min","name":"Elevación de pierna en cuadrupedia"},{"dur":"5 min","name":"Plancha modificada en rodillas"},{"dur":"5 min","name":"Curl abdominal progresivo"},{"dur":"5 min","name":"Estiramiento de caderas y columna"}],"en":[{"dur":"5 min","name":"Diaphragmatic breathing and pelvic floor"},{"dur":"5 min","name":"Glute bridge with kegel"},{"dur":"5 min","name":"Quadruped leg raise"},{"dur":"5 min","name":"Modified knee plank"},{"dur":"5 min","name":"Progressive abdominal curl"},{"dur":"5 min","name":"Hip and spine stretch"}]}',
 '{"es":["Consulta a tu matrona antes de empezar","Para si sientes presión hacia abajo o pérdidas","Avanza despacio: el suelo pélvico marca el ritmo"],"en":["Check with your midwife before starting","Stop if you feel downward pressure or leaking","Progress slowly: the pelvic floor sets the pace"]}'),

-- ─── MOBILITY ────────────────────────────────────────────────────────────────

('movilidad_caderas_25', 27, 'mobility', '🦵',
 '{"es":"Movilidad de caderas","en":"Hip mobility","fr":"Mobilité des hanches","it":"Mobilità delle anche"}',
 '{"es":"Trabajo específico de apertura y movilidad de caderas para aliviar tensión pélvica","en":"Targeted hip opening and mobility to relieve pelvic tension"}',
 25, 'low', 65,
 ARRAY['menstrual','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['reduce_symptoms','rehab','posture'],
 ARRAY['endometriosis','dysmenorrhea','back_pain','adenomyosis','pcos'],
 ARRAY[]::text[],
 '{"es":[{"dur":"3 min c/lado","name":"90-90 estiramiento de caderas"},{"dur":"3 min c/lado","name":"Paloma en el suelo"},{"dur":"2 min","name":"Mariposa activa"},{"dur":"2 min c/lado","name":"Zancada baja con rotación"},{"dur":"3 min","name":"Círculos de cadera en cuadrupedia"},{"dur":"3 min","name":"Happy baby (Ananda Balasana)"}],"en":[{"dur":"3 min/side","name":"90-90 hip stretch"},{"dur":"3 min/side","name":"Floor pigeon"},{"dur":"2 min","name":"Active butterfly"},{"dur":"2 min/side","name":"Low lunge with rotation"},{"dur":"3 min","name":"Quadruped hip circles"},{"dur":"3 min","name":"Happy baby (Ananda Balasana)"}]}',
 '{"es":["Respira en cada postura para liberar tensión","No fuerces la apertura, déjate caer con la gravedad","Ideal antes de dormir en días de dolor menstrual"],"en":["Breathe into each pose to release tension","Don''t force the opening, let gravity do the work","Ideal before sleep on days of menstrual pain"]}'),

('movilidad_hombros_20', 28, 'mobility', '🙆',
 '{"es":"Movilidad de hombros y cuello","en":"Shoulder and neck mobility","fr":"Mobilité épaules et nuque","it":"Mobilità spalle e collo"}',
 '{"es":"Liberación de tensión cervical y escapular acumulada por estrés o trabajo sedentario","en":"Release of cervical and scapular tension from stress or sedentary work"}',
 20, 'low', 50,
 ARRAY['menstrual','follicular','ovulatory','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['stress','posture','rehab','energy'],
 ARRAY['neck_pain','fibromyalgia','anxiety','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"3 min","name":"Rotaciones lentas de cuello"},{"dur":"3 min","name":"Círculos de hombro y elevaciones"},{"dur":"3 min c/lado","name":"Estiramiento del trapecio sentada"},{"dur":"3 min","name":"Apertura de pecho con manos entrelazadas"},{"dur":"2 min c/lado","name":"Agujas enhebradas (Thread the needle)"},{"dur":"3 min","name":"Relajación de cuello en decúbito"}],"en":[{"dur":"3 min","name":"Slow neck rotations"},{"dur":"3 min","name":"Shoulder rolls and shrugs"},{"dur":"3 min/side","name":"Seated trapezius stretch"},{"dur":"3 min","name":"Chest opener with clasped hands"},{"dur":"2 min/side","name":"Thread the needle"},{"dur":"3 min","name":"Neck release lying down"}]}',
 '{"es":["Mueve el cuello despacio, sin tirón","Para si sientes hormigueo en los brazos","Ideal como pausa activa a mitad del día"],"en":["Move the neck slowly, no jerking","Stop if you feel tingling in the arms","Great as an active break during the day"]}'),

('stretching_nocturno_20', 29, 'mobility', '🌛',
 '{"es":"Stretching nocturno","en":"Evening stretch","fr":"Étirements du soir","it":"Stretching serale"}',
 '{"es":"Rutina suave para bajar la activación y preparar el cuerpo para el sueño","en":"Gentle routine to wind down and prepare the body for sleep"}',
 20, 'low', 50,
 ARRAY['luteal','menstrual'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home'],
 ARRAY['stress','reduce_symptoms','sleep'],
 ARRAY['pmdd','insomnia','anxiety','fibromyalgia'],
 ARRAY[]::text[],
 '{"es":[{"dur":"3 min","name":"Respiración 4-7-8 tumbada"},{"dur":"3 min c/lado","name":"Torsión supina"},{"dur":"3 min","name":"Piernas en la pared (Viparita Karani)"},{"dur":"3 min","name":"Mariposa reclinada"},{"dur":"5 min","name":"Relajación progresiva muscular"}],"en":[{"dur":"3 min","name":"4-7-8 breathing lying down"},{"dur":"3 min/side","name":"Supine spinal twist"},{"dur":"3 min","name":"Legs up the wall (Viparita Karani)"},{"dur":"3 min","name":"Reclined butterfly"},{"dur":"5 min","name":"Progressive muscle relaxation"}]}',
 '{"es":["Hazlo con luz tenue o en penumbra","Sin pantallas durante ni 30 min después","Puedes usar un antifaz al terminar"],"en":["Do it in dim or low light","No screens during or 30 min after","You can use an eye mask when you finish"]}'),

('movilidad_completa_30', 30, 'mobility', '🔄',
 '{"es":"Movilidad articular completa","en":"Full joint mobility","fr":"Mobilité articulaire complète","it":"Mobilità articolare completa"}',
 '{"es":"Recorrido articular de todo el cuerpo para mejorar rango de movimiento y reducir rigidez","en":"Full-body joint circuit to improve range of motion and reduce stiffness"}',
 30, 'low', 70,
 ARRAY['menstrual','follicular','ovulatory','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['rehab','posture','energy','reduce_symptoms'],
 ARRAY['fibromyalgia','arthritis','chronic_pain','back_pain','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"3 min","name":"Rotaciones de tobillo y muñeca"},{"dur":"3 min","name":"Círculos de rodilla y cadera"},{"dur":"3 min","name":"Rotaciones de columna de pie"},{"dur":"4 min","name":"Círculos de hombro y cuello"},{"dur":"4 min","name":"Cat-cow y extensión de columna"},{"dur":"4 min","name":"Apertura de caderas en el suelo"},{"dur":"4 min","name":"Estiramiento global de cuerpo completo"}],"en":[{"dur":"3 min","name":"Ankle and wrist circles"},{"dur":"3 min","name":"Knee and hip circles"},{"dur":"3 min","name":"Standing spinal rotations"},{"dur":"4 min","name":"Shoulder and neck circles"},{"dur":"4 min","name":"Cat-cow and spinal extension"},{"dur":"4 min","name":"Floor hip opening"},{"dur":"4 min","name":"Full-body global stretch"}]}',
 '{"es":["Mueve cada articulación en todos sus rangos","Sin rebotes, movimiento controlado","Ideal como calentamiento o rutina matutina diaria"],"en":["Move each joint through its full range","No bouncing, controlled movement","Great as a warm-up or morning daily routine"]}'),

-- ─── CARDIO ──────────────────────────────────────────────────────────────────

('bicicleta_estatica_45', 31, 'cardio', '🚴',
 '{"es":"Bicicleta estática","en":"Stationary bike","fr":"Vélo stationnaire","it":"Bici stazionaria"}',
 '{"es":"Cardio de bajo impacto articular pero alta demanda cardiovascular en bicicleta estática","en":"Low joint-impact but high cardiovascular demand on a stationary bike"}',
 45, 'medium', 280,
 ARRAY['follicular','ovulatory'],
 ARRAY['occasional','regular','athlete'],
 ARRAY['full_gym','basic_gym'],
 ARRAY['lose_weight','cardio','energy','athletic_performance'],
 ARRAY['knee_pain','joint_pain','pcos','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Pedaleo suave de calentamiento (resistencia baja)"},{"dur":"10 min","name":"Resistencia media constante"},{"dur":"10 min","name":"Intervalos: 1 min fuerte / 1 min suave x5"},{"dur":"10 min","name":"Resistencia media-alta sostenida"},{"dur":"5 min","name":"Vuelta a la calma, pedaleo suave"},{"dur":"5 min","name":"Estiramiento de cuádriceps e isquios"}],"en":[{"dur":"5 min","name":"Easy warm-up pedaling (low resistance)"},{"dur":"10 min","name":"Steady medium resistance"},{"dur":"10 min","name":"Intervals: 1 min hard / 1 min easy x5"},{"dur":"10 min","name":"Sustained medium-high resistance"},{"dur":"5 min","name":"Cool-down, easy pedaling"},{"dur":"5 min","name":"Quad and hamstring stretch"}]}',
 '{"es":["Ajusta el asiento para que la rodilla quede ligeramente doblada al fondo del pedaleo","Mantén el core activo y la espalda recta","Bebe agua cada 15 minutos"],"en":["Set the seat so your knee is slightly bent at the bottom of the stroke","Keep your core engaged and back straight","Drink water every 15 minutes"]}'),

('baile_cardio_30', 32, 'cardio', '💃',
 '{"es":"Baile cardio","en":"Cardio dance","fr":"Cardio danse","it":"Ballo cardio"}',
 '{"es":"Rutina de baile de alta energía para quemar calorías mientras te diviertes","en":"High-energy dance routine to burn calories while having fun"}',
 30, 'medium', 210,
 ARRAY['follicular','ovulatory'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym'],
 ARRAY['lose_weight','energy','mood','cardio'],
 ARRAY['depression','anxiety','fatigue','pcos'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Marcha en el sitio y balanceos de brazos"},{"dur":"5 min","name":"Paso básico de merengue con giros"},{"dur":"5 min","name":"Salsa sencilla: paso adelante-atrás"},{"dur":"5 min","name":"Movimientos de cadera afro"},{"dur":"5 min","name":"Coreografía combinada a ritmo"},{"dur":"5 min","name":"Vuelta a la calma con movimiento suave"}],"en":[{"dur":"5 min","name":"March in place and arm swings"},{"dur":"5 min","name":"Basic merengue step with turns"},{"dur":"5 min","name":"Simple salsa: step forward-back"},{"dur":"5 min","name":"Afro hip movements"},{"dur":"5 min","name":"Combined choreography at tempo"},{"dur":"5 min","name":"Cool-down with gentle movement"}]}',
 '{"es":["Pon música que te encante para subir la motivación","No te preocupes por los pasos perfectos, muévete y disfruta","Descalza o con zapatillas ligeras"],"en":["Play music you love to boost motivation","Don''t worry about perfect steps, just move and enjoy","Barefoot or in light sneakers"]}'),

('saltar_cuerda_20', 33, 'cardio', '🪢',
 '{"es":"Saltar a la cuerda","en":"Jump rope","fr":"Corde à sauter","it":"Salto con la corda"}',
 '{"es":"Cardio de alta intensidad y bajo coste para maximizar la quema calórica en poco tiempo","en":"High-intensity low-cost cardio to maximise calorie burn in a short time"}',
 20, 'high', 230,
 ARRAY['ovulatory','follicular'],
 ARRAY['occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['lose_weight','cardio','athletic_performance'],
 ARRAY['pcos','fatigue'],
 ARRAY['pregnant','joint_pain','knee_pain','osteoporosis'],
 '{"es":[{"dur":"3 min","name":"Salto básico continuo (calentamiento)"},{"dur":"2 min","name":"Descanso activo: marcha en sitio"},{"dur":"3 min","name":"Salto alterno de pies (trote)"},{"dur":"2 min","name":"Descanso activo"},{"dur":"3 min","name":"Salto rápido o doble vuelta"},{"dur":"2 min","name":"Descanso activo"},{"dur":"3 min","name":"Sprint final: máxima velocidad"},{"dur":"2 min","name":"Estiramiento de gemelos y cuádriceps"}],"en":[{"dur":"3 min","name":"Basic continuous jump (warm-up)"},{"dur":"2 min","name":"Active rest: march in place"},{"dur":"3 min","name":"Alternating foot jump (jog)"},{"dur":"2 min","name":"Active rest"},{"dur":"3 min","name":"Fast jump or double-under"},{"dur":"2 min","name":"Active rest"},{"dur":"3 min","name":"Final sprint: maximum speed"},{"dur":"2 min","name":"Calf and quad stretch"}]}',
 '{"es":["Usa calzado con buena amortiguación","Aterriza sobre el antepié, no con el talón","Si llevas tiempo sin saltar, empieza con 1 min e incrementa poco a poco"],"en":["Wear well-cushioned shoes","Land on the ball of your foot, not your heel","If you haven''t jumped in a while, start with 1 min and build up"]}'),

('cardio_embarazo_30', 34, 'cardio', '🤰',
 '{"es":"Cardio seguro embarazo","en":"Pregnancy-safe cardio","fr":"Cardio grossesse","it":"Cardio gravidanza"}',
 '{"es":"Cardio suave y seguro adaptado para el segundo y tercer trimestre de embarazo","en":"Gentle and safe cardio adapted for the second and third trimester of pregnancy"}',
 30, 'low', 120,
 ARRAY['follicular','ovulatory','luteal','menstrual'],
 ARRAY['sedentary','occasional','regular'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['energy','reduce_symptoms'],
 ARRAY['pregnant'],
 ARRAY['postpartum'],
 '{"es":[{"dur":"5 min","name":"Marcha en el sitio con balanceo de brazos"},{"dur":"5 min","name":"Step lateral suave"},{"dur":"5 min","name":"Marcha con elevación de rodillas baja"},{"dur":"5 min","name":"Movimiento de brazos sentada en pelota"},{"dur":"5 min","name":"Marcha con giro de tronco suave"},{"dur":"5 min","name":"Vuelta a la calma y respiración abdominal"}],"en":[{"dur":"5 min","name":"March in place with arm swing"},{"dur":"5 min","name":"Gentle side step"},{"dur":"5 min","name":"Low-knee march"},{"dur":"5 min","name":"Seated arm movement on ball"},{"dur":"5 min","name":"March with gentle trunk rotation"},{"dur":"5 min","name":"Cool-down and abdominal breathing"}]}',
 '{"es":["Mantén el ritmo conversacional: si no puedes hablar, baja la intensidad","Para si sientes mareo, contracciones o pérdida de líquido","Consulta siempre a tu ginecóloga antes de hacer ejercicio en el embarazo"],"en":["Keep conversational pace: if you can''t talk, lower the intensity","Stop if you feel dizziness, contractions or fluid loss","Always consult your OB before exercising during pregnancy"]}'),

-- ─── HIIT ────────────────────────────────────────────────────────────────────

('hiit_bajo_impacto_25', 35, 'hiit', '⚡',
 '{"es":"HIIT bajo impacto","en":"Low-impact HIIT","fr":"HIIT faible impact","it":"HIIT basso impatto"}',
 '{"es":"Alta intensidad sin saltos ni impacto articular, ideal para articulaciones sensibles o fase lútea","en":"High intensity without jumps or joint impact, ideal for sensitive joints or luteal phase"}',
 25, 'medium', 190,
 ARRAY['follicular','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['lose_weight','tone','energy','cardio'],
 ARRAY['knee_pain','joint_pain','pcos','hypothyroid','back_pain'],
 ARRAY['pregnant'],
 '{"es":[{"dur":"3 min","name":"Calentamiento: marcha con brazos"},{"dur":"40 seg","name":"Sentadilla lenta con pausa"},{"dur":"20 seg","name":"Descanso"},{"dur":"40 seg","name":"Step lateral rápido"},{"dur":"20 seg","name":"Descanso"},{"dur":"40 seg","name":"Zancada alternante sin salto"},{"dur":"20 seg","name":"Descanso"},{"dur":"40 seg","name":"Plancha con toque de hombro"},{"dur":"20 seg","name":"Descanso"},{"dur":"40 seg","name":"Puente de glúteos pulsado"},{"dur":"20 seg","name":"Descanso — repite 3 rondas"},{"dur":"3 min","name":"Vuelta a la calma y estiramiento"}],"en":[{"dur":"3 min","name":"Warm-up: march with arms"},{"dur":"40 sec","name":"Slow squat with pause"},{"dur":"20 sec","name":"Rest"},{"dur":"40 sec","name":"Fast lateral step"},{"dur":"20 sec","name":"Rest"},{"dur":"40 sec","name":"Alternating lunge no jump"},{"dur":"20 sec","name":"Rest"},{"dur":"40 sec","name":"Plank shoulder tap"},{"dur":"20 sec","name":"Rest"},{"dur":"40 sec","name":"Pulsed glute bridge"},{"dur":"20 sec","name":"Rest — repeat 3 rounds"},{"dur":"3 min","name":"Cool-down and stretch"}]}',
 '{"es":["Pon el foco en la intensidad del esfuerzo, no en los saltos","Mantén el core activo durante toda la sesión","Ajusta la velocidad para no perder la técnica"],"en":["Focus on effort intensity, not jumps","Keep your core engaged throughout","Adjust speed to maintain technique"]}'),

('tabata_20', 36, 'hiit', '🔥',
 '{"es":"Tabata","en":"Tabata","fr":"Tabata","it":"Tabata"}',
 '{"es":"Protocolo Tabata original: 8 rondas de 20 seg de trabajo máximo y 10 seg de descanso","en":"Original Tabata protocol: 8 rounds of 20 sec max work and 10 sec rest"}',
 20, 'high', 240,
 ARRAY['ovulatory'],
 ARRAY['regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['lose_weight','athletic_performance','cardio','tone'],
 ARRAY['pcos','fatigue'],
 ARRAY['pregnant','joint_pain','knee_pain','osteoporosis'],
 '{"es":[{"dur":"3 min","name":"Calentamiento dinámico obligatorio"},{"dur":"4 min","name":"Bloque 1 — Burpees: 8×(20s trabajo / 10s descanso)"},{"dur":"1 min","name":"Descanso activo"},{"dur":"4 min","name":"Bloque 2 — Sentadillas de salto: 8×(20s / 10s)"},{"dur":"1 min","name":"Descanso activo"},{"dur":"4 min","name":"Bloque 3 — Mountain climbers: 8×(20s / 10s)"},{"dur":"3 min","name":"Vuelta a la calma y estiramiento"}],"en":[{"dur":"3 min","name":"Mandatory dynamic warm-up"},{"dur":"4 min","name":"Block 1 — Burpees: 8×(20s work / 10s rest)"},{"dur":"1 min","name":"Active rest"},{"dur":"4 min","name":"Block 2 — Jump squats: 8×(20s / 10s)"},{"dur":"1 min","name":"Active rest"},{"dur":"4 min","name":"Block 3 — Mountain climbers: 8×(20s / 10s)"},{"dur":"3 min","name":"Cool-down and stretch"}]}',
 '{"es":["El trabajo debe ser al máximo: si puedes hablar, no es Tabata","Nunca te saltes el calentamiento","Una sesión de Tabata a la semana es suficiente"],"en":["Work must be at maximum: if you can talk, it''s not Tabata","Never skip the warm-up","One Tabata session per week is enough"]}'),

-- ─── STRENGTH ────────────────────────────────────────────────────────────────

('fuerza_gluteos_40', 37, 'strength', '🍑',
 '{"es":"Fuerza de glúteos","en":"Glute strength","fr":"Force des fessiers","it":"Forza glutei"}',
 '{"es":"Sesión específica de glúteos con progresión de carga para tonificar y fortalecer","en":"Targeted glute session with load progression to tone and strengthen"}',
 40, 'medium', 185,
 ARRAY['follicular','ovulatory'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['tone','lose_weight','posture','athletic_performance'],
 ARRAY['pcos','back_pain','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Activación: puente de glúteos x20 y clamshell x15"},{"dur":"8 min","name":"Sentadilla goblet 4×12"},{"dur":"8 min","name":"Hip thrust con peso corporal o barra 4×15"},{"dur":"6 min","name":"Peso muerto rumano con mancuernas 3×12"},{"dur":"6 min","name":"Patada de glúteo en cuadrupedia 3×15 c/lado"},{"dur":"4 min","name":"Estiramiento de glúteos y piriforme"},{"dur":"3 min","name":"Foam roller en glúteos"}],"en":[{"dur":"5 min","name":"Activation: glute bridge x20 and clamshell x15"},{"dur":"8 min","name":"Goblet squat 4×12"},{"dur":"8 min","name":"Hip thrust bodyweight or barbell 4×15"},{"dur":"6 min","name":"Dumbbell Romanian deadlift 3×12"},{"dur":"6 min","name":"Quadruped glute kickback 3×15/side"},{"dur":"4 min","name":"Glute and piriformis stretch"},{"dur":"3 min","name":"Foam roll glutes"}]}',
 '{"es":["Activa los glúteos conscientemente antes de cada rep","El hip thrust es el ejercicio más eficaz para el glúteo mayor","Progresa el peso cada 2 semanas si completas las series sin dificultad"],"en":["Consciously activate glutes before each rep","Hip thrust is the most effective exercise for the glute max","Progress weight every 2 weeks if you complete sets without difficulty"]}'),

('fuerza_core_30', 38, 'strength', '🧱',
 '{"es":"Fuerza de core","en":"Core strength","fr":"Force du core","it":"Forza del core"}',
 '{"es":"Trabajo profundo de musculatura abdominal, lumbar y pélvica para una base sólida","en":"Deep work on abdominal, lumbar and pelvic muscles for a solid foundation"}',
 30, 'medium', 150,
 ARRAY['follicular','ovulatory','luteal'],
 ARRAY['sedentary','occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['tone','posture','rehab'],
 ARRAY['back_pain','diastasis','incontinence','pcos'],
 ARRAY['pregnant'],
 '{"es":[{"dur":"3 min","name":"Activación de suelo pélvico y transverso"},{"dur":"5 min","name":"Plancha frontal progresiva 3×30-45s"},{"dur":"5 min","name":"Plancha lateral 3×20s c/lado"},{"dur":"5 min","name":"Dead bug 3×10 c/lado"},{"dur":"5 min","name":"Bird dog 3×10 c/lado"},{"dur":"4 min","name":"Pallof press o rotación con banda"},{"dur":"3 min","name":"Estiramiento lumbar y cat-cow"}],"en":[{"dur":"3 min","name":"Pelvic floor and transverse abdominis activation"},{"dur":"5 min","name":"Front plank progression 3×30-45s"},{"dur":"5 min","name":"Side plank 3×20s per side"},{"dur":"5 min","name":"Dead bug 3×10 per side"},{"dur":"5 min","name":"Bird dog 3×10 per side"},{"dur":"4 min","name":"Pallof press or band rotation"},{"dur":"3 min","name":"Lumbar stretch and cat-cow"}]}',
 '{"es":["El core incluye transverso, multífidos y suelo pélvico, no solo el recto abdominal","Si tienes diastasis, evita los crunches clásicos","Exhala en el esfuerzo, inhala al ceder"],"en":["Core includes transverse, multifidus and pelvic floor, not just rectus abdominis","If you have diastasis, avoid traditional crunches","Exhale on effort, inhale on release"]}'),

('fuerza_funcional_45', 39, 'strength', '💪',
 '{"es":"Fuerza funcional","en":"Functional strength","fr":"Force fonctionnelle","it":"Forza funzionale"}',
 '{"es":"Movimientos multiarticulares que replican gestos del día a día para una fuerza aplicada","en":"Multi-joint movements that replicate daily gestures for applied strength"}',
 45, 'medium', 220,
 ARRAY['follicular','ovulatory'],
 ARRAY['occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['tone','athletic_performance','posture','lose_weight'],
 ARRAY['pcos','hypothyroid','back_pain'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Calentamiento dinámico"},{"dur":"8 min","name":"Sentadilla + press de hombros 4×10"},{"dur":"8 min","name":"Peso muerto + remo con mancuerna 4×10"},{"dur":"7 min","name":"Zancada inversa + curl de bíceps 3×10 c/lado"},{"dur":"7 min","name":"Flexiones + remo en plancha 3×8"},{"dur":"5 min","name":"Turkish get-up o cargada funcional 3×5 c/lado"},{"dur":"5 min","name":"Estiramiento cuerpo completo"}],"en":[{"dur":"5 min","name":"Dynamic warm-up"},{"dur":"8 min","name":"Squat + shoulder press 4×10"},{"dur":"8 min","name":"Deadlift + dumbbell row 4×10"},{"dur":"7 min","name":"Reverse lunge + bicep curl 3×10/side"},{"dur":"7 min","name":"Push-up + plank row 3×8"},{"dur":"5 min","name":"Turkish get-up or functional carry 3×5/side"},{"dur":"5 min","name":"Full-body stretch"}]}',
 '{"es":["Prioriza técnica sobre peso","Los movimientos compuestos dan más beneficio hormonal que los aislados","Descansa 60-90 seg entre series"],"en":["Prioritize technique over weight","Compound movements give more hormonal benefit than isolation exercises","Rest 60-90 sec between sets"]}'),

('fuerza_cuerpo_completo_50', 40, 'strength', '🏋️',
 '{"es":"Fuerza cuerpo completo","en":"Full body strength","fr":"Force corps entier","it":"Forza corpo intero"}',
 '{"es":"Sesión completa de tren superior e inferior para máxima eficiencia cuando entrenas pocos días","en":"Complete upper and lower body session for maximum efficiency when training few days a week"}',
 50, 'medium', 240,
 ARRAY['follicular','ovulatory'],
 ARRAY['occasional','regular','athlete'],
 ARRAY['home','full_gym','basic_gym'],
 ARRAY['tone','lose_weight','athletic_performance','posture'],
 ARRAY['pcos','hypothyroid'],
 ARRAY[]::text[],
 '{"es":[{"dur":"5 min","name":"Calentamiento articular"},{"dur":"10 min","name":"Sentadilla trasera o goblet 4×10"},{"dur":"8 min","name":"Press de banca o flexiones 4×10"},{"dur":"8 min","name":"Peso muerto convencional 4×8"},{"dur":"7 min","name":"Remo con barra o mancuernas 4×10"},{"dur":"7 min","name":"Zancada + press de hombro 3×10 c/lado"},{"dur":"5 min","name":"Estiramiento y foam roller"}],"en":[{"dur":"5 min","name":"Joint warm-up"},{"dur":"10 min","name":"Back squat or goblet squat 4×10"},{"dur":"8 min","name":"Bench press or push-ups 4×10"},{"dur":"8 min","name":"Conventional deadlift 4×8"},{"dur":"7 min","name":"Barbell or dumbbell row 4×10"},{"dur":"7 min","name":"Lunge + shoulder press 3×10/side"},{"dur":"5 min","name":"Stretch and foam roll"}]}',
 '{"es":["Ideal si entrenas 2-3 días a la semana","Registra el peso para progresar semana a semana","Descansa 2 min entre series de ejercicios grandes"],"en":["Ideal if you train 2-3 days a week","Track the weight used to progress week by week","Rest 2 min between sets of big compound exercises"]}');

COMMIT;
