-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- MEIRINS Â· Recetas LOTE 1 (30) â€” refuerzo de keto, low_carb, pescatarian,
-- paleo, vegan y low_fodmap. Ejecutar en Supabase SQL Editor.
-- Objetivo global: ~250-300 recetas multi-etiquetadas (â‰¥100 por categorÃ­a grande)
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- â”€â”€ KETO / LOW CARB â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('salmon_horno_esparragos',41,'dinner','ðŸŸ',
'{"es":"SalmÃ³n al horno con espÃ¡rragos","en":"Baked salmon with asparagus","fr":"Saumon au four et asperges","it":"Salmone al forno con asparagi"}',
'{"es":"Omega-3 y proteÃ­na de calidad con verdura verde","en":"Omega-3 and quality protein with green veg"}',
5,18,460,34,8,32,4,
ARRAY['keto','low_carb','paleo','pescatarian','high_protein','anti_inflammatory','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['lose_weight','maintain','reduce_symptoms'],
ARRAY['endometriosis','pcos','type2_diabetes'],
ARRAY['fish'],
'easy','under_20','high',
'{"es":["180g lomo de salmÃ³n","200g espÃ¡rragos verdes","1 cda aceite de oliva","LimÃ³n, sal, pimienta y eneldo"],"en":["180g salmon fillet","200g green asparagus","1 tbsp olive oil","Lemon, salt, pepper and dill"]}',
'{"es":["Precalienta el horno a 200Â°C","Coloca salmÃ³n y espÃ¡rragos en una bandeja con aceite y especias","Hornea 15-18 min","Termina con limÃ³n y eneldo"],"en":["Preheat oven to 200Â°C","Place salmon and asparagus on a tray with oil and seasoning","Bake 15-18 min","Finish with lemon and dill"]}'
),

('pollo_coco_curry_keto',42,'lunch','ðŸ›',
'{"es":"Curry de pollo con leche de coco","en":"Chicken curry with coconut milk","fr":"Curry de poulet au lait de coco","it":"Curry di pollo al latte di cocco"}',
'{"es":"Cremoso, saciante y muy bajo en carbohidratos","en":"Creamy, filling and very low in carbs"}',
10,20,520,38,10,36,3,
ARRAY['keto','low_carb','paleo','high_protein','gluten_free','lactose_free'],
ARRAY['luteal','menstrual'],
ARRAY['lose_weight','maintain','gain_muscle'],
ARRAY['pcos','type2_diabetes'],
ARRAY[]::text[],
'easy','20_to_40','medium',
'{"es":["200g pechuga de pollo en dados","200ml leche de coco","1 cda pasta de curry suave","Â½ calabacÃ­n en dados","1 cda aceite de coco","Cilantro fresco"],"en":["200g diced chicken breast","200ml coconut milk","1 tbsp mild curry paste","Â½ diced courgette","1 tbsp coconut oil","Fresh coriander"]}',
'{"es":["Dora el pollo en el aceite 5 min","AÃ±ade la pasta de curry y remueve 1 min","Incorpora la leche de coco y el calabacÃ­n","Cocina a fuego suave 12-15 min","Sirve con cilantro"],"en":["Brown the chicken in oil 5 min","Add curry paste and stir 1 min","Add coconut milk and courgette","Simmer 12-15 min","Serve with coriander"]}'
),

('ensalada_aguacate_huevo_keto',43,'lunch','ðŸ¥‘',
'{"es":"Ensalada keto de aguacate, huevo y bacon","en":"Keto avocado, egg and bacon salad","fr":"Salade keto avocat, Å“uf et bacon","it":"Insalata keto avocado, uovo e bacon"}',
'{"es":"Grasas saludables y proteÃ­na sin apenas carbohidratos","en":"Healthy fats and protein with almost no carbs"}',
10,8,540,24,7,46,7,
ARRAY['keto','low_carb','high_protein','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','maintain'],
ARRAY['pcos','type2_diabetes'],
ARRAY['egg'],
'easy','under_20','medium',
'{"es":["2 huevos","1 aguacate","2 lonchas de bacon","80g rÃºcula","1 cda aceite de oliva","Vinagre y mostaza"],"en":["2 eggs","1 avocado","2 bacon rashers","80g rocket","1 tbsp olive oil","Vinegar and mustard"]}',
'{"es":["Cuece los huevos 9 min y enfrÃ­a","Dora el bacon hasta crujiente","Monta la ensalada con rÃºcula, aguacate, huevo y bacon troceados","AliÃ±a con aceite, vinagre y mostaza"],"en":["Boil eggs 9 min and cool","Crisp the bacon","Assemble rocket, avocado, chopped egg and bacon","Dress with oil, vinegar and mustard"]}'
),

('revuelto_setas_queso_keto',44,'breakfast','ðŸ³',
'{"es":"Revuelto de setas con queso de cabra","en":"Mushroom scramble with goat cheese","fr":"Brouillade champignons et chÃ¨vre","it":"Strapazzate ai funghi con caprino"}',
'{"es":"Desayuno salado keto, saciante hasta la comida","en":"Savoury keto breakfast that keeps you full till lunch"}',
5,10,390,22,6,30,2,
ARRAY['keto','low_carb','vegetarian','high_protein','gluten_free'],
ARRAY['luteal','menstrual'],
ARRAY['lose_weight','maintain'],
ARRAY['type2_diabetes'],
ARRAY['egg','lactose'],
'easy','under_20','medium',
'{"es":["3 huevos","100g setas variadas","30g queso de cabra","1 cdta mantequilla","Cebollino, sal y pimienta"],"en":["3 eggs","100g mixed mushrooms","30g goat cheese","1 tsp butter","Chives, salt and pepper"]}',
'{"es":["Saltea las setas en mantequilla 4 min","Bate los huevos y aÃ±Ã¡delos a fuego suave","Remueve hasta cuajar cremoso","Desmiga el queso por encima y termina con cebollino"],"en":["SautÃ© mushrooms in butter 4 min","Beat eggs and add over low heat","Stir until creamy","Crumble cheese on top and finish with chives"]}'
),

('dorada_plancha_verduras',45,'dinner','ðŸ ',
'{"es":"Dorada a la plancha con verduras salteadas","en":"Grilled sea bream with sautÃ©ed vegetables","fr":"Daurade grillÃ©e et lÃ©gumes sautÃ©s","it":"Orata alla griglia con verdure saltate"}',
'{"es":"Cena ligera mediterrÃ¡nea baja en carbohidratos","en":"Light Mediterranean low-carb dinner"}',
8,15,410,36,9,24,4,
ARRAY['low_carb','pescatarian','mediterranean','high_protein','gluten_free','lactose_free','paleo','anti_inflammatory'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['lose_weight','maintain'],
ARRAY['hypertension','type2_diabetes'],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["1 dorada en filetes (250g)","1 calabacÃ­n","1 pimiento rojo","2 cda aceite de oliva","Ajo, perejil y limÃ³n"],"en":["1 sea bream filleted (250g)","1 courgette","1 red pepper","2 tbsp olive oil","Garlic, parsley and lemon"]}',
'{"es":["Saltea las verduras en tiras con 1 cda de aceite 6-8 min","Haz la dorada a la plancha 3-4 min por lado","Sirve con ajo-perejil, limÃ³n y el resto del aceite en crudo"],"en":["SautÃ© vegetable strips in 1 tbsp oil 6-8 min","Grill the bream 3-4 min per side","Serve with garlic-parsley, lemon and remaining raw oil"]}'
),

('crema_calabacin_keto',46,'dinner','ðŸ¥£',
'{"es":"Crema de calabacÃ­n con parmesano","en":"Courgette cream soup with parmesan","fr":"VeloutÃ© de courgette au parmesan","it":"Vellutata di zucchine al parmigiano"}',
'{"es":"Reconfortante, ligera y baja en hidratos","en":"Comforting, light and low-carb"}',
8,15,280,12,11,21,3,
ARRAY['keto','low_carb','vegetarian','gluten_free'],
ARRAY['menstrual','luteal'],
ARRAY['lose_weight','maintain','reduce_symptoms'],
ARRAY['hypothyroid'],
ARRAY['lactose'],
'easy','20_to_40','low',
'{"es":["2 calabacines","Â½ cebolla","30g parmesano","200ml caldo de verduras","1 cda aceite de oliva","50ml nata ligera (opcional)"],"en":["2 courgettes","Â½ onion","30g parmesan","200ml vegetable stock","1 tbsp olive oil","50ml light cream (optional)"]}',
'{"es":["SofrÃ­e la cebolla 3 min","AÃ±ade el calabacÃ­n en rodajas y el caldo","Cocina 12 min y tritura","Sirve con parmesano rallado"],"en":["SautÃ© onion 3 min","Add sliced courgette and stock","Cook 12 min and blend","Serve with grated parmesan"]}'
),

('atun_encebollado_lowcarb',47,'lunch','ðŸŸ',
'{"es":"AtÃºn encebollado con pimientos","en":"Tuna with caramelised onion and peppers","fr":"Thon aux oignons et poivrons","it":"Tonno con cipolle e peperoni"}',
'{"es":"Plato de cuchara rÃ¡pido, alto en proteÃ­na","en":"Quick high-protein dish"}',
8,15,430,40,12,24,3,
ARRAY['low_carb','pescatarian','mediterranean','high_protein','gluten_free','lactose_free','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','maintain','performance'],
ARRAY['anemia'],
ARRAY['fish'],
'easy','20_to_40','medium',
'{"es":["200g atÃºn fresco en tacos","1 cebolla grande","1 pimiento verde","2 cda aceite de oliva","PimentÃ³n, laurel y vinagre de jerez"],"en":["200g fresh tuna cubes","1 large onion","1 green pepper","2 tbsp olive oil","Paprika, bay leaf and sherry vinegar"]}',
'{"es":["Pocha la cebolla y el pimiento 8 min","AÃ±ade pimentÃ³n, laurel y un chorrito de vinagre","Incorpora el atÃºn y cocina 3-4 min (jugoso por dentro)"],"en":["Slowly cook onion and pepper 8 min","Add paprika, bay leaf and a splash of vinegar","Add tuna and cook 3-4 min (juicy inside)"]}'
),

('aguacate_relleno_atun',48,'dinner','ðŸ¥‘',
'{"es":"Aguacates rellenos de atÃºn y huevo","en":"Avocados stuffed with tuna and egg","fr":"Avocats farcis thon et Å“uf","it":"Avocado ripieni di tonno e uovo"}',
'{"es":"Cena frÃ­a en 10 minutos sin cocinar apenas","en":"Cold dinner in 10 minutes with barely any cooking"}',
10,9,470,28,8,36,8,
ARRAY['keto','low_carb','pescatarian','high_protein','gluten_free','lactose_free','low_fodmap'],
ARRAY['ovulation','luteal'],
ARRAY['lose_weight','maintain'],
ARRAY['pcos'],
ARRAY['fish','egg'],
'easy','under_20','medium',
'{"es":["1 aguacate grande","1 lata de atÃºn al natural","1 huevo cocido","1 cda yogur griego o mayonesa ligera","Cebollino y pimienta"],"en":["1 large avocado","1 tin of tuna in water","1 boiled egg","1 tbsp Greek yoghurt or light mayo","Chives and pepper"]}',
'{"es":["Corta el aguacate por la mitad y retira algo de pulpa","Mezcla atÃºn, huevo picado, la pulpa y el yogur","Rellena las mitades y termina con cebollino"],"en":["Halve the avocado and scoop out some flesh","Mix tuna, chopped egg, the flesh and yoghurt","Fill the halves and top with chives"]}'
),

-- â”€â”€ PESCATARIAN / MEDITERRÃNEA â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('merluza_salsa_verde',49,'lunch','ðŸŽ£',
'{"es":"Merluza en salsa verde con guisantes","en":"Hake in green sauce with peas","fr":"Colin sauce verte aux petits pois","it":"Nasello in salsa verde con piselli"}',
'{"es":"ClÃ¡sico ligero, rico en proteÃ­na magra","en":"Light classic, rich in lean protein"}',
10,15,380,36,14,18,4,
ARRAY['pescatarian','mediterranean','high_protein','gluten_free','lactose_free','low_carb'],
ARRAY['menstrual','follicular'],
ARRAY['lose_weight','maintain'],
ARRAY['hypertension','anemia'],
ARRAY['fish'],
'medium','20_to_40','medium',
'{"es":["200g lomo de merluza","80g guisantes","2 dientes de ajo","Perejil fresco abundante","150ml caldo de pescado","2 cda aceite de oliva","1 cdta harina de arroz"],"en":["200g hake loin","80g peas","2 garlic cloves","Plenty of fresh parsley","150ml fish stock","2 tbsp olive oil","1 tsp rice flour"]}',
'{"es":["Dora el ajo en el aceite y aÃ±ade la harina","Vierte el caldo poco a poco hasta ligar","Incorpora merluza y guisantes, cocina 8 min tapado","Termina con mucho perejil picado"],"en":["Brown garlic in oil and add flour","Slowly pour stock until it binds","Add hake and peas, cook covered 8 min","Finish with plenty of chopped parsley"]}'
),

('gambas_ajillo_calabacin',50,'dinner','ðŸ¤',
'{"es":"Gambas al ajillo con espaguetis de calabacÃ­n","en":"Garlic prawns with courgette noodles","fr":"Crevettes Ã  l''ail et spaghettis de courgette","it":"Gamberi all''aglio con spaghetti di zucchine"}',
'{"es":"VersiÃ³n low carb del clÃ¡sico, lista en 15 minutos","en":"Low-carb take on the classic, ready in 15 minutes"}',
10,8,360,30,9,23,3,
ARRAY['pescatarian','low_carb','keto','mediterranean','high_protein','gluten_free','lactose_free','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','maintain','performance'],
ARRAY['pcos','type2_diabetes'],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["200g gambas peladas","1 calabacÃ­n grande en espirales","3 dientes de ajo","1 guindilla","3 cda aceite de oliva","Perejil"],"en":["200g peeled prawns","1 large spiralised courgette","3 garlic cloves","1 chilli","3 tbsp olive oil","Parsley"]}',
'{"es":["Dora ajo laminado y guindilla en el aceite","Sube el fuego y saltea las gambas 2-3 min","AÃ±ade los espaguetis de calabacÃ­n 1-2 min","Termina con perejil"],"en":["Brown sliced garlic and chilli in oil","Turn up heat and sautÃ© prawns 2-3 min","Add courgette noodles 1-2 min","Finish with parsley"]}'
),

('sardinas_horno_tomate',51,'lunch','ðŸŸ',
'{"es":"Sardinas al horno con tomate y orÃ©gano","en":"Baked sardines with tomato and oregano","fr":"Sardines au four, tomate et origan","it":"Sardine al forno con pomodoro e origano"}',
'{"es":"Calcio, omega-3 y hierro por muy poco dinero","en":"Calcium, omega-3 and iron on a budget"}',
8,15,390,32,10,25,3,
ARRAY['pescatarian','mediterranean','high_protein','gluten_free','lactose_free','paleo','anti_inflammatory','low_carb'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['anemia','endometriosis','hypothyroid'],
ARRAY['fish'],
'easy','20_to_40','low',
'{"es":["6 sardinas limpias","2 tomates maduros","1 cebolla","2 cda aceite de oliva","OrÃ©gano y limÃ³n"],"en":["6 cleaned sardines","2 ripe tomatoes","1 onion","2 tbsp olive oil","Oregano and lemon"]}',
'{"es":["Haz una cama de tomate y cebolla en rodajas","Coloca las sardinas encima con aceite y orÃ©gano","Hornea a 200Â°C 12-15 min","Sirve con limÃ³n"],"en":["Make a bed of sliced tomato and onion","Lay sardines on top with oil and oregano","Bake at 200Â°C 12-15 min","Serve with lemon"]}'
),

('poke_salmon_integral',52,'lunch','ðŸš',
'{"es":"Poke de salmÃ³n con arroz integral y edamame","en":"Salmon poke with brown rice and edamame","fr":"Poke saumon, riz complet et edamame","it":"Poke di salmone con riso integrale ed edamame"}',
'{"es":"Completo y fresco: proteÃ­na, omega-3 y fibra","en":"Complete and fresh: protein, omega-3 and fibre"}',
15,0,560,32,55,22,7,
ARRAY['pescatarian','high_protein','lactose_free','standard'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance','maintain'],
ARRAY['anemia'],
ARRAY['fish','soy','sesame'],
'easy','under_20','high',
'{"es":["120g salmÃ³n fresco calidad sushi en dados","150g arroz integral cocido","50g edamame","Â¼ aguacate","Pepino y zanahoria en juliana","1 cda salsa de soja","1 cdta aceite de sÃ©samo","SÃ©samo tostado"],"en":["120g sushi-grade salmon, diced","150g cooked brown rice","50g edamame","Â¼ avocado","Julienned cucumber and carrot","1 tbsp soy sauce","1 tsp sesame oil","Toasted sesame"]}',
'{"es":["Marina el salmÃ³n con soja y aceite de sÃ©samo 5 min","Monta el bol: arroz, verduras, edamame y salmÃ³n","Termina con sÃ©samo tostado"],"en":["Marinate salmon in soy and sesame oil 5 min","Build the bowl: rice, veg, edamame and salmon","Top with toasted sesame"]}'
),

-- â”€â”€ VEGANAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('tofu_salteado_brocoli',53,'dinner','ðŸ¥¦',
'{"es":"Tofu salteado con brÃ³coli y anacardos","en":"Stir-fried tofu with broccoli and cashews","fr":"Tofu sautÃ©, brocoli et noix de cajou","it":"Tofu saltato con broccoli e anacardi"}',
'{"es":"ProteÃ­na vegetal completa en una sartÃ©n","en":"Complete plant protein in one pan"}',
10,12,450,24,28,28,7,
ARRAY['vegan','vegetarian','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','maintain'],
ARRAY['pcos','hypertension'],
ARRAY['soy','nuts','sesame'],
'easy','20_to_40','medium',
'{"es":["200g tofu firme en dados","250g brÃ³coli","30g anacardos","2 cda salsa de soja","1 cda aceite de sÃ©samo","1 diente de ajo, jengibre fresco"],"en":["200g firm tofu, diced","250g broccoli","30g cashews","2 tbsp soy sauce","1 tbsp sesame oil","1 garlic clove, fresh ginger"]}',
'{"es":["Dora el tofu en el aceite 5 min y reserva","Saltea brÃ³coli, ajo y jengibre 5 min","Vuelve a aÃ±adir el tofu con la soja","Termina con anacardos tostados"],"en":["Brown tofu in oil 5 min and set aside","Stir-fry broccoli, garlic and ginger 5 min","Return tofu with the soy sauce","Finish with toasted cashews"]}'
),

('lentejas_estofadas_veganas',54,'lunch','ðŸ²',
'{"es":"Lentejas estofadas con verduras","en":"Stewed lentils with vegetables","fr":"Lentilles mijotÃ©es aux lÃ©gumes","it":"Lenticchie stufate con verdure"}',
'{"es":"Hierro vegetal y fibra: el plato estrella de la fase menstrual","en":"Plant iron and fibre: the star dish of the menstrual phase"}',
10,30,480,24,68,8,16,
ARRAY['vegan','vegetarian','mediterranean','lactose_free','gluten_free','standard','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['anemia','endometriosis'],
ARRAY[]::text[],
'easy','40_plus','low',
'{"es":["200g lentejas pardinas","1 zanahoria","1 pimiento verde","Â½ cebolla","2 dientes de ajo","1 tomate","PimentÃ³n, comino y laurel","2 cda aceite de oliva"],"en":["200g brown lentils","1 carrot","1 green pepper","Â½ onion","2 garlic cloves","1 tomato","Paprika, cumin and bay leaf","2 tbsp olive oil"]}',
'{"es":["SofrÃ­e la verdura picada 5 min","AÃ±ade lentejas, especias y agua hasta cubrir +2 dedos","Cocina a fuego medio 25-30 min","Rectifica de sal y reposa 5 min"],"en":["SautÃ© chopped vegetables 5 min","Add lentils, spices and water to cover +2 fingers","Cook over medium heat 25-30 min","Season and rest 5 min"]}'
),

('garbanzos_espinacas_curry',55,'lunch','ðŸ›',
'{"es":"Garbanzos al curry con espinacas y coco","en":"Chickpea curry with spinach and coconut","fr":"Curry de pois chiches, Ã©pinards et coco","it":"Ceci al curry con spinaci e cocco"}',
'{"es":"Vegano, antiinflamatorio y listo en 20 minutos","en":"Vegan, anti-inflammatory and ready in 20 minutes"}',
8,15,510,18,62,22,14,
ARRAY['vegan','vegetarian','lactose_free','gluten_free','anti_inflammatory','standard'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['endometriosis','anemia','pcos'],
ARRAY[]::text[],
'easy','20_to_40','low',
'{"es":["400g garbanzos cocidos","150g espinacas","200ml leche de coco","1 cda curry en polvo","1 tomate triturado","Â½ cebolla","1 cda aceite de oliva"],"en":["400g cooked chickpeas","150g spinach","200ml coconut milk","1 tbsp curry powder","1 crushed tomato","Â½ onion","1 tbsp olive oil"]}',
'{"es":["SofrÃ­e la cebolla y el curry 3 min","AÃ±ade tomate, garbanzos y leche de coco","Cocina 10 min a fuego suave","Incorpora las espinacas hasta que mermen"],"en":["SautÃ© onion and curry 3 min","Add tomato, chickpeas and coconut milk","Simmer 10 min","Stir in spinach until wilted"]}'
),

('tempeh_quinoa_bowl',56,'lunch','ðŸ¥—',
'{"es":"Bowl de tempeh, quinoa y boniato asado","en":"Tempeh, quinoa and roasted sweet potato bowl","fr":"Bowl tempeh, quinoa et patate douce rÃ´tie","it":"Bowl di tempeh, quinoa e patata dolce al forno"}',
'{"es":"ProteÃ­na fermentada y carbohidrato complejo para entrenar","en":"Fermented protein and complex carbs for training days"}',
15,25,560,28,64,20,11,
ARRAY['vegan','vegetarian','lactose_free','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance','energy'],
ARRAY['pcos'],
ARRAY['soy'],
'medium','20_to_40','medium',
'{"es":["120g tempeh en lÃ¡minas","80g quinoa","1 boniato pequeÃ±o","1 cda salsa de soja","1 cda aceite de oliva","RÃºcula y semillas de calabaza"],"en":["120g sliced tempeh","80g quinoa","1 small sweet potato","1 tbsp soy sauce","1 tbsp olive oil","Rocket and pumpkin seeds"]}',
'{"es":["Asa el boniato en dados a 200Â°C 25 min","Cuece la quinoa 12 min","Dora el tempeh con la soja 3 min por lado","Monta el bowl con rÃºcula y semillas"],"en":["Roast diced sweet potato at 200Â°C 25 min","Cook quinoa 12 min","Brown tempeh with soy 3 min per side","Assemble bowl with rocket and seeds"]}'
),

('tostada_hummus_tomate',57,'breakfast','ðŸž',
'{"es":"Tostada integral con hummus y tomate","en":"Wholegrain toast with hummus and tomato","fr":"Tartine complÃ¨te houmous-tomate","it":"Toast integrale con hummus e pomodoro"}',
'{"es":"Desayuno salado vegano en 5 minutos","en":"Savoury vegan breakfast in 5 minutes"}',
5,2,340,12,44,13,9,
ARRAY['vegan','vegetarian','mediterranean','lactose_free','standard'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY['anemia'],
ARRAY['gluten','sesame'],
'easy','under_20','low',
'{"es":["2 rebanadas de pan integral","60g hummus","1 tomate","OrÃ©gano, aceite de oliva y sal"],"en":["2 slices wholegrain bread","60g hummus","1 tomato","Oregano, olive oil and salt"]}',
'{"es":["Tuesta el pan","Unta el hummus generosamente","Cubre con tomate en rodajas, orÃ©gano y un hilo de aceite"],"en":["Toast the bread","Spread hummus generously","Top with sliced tomato, oregano and a drizzle of oil"]}'
),

('chia_pudding_mango',58,'breakfast','ðŸ¥­',
'{"es":"Pudding de chÃ­a con mango y coco","en":"Chia pudding with mango and coconut","fr":"Pudding de chia mangue-coco","it":"Budino di chia con mango e cocco"}',
'{"es":"Se prepara la noche anterior: desayuno listo al despertar","en":"Made the night before: breakfast ready when you wake up"}',
5,0,330,8,38,16,11,
ARRAY['vegan','vegetarian','lactose_free','gluten_free','anti_inflammatory','paleo'],
ARRAY['ovulation','luteal'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["3 cda semillas de chÃ­a","200ml bebida de coco","Â½ mango maduro","Coco rallado","Unas gotas de vainilla"],"en":["3 tbsp chia seeds","200ml coconut drink","Â½ ripe mango","Grated coconut","A few drops of vanilla"]}',
'{"es":["Mezcla chÃ­a, bebida de coco y vainilla","Refrigera mÃ­nimo 4 horas o toda la noche","Sirve con mango en dados y coco rallado"],"en":["Mix chia, coconut drink and vanilla","Refrigerate at least 4 hours or overnight","Serve with diced mango and grated coconut"]}'
),

('wok_verduras_seitan',59,'dinner','ðŸ¥¡',
'{"es":"Wok de seitÃ¡n con verduras crujientes","en":"Seitan wok with crunchy vegetables","fr":"Wok de seitan aux lÃ©gumes croquants","it":"Wok di seitan con verdure croccanti"}',
'{"es":"Alto en proteÃ­na vegetal, estilo asiÃ¡tico","en":"High in plant protein, Asian style"}',
10,10,420,30,32,18,7,
ARRAY['vegan','vegetarian','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','maintain','performance'],
ARRAY[]::text[],
ARRAY['gluten','soy','sesame'],
'easy','under_20','medium',
'{"es":["150g seitÃ¡n en tiras","1 zanahoria","Â½ pimiento rojo","100g col china","2 cda salsa de soja","1 cda aceite de sÃ©samo","Jengibre y ajo"],"en":["150g seitan strips","1 carrot","Â½ red pepper","100g Chinese cabbage","2 tbsp soy sauce","1 tbsp sesame oil","Ginger and garlic"]}',
'{"es":["Calienta el wok con el aceite muy fuerte","Saltea el seitÃ¡n 2 min y reserva","Saltea las verduras 3-4 min (crujientes)","Junta todo con la soja, ajo y jengibre 1 min"],"en":["Heat wok with oil until very hot","Stir-fry seitan 2 min and set aside","Stir-fry vegetables 3-4 min (keep crunchy)","Combine all with soy, garlic and ginger 1 min"]}'
),

('crema_cacahuete_manzana_snack',60,'afternoon_snack','ðŸŽ',
'{"es":"Manzana con crema de cacahuete y canela","en":"Apple with peanut butter and cinnamon","fr":"Pomme, beurre de cacahuÃ¨te et cannelle","it":"Mela con burro di arachidi e cannella"}',
'{"es":"Snack dulce-salado que corta el antojo de la fase lÃºtea","en":"Sweet-savoury snack that kills luteal cravings"}',
3,0,220,6,25,11,5,
ARRAY['vegan','vegetarian','lactose_free','gluten_free','standard'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','reduce_symptoms'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["1 manzana","1 cda crema de cacahuete 100%","Canela"],"en":["1 apple","1 tbsp 100% peanut butter","Cinnamon"]}',
'{"es":["Corta la manzana en gajos","Unta o moja en la crema de cacahuete","Espolvorea canela"],"en":["Cut apple into wedges","Spread or dip in peanut butter","Sprinkle cinnamon"]}'
),

-- â”€â”€ PALEO â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('pollo_limon_boniato_paleo',61,'lunch','ðŸ—',
'{"es":"Pollo al limÃ³n con boniato asado","en":"Lemon chicken with roasted sweet potato","fr":"Poulet au citron et patate douce rÃ´tie","it":"Pollo al limone con patata dolce al forno"}',
'{"es":"Paleo clÃ¡sico: proteÃ­na magra + tubÃ©rculo","en":"Paleo classic: lean protein + tuber"}',
10,30,520,42,38,20,6,
ARRAY['paleo','gluten_free','lactose_free','high_protein','standard','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance','maintain'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_to_40','medium',
'{"es":["1 pechuga grande de pollo","1 boniato","1 limÃ³n","2 cda aceite de oliva","Romero, ajo en polvo, sal y pimienta"],"en":["1 large chicken breast","1 sweet potato","1 lemon","2 tbsp olive oil","Rosemary, garlic powder, salt and pepper"]}',
'{"es":["Asa el boniato en gajos con aceite a 200Â°C 25-30 min","Marina el pollo con limÃ³n y especias 10 min","Hazlo a la plancha 5-6 min por lado","Sirve con el jugo del limÃ³n asado"],"en":["Roast sweet potato wedges with oil at 200Â°C 25-30 min","Marinate chicken in lemon and spices 10 min","Grill 5-6 min per side","Serve with roasted lemon juice"]}'
),

('ternera_salteada_pimientos_paleo',62,'dinner','ðŸ¥©',
'{"es":"Ternera salteada con pimientos y champiÃ±ones","en":"Beef stir-fry with peppers and mushrooms","fr":"BÅ“uf sautÃ© aux poivrons et champignons","it":"Manzo saltato con peperoni e funghi"}',
'{"es":"Hierro hemo y zinc: refuerzo ideal en la menstruaciÃ³n","en":"Heme iron and zinc: ideal boost during your period"}',
10,10,440,38,12,27,4,
ARRAY['paleo','low_carb','keto','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','follicular'],
ARRAY['gain_muscle','maintain','energy'],
ARRAY['anemia'],
ARRAY[]::text[],
'easy','under_20','high',
'{"es":["180g tiras de ternera","1 pimiento rojo","100g champiÃ±ones","1 diente de ajo","2 cda aceite de oliva","Sal, pimienta y tomillo"],"en":["180g beef strips","1 red pepper","100g mushrooms","1 garlic clove","2 tbsp olive oil","Salt, pepper and thyme"]}',
'{"es":["Saltea la ternera a fuego fuerte 2 min y reserva","Saltea pimiento, champiÃ±ones y ajo 5 min","Junta todo 1 min con tomillo"],"en":["Sear beef over high heat 2 min and set aside","SautÃ© pepper, mushrooms and garlic 5 min","Combine 1 min with thyme"]}'
),

('huevos_rotos_boniato_paleo',63,'breakfast','ðŸ ',
'{"es":"Huevos con boniato y aguacate","en":"Eggs with sweet potato and avocado","fr":"Å’ufs, patate douce et avocat","it":"Uova con patata dolce e avocado"}',
'{"es":"Desayuno paleo completo para dÃ­as de entreno fuerte","en":"Complete paleo breakfast for hard training days"}',
10,15,490,20,38,29,8,
ARRAY['paleo','vegetarian','gluten_free','lactose_free','standard'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance','energy'],
ARRAY[]::text[],
ARRAY['egg'],
'easy','20_to_40','medium',
'{"es":["2 huevos","1 boniato pequeÃ±o","Â½ aguacate","1 cda aceite de oliva","PimentÃ³n y sal"],"en":["2 eggs","1 small sweet potato","Â½ avocado","1 tbsp olive oil","Paprika and salt"]}',
'{"es":["Cocina el boniato en dados en sartÃ©n tapada 10-12 min","Haz los huevos a la plancha encima","Sirve con aguacate y pimentÃ³n"],"en":["Cook diced sweet potato in a covered pan 10-12 min","Fry eggs on top","Serve with avocado and paprika"]}'
),

-- â”€â”€ LOW FODMAP â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('pollo_arroz_zanahoria_fodmap',64,'lunch','ðŸš',
'{"es":"Pollo a la plancha con arroz y zanahoria","en":"Grilled chicken with rice and carrot","fr":"Poulet grillÃ©, riz et carotte","it":"Pollo alla griglia con riso e carota"}',
'{"es":"Plato seguro para digestiones sensibles (low FODMAP)","en":"Safe dish for sensitive digestion (low FODMAP)"}',
5,20,480,38,52,12,3,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','standard'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['maintain','gain_muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_to_40','low',
'{"es":["180g pechuga de pollo","80g arroz blanco","1 zanahoria","1 cda aceite de oliva","Jengibre, sal y cebollino (parte verde)"],"en":["180g chicken breast","80g white rice","1 carrot","1 tbsp olive oil","Ginger, salt and chives (green part)"]}',
'{"es":["Cuece el arroz con la zanahoria en rodajas 15 min","Haz el pollo a la plancha 5-6 min por lado","Sirve con aceite en crudo, jengibre y cebollino"],"en":["Cook rice with sliced carrot 15 min","Grill chicken 5-6 min per side","Serve with raw oil, ginger and chives"]}'
),

('tortilla_patata_fodmap',65,'dinner','ðŸ¥”',
'{"es":"Tortilla de patata y calabacÃ­n (sin cebolla)","en":"Potato and courgette omelette (no onion)","fr":"Tortilla pomme de terre-courgette (sans oignon)","it":"Frittata di patate e zucchine (senza cipolla)"}',
'{"es":"La tortilla de siempre en versiÃ³n apta para SII","en":"The classic omelette in an IBS-friendly version"}',
10,20,420,18,34,24,4,
ARRAY['low_fodmap','vegetarian','gluten_free','lactose_free','standard'],
ARRAY['menstrual','luteal'],
ARRAY['maintain'],
ARRAY[]::text[],
ARRAY['egg'],
'medium','20_to_40','low',
'{"es":["3 huevos","1 patata mediana","Â½ calabacÃ­n","3 cda aceite de oliva","Sal"],"en":["3 eggs","1 medium potato","Â½ courgette","3 tbsp olive oil","Salt"]}',
'{"es":["Pocha la patata y el calabacÃ­n en el aceite 12 min","Escurre y mezcla con los huevos batidos","Cuaja la tortilla 3 min por lado"],"en":["Slowly fry potato and courgette in oil 12 min","Drain and mix with beaten eggs","Set the omelette 3 min per side"]}'
),

('salmon_papillote_fodmap',66,'dinner','ðŸ“¦',
'{"es":"SalmÃ³n en papillote con calabacÃ­n y limÃ³n","en":"Salmon en papillote with courgette and lemon","fr":"Saumon en papillote, courgette et citron","it":"Salmone al cartoccio con zucchine e limone"}',
'{"es":"Sin sartenes: todo al horno en su papel, digestiÃ³n fÃ¡cil","en":"No pans: everything baked in parchment, easy to digest"}',
8,18,430,34,7,29,3,
ARRAY['low_fodmap','pescatarian','low_carb','keto','paleo','gluten_free','lactose_free','anti_inflammatory','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['lose_weight','maintain','reduce_symptoms'],
ARRAY['endometriosis','hypertension'],
ARRAY['fish'],
'easy','under_20','high',
'{"es":["180g salmÃ³n","Â½ calabacÃ­n en rodajas","Â½ limÃ³n","1 cda aceite de oliva","Eneldo y pimienta"],"en":["180g salmon","Â½ sliced courgette","Â½ lemon","1 tbsp olive oil","Dill and pepper"]}',
'{"es":["Pon salmÃ³n y calabacÃ­n sobre papel de horno","AliÃ±a con aceite, limÃ³n y eneldo","Cierra el paquete y hornea a 190Â°C 15-18 min"],"en":["Place salmon and courgette on baking paper","Season with oil, lemon and dill","Seal the parcel and bake at 190Â°C 15-18 min"]}'
),

-- â”€â”€ ALTA PROTEÃNA / ESTÃNDAR (refuerzo desayunos y snacks) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('pancakes_avena_proteicos',67,'breakfast','ðŸ¥ž',
'{"es":"Pancakes proteicos de avena y plÃ¡tano","en":"Oat and banana protein pancakes","fr":"Pancakes protÃ©inÃ©s avoine-banane","it":"Pancake proteici avena e banana"}',
'{"es":"3 ingredientes + proteÃ­na: el desayuno post-entreno","en":"3 ingredients + protein: the post-workout breakfast"}',
5,10,440,32,48,12,6,
ARRAY['high_protein','vegetarian','standard','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance'],
ARRAY[]::text[],
ARRAY['egg'],
'easy','under_20','medium',
'{"es":["60g copos de avena","1 plÃ¡tano","2 huevos","1 scoop proteÃ­na sabor vainilla","Canela y aceite de coco para la sartÃ©n"],"en":["60g oat flakes","1 banana","2 eggs","1 scoop vanilla protein","Cinnamon and coconut oil for the pan"]}',
'{"es":["Tritura todos los ingredientes","Haz pancakes pequeÃ±os 2 min por lado a fuego medio","Sirve con canela y fruta"],"en":["Blend all ingredients","Cook small pancakes 2 min per side over medium heat","Serve with cinnamon and fruit"]}'
),

('skyr_granola_snack',68,'morning_snack','ðŸ«',
'{"es":"Skyr con arÃ¡ndanos y semillas de calabaza","en":"Skyr with blueberries and pumpkin seeds","fr":"Skyr, myrtilles et graines de courge","it":"Skyr con mirtilli e semi di zucca"}',
'{"es":"20g de proteÃ­na en un snack de 3 minutos","en":"20g of protein in a 3-minute snack"}',
3,0,210,20,18,6,3,
ARRAY['high_protein','vegetarian','standard','gluten_free','low_fodmap'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['lose_weight','gain_muscle','maintain'],
ARRAY['pcos'],
ARRAY['lactose'],
'easy','under_20','medium',
'{"es":["150g skyr natural","60g arÃ¡ndanos","1 cda semillas de calabaza"],"en":["150g plain skyr","60g blueberries","1 tbsp pumpkin seeds"]}',
'{"es":["Sirve el skyr en un bol","AÃ±ade arÃ¡ndanos y semillas"],"en":["Spoon skyr into a bowl","Top with blueberries and seeds"]}'
),

('huevo_duro_snack_fodmap',69,'morning_snack','ðŸ¥š',
'{"es":"Huevos duros con tomatitos y sal de hierbas","en":"Boiled eggs with cherry tomatoes and herb salt","fr":"Å’ufs durs, tomates cerises et sel aux herbes","it":"Uova sode con pomodorini e sale alle erbe"}',
'{"es":"Snack proteico de bolsillo, apto low FODMAP","en":"Pocket protein snack, low FODMAP friendly"}',
2,9,180,13,5,12,1,
ARRAY['high_protein','vegetarian','low_carb','keto','paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['ovulation','luteal'],
ARRAY['lose_weight','maintain'],
ARRAY['type2_diabetes'],
ARRAY['egg'],
'easy','under_20','low',
'{"es":["2 huevos","6 tomates cherry","Sal de hierbas"],"en":["2 eggs","6 cherry tomatoes","Herb salt"]}',
'{"es":["Cuece los huevos 9 min","EnfrÃ­a, pela y sirve con los tomatitos y la sal"],"en":["Boil eggs 9 min","Cool, peel and serve with tomatoes and salt"]}'
),

('crema_cacao_avellanas_fit',70,'afternoon_snack','ðŸ«',
'{"es":"Yogur con cacao, avellanas y plÃ¡tano","en":"Yoghurt with cocoa, hazelnuts and banana","fr":"Yaourt cacao, noisettes et banane","it":"Yogurt con cacao, nocciole e banana"}',
'{"es":"El antojo de chocolate de la fase lÃºtea, en versiÃ³n real food","en":"The luteal chocolate craving, real-food version"}',
4,0,260,14,28,11,5,
ARRAY['vegetarian','standard','gluten_free','high_protein'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','reduce_symptoms'],
ARRAY[]::text[],
ARRAY['lactose','nuts'],
'easy','under_20','low',
'{"es":["150g yogur griego","1 cdta cacao puro","Â½ plÃ¡tano","15g avellanas tostadas"],"en":["150g Greek yoghurt","1 tsp pure cocoa","Â½ banana","15g toasted hazelnuts"]}',
'{"es":["Mezcla el yogur con el cacao","AÃ±ade plÃ¡tano en rodajas y avellanas troceadas"],"en":["Mix yoghurt with cocoa","Top with sliced banana and chopped hazelnuts"]}'
)

ON CONFLICT (id) DO NOTHING;

-- VerificaciÃ³n: recuento por dieta tras el lote
-- SELECT unnest(diets) AS dieta, count(*) FROM recipes GROUP BY 1 ORDER BY 2 DESC;
