-- ─────────────────────────────────────────────────────────────────────────────
-- Table: program_content
-- Stores fitness/nutrition program data in all three languages.
-- data_es  → written manually (source of truth, Spanish)
-- data_en  → auto-generated by Edge Function on INSERT/UPDATE of data_es
-- data_fr  → auto-generated by Edge Function on INSERT/UPDATE of data_es
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.program_content (
  id            TEXT        PRIMARY KEY,          -- e.g. 'marina', 'default'
  data_es       JSONB       NOT NULL,             -- Spanish source (edit this one)
  data_en       JSONB,                            -- Auto-filled by Edge Function
  data_fr       JSONB,                            -- Auto-filled by Edge Function
  translated_at TIMESTAMPTZ,                      -- Last time translations were updated
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Row-level security: all authenticated users can read; only service_role can write
ALTER TABLE public.program_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read program_content"
  ON public.program_content FOR SELECT
  USING (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- Trigger: keep updated_at fresh
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS program_content_updated_at ON public.program_content;
CREATE TRIGGER program_content_updated_at
  BEFORE UPDATE ON public.program_content
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- NOTE: The Database Webhook is created via the Supabase Dashboard UI
-- (or via the CLI steps in README below) — not here, because it requires
-- the Edge Function URL which is only known after deployment.
--
-- Webhook settings:
--   Name:    auto-translate-program
--   Table:   program_content
--   Events:  INSERT, UPDATE
--   URL:     https://lpcvkzmfemxziuhdmzpx.supabase.co/functions/v1/translate-program
--   Headers: Authorization: Bearer <service_role_key>
-- ─────────────────────────────────────────────────────────────────────────────
