-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 6 (+30) — display_order 191-220
-- Enfocado en: low_fodmap, standard, postentrenamiento, sweet treats sanos
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 5
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── LOW FODMAP ────────────────────────────────────────────────────────────────

('pollo_zanahoria_jengibre_lf',191,'dinner','🍋',
'{"es":"Pollo con zanahoria y jengibre (low FODMAP)","en":"Chicken with carrot and ginger (low FODMAP)","fr":"Poulet carotte-gingembre (low FODMAP)","it":"Pollo con carota e zenzero (low FODMAP)"}',
'{"es":"Sin cebolla ni ajo — FODMAP bajo con todo el sabor del jengibre","en":"No onion or garlic — low FODMAP with all the flavour from ginger"}',
10,20,360,36,18,14,4,
ARRAY['gluten_free','lactose_free','high_protein','low_fodmap'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','muscle'],
ARRAY['bloating','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g pechuga pollo en dados","3 zanahorias en bastones","1 pimiento rojo","2 cdas jengibre fresco rallado","2 cdas aceite de oliva (sin ajos macerados)","2 cdas tamari","1 cdta azúcar de coco","Cebolleta solo la parte verde, semillas sésamo"],"en":["300g chicken breast diced","3 carrots in sticks","1 red pepper","2 tbsp fresh grated ginger","2 tbsp plain olive oil (no garlic infused)","2 tbsp tamari","1 tsp coconut sugar","Spring onion green part only, sesame seeds"]}',
'{"es":["Calienta aceite en wok y saltea el pollo 5-6 min","Añade zanahoria y pimiento, saltea 4 min","Mezcla tamari, jengibre y azúcar de coco","Vierte la salsa sobre el pollo y verduras, mezcla 2 min","Sirve con la parte verde de cebolleta y sésamo"],"en":["Heat oil in wok and stir-fry chicken 5-6 min","Add carrot and pepper, stir-fry 4 min","Mix tamari, ginger and coconut sugar","Pour sauce over chicken and vegetables, toss 2 min","Serve with spring onion green tops and sesame"]}'
),

('salmón_patata_eneldo_lf',192,'dinner','🐟',
'{"es":"Salmón con patata y eneldo (low FODMAP)","en":"Salmon with potato and dill (low FODMAP)","fr":"Saumon pomme de terre-aneth (low FODMAP)","it":"Salmone con patate e aneto (low FODMAP)"}',
'{"es":"Cena reconfortante y FODMAP baja: salmón al horno con puré de patata suave","en":"Comforting low FODMAP dinner: baked salmon with smooth potato mash"}',
10,25,460,34,36,16,4,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_fodmap','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle'],
ARRAY['bloating','cramps'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 filetes salmón (150g c/u)","300g patata en cubos","2 cdas aceite de oliva","Zumo de limón","Eneldo fresco o seco","Sal, pimienta","Aceite de oliva para el puré"],"en":["2 salmon fillets (150g each)","300g potato cubed","2 tbsp olive oil","Lemon juice","Fresh or dried dill","Salt, pepper","Olive oil for mash"]}',
'{"es":["Cuece las patatas 15-18 min hasta tiernas, haz un puré con aceite y sal","Unta el salmón con aceite, limón, eneldo, sal y pimienta","Hornea a 200°C 15-18 min","Sirve el salmón sobre el puré de patata"],"en":["Boil potatoes 15-18 min until tender, mash with oil and salt","Coat salmon with oil, lemon, dill, salt and pepper","Bake at 200°C 15-18 min","Serve salmon over potato mash"]}'
),

('arroz_pollo_hierbas_lf',193,'lunch','🍚',
'{"es":"Arroz con pollo y hierbas (low FODMAP)","en":"Rice with chicken and herbs (low FODMAP)","fr":"Riz au poulet et herbes (low FODMAP)","it":"Riso con pollo ed erbe (low FODMAP)"}',
'{"es":"Comfort food universal adaptado al bajo FODMAP — sin cebolla, sin ajo","en":"Universal comfort food adapted to low FODMAP — no onion, no garlic"}',
10,25,450,32,54,10,3,
ARRAY['gluten_free','lactose_free','high_protein','low_fodmap'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['bloating','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g arroz basmati","300g pechuga pollo en tiras","1 pimiento rojo","1 zanahoria","600ml caldo de pollo sin cebolla ni ajo","Aceite infusionado con ajo (o aceite oliva normal)","Tomillo, perejil, sal, pimienta"],"en":["200g basmati rice","300g chicken breast in strips","1 red pepper","1 carrot","600ml chicken broth (no onion or garlic)","Garlic-infused oil (or plain olive oil)","Thyme, parsley, salt, pepper"]}',
'{"es":["Dora el pollo en aceite 4-5 min, reserva","Saltea pimiento y zanahoria 3 min","Añade arroz y tuesta 1 min","Incorpora el caldo, hierbas, sal y pimienta","Cuece tapado 15 min. Reincorpora el pollo los últimos 5 min"],"en":["Brown chicken in oil 4-5 min, set aside","Sauté pepper and carrot 3 min","Add rice and toast 1 min","Add broth, herbs, salt and pepper","Cook covered 15 min. Return chicken for final 5 min"]}'
),

('tortilla_patata_lf',194,'lunch','🥚',
'{"es":"Tortilla de patata sin cebolla (low FODMAP)","en":"Potato omelette without onion (low FODMAP)","fr":"Tortilla sans oignon (low FODMAP)","it":"Frittata di patate senza cipolla (low FODMAP)"}',
'{"es":"Tortilla española adaptada al FODMAP bajo — igual de rica sin cebolla","en":"Spanish omelette adapted to low FODMAP — just as delicious without onion"}',
5,20,340,16,30,16,3,
ARRAY['vegetarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY['bloating'],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["4 huevos","2 patatas medianas en rodajas finas","3 cdas aceite de oliva","Sal, pimienta","Cebolleta (solo parte verde, opt)"],"en":["4 eggs","2 medium potatoes thinly sliced","3 tbsp olive oil","Salt, pepper","Spring onion (green tops only, opt)"]}',
'{"es":["Pocha las patatas en aceite a fuego bajo 12-15 min hasta tiernas","Bate los huevos con sal y pimienta","Mezcla las patatas escurridas con los huevos batidos","Cuaja en sartén 4 min por cada lado"],"en":["Poach potatoes in oil over low heat 12-15 min until tender","Beat eggs with salt and pepper","Combine drained potatoes with beaten eggs","Set in pan 4 min per side"]}'
),

-- ── STANDARD (para todos) ─────────────────────────────────────────────────────

('pasta_carbonara_ligera',195,'dinner','🍝',
'{"es":"Carbonara ligera sin nata","en":"Light carbonara without cream","fr":"Carbonara légère sans crème","it":"Carbonara leggera senza panna"}',
'{"es":"La carbonara real: solo huevo, queso y panceta — sin nata nunca","en":"Real carbonara: just egg, cheese and pancetta — never cream"}',
5,15,520,26,58,18,3,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'medium','20_40','medium',
'{"es":["150g pasta espagueti","80g panceta o guanciale en dados","2 huevos + 1 yema extra","40g pecorino o parmesano rallado","Pimienta negra abundante","Sal para el agua de cocción"],"en":["150g spaghetti","80g pancetta or guanciale diced","2 eggs + 1 extra yolk","40g grated pecorino or parmesan","Plenty of black pepper","Salt for cooking water"]}',
'{"es":["Cuece la pasta al dente, reserva 1 taza del agua de cocción","Dora la panceta en sartén seca hasta crujiente","Bate huevos con queso y pimienta en un bol","Fuera del fuego, mezcla pasta con panceta","Añade mezcla de huevo y un poco de agua de pasta, remueve rápido"],"en":["Cook pasta al dente, reserve 1 cup cooking water","Render pancetta in dry pan until crispy","Whisk eggs with cheese and pepper in a bowl","Off heat, toss pasta with pancetta","Add egg mixture and a splash of pasta water, toss quickly"]}'
),

('pollo_pesto_pasta',196,'dinner','🌿',
'{"es":"Pechuga de pollo con pasta al pesto","en":"Chicken breast with pesto pasta","fr":"Blanc de poulet pâtes au pesto","it":"Petto di pollo con pasta al pesto"}',
'{"es":"Clásico italiano express: pesto fresco, pollo a la plancha, pasta en 20 min","en":"Express Italian classic: fresh pesto, grilled chicken, pasta in 20 min"}',
5,18,540,42,46,14,5,
ARRAY['standard','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['gluten','dairy','nuts'],
'easy','20_40','medium',
'{"es":["150g pasta de tu elección","200g pechuga pollo a la plancha","4 cdas pesto de albahaca","Tomates cherry","Parmesano para servir","Sal, pimienta"],"en":["150g pasta of your choice","200g grilled chicken breast","4 tbsp basil pesto","Cherry tomatoes","Parmesan to serve","Salt, pepper"]}',
'{"es":["Cuece la pasta según instrucciones","Haz el pollo a la plancha salpimentado 5-6 min por lado","Mezcla la pasta caliente con el pesto","Sirve con el pollo encima, tomates cherry y parmesano"],"en":["Cook pasta according to instructions","Grill seasoned chicken 5-6 min per side","Toss warm pasta with pesto","Serve with chicken on top, cherry tomatoes and parmesan"]}'
),

('estofado_lentejas_verduras',197,'lunch','🫘',
'{"es":"Estofado de lentejas con verduras","en":"Lentil and vegetable stew","fr":"Ragoût de lentilles aux légumes","it":"Stufato di lenticchie con verdure"}',
'{"es":"Estofado mediterráneo nutritivo, completo y económico — la cuchara española","en":"Nutritious Mediterranean stew, complete and budget-friendly"}',
10,30,380,18,52,8,14,
ARRAY['vegan','gluten_free','vegetarian','standard','mediterranean','lactose_free'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['anemia','fatigue'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas pardinas o verdes","1 patata en cubos","2 zanahorias","1/2 cebolla","2 dientes ajo","1 pimiento verde","1 hoja laurel","1 cdta pimentón dulce","Aceite de oliva, sal, pimienta","800ml agua o caldo"],"en":["200g brown or green lentils","1 potato cubed","2 carrots","1/2 onion","2 garlic cloves","1 green pepper","1 bay leaf","1 tsp sweet paprika","Olive oil, salt, pepper","800ml water or broth"]}',
'{"es":["Sofríe cebolla, ajo y pimiento en aceite 5 min","Añade pimentón y rehoga 30 seg","Incorpora lentejas, patata, zanahoria, laurel y agua","Hierve y cocina 25-30 min a fuego medio hasta tiernas","Ajusta sal y sirve"],"en":["Sauté onion, garlic and pepper in oil 5 min","Add paprika and stir 30 sec","Add lentils, potato, carrot, bay leaf and water","Boil then cook 25-30 min on medium heat until tender","Adjust salt and serve"]}'
),

('tortilla_francesa_jamón',198,'breakfast','🥚',
'{"es":"Tortilla francesa rellena de jamón y queso","en":"French omelette with ham and cheese","fr":"Omelette farcie jambon-fromage","it":"Omelette francese con prosciutto e formaggio"}',
'{"es":"Desayuno o cena express de 5 min: proteína + calcio en una tortilla","en":"5-minute breakfast or dinner: protein + calcium in one omelette"}',
2,5,300,24,4,20,0,
ARRAY['standard','gluten_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["3 huevos","30g jamón cocido o serrano","30g queso semicurado o gruyer rallado","1 cda mantequilla o aceite","Sal, pimienta, cebollino fresco"],"en":["3 eggs","30g cooked or cured ham","30g grated semi-cured or gruyere cheese","1 tbsp butter or oil","Salt, pepper, fresh chives"]}',
'{"es":["Bate los huevos con sal y pimienta","Funde la mantequilla en sartén a fuego medio-alto","Vierte los huevos y remueve hasta que empiecen a cuajar","Cuando esté casi hecho, añade jamón y queso en el centro","Dobla y sirve con cebollino"],"en":["Beat eggs with salt and pepper","Melt butter in pan over medium-high heat","Pour in eggs and stir until starting to set","When almost done, add ham and cheese in centre","Fold and serve with chives"]}'
),

-- ── POST-ENTRENAMIENTO ────────────────────────────────────────────────────────

('tarta_avena_chocolate_proteica',199,'afternoon_snack','🍫',
'{"es":"Tarta proteica de avena y chocolate","en":"Protein oat and chocolate cake","fr":"Gâteau protéiné avoine-chocolat","it":"Torta proteica avena e cioccolato"}',
'{"es":"Bizcocho saludable post-entreno: avena, proteína y cacao — sin azúcar añadido","en":"Healthy post-workout cake: oats, protein and cocoa — no added sugar"}',
10,25,260,18,28,8,5,
ARRAY['vegetarian'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'easy','20_40','low',
'{"es":["100g copos de avena","1 scoop proteína de chocolate","2 huevos","1 plátano maduro","3 cdas cacao puro","1 cdta levadura","100ml leche o bebida vegetal","Pepitas de chocolate negro (opt)"],"en":["100g rolled oats","1 scoop chocolate protein","2 eggs","1 ripe banana","3 tbsp pure cocoa","1 tsp baking powder","100ml milk or plant drink","Dark chocolate chips (opt)"]}',
'{"es":["Tritura la avena hasta harina fina en batidora","Mezcla todos los ingredientes hasta masa homogénea","Vierte en molde 20cm engrasado","Hornea 22-25 min a 175°C — palillo limpio = listo","Deja enfriar 10 min antes de desmoldar"],"en":["Blend oats to fine flour in blender","Mix all ingredients to smooth batter","Pour into greased 20cm tin","Bake 22-25 min at 175°C — clean toothpick = done","Cool 10 min before unmoulding"]}'
),

('batido_recuperacion_postentrenamiento',200,'afternoon_snack','🥤',
'{"es":"Batido de recuperación post-entreno","en":"Post-workout recovery shake","fr":"Shake de récupération post-entraînement","it":"Frullato di recupero post-allenamento"}',
'{"es":"Ventana anabólica: proteína + carbos rápidos justo después del entrenamiento","en":"Anabolic window: protein + fast carbs right after training"}',
3,0,340,32,42,4,3,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','energy'],
ARRAY['fatigue'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["1 scoop proteína de suero (cualquier sabor)","1 plátano maduro","200ml leche desnatada","80g fresas o arándanos","1 cda miel"],"en":["1 scoop whey protein (any flavour)","1 ripe banana","200ml skimmed milk","80g strawberries or blueberries","1 tbsp honey"]}',
'{"es":["Pon todos los ingredientes en la batidora","Tritura 30-45 segundos","Consume dentro de los 30 min posteriores al entrenamiento"],"en":["Add all ingredients to blender","Blend 30-45 seconds","Consume within 30 min after training"]}'
),

('arroz_atun_aceite_oliva',201,'lunch','🍚',
'{"es":"Arroz con atún y aceite de oliva","en":"Rice with tuna and olive oil","fr":"Riz thon-huile d''olive","it":"Riso con tonno e olio d''oliva"}',
'{"es":"Clásico post-entreno sin cocinar: arroz + atún en 2 minutos","en":"Classic no-cook post-workout: rice + tuna in 2 minutes"}',
2,12,440,30,56,8,3,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','standard'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','energy'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["80g arroz blanco o basmati","160g atún al natural (lata, escurrido)","1 cdta aceite de oliva","Sal, pimienta","Zumo de limón, perejil (opt)"],"en":["80g white or basmati rice","160g tuna in water (can, drained)","1 tsp olive oil","Salt, pepper","Lemon juice, parsley (opt)"]}',
'{"es":["Cuece el arroz según instrucciones","Escurre el atún","Mezcla arroz caliente con atún, aceite, sal y pimienta","Añade limón y perejil al gusto"],"en":["Cook rice according to instructions","Drain the tuna","Mix warm rice with tuna, oil, salt and pepper","Add lemon and parsley to taste"]}'
),

-- ── DESAYUNOS ADICIONALES ─────────────────────────────────────────────────────

('tostadas_mantequilla_platano',202,'breakfast','🍞',
'{"es":"Tostadas con mantequilla de almendras y plátano","en":"Toast with almond butter and banana","fr":"Toasts beurre d''amandes et banane","it":"Toast con burro di mandorle e banana"}',
'{"es":"Desayuno sencillo y energético: carbos, grasas y dulzor natural","en":"Simple energising breakfast: carbs, fats and natural sweetness"}',
3,3,380,10,50,16,6,
ARRAY['vegetarian','vegan'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['gluten','nuts'],
'easy','under_20','low',
'{"es":["2 rebanadas pan integral o de centeno","2 cdas mantequilla de almendras","1/2 plátano en rodajas","1 pizca canela","Semillas de chía (opt)"],"en":["2 slices wholegrain or rye bread","2 tbsp almond butter","1/2 banana sliced","1 pinch cinnamon","Chia seeds (opt)"]}',
'{"es":["Tuesta el pan","Extiende la mantequilla de almendras","Coloca el plátano encima y espolvorea canela y semillas de chía"],"en":["Toast the bread","Spread almond butter","Top with banana slices and sprinkle cinnamon and chia seeds"]}'
),

('fruta_seca_mixta',203,'morning_snack','🥜',
'{"es":"Mix de frutos secos y semillas","en":"Mixed nuts and seeds mix","fr":"Mélange de noix et graines","it":"Mix di frutta secca e semi"}',
'{"es":"El snack más simple: energía densa, omega-3 y sin preparación","en":"The simplest snack: dense energy, omega-3 and zero prep"}',
1,0,200,6,8,17,3,
ARRAY['vegan','gluten_free','vegetarian','keto','paleo','low_carb','low_fodmap'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['energy','maintain'],
ARRAY['cramps','fatigue'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["10g nueces","10g almendras","5g semillas de calabaza","5g semillas de girasol","5g anacardos (en fase folicular/ovulación)"],"en":["10g walnuts","10g almonds","5g pumpkin seeds","5g sunflower seeds","5g cashews (follicular/ovulation phase)"]}',
'{"es":["Pesa y mezcla en una bolsita o bol pequeño","Consume como snack a media mañana o entre horas"],"en":["Weigh and mix in a small bag or bowl","Eat as mid-morning or between-meal snack"]}'
),

-- ── ALMUERZOS ADICIONALES ─────────────────────────────────────────────────────

('pad_thai_pollo',204,'lunch','🍜',
'{"es":"Pad Thai de pollo","en":"Chicken pad Thai","fr":"Pad Thai au poulet","it":"Pad Thai di pollo"}',
'{"es":"Clásico tailandés en casa: fideos de arroz, pollo, huevo y salsa de tamarindo","en":"Thai classic at home: rice noodles, chicken, egg and tamarind sauce"}',
15,12,480,30,56,14,4,
ARRAY['gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['eggs','soy','nuts'],
'medium','20_40','medium',
'{"es":["150g fideos de arroz","200g pechuga pollo en tiras","2 huevos","100g brotes de soja","2 cebolletas","Salsa: 2 cdas tamari, 1 cda zumo lima, 1 cdta pasta tamarindo, 1 cdta azúcar","Cacahuetes triturados, cilantro, lima"],"en":["150g rice noodles","200g chicken breast in strips","2 eggs","100g bean sprouts","2 spring onions","Sauce: 2 tbsp tamari, 1 tbsp lime juice, 1 tsp tamarind paste, 1 tsp sugar","Crushed peanuts, coriander, lime"]}',
'{"es":["Remoja los fideos en agua caliente 8 min, escurre","Saltea el pollo en aceite 5 min en wok","Aparta el pollo, haz los huevos revueltos en el wok","Añade fideos, brotes, salsa y pollo — saltea 3 min","Sirve con cacahuetes, cilantro y lima"],"en":["Soak noodles in hot water 8 min, drain","Stir-fry chicken in oil 5 min in wok","Push chicken aside, scramble eggs in wok","Add noodles, sprouts, sauce and chicken — toss 3 min","Serve with peanuts, coriander and lime"]}'
),

('ensalada_caprese',205,'lunch','🍅',
'{"es":"Ensalada caprese clásica","en":"Classic caprese salad","fr":"Salade caprese classique","it":"Insalata caprese classica"}',
'{"es":"La trilogía italiana perfecta: tomate, mozzarella, albahaca y aceite de oliva","en":"The perfect Italian trilogy: tomato, mozzarella, basil and olive oil"}',
5,0,310,16,12,22,2,
ARRAY['vegetarian','gluten_free','mediterranean'],
ARRAY['ovulation','follicular'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','medium',
'{"es":["250g tomates de pera o kumato maduros","150g mozzarella fresca","Albahaca fresca","3 cdas aceite de oliva virgen extra","Sal marina, pimienta negra","Vinagre balsámico (opt)"],"en":["250g plum or kumato tomatoes ripe","150g fresh mozzarella","Fresh basil","3 tbsp extra virgin olive oil","Sea salt, black pepper","Balsamic vinegar (opt)"]}',
'{"es":["Corta los tomates y la mozzarella en rodajas del mismo grosor","Alterna en el plato: tomate, mozzarella, albahaca","Aliña con aceite, sal y pimienta","Añade un hilo de balsámico si te gusta"],"en":["Slice tomatoes and mozzarella to same thickness","Alternate on plate: tomato, mozzarella, basil","Dress with oil, salt and pepper","Drizzle balsamic if you like"]}'
),

('burrito_pollo_frijoles',206,'lunch','🌯',
'{"es":"Burrito de pollo y frijoles","en":"Chicken and bean burrito","fr":"Burrito poulet-haricots","it":"Burrito di pollo e fagioli"}',
'{"es":"Burrito completo con proteína, fibra y carbos energéticos","en":"Complete burrito with protein, fibre and energising carbs"}',
10,10,560,34,62,14,10,
ARRAY['standard','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'easy','20_40','low',
'{"es":["1 tortilla de trigo grande","150g pollo a la plancha en tiras","120g frijoles negros cocidos","40g arroz blanco cocido","30g queso cheddar rallado","2 cdas salsa de tomate","1/4 aguacate aplastado","Sal, comino, pimentón"],"en":["1 large flour tortilla","150g grilled chicken in strips","120g cooked black beans","40g cooked white rice","30g grated cheddar","2 tbsp tomato salsa","1/4 avocado mashed","Salt, cumin, paprika"]}',
'{"es":["Calienta la tortilla en sartén 30 seg por lado","Coloca todos los ingredientes en el centro","Dobla los bordes y enrolla bien apretado","Opcional: dóralo en la sartén 1 min por lado para sellarlo"],"en":["Warm tortilla in pan 30 sec per side","Place all ingredients in centre","Fold edges and roll tightly","Optional: toast in pan 1 min per side to seal"]}'
),

-- ── CENAS ADICIONALES ─────────────────────────────────────────────────────────

('carne_asada_boniato_asado',207,'dinner','🥩',
'{"es":"Entrecot con boniato asado y ensalada verde","en":"Sirloin steak with roasted sweet potato and green salad","fr":"Entrecôte patate douce rôtie et salade","it":"Controfiletto con patata dolce arrostita e insalata"}',
'{"es":"La cena perfecta para la fase menstrual: hierro hemínico + vitamina A + fibra","en":"Perfect dinner for menstrual phase: heme iron + vitamin A + fibre"}',
5,30,520,36,34,22,6,
ARRAY['gluten_free','lactose_free','high_protein','paleo','standard'],
ARRAY['menstrual','luteal'],
ARRAY['muscle','maintain'],
ARRAY['anemia','cramps','fatigue'],
ARRAY[]::text[],
'medium','40_60','high',
'{"es":["200g entrecot o solomillo","1 boniato mediano","Mix de hojas verdes","1 tomate","Vinagreta de mostaza","Sal, pimienta, aceite de oliva","Romero"],"en":["200g sirloin or fillet steak","1 medium sweet potato","Mixed green leaves","1 tomato","Mustard vinaigrette","Salt, pepper, olive oil","Rosemary"]}',
'{"es":["Precalienta horno a 200°C","Corta el boniato en gajos con piel, aliña con aceite, romero y sal","Hornea 25-30 min hasta tierno y dorado","Saca el boniato, calienta plancha al máximo y cocina el entrecot 2-3 min por lado","Sirve con la ensalada verde aliñada"],"en":["Preheat oven to 200°C","Cut sweet potato in wedges with skin, dress with oil, rosemary and salt","Roast 25-30 min until tender and golden","Remove potato, heat griddle to max and cook steak 2-3 min per side","Serve with dressed green salad"]}'
),

('pollo_cacciatore',208,'dinner','🍅',
'{"es":"Pollo alla cacciatora","en":"Chicken cacciatore","fr":"Poulet chasseur","it":"Pollo alla cacciatora"}',
'{"es":"Guiso italiano de pollo con tomate, aceitunas y hierbas — rústico y delicioso","en":"Italian chicken stew with tomatoes, olives and herbs — rustic and delicious"}',
10,35,390,34,18,18,5,
ARRAY['gluten_free','lactose_free','high_protein','mediterranean'],
ARRAY['luteal','menstrual','follicular'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','40_60','medium',
'{"es":["4 contramuslos de pollo sin piel","400g tomate triturado","60g aceitunas sin hueso","1/2 cebolla","3 dientes ajo","100ml vino tinto","Tomillo, romero, laurel","Aceite de oliva, sal, pimienta"],"en":["4 skinless chicken thighs","400g crushed tomatoes","60g pitted olives","1/2 onion","3 garlic cloves","100ml red wine","Thyme, rosemary, bay leaf","Olive oil, salt, pepper"]}',
'{"es":["Dora el pollo en aceite 4-5 min por lado, reserva","Sofríe cebolla y ajo en el mismo aceite 3 min","Añade vino, evapora 2 min","Incorpora tomate, aceitunas, hierbas y el pollo","Cocina tapado 25-30 min a fuego lento"],"en":["Brown chicken in oil 4-5 min per side, set aside","Sauté onion and garlic in same oil 3 min","Add wine, evaporate 2 min","Add tomatoes, olives, herbs and chicken","Cook covered 25-30 min on low heat"]}'
),

('pizza_coliflor_base',209,'dinner','🍕',
'{"es":"Pizza con base de coliflor","en":"Cauliflower crust pizza","fr":"Pizza à base de chou-fleur","it":"Pizza con base di cavolfiore"}',
'{"es":"Base de pizza baja en carbos con coliflor — sin gluten y crujiente","en":"Low-carb pizza base with cauliflower — gluten-free and crispy"}',
20,25,340,20,18,20,8,
ARRAY['vegetarian','gluten_free','keto','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'medium','40_60','low',
'{"es":["1 coliflor mediana (aprox 600g)","1 huevo","50g mozzarella rallada para la base","Sal, orégano, ajo en polvo","Toppings: salsa de tomate, mozzarella, albahaca, tomates cherry"],"en":["1 medium cauliflower (approx 600g)","1 egg","50g grated mozzarella for base","Salt, oregano, garlic powder","Toppings: tomato sauce, mozzarella, basil, cherry tomatoes"]}',
'{"es":["Tritura la coliflor hasta grano fino y cocina 4 min en microondas","Deja enfriar, exprime en paño para eliminar agua (paso clave)","Mezcla con huevo, queso, sal y especias","Extiende en bandeja y hornea 20 min a 220°C hasta dorada","Añade toppings y hornea 8-10 min más"],"en":["Pulse cauliflower to fine grain and microwave 4 min","Cool then squeeze in a cloth to remove water (key step)","Mix with egg, cheese, salt and spices","Spread on tray and bake 20 min at 220°C until golden","Add toppings and bake 8-10 min more"]}'
),

('crema_brocoli_coco',210,'dinner','🥦',
'{"es":"Crema de brócoli y leche de coco","en":"Broccoli and coconut cream","fr":"Crème de brocoli au lait de coco","it":"Crema di broccoli e latte di cocco"}',
'{"es":"Crema verde antiinflamatoria: brócoli con cúrcuma y leche de coco","en":"Green anti-inflammatory cream: broccoli with turmeric and coconut milk"}',
5,20,240,8,22,14,7,
ARRAY['vegan','gluten_free','vegetarian','anti_inflammatory','lactose_free','keto','low_carb'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['lose_weight','maintain'],
ARRAY['inflammation','bloating'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["600g brócoli en flores","200ml leche de coco","400ml caldo de verduras","1 cdta cúrcuma","1/2 cdta jengibre","2 dientes ajo","Sal, pimienta","Semillas de calabaza para decorar"],"en":["600g broccoli florets","200ml coconut milk","400ml vegetable broth","1 tsp turmeric","1/2 tsp ginger","2 garlic cloves","Salt, pepper","Pumpkin seeds to garnish"]}',
'{"es":["Sofríe el ajo en aceite 2 min","Añade brócoli, cúrcuma y jengibre, rehoga 2 min","Vierte el caldo y cuece 12-15 min hasta tierno","Añade leche de coco y tritura hasta crema suave","Ajusta sal y sirve con semillas de calabaza"],"en":["Sauté garlic in oil 2 min","Add broccoli, turmeric and ginger, stir 2 min","Pour broth and cook 12-15 min until tender","Add coconut milk and blend until smooth","Adjust salt and serve with pumpkin seeds"]}'
),

('berberechos_vinagreta',211,'dinner','🦪',
'{"es":"Berberechos en vinagreta","en":"Cockles in vinaigrette","fr":"Coques en vinaigrette","it":"Vongole in vinaigrette"}',
'{"es":"Aperitivo o cena ligera: proteína de mar con vinagreta refrescante","en":"Starter or light dinner: seafood protein with refreshing vinaigrette"}',
10,0,180,20,8,6,1,
ARRAY['pescatarian','gluten_free','lactose_free','keto','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["300g berberechos en conserva al natural","1/2 pimiento rojo en daditos","1/4 cebolla roja en daditos","1 tomate en daditos","2 cdas aceite de oliva","1 cda vinagre de jerez","Perejil fresco, sal, pimienta"],"en":["300g canned cockles in brine","1/2 red pepper diced","1/4 red onion diced","1 tomato diced","2 tbsp olive oil","1 tbsp sherry vinegar","Fresh parsley, salt, pepper"]}',
'{"es":["Escurre y aclara los berberechos","Mezcla pimiento, cebolla y tomate","Prepara la vinagreta con aceite, vinagre, sal y pimienta","Combina todo y deja reposar 10 min antes de servir"],"en":["Drain and rinse cockles","Mix pepper, onion and tomato","Make vinaigrette with oil, vinegar, salt and pepper","Combine everything and rest 10 min before serving"]}'
),

('fideos_soba_teriyaki',212,'dinner','🍜',
'{"es":"Fideos soba con pollo teriyaki","en":"Soba noodles with chicken teriyaki","fr":"Nouilles soba au poulet teriyaki","it":"Spaghetti soba con pollo teriyaki"}',
'{"es":"Cena japonesa ligera: fideos de trigo sarraceno con pollo glaseado","en":"Light Japanese dinner: buckwheat noodles with glazed chicken"}',
10,15,470,32,54,12,4,
ARRAY['lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['gluten','soy','sesame'],
'easy','20_40','medium',
'{"es":["150g fideos soba","200g pechuga pollo en tiras","Salsa teriyaki: 2 cdas tamari, 1 cda mirin, 1 cdta miel, 1 cdta maicena","1 zanahoria en juliana","2 cebolletas","Sésamo, jengibre"],"en":["150g soba noodles","200g chicken breast in strips","Teriyaki sauce: 2 tbsp tamari, 1 tbsp mirin, 1 tsp honey, 1 tsp cornstarch","1 carrot julienned","2 spring onions","Sesame, ginger"]}',
'{"es":["Cuece los soba 5-6 min, escurre y reserva","Saltea el pollo en aceite 5 min","Añade la salsa teriyaki y cocina 3 min hasta que espese y glasee","Sirve sobre los fideos con zanahoria, cebolleta y sésamo"],"en":["Cook soba 5-6 min, drain and set aside","Stir-fry chicken in oil 5 min","Add teriyaki sauce and cook 3 min until it thickens and glazes","Serve over noodles with carrot, spring onion and sesame"]}'
),

-- ── RECETAS ESPECIALES ────────────────────────────────────────────────────────

('caldo_huesos_casero',213,'dinner','🍵',
'{"es":"Caldo de huesos casero","en":"Homemade bone broth","fr":"Bouillon d''os maison","it":"Brodo di ossa fatto in casa"}',
'{"es":"Superalimento para la fase menstrual: colágeno, minerales y reconfortante","en":"Superfood for menstrual phase: collagen, minerals and deeply comforting"}',
10,120,80,8,4,3,0,
ARRAY['gluten_free','lactose_free','paleo','keto','low_carb','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY['cramps','anemia','fatigue'],
ARRAY[]::text[],
'easy','over_60','low',
'{"es":["1kg huesos de ternera o pollo (carcasas)","2 zanahorias","2 ramas apio","1 cebolla partida","2 dientes ajo","1 cda vinagre de manzana (ayuda a extraer minerales)","Sal, pimienta en grano, laurel, tomillo","3L agua"],"en":["1kg beef or chicken bones (carcasses)","2 carrots","2 celery stalks","1 onion halved","2 garlic cloves","1 tbsp apple cider vinegar (helps extract minerals)","Salt, peppercorns, bay leaf, thyme","3L water"]}',
'{"es":["Pon los huesos en olla con el agua y el vinagre — espera 30 min antes de encender","Hierve y elimina la espuma que sube","Añade verduras y hierbas","Cuece a fuego muy bajo 2-4 horas tapado (o 8-12h si tienes tiempo)","Cuela y guarda en botes. Dura 5 días en nevera o 3 meses congelado"],"en":["Place bones in pot with water and vinegar — wait 30 min before turning on heat","Bring to boil and remove rising foam","Add vegetables and herbs","Simmer on very low heat 2-4 hours covered (or 8-12h if time allows)","Strain and store in jars. Keeps 5 days fridge or 3 months frozen"]}'
),

('pudin_chia_mango',214,'afternoon_snack','🥭',
'{"es":"Pudín de chía con mango y lima","en":"Chia pudding with mango and lime","fr":"Pudding chia mangue-citron vert","it":"Pudding di chia con mango e lime"}',
'{"es":"Snack o desayuno cremoso: omega-3 de la chía con dulzor tropical del mango","en":"Creamy snack or breakfast: omega-3 from chia with tropical sweetness of mango"}',
5,0,280,8,34,12,12,
ARRAY['vegan','gluten_free','vegetarian','lactose_free','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY['inflammation'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["3 cdas semillas de chía","200ml leche de coco light","1 cdta miel o sirope de arce","1/2 cdta extracto de vainilla","1/2 mango maduro en dados","Zumo y ralladura de lima"],"en":["3 tbsp chia seeds","200ml light coconut milk","1 tsp honey or maple syrup","1/2 tsp vanilla extract","1/2 ripe mango diced","Lime juice and zest"]}',
'{"es":["Mezcla chía con leche de coco, miel y vainilla","Remueve bien y refrigera mínimo 4 horas (mejor overnight)","Al servir, añade el mango y el zumo de lima"],"en":["Mix chia with coconut milk, honey and vanilla","Stir well and refrigerate at least 4 hours (overnight is better)","When serving, top with mango and lime juice"]}'
),

('crumble_manzana_avena',215,'afternoon_snack','🍎',
'{"es":"Crumble de manzana y avena","en":"Apple and oat crumble","fr":"Crumble pomme-avoine","it":"Crumble di mela e avena"}',
'{"es":"Postre sano o merienda caliente: manzana caramelizada con crumble de avena","en":"Healthy dessert or warm snack: caramelised apple with oat crumble"}',
10,20,290,5,44,11,5,
ARRAY['vegetarian','vegan'],
ARRAY['luteal','follicular'],
ARRAY['energy','maintain'],
ARRAY['cramps','pms'],
ARRAY['gluten','nuts'],
'easy','20_40','low',
'{"es":["3 manzanas peladas y en dados","1 cdta canela","1 cda miel o azúcar de coco","Para el crumble: 80g avena, 2 cdas aceite de coco, 1 cda miel, 1 pizca sal"],"en":["3 apples peeled and diced","1 tsp cinnamon","1 tbsp honey or coconut sugar","For crumble: 80g oats, 2 tbsp coconut oil, 1 tbsp honey, 1 pinch salt"]}',
'{"es":["Mezcla las manzanas con canela y miel, coloca en molde","Mezcla los ingredientes del crumble y esparce por encima","Hornea 20 min a 180°C hasta dorado"],"en":["Mix apples with cinnamon and honey, place in baking dish","Mix crumble ingredients and scatter over top","Bake 20 min at 180°C until golden"]}'
),

('muffins_espinacas_queso',216,'morning_snack','🧇',
'{"es":"Muffins salados de espinacas y queso","en":"Savoury spinach and cheese muffins","fr":"Muffins salés épinards-fromage","it":"Muffin salati spinaci e formaggio"}',
'{"es":"Merienda salada portátil: proteína + hierro + calcio para llevar","en":"Portable savoury snack: protein + iron + calcium to go"}',
10,20,180,10,12,10,2,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['energy','muscle'],
ARRAY['anemia'],
ARRAY['eggs','dairy'],
'easy','20_40','low',
'{"es":["3 huevos","100g espinacas frescas picadas","50g queso rallado (cheddar o emmental)","50g harina de avena o de arroz","1 cdta levadura","Sal, pimienta, ajo en polvo","Aceite para los moldes"],"en":["3 eggs","100g fresh spinach chopped","50g grated cheese (cheddar or emmental)","50g oat or rice flour","1 tsp baking powder","Salt, pepper, garlic powder","Oil for moulds"]}',
'{"es":["Precalienta horno a 180°C","Bate los huevos, añade espinacas, queso, harina, levadura y especias","Vierte en moldes de muffin engrasados (sale aprox 6)","Hornea 18-20 min hasta dorados y firmes"],"en":["Preheat oven to 180°C","Beat eggs, add spinach, cheese, flour, baking powder and spices","Pour into greased muffin moulds (makes approx 6)","Bake 18-20 min until golden and firm"]}'
),

('ensalada_pollo_mango',217,'lunch','🥗',
'{"es":"Ensalada de pollo y mango con vinagreta de lima","en":"Chicken and mango salad with lime dressing","fr":"Salade poulet-mangue vinaigrette citron vert","it":"Insalata di pollo e mango con vinaigrette al lime"}',
'{"es":"Ensalada fresca tropical que mezcla proteína y fruta — verano todo el año","en":"Fresh tropical salad combining protein and fruit — summer all year"}',
10,10,360,30,28,12,4,
ARRAY['gluten_free','lactose_free','high_protein','standard'],
ARRAY['ovulation','follicular'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["200g pechuga de pollo a la plancha en tiras","1/2 mango maduro en dados","Mix de hojas verdes","1/4 pepino en rodajas","Cilantro fresco","Vinagreta: zumo de 2 limas, 1 cda aceite de oliva, 1 cdta miel, sal"],"en":["200g grilled chicken breast in strips","1/2 ripe mango diced","Mixed green leaves","1/4 cucumber sliced","Fresh coriander","Dressing: juice of 2 limes, 1 tbsp olive oil, 1 tsp honey, salt"]}',
'{"es":["Haz el pollo a la plancha salpimentado 5-6 min por lado, deja enfriar ligeramente","Prepara la vinagreta de lima mezclando sus ingredientes","Coloca las hojas verdes, pepino, mango y pollo","Aliña y espolvorea cilantro"],"en":["Grill seasoned chicken 5-6 min per side, cool slightly","Make lime dressing by mixing its ingredients","Arrange greens, cucumber, mango and chicken","Dress and scatter coriander"]}'
),

('croquetas_pollo_jamon',218,'dinner','🍽️',
'{"es":"Croquetas de pollo y jamón (versión saludable)","en":"Chicken and ham croquettes (healthier version)","fr":"Croquettes poulet-jambon (version saine)","it":"Crocchette di pollo e prosciutto (versione sana)"}',
'{"es":"Croquetas horneadas en vez de fritas — el clásico español aligerado","en":"Baked not fried croquettes — lightened Spanish classic"}',
20,25,360,20,34,14,3,
ARRAY['standard','high_protein'],
ARRAY['follicular','luteal'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'medium','40_60','medium',
'{"es":["200g pollo cocido desmenuzado","50g jamón serrano picado","40g mantequilla","40g harina","400ml leche caliente","Nuez moscada, sal, pimienta","Pan rallado, 1 huevo para rebozar"],"en":["200g shredded cooked chicken","50g serrano ham diced","40g butter","40g flour","400ml warm milk","Nutmeg, salt, pepper","Breadcrumbs, 1 egg for coating"]}',
'{"es":["Funde mantequilla, añade harina y cocina 2 min removiendo","Añade leche caliente poco a poco, remueve hasta bechamel espesa","Incorpora pollo y jamón, salpimenta y añade nuez moscada","Enfría la masa en nevera 2 horas mínimo","Forma croquetas, pasa por huevo y pan rallado, hornea 20 min a 200°C"],"en":["Melt butter, add flour and cook 2 min stirring","Add warm milk gradually, stir to thick béchamel","Add chicken and ham, season with salt, pepper and nutmeg","Cool dough in fridge minimum 2 hours","Shape croquettes, coat in egg and breadcrumbs, bake 20 min at 200°C"]}'
),

('verduras_salteadas_jengibre',219,'dinner','🥦',
'{"es":"Verduras salteadas con jengibre y sésamo","en":"Stir-fried vegetables with ginger and sesame","fr":"Légumes sautés gingembre-sésame","it":"Verdure saltate con zenzero e sesamo"}',
'{"es":"Guarnición o plato vegano express: colorida, antiinflamatoria y lista en 15 min","en":"Side dish or express vegan main: colourful, anti-inflammatory and ready in 15 min"}',
10,8,200,6,22,10,7,
ARRAY['vegan','gluten_free','vegetarian','anti_inflammatory','lactose_free','low_carb'],
ARRAY['follicular','ovulation','menstrual'],
ARRAY['maintain','energy'],
ARRAY['inflammation','bloating'],
ARRAY['soy','sesame'],
'easy','under_20','low',
'{"es":["1 brócoli en flores","1 zanahoria en bastones","1 pimiento rojo en tiras","100g setas","2 cdas aceite de sésamo","2 cdas tamari","1 cdta jengibre rallado","1 diente ajo laminado","Semillas de sésamo"],"en":["1 broccoli in florets","1 carrot in sticks","1 red pepper in strips","100g mushrooms","2 tbsp sesame oil","2 tbsp tamari","1 tsp grated ginger","1 garlic clove sliced","Sesame seeds"]}',
'{"es":["Calienta aceite de sésamo en wok a fuego alto","Añade ajo y jengibre, saltea 30 seg","Incorpora las verduras más duras primero (zanahoria, brócoli)","Añade el resto, vierte tamari y saltea 5-6 min al dente","Sirve con sésamo por encima"],"en":["Heat sesame oil in wok on high heat","Add garlic and ginger, stir-fry 30 sec","Add the harder vegetables first (carrot, broccoli)","Add the rest, pour tamari and stir-fry 5-6 min al dente","Serve topped with sesame seeds"]}'
),

('panna_cotta_vainilla_frutos_rojos',220,'afternoon_snack','🍮',
'{"es":"Panna cotta de vainilla con frutos rojos","en":"Vanilla panna cotta with berries","fr":"Panna cotta vanille aux fruits rouges","it":"Panna cotta alla vaniglia con frutti di bosco"}',
'{"es":"Postre italiano ligero: suave, cremoso y con coulis de frutos rojos","en":"Light Italian dessert: smooth, creamy with a berry coulis"}',
10,5,200,4,18,12,2,
ARRAY['vegetarian','gluten_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','medium',
'{"es":["400ml leche entera o nata para montar","2 hojas gelatina (o 1 cdta agar agar para versión vegana)","2 cdas azúcar o sirope de arce","1 cdta extracto de vainilla","Para el coulis: 100g frutos rojos, 1 cda miel"],"en":["400ml whole milk or single cream","2 gelatine sheets (or 1 tsp agar agar for vegan)","2 tbsp sugar or maple syrup","1 tsp vanilla extract","For coulis: 100g berries, 1 tbsp honey"]}',
'{"es":["Remoja la gelatina en agua fría 5 min","Calienta la leche con azúcar y vainilla sin hervir","Escurre la gelatina e incorpórala removiendo hasta disolver","Vierte en vasitos y refrigera 4 horas mínimo","Prepara el coulis calentando los frutos rojos con miel 5 min y triturando"],"en":["Soak gelatine in cold water 5 min","Heat milk with sugar and vanilla without boiling","Drain gelatine and stir in until dissolved","Pour into glasses and refrigerate minimum 4 hours","Make coulis by heating berries with honey 5 min and blending"]}'
)
ON CONFLICT (id) DO NOTHING;
