-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- MEIRINS Â· Recetas LOTE 3 (+30) â€” display_order 101-130
-- Enfocado en categorÃ­as dÃ©biles: keto, low_fodmap, paleo, pescatarian
-- Ejecutar en Supabase SQL Editor DESPUÃ‰S del lote 2
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- â”€â”€ DESAYUNOS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('panqueques_coco_keto',101,'breakfast','ðŸ¥ž',
'{"es":"Panqueques de coco keto","en":"Keto coconut pancakes","fr":"Pancakes coco keto","it":"Pancake keto al cocco"}',
'{"es":"Solo 3 ingredientes y 0 gluten: huevo, queso crema y harina de coco","en":"Just 3 ingredients and 0 gluten: egg, cream cheese and coconut flour"}',
5,10,320,18,6,26,3,
ARRAY['keto','low_carb','gluten_free','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','energy'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["2 huevos","60g queso crema natural","2 cdas harina de coco","1 pizca sal","1 cdta extracto vainilla (opt)","Aceite de coco para la sartÃ©n"],"en":["2 eggs","60g cream cheese","2 tbsp coconut flour","1 pinch salt","1 tsp vanilla extract (opt)","Coconut oil for pan"]}',
'{"es":["Mezcla huevos, queso crema, harina de coco, sal y vainilla hasta obtener una masa homogÃ©nea","Calienta una sartÃ©n con aceite de coco a fuego medio","Vierte pequeÃ±as porciones de masa y cocina 2-3 min por lado","Sirve con frutos del bosque o nata"],"en":["Blend eggs, cream cheese, coconut flour, salt and vanilla until smooth","Heat pan with coconut oil over medium heat","Pour small portions and cook 2-3 min per side","Serve with berries or whipped cream"]}'
),

('huevos_aguacate_horneados',102,'breakfast','ðŸ¥‘',
'{"es":"Huevos al horno en aguacate","en":"Baked eggs in avocado","fr":"Å’ufs au four dans l''avocat","it":"Uova al forno nell''avocado"}',
'{"es":"Desayuno keto express: aguacate como cuenco natural para el huevo al horno","en":"Express keto breakfast: avocado as natural bowl for baked egg"}',
5,15,380,16,8,32,7,
ARRAY['keto','low_carb','paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['luteal','follicular'],
ARRAY['lose_weight','energy'],
ARRAY[]::text[],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["1 aguacate maduro","2 huevos","Sal y pimienta","PimentÃ³n ahumado","Cebollino fresco (opt)"],"en":["1 ripe avocado","2 eggs","Salt and pepper","Smoked paprika","Fresh chives (opt)"]}',
'{"es":["Precalienta el horno a 200Â°C","Corta el aguacate por la mitad y retira un poco de pulpa para que quepa el huevo","Coloca cada mitad en una bandeja de horno","Casca un huevo en cada mitad, sazona","Hornea 12-15 min hasta que la clara cuaje"],"en":["Preheat oven to 200Â°C","Halve avocado and scoop out a little flesh to fit the egg","Place halves on baking tray","Crack one egg into each half, season","Bake 12-15 min until white is set"]}'
),

('chia_leche_coco_fodmap',103,'breakfast','ðŸ¥¥',
'{"es":"Pudding de chÃ­a con leche de coco","en":"Coconut milk chia pudding","fr":"Pudding de chia au lait de coco","it":"Pudding di chia con latte di cocco"}',
'{"es":"Bajo FODMAP, vegano y preparado la noche anterior: el desayuno sin estrÃ©s","en":"Low-FODMAP, vegan and prep-ahead: the stress-free breakfast"}',
5,0,310,8,22,22,9,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['ibs','bloating'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["200ml leche de coco (lata)","3 cdas semillas de chÃ­a","1 cdta sirope de arce","1/2 cdta vainilla","Kiwi o fresas para decorar"],"en":["200ml coconut milk (can)","3 tbsp chia seeds","1 tsp maple syrup","1/2 tsp vanilla","Kiwi or strawberries to top"]}',
'{"es":["Mezcla la leche de coco con las semillas de chÃ­a, sirope y vainilla","Remueve bien y deja reposar 5 min, vuelve a remover para evitar grumos","Refrigera tapado al menos 4h o toda la noche","Sirve con frutas bajas en FODMAP (kiwi, fresas)"],"en":["Mix coconut milk with chia seeds, syrup and vanilla","Stir well, rest 5 min, stir again to prevent clumps","Refrigerate covered at least 4h or overnight","Serve with low-FODMAP fruits (kiwi, strawberries)"]}'
),

-- â”€â”€ COMIDAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('salmon_espinacas_keto',104,'lunch','ðŸŸ',
'{"es":"SalmÃ³n con espinacas a la crema","en":"Salmon with creamed spinach","fr":"Saumon aux Ã©pinards Ã  la crÃ¨me","it":"Salmone con spinaci cremosi"}',
'{"es":"Comida keto completa: omega-3 del salmÃ³n + hierro de las espinacas + grasas saludables","en":"Complete keto meal: omega-3 from salmon + iron from spinach + healthy fats"}',
10,20,520,42,7,35,4,
ARRAY['keto','low_carb','pescatarian','gluten_free','low_fodmap'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy'],
ARRAY['anemia','pms'],
ARRAY['fish','dairy'],
'medium','20_40','medium',
'{"es":["2 lomos de salmÃ³n (150g c/u)","200g espinacas baby","100ml nata para cocinar","30g queso parmesano rallado","1 cdta ajo en polvo (no ajo fresco â€” low FODMAP)","Sal, pimienta, aceite de oliva"],"en":["2 salmon fillets (150g each)","200g baby spinach","100ml cooking cream","30g grated parmesan","1 tsp garlic powder (no fresh garlic â€” low FODMAP)","Salt, pepper, olive oil"]}',
'{"es":["Sazona el salmÃ³n con sal, pimienta y ajo en polvo","CocÃ­nalo en sartÃ©n con aceite de oliva 4-5 min por lado","En la misma sartÃ©n, aÃ±ade las espinacas y rehoga 2 min","AÃ±ade la nata y el parmesano, cocina 3 min removiendo","Sirve el salmÃ³n sobre el lecho de espinacas a la crema"],"en":["Season salmon with salt, pepper and garlic powder","Cook in olive oil pan 4-5 min per side","In same pan, add spinach and sautÃ© 2 min","Add cream and parmesan, cook 3 min stirring","Serve salmon over creamed spinach"]}'
),

('bowl_atun_quinoa_pescatarian',105,'lunch','ðŸ ',
'{"es":"Bowl de atÃºn con quinoa y pepino","en":"Tuna quinoa cucumber bowl","fr":"Bowl thon quinoa concombre","it":"Bowl tonno quinoa cetriolo"}',
'{"es":"ProteÃ­na marina + cereal completo: combinaciÃ³n ideal para fase lÃºtea","en":"Marine protein + complete grain: ideal combination for luteal phase"}',
10,15,450,38,42,12,6,
ARRAY['pescatarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['luteal','follicular'],
ARRAY['maintain','muscle'],
ARRAY['pms','inflammation'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["150g atÃºn en agua (escurrido)","80g quinoa","1/2 pepino","10 tomates cherry","2 cdas aceite de oliva","Zumo de 1/2 limÃ³n","Sal, orÃ©gano, eneldo"],"en":["150g tuna in water (drained)","80g quinoa","1/2 cucumber","10 cherry tomatoes","2 tbsp olive oil","Juice of 1/2 lemon","Salt, oregano, dill"]}',
'{"es":["Cocina la quinoa en agua con sal 15 min, escurre y deja enfriar","Corta el pepino y los tomates cherry","Mezcla el atÃºn con el aliÃ±o de aceite de oliva, limÃ³n y especias","Monta el bowl: quinoa + verduras + atÃºn aliÃ±ado"],"en":["Cook quinoa in salted water 15 min, drain and cool","Dice cucumber and halve cherry tomatoes","Mix tuna with olive oil, lemon juice and spices dressing","Build bowl: quinoa + vegetables + dressed tuna"]}'
),

('pollo_coliflor_arroz_paleo',106,'lunch','ðŸ—',
'{"es":"Pollo salteado con arroz de coliflor","en":"Stir-fry chicken with cauliflower rice","fr":"Poulet sautÃ© au riz de chou-fleur","it":"Pollo saltato con riso di cavolfiore"}',
'{"es":"Paleo y bajo FODMAP: el arroz de coliflor sustituye al cereal sin perder volumen","en":"Paleo and low-FODMAP: cauliflower rice replaces grain without losing volume"}',
10,15,420,38,14,24,6,
ARRAY['paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','20_40','low',
'{"es":["200g pechuga de pollo en tiras","300g coliflor","1 zanahoria","100g judÃ­as verdes","2 cdas salsa de coco aminos (sin soja)","1 cdta jengibre rallado","Aceite de coco"],"en":["200g chicken breast strips","300g cauliflower","1 carrot","100g green beans","2 tbsp coconut aminos sauce","1 tsp grated ginger","Coconut oil"]}',
'{"es":["Ralla la coliflor o tritÃºrala en procesador hasta obtener granos tipo arroz","Saltea el pollo en aceite de coco 5 min","AÃ±ade la zanahoria y judÃ­as, saltea 3 min mÃ¡s","Agrega el arroz de coliflor y saltea 3 min","AÃ±ade coco aminos y jengibre, mezcla bien"],"en":["Grate cauliflower or pulse in food processor to rice-sized grains","Stir-fry chicken in coconut oil 5 min","Add carrot and green beans, stir-fry 3 more min","Add cauliflower rice and stir-fry 3 min","Add coconut aminos and ginger, mix well"]}'
),

('ensalada_nicoise_pescatarian',107,'lunch','ðŸ¥—',
'{"es":"Ensalada niÃ§oise con atÃºn fresco","en":"NiÃ§oise salad with fresh tuna","fr":"Salade niÃ§oise au thon frais","it":"Insalata niÃ§oise con tonno fresco"}',
'{"es":"ClÃ¡sico francÃ©s rico en omega-3 y proteÃ­na: perfecto para la fase folicular","en":"French classic rich in omega-3 and protein: perfect for follicular phase"}',
15,10,490,36,22,28,7,
ARRAY['pescatarian','gluten_free','lactose_free','paleo','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY['fatigue'],
ARRAY['fish','eggs'],
'medium','under_20','medium',
'{"es":["150g lomo de atÃºn fresco","2 huevos","100g judÃ­as verdes cocidas","8 tomates cherry","8 aceitunas negras","Hojas de lechuga romana","2 cdas aceite de oliva virgen","1 cdta mostaza Dijon","Zumo de limÃ³n"],"en":["150g fresh tuna loin","2 eggs","100g cooked green beans","8 cherry tomatoes","8 black olives","Romaine lettuce leaves","2 tbsp extra virgin olive oil","1 tsp Dijon mustard","Lemon juice"]}',
'{"es":["Cocina los huevos 8 min, enfrÃ­a y pela","Marca el atÃºn en sartÃ©n caliente 2 min por lado (debe quedar rosado)","Prepara la vinagreta con aceite, mostaza y limÃ³n","Monta la ensalada con la lechuga de base, aÃ±ade todos los ingredientes","AliÃ±a en el momento de servir"],"en":["Boil eggs 8 min, cool and peel","Sear tuna in hot pan 2 min per side (should be pink inside)","Make vinaigrette with oil, mustard and lemon","Build salad with lettuce base, add all ingredients","Dress just before serving"]}'
),

('caldo_huesos_paleo',108,'lunch','ðŸ²',
'{"es":"Sopa de caldo de huesos con verduras","en":"Bone broth vegetable soup","fr":"Soupe au bouillon d''os et lÃ©gumes","it":"Zuppa di brodo di ossa con verdure"}',
'{"es":"Anti-inflamatoria y reconfortante: ideal para los primeros dÃ­as de la regla","en":"Anti-inflammatory and comforting: ideal for the first days of your period"}',
15,20,280,24,18,10,5,
ARRAY['paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['inflammation','cramps','pms'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["500ml caldo de huesos (o caldo de pollo casero)","100g pechuga de pollo desmenuzada","1 zanahoria en rodajas","100g espinacas baby","1 rama apio","Sal, pimienta, cÃºrcuma","Jengibre fresco rallado"],"en":["500ml bone broth (or homemade chicken broth)","100g shredded chicken breast","1 sliced carrot","100g baby spinach","1 celery stalk","Salt, pepper, turmeric","Fresh grated ginger"]}',
'{"es":["Calienta el caldo a fuego medio","AÃ±ade la zanahoria y el apio, cocina 10 min","Agrega el pollo desmenuzado, la cÃºrcuma y el jengibre","AÃ±ade las espinacas y cocina 3 min mÃ¡s","Sazona y sirve caliente"],"en":["Heat broth over medium heat","Add carrot and celery, cook 10 min","Add shredded chicken, turmeric and ginger","Add spinach and cook 3 more min","Season and serve hot"]}'
),

('lubina_hinojo_fodmap',109,'lunch','ðŸŸ',
'{"es":"Lubina al horno con hinojo y limÃ³n","en":"Baked sea bass with fennel and lemon","fr":"Bar au four avec fenouil et citron","it":"Branzino al forno con finocchio e limone"}',
'{"es":"Bajo FODMAP y rico en proteÃ­na magra: el hinojo facilita la digestiÃ³n","en":"Low-FODMAP and rich in lean protein: fennel aids digestion"}',
10,25,380,38,8,20,4,
ARRAY['pescatarian','paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['ibs','bloating'],
ARRAY['fish'],
'medium','20_40','medium',
'{"es":["2 lomos de lubina (150g c/u)","1 bulbo de hinojo en lÃ¡minas","1 limÃ³n en rodajas","3 cdas aceite de oliva","Sal, pimienta","Tomillo fresco","Eneldo"],"en":["2 sea bass fillets (150g each)","1 fennel bulb sliced","1 lemon in rounds","3 tbsp olive oil","Salt, pepper","Fresh thyme","Dill"]}',
'{"es":["Precalienta el horno a 200Â°C","Coloca el hinojo en la base de la fuente, riega con 2 cdas de aceite","Pon los lomos de lubina encima, cubre con las rodajas de limÃ³n","Sazona, aÃ±ade el tomillo y el eneldo","Hornea 20-25 min"],"en":["Preheat oven to 200Â°C","Place fennel in baking dish base, drizzle with 2 tbsp oil","Lay sea bass fillets on top, cover with lemon slices","Season, add thyme and dill","Bake 20-25 min"]}'
),

('hamburguesa_ternera_paleo',110,'lunch','ðŸ”',
'{"es":"Hamburguesa de ternera con boniato","en":"Beef burger with sweet potato","fr":"Burger bÅ“uf avec patate douce","it":"Burger di manzo con patata dolce"}',
'{"es":"Sin pan, sin gluten: la hamburguesa paleo que sÃ­ te sacia de verdad","en":"No bun, no gluten: the paleo burger that actually satisfies"}',
10,20,580,38,32,28,6,
ARRAY['paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','luteal'],
ARRAY['muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','20_40','medium',
'{"es":["200g carne de ternera picada","1 boniato mediano","Lechuga iceberg","1 tomate","Mostaza (sin gluten)","Sal, pimienta, comino","Aceite de oliva"],"en":["200g minced beef","1 medium sweet potato","Iceberg lettuce","1 tomato","Mustard (gluten-free)","Salt, pepper, cumin","Olive oil"]}',
'{"es":["Precalienta el horno a 200Â°C. Corta el boniato en rodajas y hornea 20 min","Mezcla la ternera con sal, pimienta y comino, forma una hamburguesa","Cocina en sartÃ©n caliente 4-5 min por lado","Monta: hoja de lechuga + hamburguesa + tomate + mostaza + rodajas de boniato"],"en":["Preheat oven to 200Â°C. Slice sweet potato and bake 20 min","Mix beef with salt, pepper and cumin, form a patty","Cook in hot pan 4-5 min per side","Build: lettuce leaf + burger + tomato + mustard + sweet potato slices"]}'
),

-- â”€â”€ CENAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('curry_gambas_coco',111,'dinner','ðŸ¤',
'{"es":"Curry de gambas con leche de coco","en":"Shrimp coconut curry","fr":"Curry de crevettes Ã  la noix de coco","it":"Curry di gamberetti al cocco"}',
'{"es":"Pescetariano, bajo FODMAP y reconfortante: el curry que cuida la microbiota","en":"Pescatarian, low-FODMAP and comforting: the curry that cares for your gut"}',
10,20,420,32,16,26,4,
ARRAY['pescatarian','keto','low_carb','gluten_free','lactose_free','paleo','low_fodmap'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY['inflammation','bloating'],
ARRAY['shellfish'],
'medium','20_40','medium',
'{"es":["250g gambas peladas","200ml leche de coco","1 lata de tomate triturado (200g)","1 cdta curry en polvo","1 cdta cÃºrcuma","1 cdta jengibre rallado","Cilantro fresco","Aceite de coco","Sal"],"en":["250g peeled shrimp","200ml coconut milk","1 can crushed tomato (200g)","1 tsp curry powder","1 tsp turmeric","1 tsp grated ginger","Fresh cilantro","Coconut oil","Salt"]}',
'{"es":["Calienta aceite de coco en sartÃ©n a fuego medio","AÃ±ade curry, cÃºrcuma y jengibre, tuesta 1 min removiendo","Agrega el tomate triturado y la leche de coco, mezcla bien","Cocina 8 min a fuego suave","AÃ±ade las gambas y cocina 4-5 min hasta que estÃ©n rosadas","Decora con cilantro fresco"],"en":["Heat coconut oil in pan over medium heat","Add curry, turmeric and ginger, toast 1 min stirring","Add crushed tomato and coconut milk, mix well","Cook 8 min on low heat","Add shrimp and cook 4-5 min until pink","Garnish with fresh cilantro"]}'
),

('coliflor_asada_keto',112,'dinner','ðŸ¥¦',
'{"es":"Coliflor asada con queso y tocino","en":"Roasted cauliflower with cheese and bacon","fr":"Chou-fleur rÃ´ti au fromage et lardons","it":"Cavolfiore arrosto con formaggio e pancetta"}',
'{"es":"Keto reconfortante: el sabor de la gratinado sin el carbohidrato del cereal","en":"Comforting keto: gratin flavor without the carb of grain"}',
10,25,480,22,14,38,6,
ARRAY['keto','low_carb','gluten_free','vegetarian'],
ARRAY['luteal','follicular'],
ARRAY['lose_weight','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','20_40','low',
'{"es":["1 coliflor mediana","100g beicon en tiras","80g queso cheddar rallado","3 cdas nata para cocinar","2 cdas aceite de oliva","Sal, pimienta","PimentÃ³n ahumado"],"en":["1 medium cauliflower","100g bacon strips","80g grated cheddar","3 tbsp cooking cream","2 tbsp olive oil","Salt, pepper","Smoked paprika"]}',
'{"es":["Precalienta el horno a 210Â°C","Corta la coliflor en ramilletes, adereza con aceite, sal, pimienta y pimentÃ³n","Hornea 15 min hasta que empiece a dorar","Saltea el beicon en sartÃ©n hasta crujiente","Saca la coliflor, vierte la nata, el queso y el beicon encima","Hornea 10 min mÃ¡s hasta que el queso burbujee"],"en":["Preheat oven to 210Â°C","Cut cauliflower into florets, toss with oil, salt, pepper and paprika","Bake 15 min until starting to brown","Pan-fry bacon until crispy","Remove cauliflower, top with cream, cheese and bacon","Bake 10 more min until cheese bubbles"]}'
),

('salmÃ³n_teriyaki_paleo',113,'dinner','ðŸ ',
'{"es":"SalmÃ³n teriyaki paleo con brÃ³coli","en":"Paleo teriyaki salmon with broccoli","fr":"Saumon teriyaki palÃ©o avec brocoli","it":"Salmone teriyaki paleo con broccoli"}',
'{"es":"Sin salsa de soja: el teriyaki paleo usa coco aminos para el mismo umami","en":"No soy sauce: paleo teriyaki uses coconut aminos for the same umami"}',
10,15,490,40,12,30,5,
ARRAY['paleo','keto','low_carb','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'medium','20_40','medium',
'{"es":["2 lomos de salmÃ³n","3 cdas coco aminos","1 cda miel (sin azÃºcar para keto: stevia)","1 cdta jengibre rallado","200g brÃ³coli","1 cda aceite de sÃ©samo","Semillas de sÃ©samo","Cebollino"],"en":["2 salmon fillets","3 tbsp coconut aminos","1 tbsp honey (for keto: stevia drops)","1 tsp grated ginger","200g broccoli","1 tbsp sesame oil","Sesame seeds","Chives"]}',
'{"es":["Mezcla coco aminos, miel/stevia y jengibre para la salsa","Marina el salmÃ³n 10 min en la salsa","Cuece el brÃ³coli al vapor 5 min","Cocina el salmÃ³n en sartÃ©n con aceite de sÃ©samo 4 min por lado","AÃ±ade el resto de la salsa y deja caramelizar 1 min","Sirve con el brÃ³coli, semillas de sÃ©samo y cebollino"],"en":["Mix coconut aminos, honey/stevia and ginger for sauce","Marinate salmon 10 min in sauce","Steam broccoli 5 min","Cook salmon in sesame oil pan 4 min per side","Add rest of sauce and let caramelize 1 min","Serve with broccoli, sesame seeds and chives"]}'
),

('tortilla_verduras_fodmap',114,'dinner','ðŸ³',
'{"es":"Tortilla de verduras bajas en FODMAP","en":"Low-FODMAP vegetable omelette","fr":"Omelette aux lÃ©gumes faibles en FODMAP","it":"Frittata di verdure low-FODMAP"}',
'{"es":"Cena ligera y digestiva: solo verduras tolerables para intestino sensible","en":"Light and digestive dinner: only gut-friendly vegetables"}',
10,12,380,24,12,26,4,
ARRAY['vegetarian','keto','low_carb','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY['ibs','bloating'],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["4 huevos","1/2 pimiento rojo","100g espinacas baby","6 tomates cherry","1 cdta aceite de oliva","Sal, pimienta","OrÃ©gano seco"],"en":["4 eggs","1/2 red bell pepper","100g baby spinach","6 cherry tomatoes","1 tsp olive oil","Salt, pepper","Dried oregano"]}',
'{"es":["Bate los huevos con sal, pimienta y orÃ©gano","Saltea el pimiento en aceite de oliva 2 min","AÃ±ade las espinacas y los tomates cherry, cocina 2 min mÃ¡s","Vierte los huevos batidos, cocina a fuego medio-bajo sin tocar 5 min","Dobla la tortilla por la mitad y sirve"],"en":["Beat eggs with salt, pepper and oregano","SautÃ© bell pepper in olive oil 2 min","Add spinach and cherry tomatoes, cook 2 more min","Pour beaten eggs, cook over medium-low without touching 5 min","Fold omelette in half and serve"]}'
),

('bacalao_pisto_pescatarian',115,'dinner','ðŸŸ',
'{"es":"Bacalao al horno con pisto de verduras","en":"Baked cod with vegetable ratatouille","fr":"Cabillaud au four avec ratatouille","it":"Merluzzo al forno con ratatouille"}',
'{"es":"ProteÃ­na magra sobre base de verduras mediterrÃ¡neas: ligero y nutritivo","en":"Lean protein on Mediterranean vegetable base: light and nutritious"}',
15,25,360,34,18,14,6,
ARRAY['pescatarian','paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY['inflammation'],
ARRAY['fish'],
'medium','20_40','medium',
'{"es":["2 lomos de bacalao fresco (150g c/u)","1 calabacÃ­n","1 berenjena pequeÃ±a","2 tomates maduros","1/2 pimiento rojo","2 cdas aceite de oliva","Tomillo, romero, sal, pimienta"],"en":["2 fresh cod fillets (150g each)","1 zucchini","1 small eggplant","2 ripe tomatoes","1/2 red bell pepper","2 tbsp olive oil","Thyme, rosemary, salt, pepper"]}',
'{"es":["Precalienta el horno a 200Â°C","Corta todas las verduras en dados, coloca en fuente con aceite y hierbas","Hornea las verduras 15 min","Coloca los lomos de bacalao sobre el pisto, sazona","Hornea 10-12 min mÃ¡s hasta que el bacalao estÃ© opaco"],"en":["Preheat oven to 200Â°C","Dice all vegetables, place in baking dish with oil and herbs","Bake vegetables 15 min","Lay cod fillets on ratatouille, season","Bake 10-12 more min until cod is opaque"]}'
),

-- â”€â”€ SNACKS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('nueces_semillas_keto',116,'snack','ðŸ¥œ',
'{"es":"Mix keto de nueces y semillas","en":"Keto nuts and seeds mix","fr":"Mix keto noix et graines","it":"Mix keto di noci e semi"}',
'{"es":"El snack mÃ¡s rÃ¡pido del mundo keto: grasas saludables, 0 cocciÃ³n","en":"The world''s fastest keto snack: healthy fats, zero cooking"}',
3,0,280,9,6,26,3,
ARRAY['keto','low_carb','paleo','vegan','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal','follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["20g nueces pecanas","15g semillas de calabaza","10g semillas de girasol","5g coco rallado sin azÃºcar","Pizca de sal marina","Pizca de canela (opt)"],"en":["20g pecans","15g pumpkin seeds","10g sunflower seeds","5g unsweetened shredded coconut","Pinch of sea salt","Pinch of cinnamon (opt)"]}',
'{"es":["Mezcla todos los ingredientes en un bol","Tuesta 3 min en sartÃ©n sin aceite a fuego medio si quieres intensificar el sabor","Guarda en un bote hermÃ©tico hasta 1 semana"],"en":["Mix all ingredients in a bowl","Toast 3 min in dry pan over medium heat if you want more flavor","Store in airtight jar up to 1 week"]}'
),

('pepino_salmon_ahumado',117,'snack','ðŸ¥’',
'{"es":"Botes de pepino con salmÃ³n ahumado","en":"Cucumber cups with smoked salmon","fr":"Rondelles de concombre au saumon fumÃ©","it":"Rondelle di cetriolo con salmone affumicato"}',
'{"es":"Snack keto y bajo FODMAP: elegante, fresco y sin carbohidratos","en":"Keto and low-FODMAP snack: elegant, fresh and carb-free"}',
5,0,180,16,4,11,1,
ARRAY['keto','low_carb','pescatarian','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["1 pepino grande","80g salmÃ³n ahumado","2 cdas queso de cabra suave (opt â€” omitir para low-FODMAP estricto)","Eneldo fresco","Zumo de limÃ³n","Pimienta negra"],"en":["1 large cucumber","80g smoked salmon","2 tbsp soft goat cheese (opt â€” omit for strict low-FODMAP)","Fresh dill","Lemon juice","Black pepper"]}',
'{"es":["Corta el pepino en rodajas gruesas de 2 cm","Con una cuchara pequeÃ±a, haz un hueco en cada rodaja sin perforar la base","Coloca el salmÃ³n ahumado en cada hueco","AÃ±ade una pizca de queso de cabra (opt), eneldo y zumo de limÃ³n","Sazona con pimienta"],"en":["Cut cucumber into 2cm thick rounds","Use small spoon to hollow each round without piercing base","Place smoked salmon in each hollow","Add a little goat cheese (opt), dill and lemon juice","Season with black pepper"]}'
),

('chips_kale_paleo',118,'snack','ðŸ¥¬',
'{"es":"Chips de kale al horno","en":"Baked kale chips","fr":"Chips de chou kale au four","it":"Chips di cavolo kale al forno"}',
'{"es":"El snack crujiente paleo: rico en hierro y vitamina K, 0 aceite industrial","en":"The crunchy paleo snack: rich in iron and vitamin K, 0 industrial oil"}',
5,15,120,5,10,7,4,
ARRAY['paleo','vegan','vegetarian','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY['anemia'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["150g hojas de kale frescas","1 cda aceite de oliva","Sal marina","PimentÃ³n ahumado (opt)","Levadura nutricional (opt)"],"en":["150g fresh kale leaves","1 tbsp olive oil","Sea salt","Smoked paprika (opt)","Nutritional yeast (opt)"]}',
'{"es":["Precalienta el horno a 160Â°C","Lava y seca bien las hojas de kale (muy importante que estÃ©n secas)","Retira los tallos gruesos y trocea las hojas","Mezcla con aceite de oliva, sal y pimentÃ³n","Extiende en bandeja y hornea 12-15 min hasta que estÃ©n crujientes"],"en":["Preheat oven to 160Â°C","Wash and dry kale leaves very well (crucial they are dry)","Remove thick stems and tear leaves","Toss with olive oil, salt and paprika","Spread on baking sheet and bake 12-15 min until crispy"]}'
),

('huevos_rellenos_pescatarian',119,'snack','ðŸ¥š',
'{"es":"Huevos rellenos con atÃºn y aguacate","en":"Deviled eggs with tuna and avocado","fr":"Å’ufs farcis au thon et avocat","it":"Uova ripiene con tonno e avocado"}',
'{"es":"Snack alto en proteÃ­na y bajo FODMAP: perfecto para despuÃ©s del entreno","en":"High-protein low-FODMAP snack: perfect post-workout"}',
10,8,260,20,4,18,3,
ARRAY['pescatarian','keto','low_carb','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'easy','under_20','low',
'{"es":["4 huevos","80g atÃºn en agua escurrido","1/2 aguacate","Zumo de 1/4 limÃ³n","Sal, pimienta","PimentÃ³n para decorar","Cebollino fresco"],"en":["4 eggs","80g drained tuna in water","1/2 avocado","Juice of 1/4 lemon","Salt, pepper","Paprika for garnish","Fresh chives"]}',
'{"es":["Cuece los huevos 8 min, enfrÃ­a en agua con hielo y pela","Corta por la mitad y separa las yemas","Aplasta las yemas con el aguacate, el atÃºn, el limÃ³n, sal y pimienta","Rellena las claras con la mezcla","Decora con pimentÃ³n y cebollino"],"en":["Boil eggs 8 min, cool in ice water and peel","Halve and separate yolks","Mash yolks with avocado, tuna, lemon, salt and pepper","Fill whites with mixture","Garnish with paprika and chives"]}'
),

-- â”€â”€ MÃS COMIDAS (focalizadas en keto/paleo/fodmap) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

('ensalada_pollo_nuez',120,'lunch','ðŸ¥—',
'{"es":"Ensalada de pollo con nueces y rÃºcula","en":"Chicken walnut arugula salad","fr":"Salade poulet noix roquette","it":"Insalata pollo noci rucola"}',
'{"es":"Keto y paleo: la nuez aporta omega-3 vegetal que potencia la acciÃ³n antiinflamatoria del pollo","en":"Keto and paleo: walnuts add plant omega-3 that enhances chicken anti-inflammatory action"}',
10,15,520,38,8,36,3,
ARRAY['keto','paleo','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','luteal'],
ARRAY['maintain','muscle'],
ARRAY['inflammation'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["180g pechuga de pollo","60g rÃºcula","30g nueces","8 tomates cherry","2 cdas aceite de oliva","1 cda vinagre de sidra de manzana","Sal, pimienta, mostaza (sin gluten)"],"en":["180g chicken breast","60g arugula","30g walnuts","8 cherry tomatoes","2 tbsp olive oil","1 tbsp apple cider vinegar","Salt, pepper, mustard (gluten-free)"]}',
'{"es":["Cocina la pechuga de pollo a la plancha 6-7 min por lado con sal y pimienta","Deja reposar 5 min y corta en tiras","Prepara la vinagreta con aceite, vinagre y mostaza","Monta la ensalada: rÃºcula + tomates + nueces + pollo + vinagreta"],"en":["Grill chicken breast 6-7 min per side with salt and pepper","Rest 5 min and slice","Make vinaigrette with oil, vinegar and mustard","Build salad: arugula + tomatoes + walnuts + chicken + vinaigrette"]}'
),

('mejillones_vapor_pescatarian',121,'lunch','ðŸ¦ª',
'{"es":"Mejillones al vapor con caldo de vino","en":"Steamed mussels in white wine broth","fr":"Moules Ã  la mariniÃ¨re","it":"Cozze al vapore con brodo di vino"}',
'{"es":"El marisco mÃ¡s econÃ³mico: alto en hierro, zinc y proteÃ­na, bajo en grasa","en":"The most affordable seafood: high in iron, zinc and protein, low in fat"}',
10,15,280,28,10,10,2,
ARRAY['pescatarian','paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy'],
ARRAY['anemia','fatigue'],
ARRAY['shellfish'],
'easy','under_20','low',
'{"es":["800g mejillones frescos","100ml vino blanco seco","Perejil fresco","Zumo de limÃ³n","1 cda aceite de oliva","Pimienta negra"],"en":["800g fresh mussels","100ml dry white wine","Fresh parsley","Lemon juice","1 tbsp olive oil","Black pepper"]}',
'{"es":["Limpia los mejillones bajo agua frÃ­a, retira las barbas","En una olla grande, calienta el aceite de oliva","AÃ±ade el vino blanco y lleva a ebulliciÃ³n","Agrega los mejillones, tapa y cocina 5-6 min agitando la olla","Descarta los que no se hayan abierto","Sirve con el caldo, limÃ³n y perejil picado"],"en":["Clean mussels under cold water, remove beards","In large pot, heat olive oil","Add white wine and bring to boil","Add mussels, cover and cook 5-6 min shaking pot","Discard any that didn''t open","Serve with broth, lemon and chopped parsley"]}'
),

('ternera_boniato_paleo',122,'lunch','ðŸ¥©',
'{"es":"Estofado de ternera con boniato","en":"Beef and sweet potato stew","fr":"RagoÃ»t de bÅ“uf Ã  la patate douce","it":"Stufato di manzo con patata dolce"}',
'{"es":"Paleo reconfortante: el boniato da el dulzor natural que equilibra el estofado","en":"Comforting paleo: sweet potato gives the natural sweetness that balances the stew"}',
15,40,560,38,36,20,6,
ARRAY['paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','muscle'],
ARRAY['cramps','fatigue'],
ARRAY[]::text[],
'medium','40_60','medium',
'{"es":["300g ternera en dados","1 boniato grande en cubos","2 zanahorias","200g tomate triturado","300ml caldo de carne","1 cda aceite de oliva","Romero, tomillo, sal, pimienta"],"en":["300g diced beef","1 large sweet potato diced","2 carrots","200g crushed tomato","300ml beef broth","1 tbsp olive oil","Rosemary, thyme, salt, pepper"]}',
'{"es":["Sella la ternera en aceite de oliva 3-4 min hasta dorar","AÃ±ade las zanahorias, boniato y hierbas","Agrega el tomate triturado y el caldo","Cuece a fuego lento 35-40 min hasta que la ternera estÃ© tierna","Rectifica la sazÃ³n y sirve"],"en":["Sear beef in olive oil 3-4 min until browned","Add carrots, sweet potato and herbs","Add crushed tomato and broth","Simmer 35-40 min until beef is tender","Adjust seasoning and serve"]}'
),

('gambas_aguacate_lettuce',123,'dinner','ðŸ¥¬',
'{"es":"Wrap de lechuga con gambas y aguacate","en":"Lettuce wrap with shrimp and avocado","fr":"Wrap de laitue avec crevettes et avocat","it":"Wrap di lattuga con gamberetti e avocado"}',
'{"es":"Keto y bajo FODMAP: la hoja de lechuga reemplaza la tortilla sin sacrificar textura","en":"Keto and low-FODMAP: lettuce leaf replaces the tortilla without sacrificing texture"}',
10,8,350,28,8,24,5,
ARRAY['keto','low_carb','pescatarian','paleo','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','low',
'{"es":["200g gambas cocidas","1 aguacate","6 hojas grandes de lechuga iceberg","8 tomates cherry","Zumo de limÃ³n","Cilantro fresco","Sal, pimienta","Salsa picante (opt)"],"en":["200g cooked shrimp","1 avocado","6 large iceberg lettuce leaves","8 cherry tomatoes","Lemon juice","Fresh cilantro","Salt, pepper","Hot sauce (opt)"]}',
'{"es":["Aplasta el aguacate con limÃ³n, sal y pimienta (guacamole rÃ¡pido)","Corta los tomates cherry por la mitad","Distribuye el guacamole en las hojas de lechuga","AÃ±ade las gambas y los tomates","Decora con cilantro y salsa picante al gusto"],"en":["Mash avocado with lemon, salt and pepper (quick guacamole)","Halve cherry tomatoes","Spread guacamole on lettuce leaves","Add shrimp and tomatoes","Garnish with cilantro and hot sauce to taste"]}'
),

('pez_espada_ensalada_paleo',124,'dinner','ðŸ¡',
'{"es":"Pez espada a la plancha con ensalada paleo","en":"Grilled swordfish with paleo salad","fr":"Espadon grillÃ© avec salade palÃ©o","it":"Pesce spada alla griglia con insalata paleo"}',
'{"es":"ProteÃ­na densa y saciante con vegetales crudos: la cena paleo mÃ¡s rÃ¡pida","en":"Dense and filling protein with raw vegetables: the fastest paleo dinner"}',
10,8,440,42,8,26,4,
ARRAY['pescatarian','paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["200g filete de pez espada","Zumo de 1 limÃ³n","2 cdas aceite de oliva","Tomillo, orÃ©gano","50g rÃºcula","1 tomate","1/2 aguacate","Sal, pimienta"],"en":["200g swordfish steak","Juice of 1 lemon","2 tbsp olive oil","Thyme, oregano","50g arugula","1 tomato","1/2 avocado","Salt, pepper"]}',
'{"es":["Marina el pez espada con limÃ³n, aceite, tomillo, orÃ©gano, sal y pimienta 5 min","Cocina en plancha muy caliente 3-4 min por lado","Prepara la ensalada con rÃºcula, tomate en dados y aguacate laminado","Sirve el pez espada sobre la ensalada con un chorro de aceite de oliva"],"en":["Marinate swordfish with lemon, oil, thyme, oregano, salt and pepper 5 min","Cook on very hot griddle 3-4 min per side","Prepare salad with arugula, diced tomato and sliced avocado","Serve swordfish over salad with a drizzle of olive oil"]}'
),

('tortilla_espaÃ±ola_fodmap',125,'dinner','ðŸ³',
'{"es":"Tortilla espaÃ±ola con patatas (versiÃ³n low FODMAP)","en":"Spanish omelette low-FODMAP version","fr":"Tortilla espagnole version low FODMAP","it":"Tortilla spagnola versione low FODMAP"}',
'{"es":"Sin cebolla, sin ajo: la tortilla espaÃ±ola que no irrita el intestino sensible","en":"No onion, no garlic: the Spanish omelette that doesn''t irritate a sensitive gut"}',
15,20,420,22,28,22,3,
ARRAY['vegetarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['ibs'],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["4 huevos","2 patatas medianas (400g)","2 cdas aceite de oliva","1 cdta cebollino picado (low FODMAP vs cebolla)","Sal, pimienta"],"en":["4 eggs","2 medium potatoes (400g)","2 tbsp olive oil","1 tsp chopped chives (low FODMAP vs onion)","Salt, pepper"]}',
'{"es":["Pela y corta las patatas en lÃ¡minas finas","CuÃ©celas en aceite de oliva a fuego suave 12-15 min hasta que estÃ©n blandas","Bate los huevos con sal y pimienta","Mezcla las patatas con los huevos batidos y el cebollino","En sartÃ©n antiadherente, vierte la mezcla y cuaja a fuego medio-bajo 6-8 min","Da la vuelta con un plato y cocina 4 min mÃ¡s"],"en":["Peel and thinly slice potatoes","Cook in olive oil over low heat 12-15 min until soft","Beat eggs with salt and pepper","Mix potatoes with beaten eggs and chives","In non-stick pan, pour mixture and set over medium-low heat 6-8 min","Flip with a plate and cook 4 more min"]}'
),

('crema_calabaza_coco_fodmap',126,'dinner','ðŸŽƒ',
'{"es":"Crema de calabaza con leche de coco","en":"Pumpkin coconut cream soup","fr":"CrÃ¨me de potiron au lait de coco","it":"Crema di zucca con latte di cocco"}',
'{"es":"Sopa reconfortante y antioxidante: la calabaza es baja en FODMAP en raciÃ³n moderada","en":"Comforting and antioxidant soup: pumpkin is low-FODMAP in moderate portions"}',
10,20,280,6,28,16,5,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['ibs','bloating','inflammation'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["400g calabaza en dados","200ml leche de coco","400ml caldo de verduras","1 cdta jengibre rallado","1 cdta cÃºrcuma","Sal, pimienta","Semillas de calabaza para decorar","Aceite de oliva"],"en":["400g pumpkin cubed","200ml coconut milk","400ml vegetable broth","1 tsp grated ginger","1 tsp turmeric","Salt, pepper","Pumpkin seeds for garnish","Olive oil"]}',
'{"es":["Rehoga la calabaza en aceite de oliva 3 min","AÃ±ade el caldo, jengibre y cÃºrcuma","Cuece 15 min hasta que la calabaza estÃ© tierna","AÃ±ade la leche de coco y tritura con batidora hasta crema homogÃ©nea","Rectifica la sazÃ³n, decora con semillas de calabaza tostadas"],"en":["SautÃ© pumpkin in olive oil 3 min","Add broth, ginger and turmeric","Cook 15 min until pumpkin is tender","Add coconut milk and blend until smooth cream","Adjust seasoning, garnish with toasted pumpkin seeds"]}'
),

('atun_tataki_paleo',127,'dinner','ðŸŸ',
'{"es":"Tataki de atÃºn con jengibre y sÃ©samo","en":"Tuna tataki with ginger and sesame","fr":"Tataki de thon au gingembre et sÃ©same","it":"Tataki di tonno con zenzero e sesamo"}',
'{"es":"Barely cooked: el tataki preserva los omega-3 del atÃºn mejor que la cocciÃ³n completa","en":"Barely cooked: tataki preserves tuna omega-3 better than full cooking"}',
10,5,360,40,6,18,2,
ARRAY['pescatarian','paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY['inflammation'],
ARRAY['fish','sesame'],
'medium','under_20','high',
'{"es":["200g lomo de atÃºn rojo fresco","2 cdas coco aminos","1 cdta jengibre rallado","2 cdas semillas de sÃ©samo (mezcla blanco y negro)","1 cda aceite de sÃ©samo","1/2 lima","RÃºcula o lechuga para acompaÃ±ar"],"en":["200g fresh bluefin tuna loin","2 tbsp coconut aminos","1 tsp grated ginger","2 tbsp sesame seeds (mixed white and black)","1 tbsp sesame oil","1/2 lime","Arugula or lettuce to serve"]}',
'{"es":["Marina el atÃºn en coco aminos y jengibre 5 min","Reboza en semillas de sÃ©samo por todos los lados","Calienta una sartÃ©n de hierro a fuego muy alto con aceite de sÃ©samo","Marca el atÃºn 30-45 segundos por cada cara (debe quedar rojo por dentro)","Deja reposar 2 min, corta en lÃ¡minas finas","Sirve sobre las hojas verdes con zumo de lima"],"en":["Marinate tuna in coconut aminos and ginger 5 min","Coat in sesame seeds on all sides","Heat iron pan over very high heat with sesame oil","Sear tuna 30-45 seconds per side (should be red inside)","Rest 2 min, slice thin","Serve over greens with lime juice"]}'
),

('brochetas_pollo_pimiento_paleo',128,'dinner','ðŸ¢',
'{"es":"Brochetas de pollo y pimiento al horno","en":"Chicken and pepper skewers oven-baked","fr":"Brochettes de poulet et poivrons au four","it":"Spiedini di pollo e peperone al forno"}',
'{"es":"Paleo y bajo FODMAP: el pimiento rojo aporta vitamina C que mejora la absorciÃ³n del hierro del pollo","en":"Paleo and low-FODMAP: red pepper provides vitamin C that improves iron absorption from chicken"}',
15,20,380,36,14,18,3,
ARRAY['paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy'],
ARRAY['anemia','fatigue'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["250g pechuga de pollo en dados","1 pimiento rojo grande","1 pimiento amarillo","2 cdas aceite de oliva","Paprika, comino, sal, pimienta","Zumo de limÃ³n","Perejil fresco"],"en":["250g chicken breast cubed","1 large red bell pepper","1 yellow bell pepper","2 tbsp olive oil","Paprika, cumin, salt, pepper","Lemon juice","Fresh parsley"]}',
'{"es":["Precalienta el horno a 200Â°C","Corta los pimientos en cuadrados similares al pollo","Marina el pollo con aceite, paprika, comino, sal, pimienta y limÃ³n","Ensarta alternando pollo y pimiento en brochetas","Hornea 18-20 min volteando a mitad de cocciÃ³n","Sirve con perejil picado"],"en":["Preheat oven to 200Â°C","Cut peppers into squares similar to chicken","Marinate chicken with oil, paprika, cumin, salt, pepper and lemon","Thread alternating chicken and pepper on skewers","Bake 18-20 min turning halfway","Serve with chopped parsley"]}'
),

('dorada_limÃ³n_paleo',129,'dinner','ðŸŸ',
'{"es":"Dorada a la sal con limÃ³n","en":"Salt-baked sea bream with lemon","fr":"Daurade en croÃ»te de sel au citron","it":"Orata sotto sale con limone"}',
'{"es":"TÃ©cnica ancestral paleo: la costra de sal mantiene la humedad y concentra el sabor del pescado","en":"Ancient paleo technique: salt crust retains moisture and concentrates fish flavor"}',
10,30,360,38,4,20,1,
ARRAY['pescatarian','paleo','keto','low_carb','gluten_free','lactose_free','low_fodmap'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['fish'],
'medium','20_40','medium',
'{"es":["1 dorada entera (400-500g)","500g sal gorda","2 claras de huevo","1 limÃ³n en rodajas","Romero fresco","Tomillo fresco","Aceite de oliva virgen extra"],"en":["1 whole sea bream (400-500g)","500g coarse salt","2 egg whites","1 lemon in slices","Fresh rosemary","Fresh thyme","Extra virgin olive oil"]}',
'{"es":["Precalienta el horno a 200Â°C","Mezcla la sal gorda con las claras de huevo hasta obtener una pasta","Coloca 1/3 de la sal en la base de la fuente","Rellena la dorada con el limÃ³n y las hierbas","Cubre la dorada completamente con el resto de la sal","Hornea 25-30 min segÃºn el tamaÃ±o","Rompe la costra en la mesa y sirve con aceite de oliva"],"en":["Preheat oven to 200Â°C","Mix coarse salt with egg whites until paste forms","Place 1/3 of salt in base of baking dish","Fill sea bream with lemon and herbs","Cover fish completely with remaining salt","Bake 25-30 min depending on size","Break crust at the table and serve with olive oil"]}'
),

('sardinas_tomate_fodmap',130,'snack','ðŸŸ',
'{"es":"Sardinas en tomate sobre endivias","en":"Sardines in tomato on endives","fr":"Sardines Ã  la tomate sur endives","it":"Sardine al pomodoro su indivia"}',
'{"es":"Snack bajo FODMAP rico en calcio: las sardinas con espina aportan mÃ¡s calcio que la leche","en":"Low-FODMAP snack rich in calcium: sardines with bones provide more calcium than milk"}',
5,0,220,18,6,14,3,
ARRAY['pescatarian','keto','low_carb','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['pms','inflammation'],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["1 lata sardinas en tomate (120g)","4 hojas de endivia","Zumo de limÃ³n","Perejil fresco","Pimienta negra"],"en":["1 can sardines in tomato (120g)","4 endive leaves","Lemon juice","Fresh parsley","Black pepper"]}',
'{"es":["Separa las hojas de endivia y Ãºsalas como cucharas/botes","Distribuye las sardinas en el tomate sobre cada hoja","Exprime un poco de limÃ³n","Decora con perejil picado y pimienta negra"],"en":["Separate endive leaves and use them as cups/scoops","Distribute sardines in tomato sauce over each leaf","Squeeze a little lemon","Garnish with chopped parsley and black pepper"]}'
);

