-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 2 (+30) — display_order 71-100
-- Más veganas, pescetarianas, keto, paleo y low_fodmap + variedad mediterránea
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 1
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── DESAYUNOS ────────────────────────────────────────────────────────────────

('gachas_trigo_sarraceno',71,'breakfast','🥣',
'{"es":"Gachas de trigo sarraceno con pera","en":"Buckwheat porridge with pear","fr":"Porridge de sarrasin à la poire","it":"Porridge di grano saraceno con pera"}',
'{"es":"Sin gluten y bajo FODMAP: alternativa al porridge clásico","en":"Gluten-free and low-FODMAP take on classic porridge"}',
5,12,340,10,56,9,7,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['ibs'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["60g trigo sarraceno en grano","200ml bebida de almendra","1 pera madura","1 cdta canela","1 cdta sirope de arce","10g nueces pecanas (opcional)"],"en":["60g buckwheat groats","200ml almond milk","1 ripe pear","1 tsp cinnamon","1 tsp maple syrup","10g pecans (optional)"]}',
'{"es":["Enjuaga el trigo sarraceno","Cuécelo 10-12 min con la bebida vegetal","Añade canela y sirope","Sirve con la pera laminada"],"en":["Rinse the buckwheat","Simmer 10-12 min in the plant milk","Add cinnamon and syrup","Serve with sliced pear"]}'
),

('muffins_huevo_verduras',72,'breakfast','🧁',
'{"es":"Muffins de huevo con verduras","en":"Veggie egg muffins","fr":"Muffins aux œufs et légumes","it":"Muffin di uova alle verdure"}',
'{"es":"Meal prep keto: hornea el domingo y desayuna toda la semana","en":"Keto meal prep: bake on Sunday, breakfast all week"}',
10,20,310,24,6,21,2,
ARRAY['vegetarian','keto','low_carb','high_protein','gluten_free'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','gain_muscle','performance'],
ARRAY['pcos','type2_diabetes'],
ARRAY['egg','lactose'],
'easy','20_to_40','low',
'{"es":["5 huevos","1 calabacín pequeño rallado","½ pimiento rojo","40g queso rallado","Sal, pimienta y orégano"],"en":["5 eggs","1 small grated courgette","½ red pepper","40g grated cheese","Salt, pepper and oregano"]}',
'{"es":["Bate los huevos con las especias","Mezcla con las verduras y el queso","Reparte en moldes de muffin","Hornea 18-20 min a 180°C"],"en":["Beat eggs with seasoning","Mix in vegetables and cheese","Divide into muffin tins","Bake 18-20 min at 180°C"]}'
),

('smoothie_verde_proteico',73,'breakfast','🥬',
'{"es":"Smoothie verde proteico","en":"Green protein smoothie","fr":"Smoothie vert protéiné","it":"Smoothie verde proteico"}',
'{"es":"Vegano y alto en proteína para mañanas con prisa","en":"Vegan, high-protein fuel for rushed mornings"}',
5,0,310,24,38,7,7,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','energy','maintain'],
ARRAY['pcos'],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["1 scoop proteína vegana (30g)","60g espinacas","100g piña","½ plátano","200ml agua o bebida vegetal","Zumo de ½ lima"],"en":["1 scoop vegan protein (30g)","60g spinach","100g pineapple","½ banana","200ml water or plant milk","Juice of ½ lime"]}',
'{"es":["Pon todo en la batidora","Tritura 1 minuto hasta que quede fino","Sirve bien frío"],"en":["Add everything to the blender","Blend 1 minute until smooth","Serve very cold"]}'
),

('porridge_quinoa_manzana',74,'breakfast','🍎',
'{"es":"Porridge de quinoa con manzana y canela","en":"Quinoa porridge with apple and cinnamon","fr":"Porridge de quinoa pomme cannelle","it":"Porridge di quinoa con mela e cannella"}',
'{"es":"Vegano y sin gluten, con proteína completa de la quinoa","en":"Vegan and gluten-free, with complete quinoa protein"}',
5,15,360,12,58,9,8,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','standard'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['anemia'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["60g quinoa","220ml bebida de avena","1 manzana","1 cdta canela","1 cdta pasas","1 cdta semillas de girasol"],"en":["60g quinoa","220ml oat milk","1 apple","1 tsp cinnamon","1 tsp raisins","1 tsp sunflower seeds"]}',
'{"es":["Enjuaga y cuece la quinoa 12 min en la bebida vegetal","Ralla media manzana dentro y cocina 2 min","Sirve con el resto de manzana, canela, pasas y semillas"],"en":["Rinse quinoa and simmer 12 min in the plant milk","Grate half the apple in and cook 2 min","Top with remaining apple, cinnamon, raisins and seeds"]}'
),

('shakshuka_ligera',75,'breakfast','🍳',
'{"es":"Shakshuka de tomate y pimiento","en":"Tomato and pepper shakshuka","fr":"Shakshuka tomate poivron","it":"Shakshuka di pomodoro e peperone"}',
'{"es":"Huevos escalfados en salsa especiada: desayuno-brunch saciante","en":"Eggs poached in spiced sauce: filling breakfast-brunch"}',
10,18,350,20,18,23,6,
ARRAY['vegetarian','low_carb','mediterranean','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','lose_weight'],
ARRAY['anemia'],
ARRAY['egg'],
'medium','20_to_40','low',
'{"es":["2 huevos","300g tomate triturado","½ pimiento rojo","½ cebolla","1 diente de ajo","1 cdta comino y pimentón","1 cda aceite de oliva","Perejil"],"en":["2 eggs","300g crushed tomatoes","½ red pepper","½ onion","1 garlic clove","1 tsp cumin and paprika","1 tbsp olive oil","Parsley"]}',
'{"es":["Sofríe cebolla, ajo y pimiento 5 min","Añade tomate y especias, reduce 8 min","Haz dos huecos y casca los huevos","Tapa y cuaja 4-5 min, termina con perejil"],"en":["Sauté onion, garlic and pepper 5 min","Add tomatoes and spices, reduce 8 min","Make two wells and crack in the eggs","Cover and set 4-5 min, finish with parsley"]}'
),

('bowl_yogur_coco_kiwi',76,'breakfast','🥝',
'{"es":"Bowl de yogur de coco con kiwi","en":"Coconut yoghurt bowl with kiwi","fr":"Bowl yaourt coco kiwi","it":"Bowl di yogurt di cocco con kiwi"}',
'{"es":"Vegano, bajo FODMAP y digestivo: el kiwi ayuda al tránsito","en":"Vegan, low-FODMAP and gut-friendly: kiwi aids digestion"}',
5,0,290,6,32,16,8,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['ibs'],
ARRAY['nuts'],
'easy','under_20','medium',
'{"es":["150g yogur de coco sin azúcar","2 kiwis","15g nueces","1 cdta semillas de chía","Canela"],"en":["150g unsweetened coconut yoghurt","2 kiwis","15g walnuts","1 tsp chia seeds","Cinnamon"]}',
'{"es":["Sirve el yogur en un bol","Pela y trocea los kiwis","Añade nueces, chía y canela"],"en":["Spoon yoghurt into a bowl","Peel and chop kiwis","Top with walnuts, chia and cinnamon"]}'
),

-- ── COMIDAS ──────────────────────────────────────────────────────────────────

('ensalada_quinoa_feta_granada',77,'lunch','🥗',
'{"es":"Ensalada de quinoa, feta y granada","en":"Quinoa, feta and pomegranate salad","fr":"Salade quinoa feta grenade","it":"Insalata di quinoa, feta e melagrana"}',
'{"es":"Mediterránea con un toque dulce y antioxidante","en":"Mediterranean with a sweet antioxidant twist"}',
15,12,480,17,52,22,9,
ARRAY['vegetarian','mediterranean','gluten_free','anti_inflammatory'],
ARRAY['ovulation','follicular'],
ARRAY['maintain','energy'],
ARRAY['endometriosis'],
ARRAY['lactose'],
'easy','20_to_40','medium',
'{"es":["70g quinoa","60g queso feta","½ granada","Rúcula","10 hojas de menta","Aceite de oliva y limón"],"en":["70g quinoa","60g feta cheese","½ pomegranate","Rocket","10 mint leaves","Olive oil and lemon"]}',
'{"es":["Cuece la quinoa 12 min y deja templar","Desgrana la granada","Mezcla con rúcula, feta y menta","Aliña con aceite y limón"],"en":["Cook quinoa 12 min, let cool","Deseed the pomegranate","Toss with rocket, feta and mint","Dress with oil and lemon"]}'
),

('fideos_arroz_gambas',78,'lunch','🍜',
'{"es":"Fideos de arroz con gambas y verduras","en":"Rice noodles with prawns and vegetables","fr":"Nouilles de riz crevettes légumes","it":"Spaghetti di riso con gamberi e verdure"}',
'{"es":"Pescetariano y sin gluten, estilo asiático en 20 minutos","en":"Pescatarian, gluten-free, Asian-style in 20 minutes"}',
10,12,490,28,62,13,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','gain_muscle','energy'],
ARRAY[]::text[],
ARRAY['shellfish','soy'],
'medium','20_to_40','medium',
'{"es":["80g fideos de arroz","150g gambas peladas","1 zanahoria","100g col china o repollo","2 cdas salsa de soja sin gluten (tamari)","1 diente de ajo","Jengibre y lima"],"en":["80g rice noodles","150g peeled prawns","1 carrot","100g Chinese cabbage","2 tbsp gluten-free soy sauce (tamari)","1 garlic clove","Ginger and lime"]}',
'{"es":["Hidrata los fideos según el paquete","Saltea ajo, jengibre y verduras 4 min","Añade las gambas 2-3 min","Junta con fideos, tamari y lima"],"en":["Soak noodles per package","Stir-fry garlic, ginger and veg 4 min","Add prawns 2-3 min","Toss with noodles, tamari and lime"]}'
),

('crema_brocoli_almendras',79,'lunch','🥦',
'{"es":"Crema de brócoli con almendras","en":"Broccoli almond soup","fr":"Velouté de brocoli aux amandes","it":"Vellutata di broccoli alle mandorle"}',
'{"es":"Vegana y baja en carbohidratos, cremosa sin nata","en":"Vegan and low-carb, creamy without cream"}',
10,18,290,11,18,20,9,
ARRAY['vegan','vegetarian','keto','low_carb','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['luteal','menstrual'],
ARRAY['lose_weight','maintain','reduce_symptoms'],
ARRAY['pcos','type2_diabetes'],
ARRAY['nuts'],
'easy','20_to_40','low',
'{"es":["350g brócoli","30g almendras","½ puerro (parte verde)","1 cda aceite de oliva","500ml caldo de verduras","Nuez moscada"],"en":["350g broccoli","30g almonds","½ leek (green part)","1 tbsp olive oil","500ml vegetable stock","Nutmeg"]}',
'{"es":["Sofríe el puerro 3 min","Añade brócoli y caldo, cuece 15 min","Tritura con las almendras","Ajusta con nuez moscada"],"en":["Sauté leek 3 min","Add broccoli and stock, cook 15 min","Blend with the almonds","Season with nutmeg"]}'
),

('berenjenas_rellenas_quinoa',80,'lunch','🍆',
'{"es":"Berenjenas rellenas de quinoa y tomate","en":"Quinoa and tomato stuffed aubergines","fr":"Aubergines farcies quinoa tomate","it":"Melanzane ripiene di quinoa e pomodoro"}',
'{"es":"Plato vegano de cuchillo y tenedor para el fin de semana","en":"Hearty vegan main for the weekend"}',
15,40,440,14,58,18,14,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','mediterranean'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','low',
'{"es":["2 berenjenas","70g quinoa","200g tomate triturado","1 cebolla","2 dientes de ajo","Comino y orégano","Aceite de oliva"],"en":["2 aubergines","70g quinoa","200g crushed tomatoes","1 onion","2 garlic cloves","Cumin and oregano","Olive oil"]}',
'{"es":["Asa las berenjenas a lo largo 25 min a 200°C","Cuece la quinoa y sofríe cebolla, ajo y tomate","Vacía las berenjenas y mezcla la pulpa con el relleno","Rellena y hornea 10 min más"],"en":["Roast halved aubergines 25 min at 200°C","Cook quinoa, sauté onion, garlic and tomato","Scoop out flesh, mix into the filling","Stuff and bake 10 more min"]}'
),

('trucha_almendras_judias',81,'lunch','🐟',
'{"es":"Trucha a las almendras con judías verdes","en":"Almond trout with green beans","fr":"Truite aux amandes haricots verts","it":"Trota alle mandorle con fagiolini"}',
'{"es":"Pescado azul de río, omega-3 y crunch de almendra","en":"River fish rich in omega-3 with almond crunch"}',
10,15,440,36,12,28,6,
ARRAY['pescatarian','paleo','low_carb','gluten_free','lactose_free','high_protein','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','maintain','performance'],
ARRAY['hypothyroid','ibs'],
ARRAY['fish','nuts'],
'medium','20_to_40','medium',
'{"es":["1 trucha en filetes (180g)","200g judías verdes","20g almendras laminadas","1 cda aceite de oliva","Limón y perejil"],"en":["1 trout, filleted (180g)","200g green beans","20g flaked almonds","1 tbsp olive oil","Lemon and parsley"]}',
'{"es":["Cuece las judías al vapor 8 min","Haz la trucha a la plancha 3 min por lado","Tuesta las almendras en la sartén","Sirve con limón y perejil"],"en":["Steam green beans 8 min","Pan-fry trout 3 min per side","Toast almonds in the pan","Serve with lemon and parsley"]}'
),

('bacalao_garbanzos_espinacas',82,'lunch','🍲',
'{"es":"Bacalao con garbanzos y espinacas","en":"Cod with chickpeas and spinach","fr":"Cabillaud pois chiches épinards","it":"Merluzzo con ceci e spinaci"}',
'{"es":"Guiso mediterráneo de siempre: hierro, proteína y fibra","en":"Classic Mediterranean stew: iron, protein and fibre"}',
10,20,470,38,42,15,11,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','gain_muscle'],
ARRAY['anemia'],
ARRAY['fish'],
'medium','20_to_40','medium',
'{"es":["180g lomo de bacalao","150g garbanzos cocidos","100g espinacas","200g tomate triturado","1 diente de ajo","Pimentón dulce","Aceite de oliva"],"en":["180g cod loin","150g cooked chickpeas","100g spinach","200g crushed tomatoes","1 garlic clove","Sweet paprika","Olive oil"]}',
'{"es":["Sofríe ajo y pimentón 1 min","Añade tomate y garbanzos, guisa 8 min","Incorpora el bacalao en trozos 6-8 min","Apaga y añade las espinacas para que se templen"],"en":["Sauté garlic and paprika 1 min","Add tomatoes and chickpeas, stew 8 min","Add cod chunks, cook 6-8 min","Turn off heat, stir in spinach to wilt"]}'
),

('tabule_coliflor',83,'lunch','🥒',
'{"es":"Tabulé de coliflor con hierbas","en":"Cauliflower tabbouleh with herbs","fr":"Taboulé de chou-fleur aux herbes","it":"Tabulè di cavolfiore alle erbe"}',
'{"es":"Versión paleo y keto del tabulé: coliflor en lugar de sémola","en":"Paleo-keto take on tabbouleh: cauliflower instead of bulgur"}',
15,5,260,8,16,19,8,
ARRAY['vegan','vegetarian','paleo','keto','low_carb','gluten_free','lactose_free'],
ARRAY['ovulation','follicular'],
ARRAY['lose_weight','maintain'],
ARRAY['pcos','type2_diabetes'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["300g coliflor","1 tomate","½ pepino","Perejil y menta abundantes","3 cdas aceite de oliva","Zumo de 1 limón"],"en":["300g cauliflower","1 tomato","½ cucumber","Plenty of parsley and mint","3 tbsp olive oil","Juice of 1 lemon"]}',
'{"es":["Ralla la coliflor hasta textura de cuscús","Saltéala 3-4 min y deja enfriar","Mezcla con tomate, pepino y hierbas picadas","Aliña con aceite y limón"],"en":["Grate cauliflower to couscous texture","Sauté 3-4 min and let cool","Mix with tomato, cucumber and chopped herbs","Dress with oil and lemon"]}'
),

('sopa_pollo_jengibre_fodmap',84,'lunch','🍲',
'{"es":"Sopa de pollo, jengibre y fideos de arroz","en":"Chicken, ginger and rice noodle soup","fr":"Soupe poulet gingembre nouilles de riz","it":"Zuppa di pollo, zenzero e spaghetti di riso"}',
'{"es":"Reconfortante y baja en FODMAP, ideal con el estómago delicado","en":"Comforting and low-FODMAP, ideal for a delicate stomach"}',
10,20,420,32,48,9,3,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','standard'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['ibs'],
ARRAY[]::text[],
'easy','20_to_40','low',
'{"es":["150g pechuga de pollo","60g fideos de arroz","1 zanahoria","1 trozo de jengibre","Parte verde de 1 cebolleta","750ml caldo bajo en FODMAP","Cilantro y lima"],"en":["150g chicken breast","60g rice noodles","1 carrot","1 piece of ginger","Green part of 1 spring onion","750ml low-FODMAP stock","Coriander and lime"]}',
'{"es":["Hierve el caldo con jengibre y zanahoria 8 min","Añade el pollo en tiras 6 min","Incorpora los fideos 3-4 min","Termina con cebolleta, cilantro y lima"],"en":["Simmer stock with ginger and carrot 8 min","Add chicken strips, 6 min","Add noodles 3-4 min","Finish with spring onion, coriander and lime"]}'
),

('ensalada_alubias_atun',85,'lunch','🫘',
'{"es":"Ensalada de alubias blancas y atún","en":"White bean and tuna salad","fr":"Salade haricots blancs et thon","it":"Insalata di cannellini e tonno"}',
'{"es":"De bote a mesa en 10 minutos: proteína doble y fibra","en":"Pantry to plate in 10 minutes: double protein and fibre"}',
10,0,450,32,40,17,12,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','gain_muscle','lose_weight'],
ARRAY['anemia'],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["150g alubias blancas cocidas","1 lata de atún","½ cebolla roja","1 tomate","Perejil","Aceite de oliva y vinagre"],"en":["150g cooked white beans","1 can tuna","½ red onion","1 tomato","Parsley","Olive oil and vinegar"]}',
'{"es":["Enjuaga las alubias","Mezcla con atún, cebolla y tomate troceado","Aliña con aceite, vinagre y perejil"],"en":["Rinse the beans","Mix with tuna, onion and chopped tomato","Dress with oil, vinegar and parsley"]}'
),

-- ── CENAS ────────────────────────────────────────────────────────────────────

('pisto_huevo_horno',86,'dinner','🍅',
'{"es":"Pisto de verduras con huevo al horno","en":"Spanish ratatouille with baked egg","fr":"Piperade de légumes et œuf au four","it":"Ratatouille con uovo al forno"}',
'{"es":"Clásico vegetariano bajo en carbohidratos, con proteína del huevo","en":"Low-carb vegetarian classic with egg protein"}',
15,30,360,16,24,22,9,
ARRAY['vegetarian','low_carb','mediterranean','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','lose_weight'],
ARRAY['endometriosis'],
ARRAY['egg'],
'medium','20_to_40','low',
'{"es":["2 huevos","1 calabacín","½ berenjena","½ pimiento rojo","½ cebolla","300g tomate triturado","2 cdas aceite de oliva"],"en":["2 eggs","1 courgette","½ aubergine","½ red pepper","½ onion","300g crushed tomatoes","2 tbsp olive oil"]}',
'{"es":["Sofríe las verduras en dados 10 min","Añade el tomate y guisa 15 min","Pasa a una fuente, casca los huevos encima","Hornea 8-10 min a 200°C"],"en":["Sauté diced vegetables 10 min","Add tomatoes, stew 15 min","Transfer to a dish, crack eggs on top","Bake 8-10 min at 200°C"]}'
),

('calabacines_rellenos_pavo',87,'dinner','🥒',
'{"es":"Calabacines rellenos de pavo","en":"Turkey stuffed courgettes","fr":"Courgettes farcies à la dinde","it":"Zucchine ripiene di tacchino"}',
'{"es":"Cena paleo alta en proteína y muy baja en carbohidratos","en":"High-protein paleo dinner, very low in carbs"}',
15,30,390,38,14,21,5,
ARRAY['paleo','low_carb','keto','high_protein','gluten_free','lactose_free','standard'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','gain_muscle'],
ARRAY['pcos','type2_diabetes'],
ARRAY[]::text[],
'medium','20_to_40','medium',
'{"es":["2 calabacines","200g pavo picado","½ cebolla","1 diente de ajo","150g tomate triturado","Orégano y pimentón","Aceite de oliva"],"en":["2 courgettes","200g turkey mince","½ onion","1 garlic clove","150g crushed tomatoes","Oregano and paprika","Olive oil"]}',
'{"es":["Vacía los calabacines a lo largo","Sofríe cebolla, ajo y pavo con la pulpa picada","Añade tomate y especias, reduce 5 min","Rellena y hornea 20 min a 190°C"],"en":["Halve and scoop out courgettes","Sauté onion, garlic and turkey with chopped flesh","Add tomatoes and spices, reduce 5 min","Stuff and bake 20 min at 190°C"]}'
),

('coliflor_asada_tahini',88,'dinner','🥬',
'{"es":"Coliflor asada con salsa tahini","en":"Roasted cauliflower with tahini sauce","fr":"Chou-fleur rôti sauce tahini","it":"Cavolfiore arrosto con salsa tahina"}',
'{"es":"Vegana y keto: especiada, dorada y con salsa cremosa de sésamo","en":"Vegan keto: spiced, golden, with creamy sesame sauce"}',
10,30,320,11,20,24,9,
ARRAY['vegan','vegetarian','keto','low_carb','paleo','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['luteal','menstrual'],
ARRAY['lose_weight','maintain','reduce_symptoms'],
ARRAY['pcos'],
ARRAY['sesame'],
'easy','20_to_40','low',
'{"es":["400g coliflor","2 cdas aceite de oliva","1 cdta comino y pimentón","2 cdas tahini","Zumo de ½ limón","Perejil y granada (opcional)"],"en":["400g cauliflower","2 tbsp olive oil","1 tsp cumin and paprika","2 tbsp tahini","Juice of ½ lemon","Parsley and pomegranate (optional)"]}',
'{"es":["Mezcla la coliflor con aceite y especias","Asa 28-30 min a 210°C","Mezcla tahini, limón y agua hasta hacer salsa","Riega la coliflor y termina con perejil"],"en":["Toss cauliflower with oil and spices","Roast 28-30 min at 210°C","Whisk tahini, lemon and water into a sauce","Drizzle over and finish with parsley"]}'
),

('pavo_judias_verdes_fodmap',89,'dinner','🥗',
'{"es":"Salteado de pavo con judías verdes","en":"Turkey and green bean stir-fry","fr":"Sauté de dinde aux haricots verts","it":"Tacchino saltato con fagiolini"}',
'{"es":"Cena baja en FODMAP en una sartén y 15 minutos","en":"One-pan low-FODMAP dinner in 15 minutes"}',
10,12,370,38,16,17,6,
ARRAY['low_fodmap','paleo','low_carb','high_protein','gluten_free','lactose_free','standard'],
ARRAY['luteal','menstrual'],
ARRAY['lose_weight','maintain','gain_muscle'],
ARRAY['ibs'],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["180g pechuga de pavo","200g judías verdes","1 zanahoria","1 cda aceite de oliva","Jengibre","Parte verde de cebolleta","Tamari (opcional)"],"en":["180g turkey breast","200g green beans","1 carrot","1 tbsp olive oil","Ginger","Spring onion greens","Tamari (optional)"]}',
'{"es":["Saltea el pavo en tiras 4 min","Añade judías y zanahoria en bastones 6 min","Termina con jengibre, cebolleta y tamari"],"en":["Stir-fry turkey strips 4 min","Add green beans and carrot sticks, 6 min","Finish with ginger, spring onion and tamari"]}'
),

('sepia_plancha_ensalada',90,'dinner','🦑',
'{"es":"Sepia a la plancha con ensalada de tomate","en":"Grilled cuttlefish with tomato salad","fr":"Seiche grillée salade de tomates","it":"Seppia alla griglia con insalata di pomodori"}',
'{"es":"Proteína magra del mar con alioli ligero de limón","en":"Lean seafood protein with light lemon aioli"}',
10,8,310,34,10,15,3,
ARRAY['pescatarian','paleo','keto','low_carb','high_protein','gluten_free','lactose_free','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','gain_muscle','performance'],
ARRAY['hypothyroid'],
ARRAY['shellfish','egg'],
'easy','under_20','medium',
'{"es":["250g sepia limpia","2 tomates","1 cda mayonesa ligera","1 diente de ajo pequeño","Limón","Perejil y aceite de oliva"],"en":["250g cleaned cuttlefish","2 tomatoes","1 tbsp light mayo","1 small garlic clove","Lemon","Parsley and olive oil"]}',
'{"es":["Plancha la sepia 3-4 min por lado a fuego fuerte","Mezcla mayonesa, ajo rallado y limón","Corta el tomate y aliña","Sirve todo con perejil"],"en":["Grill cuttlefish 3-4 min per side on high heat","Mix mayo, grated garlic and lemon","Slice and dress tomatoes","Serve with parsley"]}'
),

('tortilla_calabacin_queso',91,'dinner','🥚',
'{"es":"Tortilla de calabacín y queso","en":"Courgette and cheese omelette","fr":"Omelette courgette fromage","it":"Frittata di zucchine e formaggio"}',
'{"es":"Cena vegetariana low carb de toda la vida","en":"Timeless low-carb vegetarian dinner"}',
10,15,380,24,10,28,3,
ARRAY['vegetarian','low_carb','keto','gluten_free','high_protein'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['egg','lactose'],
'easy','20_to_40','low',
'{"es":["3 huevos","1 calabacín","40g queso semicurado rallado","1 cda aceite de oliva","Sal y pimienta"],"en":["3 eggs","1 courgette","40g grated semi-cured cheese","1 tbsp olive oil","Salt and pepper"]}',
'{"es":["Saltea el calabacín en rodajas finas 6-7 min","Bate los huevos con el queso","Junta y cuaja a fuego bajo 4 min por lado"],"en":["Sauté thin courgette slices 6-7 min","Beat eggs with the cheese","Combine and set on low heat, 4 min per side"]}'
),

('hamburguesa_alubias_vegana',92,'dinner','🍔',
'{"es":"Hamburguesa vegana de alubias rojas","en":"Vegan red bean burger","fr":"Burger végan haricots rouges","it":"Burger vegano di fagioli rossi"}',
'{"es":"Caseras, con avena y especias — congelan de maravilla","en":"Homemade with oats and spices — freeze beautifully"}',
15,12,460,18,62,15,15,
ARRAY['vegan','vegetarian','lactose_free','standard'],
ARRAY['follicular','menstrual'],
ARRAY['maintain','energy'],
ARRAY['anemia'],
ARRAY['gluten'],
'medium','20_to_40','low',
'{"es":["200g alubias rojas cocidas","40g copos de avena","½ cebolla","1 cdta comino y pimentón","Pan de hamburguesa integral","Lechuga, tomate y ½ aguacate"],"en":["200g cooked red beans","40g oat flakes","½ onion","1 tsp cumin and paprika","Wholegrain burger bun","Lettuce, tomato and ½ avocado"]}',
'{"es":["Machaca las alubias con avena, cebolla y especias","Forma 2 hamburguesas y reposa 10 min","Plancha 4-5 min por lado","Monta el burger con lechuga, tomate y aguacate"],"en":["Mash beans with oats, onion and spices","Shape 2 patties, rest 10 min","Grill 4-5 min per side","Build burger with lettuce, tomato and avocado"]}'
),

('albondigas_lentejas_veganas',93,'dinner','🧆',
'{"es":"Albóndigas de lentejas en salsa de tomate","en":"Lentil meatballs in tomato sauce","fr":"Boulettes de lentilles sauce tomate","it":"Polpette di lenticchie al sugo"}',
'{"es":"Proteína vegetal y hierro en formato de plato de domingo","en":"Plant protein and iron in Sunday-dinner format"}',
20,25,470,22,60,14,16,
ARRAY['vegan','vegetarian','lactose_free','standard'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['anemia'],
ARRAY['gluten'],
'medium','over_40','low',
'{"es":["200g lentejas cocidas","50g pan rallado","½ cebolla","1 diente de ajo","300g tomate triturado","Comino, orégano y perejil","Aceite de oliva"],"en":["200g cooked lentils","50g breadcrumbs","½ onion","1 garlic clove","300g crushed tomatoes","Cumin, oregano and parsley","Olive oil"]}',
'{"es":["Tritura lentejas con pan, ajo y especias","Forma bolitas y hornea 15 min a 200°C","Haz la salsa con cebolla y tomate","Junta y cocina 5 min más"],"en":["Blend lentils with breadcrumbs, garlic and spices","Roll into balls, bake 15 min at 200°C","Make sauce with onion and tomatoes","Combine and simmer 5 more min"]}'
),

('atun_plancha_pisto',94,'dinner','🐟',
'{"es":"Atún a la plancha con pisto","en":"Seared tuna with ratatouille","fr":"Thon grillé et piperade","it":"Tonno scottato con ratatouille"}',
'{"es":"Paleo y mediterráneo: pescado azul con verdura guisada","en":"Paleo Mediterranean: oily fish with stewed vegetables"}',
10,20,430,40,16,23,6,
ARRAY['pescatarian','paleo','low_carb','mediterranean','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','performance','maintain'],
ARRAY['hypothyroid','endometriosis'],
ARRAY['fish'],
'medium','20_to_40','high',
'{"es":["180g lomo de atún","1 calabacín","½ pimiento","½ cebolla","200g tomate triturado","2 cdas aceite de oliva"],"en":["180g tuna steak","1 courgette","½ pepper","½ onion","200g crushed tomatoes","2 tbsp olive oil"]}',
'{"es":["Sofríe las verduras y el tomate 15 min","Marca el atún 1-2 min por lado (centro rosado)","Sirve el atún sobre el pisto"],"en":["Sauté vegetables and tomatoes 15 min","Sear tuna 1-2 min per side (pink centre)","Serve tuna over the ratatouille"]}'
),

-- ── SNACKS ───────────────────────────────────────────────────────────────────

('yogur_coco_arandanos_snack',95,'morning_snack','🫐',
'{"es":"Yogur de coco con arándanos","en":"Coconut yoghurt with blueberries","fr":"Yaourt coco myrtilles","it":"Yogurt di cocco con mirtilli"}',
'{"es":"Snack vegano, keto y bajo FODMAP","en":"Vegan, keto and low-FODMAP snack"}',
3,0,180,3,14,13,4,
ARRAY['vegan','vegetarian','keto','low_carb','gluten_free','lactose_free','low_fodmap','paleo'],
ARRAY['luteal','menstrual','follicular','ovulation'],
ARRAY['lose_weight','maintain'],
ARRAY['ibs'],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["125g yogur de coco sin azúcar","60g arándanos","1 cdta semillas de calabaza"],"en":["125g unsweetened coconut yoghurt","60g blueberries","1 tsp pumpkin seeds"]}',
'{"es":["Sirve el yogur","Añade arándanos y semillas"],"en":["Spoon out the yoghurt","Top with blueberries and seeds"]}'
),

('zanahoria_guacamole',96,'afternoon_snack','🥑',
'{"es":"Bastones de zanahoria con guacamole","en":"Carrot sticks with guacamole","fr":"Bâtonnets de carotte et guacamole","it":"Bastoncini di carota con guacamole"}',
'{"es":"Grasas buenas y crunch — vegano y paleo","en":"Good fats and crunch — vegan and paleo"}',
8,0,200,3,16,15,8,
ARRAY['vegan','vegetarian','paleo','keto','low_carb','gluten_free','lactose_free'],
ARRAY['follicular','ovulation','luteal','menstrual'],
ARRAY['lose_weight','maintain'],
ARRAY['pcos'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["2 zanahorias","½ aguacate","Zumo de ¼ lima","Cilantro","Sal y comino"],"en":["2 carrots","½ avocado","Juice of ¼ lime","Coriander","Salt and cumin"]}',
'{"es":["Machaca el aguacate con lima, sal y comino","Corta las zanahorias en bastones","Moja y listo"],"en":["Mash avocado with lime, salt and cumin","Cut carrots into sticks","Dip and enjoy"]}'
),

('barritas_avena_platano',97,'morning_snack','🍌',
'{"es":"Barritas caseras de avena y plátano","en":"Homemade banana oat bars","fr":"Barres maison avoine banane","it":"Barrette fatte in casa avena e banana"}',
'{"es":"Solo 3 ingredientes base — el snack pre-entreno barato","en":"Just 3 base ingredients — the budget pre-workout snack"}',
10,20,210,5,34,7,5,
ARRAY['vegan','vegetarian','lactose_free','standard'],
ARRAY['follicular','ovulation','menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['gluten','nuts'],
'easy','20_to_40','low',
'{"es":["2 plátanos maduros","120g copos de avena","30g nueces troceadas","1 cdta canela"],"en":["2 ripe bananas","120g oat flakes","30g chopped walnuts","1 tsp cinnamon"]}',
'{"es":["Machaca los plátanos","Mezcla con avena, nueces y canela","Extiende en molde y hornea 20 min a 180°C","Corta en 6 barritas"],"en":["Mash the bananas","Mix with oats, walnuts and cinnamon","Press into a tin, bake 20 min at 180°C","Cut into 6 bars"]}'
),

('rollitos_pavo_queso',98,'morning_snack','🌯',
'{"es":"Rollitos de pavo y queso fresco","en":"Turkey and cream cheese roll-ups","fr":"Roulés dinde fromage frais","it":"Involtini di tacchino e formaggio fresco"}',
'{"es":"Snack keto de proteína rápida, sin cocinar","en":"Quick-protein keto snack, no cooking"}',
5,0,170,20,3,9,1,
ARRAY['keto','low_carb','high_protein','gluten_free','standard'],
ARRAY['follicular','ovulation'],
ARRAY['gain_muscle','lose_weight'],
ARRAY['type2_diabetes'],
ARRAY['lactose'],
'easy','under_20','medium',
'{"es":["4 lonchas de pavo","60g queso crema light","½ pepino en bastones","Pimienta"],"en":["4 turkey slices","60g light cream cheese","½ cucumber in sticks","Pepper"]}',
'{"es":["Unta el queso en las lonchas","Coloca un bastón de pepino","Enrolla y corta por la mitad"],"en":["Spread cheese on the slices","Add a cucumber stick","Roll up and halve"]}'
),

('garbanzos_crujientes_horno',99,'afternoon_snack','🌰',
'{"es":"Garbanzos crujientes al pimentón","en":"Crispy paprika chickpeas","fr":"Pois chiches croustillants au paprika","it":"Ceci croccanti alla paprika"}',
'{"es":"El sustituto vegano de las patatas fritas: fibra y proteína","en":"The vegan crisp substitute: fibre and protein"}',
5,30,220,10,30,7,9,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','mediterranean'],
ARRAY['follicular','ovulation','luteal','menstrual'],
ARRAY['maintain','lose_weight','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_to_40','low',
'{"es":["150g garbanzos cocidos","1 cda aceite de oliva","1 cdta pimentón","½ cdta comino","Sal"],"en":["150g cooked chickpeas","1 tbsp olive oil","1 tsp paprika","½ tsp cumin","Salt"]}',
'{"es":["Seca muy bien los garbanzos","Mezcla con aceite y especias","Hornea 30 min a 200°C moviendo a mitad","Deja enfriar para que crujan"],"en":["Dry chickpeas thoroughly","Toss with oil and spices","Roast 30 min at 200°C, shaking halfway","Cool so they crisp up"]}'
),

('pudding_chia_naranja',100,'afternoon_snack','🍊',
'{"es":"Pudding de chía con naranja","en":"Orange chia pudding","fr":"Pudding de chia à l''orange","it":"Budino di chia all''arancia"}',
'{"es":"Vitamina C + omega-3 vegetal en un snack dulce sin azúcar","en":"Vitamin C + plant omega-3 in a no-sugar sweet snack"}',
5,0,200,6,20,11,10,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','low_fodmap','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['anemia','ibs'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["2 cdas semillas de chía","150ml bebida de almendra","1 naranja","½ cdta vainilla"],"en":["2 tbsp chia seeds","150ml almond milk","1 orange","½ tsp vanilla"]}',
'{"es":["Mezcla chía, bebida y vainilla","Refrigera mínimo 2 horas","Sirve con la naranja en gajos"],"en":["Mix chia, milk and vanilla","Chill at least 2 hours","Serve with orange segments"]}'
);
