-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 4 (+30) — display_order 131-160
-- Enfocado en: snacks, desayunos variados, bajo FODMAP
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 3
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── SNACKS MAÑANA ─────────────────────────────────────────────────────────────

('manzana_mantequilla_cacahuete',131,'morning_snack','🍎',
'{"es":"Manzana con mantequilla de cacahuete","en":"Apple with peanut butter","fr":"Pomme au beurre de cacahuète","it":"Mela con burro di arachidi"}',
'{"es":"Snack saciante con fibra y proteína que estabiliza el azúcar en sangre","en":"Satisfying snack with fiber and protein that stabilises blood sugar"}',
2,0,210,6,28,9,5,
ARRAY['vegan','gluten_free','vegetarian'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["1 manzana mediana","2 cdas mantequilla de cacahuete natural"],"en":["1 medium apple","2 tbsp natural peanut butter"]}',
'{"es":["Lava y trocea la manzana en gajos","Sirve con la mantequilla de cacahuete para dipear"],"en":["Wash and slice the apple into wedges","Serve with peanut butter for dipping"]}'
),

('arroz_aguacate_snack',132,'morning_snack','🍙',
'{"es":"Tortitas de arroz con aguacate","en":"Rice cakes with avocado","fr":"Galettes de riz à l''avocat","it":"Gallette di riso con avocado"}',
'{"es":"Snack crujiente y saciante, sin gluten ni lácteos","en":"Crunchy and satisfying snack, gluten and dairy free"}',
3,0,180,3,22,9,5,
ARRAY['vegan','gluten_free','vegetarian','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["2 tortitas de arroz sin sal","1/2 aguacate maduro","Sal, pimienta, zumo de limón","Semillas de sésamo (opt)"],"en":["2 unsalted rice cakes","1/2 ripe avocado","Salt, pepper, lemon juice","Sesame seeds (opt)"]}',
'{"es":["Aplasta el aguacate con un tenedor y sazona con sal, pimienta y limón","Extiende sobre las tortitas de arroz y espolvorea semillas"],"en":["Mash the avocado with a fork and season with salt, pepper and lemon","Spread over rice cakes and sprinkle seeds"]}'
),

('hummus_verduras_snack',133,'morning_snack','🥕',
'{"es":"Hummus con palitos de verduras","en":"Hummus with veggie sticks","fr":"Houmous et bâtonnets de légumes","it":"Hummus con bastoncini di verdure"}',
'{"es":"Rico en proteína vegetal y fibra, perfecto para media mañana","en":"Rich in plant protein and fiber, perfect for mid-morning"}',
5,0,190,8,20,8,6,
ARRAY['vegan','gluten_free','vegetarian','mediterranean','high_protein'],
ARRAY['menstrual','follicular','luteal','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['sesame'],
'easy','under_20','low',
'{"es":["4 cdas hummus","1 zanahoria en palitos","1/2 pepino en palitos","1 tallo apio"],"en":["4 tbsp hummus","1 carrot cut in sticks","1/2 cucumber in sticks","1 celery stalk"]}',
'{"es":["Lava y corta las verduras en palitos","Sirve con el hummus para dipear"],"en":["Wash and cut vegetables into sticks","Serve with hummus for dipping"]}'
),

('yogur_frutos_rojos',134,'morning_snack','🫐',
'{"es":"Yogur griego con frutos rojos","en":"Greek yogurt with berries","fr":"Yaourt grec aux fruits rouges","it":"Yogurt greco con frutti di bosco"}',
'{"es":"Alto en proteína y probióticos, con antioxidantes de los frutos rojos","en":"High in protein and probiotics, with antioxidants from berries"}',
2,0,170,14,18,3,3,
ARRAY['vegetarian','gluten_free','high_protein','low_carb'],
ARRAY['menstrual','follicular','luteal','ovulation'],
ARRAY['energy','muscle','maintain'],
ARRAY['cramps','inflammation','pms'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["150g yogur griego 0%","80g frutos rojos mixtos (frescos o congelados)","1 cdta miel (opt)","1 cda semillas de chía"],"en":["150g 0% Greek yogurt","80g mixed berries (fresh or frozen)","1 tsp honey (opt)","1 tbsp chia seeds"]}',
'{"es":["Coloca el yogur en un bol","Añade los frutos rojos, la miel y las semillas de chía"],"en":["Place yogurt in a bowl","Top with berries, honey and chia seeds"]}'
),

('almendras_chocolate_negro',135,'morning_snack','🍫',
'{"es":"Almendras con chocolate negro","en":"Almonds with dark chocolate","fr":"Amandes et chocolat noir","it":"Mandorle con cioccolato fondente"}',
'{"es":"Snack antiinflamatorio: magnesio de las almendras + antioxidantes del cacao","en":"Anti-inflammatory snack: magnesium from almonds + cocoa antioxidants"}',
1,0,200,5,12,16,4,
ARRAY['vegan','gluten_free','vegetarian','keto','low_carb','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY['cramps','pms','fatigue'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["20g almendras crudas (aprox 15)","15g chocolate negro 85%+ (2-3 onzas)"],"en":["20g raw almonds (approx 15)","15g 85%+ dark chocolate (2-3 squares)"]}',
'{"es":["Pesa las almendras y el chocolate","Combina en un bol pequeño o lleva en una bolsita para picar"],"en":["Weigh almonds and chocolate","Combine in a small bowl or carry in a bag for snacking"]}'
),

-- ── SNACKS TARDE ──────────────────────────────────────────────────────────────

('guacamole_nachos',136,'afternoon_snack','🥑',
'{"es":"Guacamole casero con nachos","en":"Homemade guacamole with tortilla chips","fr":"Guacamole maison aux chips","it":"Guacamole fatto in casa con chips"}',
'{"es":"Grasas saludables del aguacate con el crujiente de los nachos","en":"Healthy fats from avocado with the crunch of tortilla chips"}',
5,0,240,3,22,16,6,
ARRAY['vegan','gluten_free','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["1 aguacate maduro","1/4 cebolla roja picada fina","1 cdta zumo de limón","Sal, cilantro fresco","30g nachos sin sal añadida"],"en":["1 ripe avocado","1/4 red onion finely diced","1 tsp lemon juice","Salt, fresh coriander","30g unsalted tortilla chips"]}',
'{"es":["Aplasta el aguacate con tenedor","Mezcla con cebolla, limón, sal y cilantro","Sirve con los nachos"],"en":["Mash the avocado with a fork","Mix in onion, lemon, salt and coriander","Serve with tortilla chips"]}'
),

('platano_mantequilla_almendras',137,'afternoon_snack','🍌',
'{"es":"Plátano con mantequilla de almendras","en":"Banana with almond butter","fr":"Banane au beurre d''amandes","it":"Banana con burro di mandorle"}',
'{"es":"Snack pre o post entreno: glucosa rápida + proteína y grasas saludables","en":"Pre or post workout snack: fast glucose + protein and healthy fats"}',
2,0,220,5,30,9,4,
ARRAY['vegan','gluten_free','vegetarian','paleo'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['energy','muscle'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["1 plátano mediano","2 cdas mantequilla de almendras"],"en":["1 medium banana","2 tbsp almond butter"]}',
'{"es":["Pela el plátano y córtalo en rodajas","Acompaña con la mantequilla de almendras"],"en":["Peel and slice the banana","Serve alongside almond butter for dipping"]}'
),

('bolitas_energia_avena',138,'afternoon_snack','⚡',
'{"es":"Bolitas de energía de avena y cacao","en":"Oat and cocoa energy balls","fr":"Boules d''énergie avoine-cacao","it":"Palline energetiche avena e cacao"}',
'{"es":"Snack casero sin horno: avena, cacao y miel en 10 minutos","en":"No-bake homemade snack: oats, cocoa and honey in 10 minutes"}',
10,0,280,7,36,11,5,
ARRAY['vegetarian','vegan'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','nuts'],
'easy','under_20','low',
'{"es":["100g copos de avena","2 cdas cacao puro en polvo","3 cdas mantequilla de cacahuete","2 cdas miel o sirope de arce","1 pizca sal"],"en":["100g rolled oats","2 tbsp pure cocoa powder","3 tbsp peanut butter","2 tbsp honey or maple syrup","1 pinch salt"]}',
'{"es":["Mezcla todos los ingredientes hasta obtener una masa compacta","Forma bolitas del tamaño de una nuez","Refrigera 30 min antes de consumir. Duran 5 días en nevera"],"en":["Mix all ingredients until compact dough forms","Roll into walnut-sized balls","Refrigerate 30 min before eating. Keep in fridge up to 5 days"]}'
),

('queso_cottage_fruta',139,'afternoon_snack','🍍',
'{"es":"Queso cottage con piña y nueces","en":"Cottage cheese with pineapple and walnuts","fr":"Cottage cheese à l''ananas et noix","it":"Cottage cheese con ananas e noci"}',
'{"es":"Alto en proteína y bajo en grasa, combinación dulce y saciante","en":"High protein, low fat — sweet and satisfying combination"}',
3,0,190,18,16,5,1,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['dairy','nuts'],
'easy','under_20','low',
'{"es":["150g queso cottage bajo en grasa","80g piña en trozos (fresca o en su jugo)","10g nueces picadas"],"en":["150g low-fat cottage cheese","80g pineapple chunks (fresh or in juice)","10g chopped walnuts"]}',
'{"es":["Coloca el cottage cheese en un bol","Añade la piña y las nueces por encima"],"en":["Place cottage cheese in a bowl","Top with pineapple and walnuts"]}'
),

('edamame_sal_marina',140,'afternoon_snack','🫛',
'{"es":"Edamame con sal marina","en":"Edamame with sea salt","fr":"Edamame au sel marin","it":"Edamame con sale marino"}',
'{"es":"Proteína vegetal completa en un snack de 5 minutos","en":"Complete plant protein in a 5-minute snack"}',
1,5,150,12,11,5,5,
ARRAY['vegan','gluten_free','vegetarian','high_protein'],
ARRAY['follicular','ovulation','menstrual'],
ARRAY['muscle','energy'],
ARRAY['anemia','fatigue'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["150g edamame congelado (en vaina)","Agua para hervir","Sal marina gruesa"],"en":["150g frozen edamame (in pod)","Water for boiling","Coarse sea salt"]}',
'{"es":["Hierve el edamame 3-5 min en agua con sal","Escurre y espolvorea con sal marina gruesa","Come directamente de las vainas"],"en":["Boil edamame 3-5 min in salted water","Drain and sprinkle with coarse sea salt","Eat directly from the pods"]}'
),

-- ── DESAYUNOS ─────────────────────────────────────────────────────────────────

('smoothie_bowl_tropical',141,'breakfast','🥭',
'{"es":"Smoothie bowl tropical","en":"Tropical smoothie bowl","fr":"Smoothie bowl tropical","it":"Smoothie bowl tropicale"}',
'{"es":"Base de mango y plátano congelado con toppings coloridos y nutritivos","en":"Frozen mango and banana base with colourful nutritious toppings"}',
8,0,340,8,60,8,7,
ARRAY['vegan','gluten_free','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["150g mango congelado","1 plátano congelado","50ml leche de coco","Toppings: fruta fresca, granola sin azúcar, semillas de cáñamo"],"en":["150g frozen mango","1 frozen banana","50ml coconut milk","Toppings: fresh fruit, unsweetened granola, hemp seeds"]}',
'{"es":["Tritura el mango, plátano y leche de coco hasta obtener una textura espesa","Vierte en un bol y añade los toppings al gusto"],"en":["Blend frozen mango, banana and coconut milk until thick and smooth","Pour into a bowl and add toppings as desired"]}'
),

('overnight_oats_manzana',142,'breakfast','🌙',
'{"es":"Overnight oats de manzana y canela","en":"Apple cinnamon overnight oats","fr":"Overnight oats pomme-cannelle","it":"Overnight oats mela e cannella"}',
'{"es":"Prepara la noche anterior: desayuno sin cocinar, alto en fibra","en":"Prep the night before: no-cook breakfast, high in fiber"}',
5,0,380,12,58,10,8,
ARRAY['vegetarian','vegan','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['gluten','nuts'],
'easy','under_20','low',
'{"es":["60g copos de avena","200ml leche vegetal","1 cdta canela","1 cdta miel o sirope de arce","1/2 manzana rallada","1 cda mantequilla de almendras"],"en":["60g rolled oats","200ml plant milk","1 tsp cinnamon","1 tsp honey or maple syrup","1/2 grated apple","1 tbsp almond butter"]}',
'{"es":["Mezcla la avena con la leche vegetal, canela y miel en un tarro","Añade la manzana rallada y remueve","Refrigera overnight (mínimo 6h)","Por la mañana añade la mantequilla de almendras"],"en":["Mix oats with plant milk, cinnamon and honey in a jar","Add grated apple and stir","Refrigerate overnight (minimum 6h)","In the morning top with almond butter"]}'
),

('tofu_revuelto',143,'breakfast','🍳',
'{"es":"Tofu revuelto con cúrcuma","en":"Turmeric scrambled tofu","fr":"Tofu brouillé au curcuma","it":"Tofu strapazzato alla curcuma"}',
'{"es":"Alternativa vegana a los huevos revueltos, alta en proteína y antiinflamatoria","en":"Vegan scrambled egg alternative, high protein and anti-inflammatory"}',
5,8,260,18,12,14,4,
ARRAY['vegan','gluten_free','vegetarian','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['muscle','energy'],
ARRAY['inflammation'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["200g tofu firme","1/2 cdta cúrcuma","1/4 cdta comino","Sal negra (kala namak) o sal normal","Pimienta negra","1/2 pimiento rojo en daditos","1 puñado espinacas baby","1 cda aceite de oliva"],"en":["200g firm tofu","1/2 tsp turmeric","1/4 tsp cumin","Black salt (kala namak) or regular salt","Black pepper","1/2 red pepper diced","1 handful baby spinach","1 tbsp olive oil"]}',
'{"es":["Desmenuza el tofu con las manos hasta textura de huevo revuelto","Calienta aceite en sartén y saltea el pimiento 2 min","Añade el tofu, cúrcuma, comino, sal y pimienta","Cocina 5-7 min removiendo. Añade espinacas al final"],"en":["Crumble tofu with your hands to scrambled egg texture","Heat oil in pan and sauté pepper 2 min","Add tofu, turmeric, cumin, salt and pepper","Cook 5-7 min stirring. Add spinach at the end"]}'
),

('tostada_salmon_aguacate',144,'breakfast','🐟',
'{"es":"Tostada de aguacate y salmón ahumado","en":"Avocado and smoked salmon toast","fr":"Toast avocat-saumon fumé","it":"Toast avocado e salmone affumicato"}',
'{"es":"Desayuno rico en omega-3 y grasas saludables para el cerebro","en":"Breakfast rich in omega-3 and healthy brain fats"}',
5,3,380,20,28,16,6,
ARRAY['pescatarian','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['energy','muscle','maintain'],
ARRAY[]::text[],
ARRAY['gluten','fish'],
'easy','under_20','medium',
'{"es":["2 rebanadas pan de centeno o integral","1/2 aguacate","80g salmón ahumado","Alcaparras, zumo de limón","Eneldo fresco","Pimienta negra"],"en":["2 slices rye or wholegrain bread","1/2 avocado","80g smoked salmon","Capers, lemon juice","Fresh dill","Black pepper"]}',
'{"es":["Tuesta el pan","Aplasta el aguacate y extiéndelo sobre las tostadas","Coloca el salmón encima","Termina con alcaparras, eneldo, limón y pimienta"],"en":["Toast the bread","Mash avocado and spread over the toasts","Lay smoked salmon on top","Finish with capers, dill, lemon and pepper"]}'
),

('shakshuka_ligera',145,'breakfast','🍅',
'{"es":"Shakshuka ligera de tomate y pimiento","en":"Light tomato and pepper shakshuka","fr":"Shakshuka légère tomates-poivrons","it":"Shakshuka leggera pomodoro e peperone"}',
'{"es":"Huevos escalfados en salsa de tomate especiada, rico en licopeno","en":"Eggs poached in spiced tomato sauce, rich in lycopene"}',
5,15,280,16,22,12,5,
ARRAY['vegetarian','gluten_free','mediterranean','lactose_free'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['cramps','inflammation'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["400g tomate triturado (lata)","1 pimiento rojo","1/2 cebolla","2 dientes ajo","1 cdta comino","1 cdta pimentón dulce","1/4 cdta cayena","2-3 huevos","Aceite de oliva, sal, perejil fresco"],"en":["400g crushed tomatoes (can)","1 red pepper","1/2 onion","2 garlic cloves","1 tsp cumin","1 tsp sweet paprika","1/4 tsp cayenne","2-3 eggs","Olive oil, salt, fresh parsley"]}',
'{"es":["Sofríe cebolla y pimiento en aceite 5 min","Añade ajo y especias, cocina 1 min","Vierte el tomate, salpimenta y cocina 8 min","Haz huecos y rompe los huevos dentro","Tapa y cocina 5 min hasta que la clara cuaje"],"en":["Sauté onion and pepper in oil 5 min","Add garlic and spices, cook 1 min","Pour in tomatoes, season and cook 8 min","Make wells and crack eggs into them","Cover and cook 5 min until whites set"]}'
),

('batido_proteina_frutos_rojos',146,'breakfast','🫐',
'{"es":"Batido de proteína con frutos rojos","en":"Berry protein smoothie","fr":"Smoothie protéiné aux fruits rouges","it":"Frullato proteico ai frutti di bosco"}',
'{"es":"Desayuno express: proteína + antioxidantes en menos de 5 minutos","en":"Express breakfast: protein + antioxidants in under 5 minutes"}',
3,0,310,28,30,5,5,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['menstrual','follicular','ovulation','luteal'],
ARRAY['muscle','energy'],
ARRAY['fatigue','inflammation'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["1 scoop proteína de suero (vainilla o sin sabor)","150g frutos rojos congelados","200ml leche o leche vegetal","1 cda semillas de lino","Hielo al gusto"],"en":["1 scoop whey protein (vanilla or plain)","150g frozen berries","200ml milk or plant milk","1 tbsp flaxseeds","Ice as desired"]}',
'{"es":["Pon todos los ingredientes en la batidora","Tritura 30-60 segundos hasta que quede cremoso","Bebe inmediatamente"],"en":["Add all ingredients to blender","Blend 30-60 seconds until creamy","Drink immediately"]}'
),

-- ── ALMUERZOS ─────────────────────────────────────────────────────────────────

('sopa_lentejas_rojas',147,'lunch','🍲',
'{"es":"Sopa de lentejas rojas y cúrcuma","en":"Red lentil and turmeric soup","fr":"Soupe de lentilles rouges au curcuma","it":"Zuppa di lenticchie rosse e curcuma"}',
'{"es":"Sopa reconfortante rica en hierro y proteína vegetal, antiinflamatoria","en":"Comforting soup rich in iron and plant protein, anti-inflammatory"}',
10,20,320,18,48,5,12,
ARRAY['vegan','gluten_free','vegetarian','anti_inflammatory','high_protein','lactose_free'],
ARRAY['menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY['anemia','fatigue','inflammation','cramps'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas rojas secas","1L caldo de verduras","1 cebolla","2 dientes ajo","1 cdta cúrcuma","1 cdta comino","1/2 cdta jengibre en polvo","1 cda aceite de oliva","Sal, pimienta","Zumo de medio limón"],"en":["200g dry red lentils","1L vegetable broth","1 onion","2 garlic cloves","1 tsp turmeric","1 tsp cumin","1/2 tsp ground ginger","1 tbsp olive oil","Salt, pepper","Juice of half a lemon"]}',
'{"es":["Sofríe cebolla y ajo en aceite 4 min","Añade especias y cocina 1 min","Incorpora lentejas y caldo. Hierve y baja fuego","Cocina 15-18 min hasta que las lentejas se deshagan","Tritura con batidora, ajusta sal. Añade limón al servir"],"en":["Sauté onion and garlic in oil 4 min","Add spices and cook 1 min","Add lentils and broth. Boil then reduce heat","Cook 15-18 min until lentils break down","Blend smooth, adjust salt. Add lemon when serving"]}'
),

('bowl_quinoa_judias_negras',148,'lunch','🫘',
'{"es":"Bowl de quinoa y judías negras","en":"Quinoa and black bean bowl","fr":"Bowl quinoa et haricots noirs","it":"Bowl di quinoa e fagioli neri"}',
'{"es":"Proteína vegetal completa con todos los aminoácidos esenciales","en":"Complete plant protein with all essential amino acids"}',
5,15,420,18,58,10,12,
ARRAY['vegan','gluten_free','vegetarian','high_protein','lactose_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','maintain','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["80g quinoa cruda","200ml agua o caldo","240g judías negras cocidas (lata)","1/2 aguacate","Maíz, cilantro, zumo lima","1 cda aceite de oliva","Sal, comino, pimentón"],"en":["80g raw quinoa","200ml water or broth","240g cooked black beans (can)","1/2 avocado","Corn, coriander, lime juice","1 tbsp olive oil","Salt, cumin, paprika"]}',
'{"es":["Cuece la quinoa en agua o caldo 12-14 min","Calienta las judías con comino y pimentón","Monta el bol: quinoa, judías, aguacate, maíz","Aliña con aceite, lima, cilantro y sal"],"en":["Cook quinoa in water or broth 12-14 min","Heat black beans with cumin and paprika","Assemble bowl: quinoa, beans, avocado, corn","Dress with oil, lime, coriander and salt"]}'
),

('ensalada_atun_plancha',149,'lunch','🐟',
'{"es":"Ensalada de atún a la plancha con limón","en":"Grilled tuna salad with lemon","fr":"Salade de thon grillé au citron","it":"Insalata di tonno alla griglia con limone"}',
'{"es":"Fresco, proteico y bajo en calorías — ensalada de restaurante en casa","en":"Fresh, high-protein and low calorie — restaurant salad at home"}',
10,6,360,38,12,16,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['fish'],
'medium','under_20','medium',
'{"es":["200g filete de atún fresco","Mix de hojas verdes","1/2 pepino","1 tomate","Aceitunas negras","2 cdas aceite de oliva","Zumo de 1 limón","Sal, pimienta, orégano"],"en":["200g fresh tuna steak","Mixed salad leaves","1/2 cucumber","1 tomato","Black olives","2 tbsp olive oil","Juice of 1 lemon","Salt, pepper, oregano"]}',
'{"es":["Salpimenta el atún y hazlo a la plancha 2-3 min por lado (que quede rosado dentro)","Coloca las hojas verdes, pepino, tomate y aceitunas en un plato","Coloca el atún encima y aliña con aceite, limón y orégano"],"en":["Season tuna and grill 2-3 min per side (keep it pink inside)","Arrange salad leaves, cucumber, tomato and olives on a plate","Place tuna on top and dress with oil, lemon and oregano"]}'
),

('wraps_pavo_lechuga',150,'lunch','🌯',
'{"es":"Wraps de lechuga con pavo y aguacate","en":"Lettuce wraps with turkey and avocado","fr":"Wraps de laitue dinde-avocat","it":"Wrap di lattuga con tacchino e avocado"}',
'{"es":"Wraps sin gluten usando hojas de lechuga — bajo en carbos y muy saciante","en":"Gluten-free wraps using lettuce leaves — low carb and very filling"}',
10,0,320,28,12,18,5,
ARRAY['gluten_free','lactose_free','high_protein','low_carb','paleo'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['lose_weight','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["8 hojas grandes de lechuga romana","200g pavo en lonchas (sin aditivos)","1/2 aguacate en rodajas","1 tomate en dados","Mostaza (sin azúcar)","Sal, pimienta"],"en":["8 large romaine lettuce leaves","200g turkey slices (no additives)","1/2 avocado sliced","1 tomato diced","Mustard (sugar-free)","Salt, pepper"]}',
'{"es":["Lava y seca las hojas de lechuga","Coloca sobre cada hoja: pavo, aguacate, tomate","Añade mostaza, sal y pimienta","Enrolla o come como taco"],"en":["Wash and dry lettuce leaves","Place on each leaf: turkey, avocado, tomato","Add mustard, salt and pepper","Roll up or eat as a taco"]}'
),

-- ── CENAS ─────────────────────────────────────────────────────────────────────

('lubina_horno_limón',151,'dinner','🐟',
'{"es":"Lubina al horno con limón y hierbas","en":"Baked sea bass with lemon and herbs","fr":"Bar au four citron-herbes","it":"Branzino al forno con limone ed erbe"}',
'{"es":"Pescado blanco ligero al horno, rico en omega-3 y bajo en grasa","en":"Light baked white fish, rich in omega-3 and low in fat"}',
5,20,290,36,2,14,1,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','paleo','keto','mediterranean'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['lose_weight','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 filetes lubina (aprox 180g cada uno)","1 limón en rodajas","Romero y tomillo frescos","2 cdas aceite de oliva","2 dientes ajo laminados","Sal, pimienta"],"en":["2 sea bass fillets (approx 180g each)","1 lemon sliced","Fresh rosemary and thyme","2 tbsp olive oil","2 garlic cloves sliced","Salt, pepper"]}',
'{"es":["Precalienta horno a 200°C","Coloca el pescado en papel vegetal","Cubre con rodajas de limón, ajo, hierbas y aceite","Salpimenta y hornea 18-20 min"],"en":["Preheat oven to 200°C","Place fish on baking paper","Cover with lemon slices, garlic, herbs and oil","Season and bake 18-20 min"]}'
),

('pollo_tikka_ligero',152,'dinner','🍛',
'{"es":"Tikka masala de pollo ligero","en":"Light chicken tikka masala","fr":"Tikka masala de poulet léger","it":"Pollo tikka masala leggero"}',
'{"es":"Clásico indio aligerado con yogur bajo en grasa en lugar de nata","en":"Indian classic lightened with low-fat yogurt instead of cream"}',
15,20,380,38,18,14,4,
ARRAY['gluten_free','high_protein','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','20_40','medium',
'{"es":["300g pechuga de pollo en dados","200g tomate triturado","100g yogur natural desnatado","1/2 cebolla","2 dientes ajo","1 cdta garam masala","1 cdta cúrcuma","1 cdta comino","1 cdta pimentón","Jengibre rallado, aceite de coco, sal"],"en":["300g chicken breast diced","200g crushed tomatoes","100g non-fat natural yogurt","1/2 onion","2 garlic cloves","1 tsp garam masala","1 tsp turmeric","1 tsp cumin","1 tsp paprika","Grated ginger, coconut oil, salt"]}',
'{"es":["Marina el pollo con yogur, garam masala, cúrcuma y sal 15 min","Sofríe cebolla y ajo en aceite 4 min","Añade pollo marinado, dora 5 min","Incorpora tomate y especias restantes, cocina 15 min a fuego medio"],"en":["Marinate chicken with yogurt, garam masala, turmeric and salt 15 min","Sauté onion and garlic in oil 4 min","Add marinated chicken, brown 5 min","Add tomatoes and remaining spices, cook 15 min on medium heat"]}'
),

('dahl_lentejas',153,'dinner','🫘',
'{"es":"Dahl de lentejas rojas","en":"Red lentil dahl","fr":"Dahl de lentilles rouges","it":"Dahl di lenticchie rosse"}',
'{"es":"Guiso indio vegano, reconfortante y rico en proteína vegetal","en":"Vegan Indian stew, comforting and rich in plant protein"}',
10,25,360,20,52,7,14,
ARRAY['vegan','gluten_free','vegetarian','anti_inflammatory','high_protein','lactose_free'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY['cramps','inflammation','anemia'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas rojas","1 lata tomate triturado (400g)","200ml leche de coco","1 cebolla","3 dientes ajo","1 cdta jengibre rallado","1 cdta cúrcuma","1 cdta garam masala","1 cdta comino","Aceite de coco, sal","Cilantro fresco, arroz para acompañar"],"en":["200g red lentils","1 can crushed tomatoes (400g)","200ml coconut milk","1 onion","3 garlic cloves","1 tsp grated ginger","1 tsp turmeric","1 tsp garam masala","1 tsp cumin","Coconut oil, salt","Fresh coriander, rice to serve"]}',
'{"es":["Sofríe cebolla, ajo y jengibre en aceite 5 min","Añade especias y cocina 1 min","Incorpora lentejas, tomate y leche de coco","Hierve y cocina a fuego lento 20-25 min removiendo","Sirve sobre arroz con cilantro fresco"],"en":["Sauté onion, garlic and ginger in oil 5 min","Add spices and cook 1 min","Add lentils, tomatoes and coconut milk","Boil then simmer 20-25 min stirring","Serve over rice with fresh coriander"]}'
),

('berenjena_parmigiana',154,'dinner','🍆',
'{"es":"Berenjena a la parmigiana ligera","en":"Light aubergine parmigiana","fr":"Aubergine à la parmigiana légère","it":"Parmigiana di melanzane leggera"}',
'{"es":"Versión ligera del clásico italiano: sin fritura, al horno","en":"Light version of the Italian classic: no frying, oven-baked"}',
15,35,320,14,28,15,9,
ARRAY['vegetarian','gluten_free','mediterranean'],
ARRAY['luteal','follicular'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','40_60','low',
'{"es":["2 berenjenas grandes","300g tomate triturado","100g mozzarella light","30g parmesano rallado","2 dientes ajo","Albahaca fresca","Aceite de oliva, sal, pimienta"],"en":["2 large aubergines","300g crushed tomatoes","100g light mozzarella","30g grated parmesan","2 garlic cloves","Fresh basil","Olive oil, salt, pepper"]}',
'{"es":["Corta las berenjenas en rodajas de 1cm, salpimenta y hornea 15 min a 200°C","Prepara la salsa: sofríe ajo, añade tomate y cocina 10 min","Monta en bandeja: berenjena, salsa, mozzarella, repetir","Espolvorea parmesano y hornea 20 min más"],"en":["Slice aubergines 1cm thick, season and bake 15 min at 200°C","Make sauce: sauté garlic, add tomatoes and cook 10 min","Layer in dish: aubergine, sauce, mozzarella, repeat","Top with parmesan and bake 20 more min"]}'
),

('salmon_miso_jengibre',155,'dinner','🍣',
'{"es":"Salmón con glaseado miso y jengibre","en":"Salmon with miso and ginger glaze","fr":"Saumon glacé miso-gingembre","it":"Salmone glassato miso e zenzero"}',
'{"es":"Salmón japonés: omega-3 + probióticos del miso en 20 minutos","en":"Japanese-style salmon: omega-3 + probiotics from miso in 20 minutes"}',
5,15,410,36,8,26,1,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular','ovulation'],
ARRAY['muscle','energy'],
ARRAY['inflammation','fatigue'],
ARRAY['fish','soy','sesame'],
'easy','20_40','medium',
'{"es":["2 filetes de salmón (150g cada uno)","2 cdas miso blanco","1 cda mirin o miel","1 cdta jengibre rallado","1 cdta aceite de sésamo","Semillas de sésamo, cebolleta"],"en":["2 salmon fillets (150g each)","2 tbsp white miso","1 tbsp mirin or honey","1 tsp grated ginger","1 tsp sesame oil","Sesame seeds, spring onion"]}',
'{"es":["Mezcla miso, mirin, jengibre y aceite de sésamo","Unta el salmón con el glaseado por todos lados","Precalienta horno a 200°C o usa la plancha","Cocina 12-15 min en horno o 4-5 min por lado en plancha","Sirve con semillas de sésamo y cebolleta"],"en":["Mix miso, mirin, ginger and sesame oil","Coat salmon with glaze on all sides","Preheat oven to 200°C or heat griddle","Bake 12-15 min or grill 4-5 min per side","Serve with sesame seeds and spring onion"]}'
),

('curry_verduras_coco',156,'dinner','🥥',
'{"es":"Curry de verduras con leche de coco","en":"Vegetable coconut curry","fr":"Curry de légumes au lait de coco","it":"Curry di verdure al latte di cocco"}',
'{"es":"Curry tailandés vegano: cremoso, especiado y lleno de color","en":"Vegan Thai curry: creamy, spiced and full of colour"}',
10,20,350,8,40,18,8,
ARRAY['vegan','gluten_free','vegetarian','anti_inflammatory','lactose_free'],
ARRAY['luteal','menstrual','follicular'],
ARRAY['maintain','energy'],
ARRAY['inflammation','bloating'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["1 lata leche de coco (400ml)","1 cda pasta de curry rojo o amarillo","1 pimiento rojo","1 calabacín","100g judías verdes","1 zanahoria","200ml caldo de verduras","Jengibre, ajo, aceite de coco, sal","Arroz integral o arroz jazmín para acompañar"],"en":["1 can coconut milk (400ml)","1 tbsp red or yellow curry paste","1 red pepper","1 courgette","100g green beans","1 carrot","200ml vegetable broth","Ginger, garlic, coconut oil, salt","Brown or jasmine rice to serve"]}',
'{"es":["Sofríe la pasta de curry con ajo y jengibre en aceite 2 min","Añade las verduras troceadas y saltea 3 min","Vierte leche de coco y caldo, hierve 15 min","Ajusta sal y sirve sobre arroz"],"en":["Sauté curry paste with garlic and ginger in oil 2 min","Add chopped vegetables and stir-fry 3 min","Pour in coconut milk and broth, simmer 15 min","Adjust salt and serve over rice"]}'
),

('pasta_calabacin_pesto',157,'dinner','🌿',
'{"es":"Pasta de calabacín con pesto de albahaca","en":"Courgette pasta with basil pesto","fr":"Pâtes de courgette au pesto de basilic","it":"Pasta di zucchine al pesto di basilico"}',
'{"es":"Pasta baja en carbos usando espirales de calabacín — fresca y sin gluten","en":"Low-carb pasta using courgette spirals — fresh and gluten free"}',
10,5,280,8,14,22,5,
ARRAY['vegetarian','gluten_free','vegan','keto','low_carb','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['lose_weight','maintain'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["2 calabacines grandes","4 cdas pesto de albahaca (sin queso si vegana)","10 tomates cherry partidos","Piñones tostados (opt)","Sal, pimienta"],"en":["2 large courgettes","4 tbsp basil pesto (dairy-free if vegan)","10 cherry tomatoes halved","Toasted pine nuts (opt)","Salt, pepper"]}',
'{"es":["Espiralizad los calabacines o usa un pelador para hacer cintas","Saltea los zoodles en sartén seca 2-3 min para quitarles agua","Mezcla con el pesto y los tomates cherry","Sirve con piñones tostados"],"en":["Spiralize courgettes or use a peeler to make ribbons","Sauté zoodles in a dry pan 2-3 min to remove water","Toss with pesto and cherry tomatoes","Serve with toasted pine nuts"]}'
),

('pollo_limon_alcaparras',158,'dinner','🍋',
'{"es":"Pollo al limón con alcaparras","en":"Lemon chicken with capers","fr":"Poulet citron-câpres","it":"Pollo al limone con capperi"}',
'{"es":"Clásico mediterráneo: rápido, proteico y lleno de sabor","en":"Mediterranean classic: quick, protein-packed and full of flavour"}',
5,15,340,38,4,18,1,
ARRAY['gluten_free','lactose_free','high_protein','low_carb','paleo','keto','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','medium',
'{"es":["300g pechuga de pollo fileteada","Zumo de 1 limón y su ralladura","2 cdas alcaparras","2 dientes ajo laminados","2 cdas aceite de oliva","Sal, pimienta, perejil fresco"],"en":["300g sliced chicken breast","Juice of 1 lemon and its zest","2 tbsp capers","2 garlic cloves sliced","2 tbsp olive oil","Salt, pepper, fresh parsley"]}',
'{"es":["Salpimenta el pollo","Dora en aceite 3-4 min por lado","Añade ajo, zumo y ralladura de limón, alcaparras","Cocina 3 min más hasta que el pollo esté hecho","Sirve con perejil picado"],"en":["Season chicken with salt and pepper","Brown in oil 3-4 min per side","Add garlic, lemon juice and zest, capers","Cook 3 more min until chicken is cooked through","Serve with chopped parsley"]}'
),

('tortilla_española_ligera',159,'dinner','🥚',
'{"es":"Tortilla española ligera","en":"Light Spanish omelette","fr":"Omelette espagnole légère","it":"Frittata spagnola leggera"}',
'{"es":"Tortilla de patata con menos aceite — proteína + carbos equilibrados","en":"Spanish omelette with less oil — balanced protein + carbs"}',
10,20,360,18,32,16,3,
ARRAY['vegetarian','gluten_free','mediterranean','lactose_free'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["4 huevos","2 patatas medianas (aprox 300g)","1/2 cebolla","3 cdas aceite de oliva","Sal, pimienta"],"en":["4 eggs","2 medium potatoes (approx 300g)","1/2 onion","3 tbsp olive oil","Salt, pepper"]}',
'{"es":["Pela y corta las patatas en rodajas finas","Pocha patatas y cebolla en aceite 12-15 min a fuego bajo","Escurre el aceite (reserva). Bate los huevos con sal y mezcla con patatas","Cuaja en sartén 4 min, da la vuelta con un plato, otros 3 min"],"en":["Peel and slice potatoes thinly","Poach potatoes and onion in oil 12-15 min on low heat","Drain oil (keep it). Beat eggs with salt and mix with potatoes","Set in pan 4 min, flip with a plate, cook 3 more min"]}'
),

('bol_buddha_tahini',160,'dinner','🥙',
'{"es":"Bol Buddha con tahini y garbanzos","en":"Buddha bowl with tahini and chickpeas","fr":"Buddha bowl tahini-pois chiches","it":"Buddha bowl con tahini e ceci"}',
'{"es":"Bol completo vegano con proteína, grasa y fibra en cada bocado","en":"Complete vegan bowl with protein, fat and fibre in every bite"}',
15,20,460,16,52,18,12,
ARRAY['vegan','gluten_free','vegetarian','mediterranean','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['sesame'],
'easy','20_40','low',
'{"es":["80g quinoa o arroz integral","240g garbanzos cocidos (lata)","1 zanahoria rallada","1/4 col lombarda en juliana","1/2 aguacate","Salsa tahini: 2 cdas tahini, zumo de limón, agua, ajo, sal"],"en":["80g quinoa or brown rice","240g cooked chickpeas (can)","1 grated carrot","1/4 red cabbage in julienne","1/2 avocado","Tahini dressing: 2 tbsp tahini, lemon juice, water, garlic, salt"]}',
'{"es":["Cuece el grano según instrucciones","Asa los garbanzos con pimentón y aceite 20 min a 200°C","Prepara la salsa tahini mezclando todos los ingredientes","Monta el bol con todos los elementos y la salsa encima"],"en":["Cook grain according to instructions","Roast chickpeas with paprika and oil 20 min at 200°C","Make tahini dressing by mixing all ingredients","Assemble bowl with all elements and dressing on top"]}'
)
ON CONFLICT (id) DO NOTHING;
