-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 10 (15) — display_order 311-325
-- Enfocado en: vegetarian, high_protein (cierre de categorías)
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 9
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── VEGETARIAN + HIGH PROTEIN ─────────────────────────────────────────────────

('curry_tofu_lentejas_veg',311,'dinner','🍛',
'{"es":"Curry de tofu y lentejas rojas","en":"Tofu and red lentil curry","fr":"Curry de tofu et lentilles rouges","it":"Curry di tofu e lenticchie rosse"}',
'{"es":"Doble proteína vegetal: tofu y lentejas en curry cremoso de coco — alto en proteína sin carne","en":"Double plant protein: tofu and lentils in creamy coconut curry — high protein without meat"}',
8,25,480,28,48,16,10,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['soy'],
'easy','20_40','low',
'{"es":["200g tofu firme en dados","150g lentejas rojas","400ml leche de coco","300ml caldo de verduras","1 cebolla en dados","3 dientes de ajo","1 cdta jengibre rallado","2 cdtas curry en polvo","1 cdta cúrcuma","1 cdta comino","2 cdas aceite de oliva","Espinacas baby","Cilantro, sal"],"en":["200g firm tofu diced","150g red lentils","400ml coconut milk","300ml vegetable stock","1 onion diced","3 garlic cloves","1 tsp grated ginger","2 tsp curry powder","1 tsp turmeric","1 tsp cumin","2 tbsp olive oil","Baby spinach","Coriander, salt"]}',
'{"es":["Dora el tofu en aceite a fuego alto 4-5 min hasta crujiente, reserva","Sofríe la cebolla, el ajo y el jengibre en el mismo aceite 4 min","Añade las especias y cocina 1 min","Incorpora las lentejas, la leche de coco y el caldo","Cuece 18-20 min hasta que las lentejas estén tiernas","Añade las espinacas y el tofu, cocina 2 min más","Sirve con cilantro fresco"],"en":["Brown tofu in oil over high heat 4-5 min until crispy, set aside","Sauté onion, garlic and ginger in same oil 4 min","Add spices and cook 1 min","Add lentils, coconut milk and stock","Cook 18-20 min until lentils are tender","Add spinach and tofu, cook 2 min more","Serve with fresh coriander"]}'
),

('bol_quinoa_huevo_veg',312,'lunch','🥚',
'{"es":"Bol de quinoa con huevo poché y edamame","en":"Quinoa bowl with poached egg and edamame","fr":"Bowl quinoa oeuf poche et edamame","it":"Bowl di quinoa con uovo in camicia ed edamame"}',
'{"es":"Bol vegetariano alto en proteína: quinoa, huevo escalfado, edamame y tahini","en":"High protein vegetarian bowl: quinoa, poached egg, edamame and tahini"}',
10,15,480,26,52,16,8,
ARRAY['vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['eggs','soy','sesame'],
'medium','20_40','low',
'{"es":["160g quinoa","2 huevos","100g edamame cocido","1/2 aguacate","Hojas de espinaca baby","Para el tahini: 2 cdas tahini, zumo de 1 limón, 1 diente de ajo, agua, sal","1 cdta vinagre blanco (para los huevos)","Semillas de sésamo, cebolleta verde"],"en":["160g quinoa","2 eggs","100g cooked edamame","1/2 avocado","Baby spinach leaves","For tahini: 2 tbsp tahini, juice of 1 lemon, 1 garlic clove, water, salt","1 tsp white vinegar (for the eggs)","Sesame seeds, spring onion"]}',
'{"es":["Cuece la quinoa, deja templar","Prepara la salsa de tahini mezclando todos sus ingredientes con agua hasta obtener consistencia cremosa","Escalfa los huevos en agua con vinagre 3 min","Monta el bol: quinoa, espinacas, edamame, aguacate","Coloca el huevo encima, riega con tahini y decora con sésamo y cebolleta"],"en":["Cook quinoa, let cool slightly","Prepare tahini sauce mixing all ingredients with water until creamy","Poach eggs in water with vinegar 3 min","Build bowl: quinoa, spinach, edamame, avocado","Place egg on top, drizzle with tahini and garnish with sesame and spring onion"]}'
),

('tortilla_quinoa_garbanzos_veg',313,'lunch','🫘',
'{"es":"Ensalada de garbanzos con quinoa y feta","en":"Chickpea and quinoa salad with feta","fr":"Salade de pois chiches quinoa et feta","it":"Insalata di ceci e quinoa con feta"}',
'{"es":"Ensalada proteica vegetariana: garbanzos, quinoa y feta — completa y sin carne","en":"Vegetarian protein salad: chickpeas, quinoa and feta — complete without meat"}',
10,15,500,22,60,16,10,
ARRAY['vegetarian','gluten_free','high_protein','mediterranean'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['dairy'],
'easy','20_40','low',
'{"es":["160g quinoa cocida","200g garbanzos cocidos","80g queso feta desmenuzado","150g tomates cherry en mitades","1/2 pepino en dados","Hojas de menta y perejil","Para la vinagreta: 2 cdas aceite de oliva, 1 cda zumo de limón, 1 cdta comino, sal, pimienta"],"en":["160g cooked quinoa","200g cooked chickpeas","80g crumbled feta","150g cherry tomatoes halved","1/2 cucumber diced","Mint and parsley leaves","For dressing: 2 tbsp olive oil, 1 tbsp lemon juice, 1 tsp cumin, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando todos sus ingredientes","Mezcla la quinoa, los garbanzos, el tomate y el pepino","Riega con la vinagreta y remueve bien","Añade el feta y las hierbas frescas","Sirve templado o frío"],"en":["Prepare dressing by mixing all ingredients","Mix quinoa, chickpeas, tomato and cucumber","Drizzle with dressing and toss well","Add feta and fresh herbs","Serve warm or cold"]}'
),

('lasaña_vegetal_veg',314,'dinner','🍆',
'{"es":"Lasaña de verduras con bechamel de almendra","en":"Vegetable lasagne with almond bechamel","fr":"Lasagne de legumes bechamel aux amandes","it":"Lasagne di verdure con besciamella alle mandorle"}',
'{"es":"Lasaña vegetariana con berenjena, calabacín, espinacas y bechamel ligera — reconfortante","en":"Vegetarian lasagne with aubergine, courgette, spinach and light bechamel — comforting"}',
20,45,520,20,58,20,8,
ARRAY['vegetarian','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','dairy','nuts'],
'medium','over_40','medium',
'{"es":["9 láminas de lasaña precocidas","1 berenjena en láminas finas","2 calabacines en láminas","150g espinacas","300g tomate triturado","1 cebolla","2 dientes de ajo","Para la bechamel ligera: 500ml leche de almendra, 2 cdas harina de arroz, 2 cdas aceite de oliva, nuez moscada, sal","80g parmesano rallado"],"en":["9 precooked lasagne sheets","1 aubergine thinly sliced","2 courgettes sliced","150g spinach","300g crushed tomato","1 onion","2 garlic cloves","For light bechamel: 500ml almond milk, 2 tbsp rice flour, 2 tbsp olive oil, nutmeg, salt","80g grated parmesan"]}',
'{"es":["Precalienta el horno a 180°C","Asa las láminas de berenjena y calabacín a la plancha o en sartén","Sofríe la cebolla y el ajo, añade el tomate y las espinacas, cuece 8 min","Prepara la bechamel: calienta aceite, añade la harina, incorpora la leche caliente poco a poco removiendo hasta espesar","Monta en bandeja: bechamel, láminas, verduras, tomate, láminas, repite","Termina con bechamel y parmesano","Hornea 35-40 min"],"en":["Preheat oven to 180°C","Grill aubergine and courgette slices in a griddle pan","Sauté onion and garlic, add tomato and spinach, cook 8 min","Make bechamel: heat oil, add flour, add hot milk gradually stirring until thick","Layer in dish: bechamel, sheets, vegetables, tomato, sheets, repeat","Finish with bechamel and parmesan","Bake 35-40 min"]}'
),

('revuelto_tofu_silken_veg',315,'breakfast','🥚',
'{"es":"Revuelto de tofu sedoso con cúrcuma (vegan)","en":"Silken tofu scramble with turmeric (vegan)","fr":"Brouille de tofu soyeux a la curcuma (vegan)","it":"Strapazzata di tofu morbido alla curcuma (vegan)"}',
'{"es":"El huevo revuelto vegano: tofu sedoso con cúrcuma, levadura nutricional y verduras","en":"The vegan scrambled egg: silken tofu with turmeric, nutritional yeast and vegetables"}',
5,8,300,20,12,18,4,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["300g tofu sedoso escurrido","2 cdas levadura nutricional","1/2 cdta cúrcuma","1/4 cdta cúrcuma negra o kala namak (da sabor a huevo, opcional)","100g espinacas baby","1/2 pimiento rojo en dados pequeños","1 cda aceite de oliva","Sal, pimienta negra","Cebollino verde, tostadas de centeno para acompañar"],"en":["300g silken tofu drained","2 tbsp nutritional yeast","1/2 tsp turmeric","1/4 tsp black salt or kala namak (gives egg flavour, optional)","100g baby spinach","1/2 red pepper finely diced","1 tbsp olive oil","Salt, black pepper","Green chives, rye toast to serve"]}',
'{"es":["Saltea el pimiento en aceite 2 min","Añade las espinacas y cocina 1 min","Desmiga el tofu en la sartén con las manos o un tenedor","Añade la levadura, la cúrcuma y la sal negra","Cocina a fuego medio removiendo 4-5 min","Sirve con cebollino y tostadas de centeno"],"en":["Sauté pepper in oil 2 min","Add spinach and cook 1 min","Crumble tofu into the pan by hand or with a fork","Add nutritional yeast, turmeric and black salt","Cook over medium heat stirring 4-5 min","Serve with chives and rye toast"]}'
),

('bol_edamame_proteico_veg',316,'lunch','🌿',
'{"es":"Bol proteico de edamame, tempeh y arroz integral","en":"Protein bowl with edamame, tempeh and brown rice","fr":"Bowl proteine edamame tempeh et riz complet","it":"Bowl proteico con edamame, tempeh e riso integrale"}',
'{"es":"Trío de proteína vegetal completa: edamame, tempeh y arroz integral con vinagreta de miso","en":"Complete plant protein trio: edamame, tempeh and brown rice with miso dressing"}',
10,25,560,32,60,18,10,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['soy','gluten'],
'medium','20_40','low',
'{"es":["160g arroz integral","150g tempeh en dados","100g edamame cocido","1 zanahoria rallada","1/2 pepino en rodajas","Para la vinagreta de miso: 1 cda miso blanco, 1 cda tamari, 1 cda aceite de sésamo, zumo de 1 lima, 1 cdta jengibre rallado","Semillas de sésamo, cebolleta"],"en":["160g brown rice","150g tempeh diced","100g cooked edamame","1 grated carrot","1/2 cucumber sliced","For miso dressing: 1 tbsp white miso, 1 tbsp tamari, 1 tbsp sesame oil, juice of 1 lime, 1 tsp grated ginger","Sesame seeds, spring onion"]}',
'{"es":["Cuece el arroz integral según instrucciones (unos 25 min)","Dora el tempeh en sartén con un poco de aceite 4-5 min por lado","Prepara la vinagreta mezclando todos sus ingredientes","Monta el bol con el arroz, el edamame, la zanahoria y el pepino","Coloca el tempeh encima y riega con la vinagreta de miso","Decora con sésamo y cebolleta"],"en":["Cook brown rice according to instructions (about 25 min)","Brown tempeh in a pan with a little oil 4-5 min per side","Prepare dressing by mixing all ingredients","Build bowl with rice, edamame, carrot and cucumber","Place tempeh on top and drizzle with miso dressing","Garnish with sesame and spring onion"]}'
),

('tortilla_proteica_claras_veg',317,'breakfast','🍳',
'{"es":"Tortilla de claras con queso ricotta y tomate","en":"Egg white omelette with ricotta and tomato","fr":"Omelette de blancs d''oeufs ricotta et tomate","it":"Omelette di albumi con ricotta e pomodoro"}',
'{"es":"Tortilla muy proteica y ligera: solo claras, ricotta cremosa y tomate fresco","en":"Very protein-rich and light omelette: only whites, creamy ricotta and fresh tomato"}',
5,6,280,28,6,16,1,
ARRAY['vegetarian','gluten_free','low_carb','high_protein','keto'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["5 claras de huevo","60g queso ricotta","1 tomate maduro en dados","Albahaca fresca","1 cdta aceite de oliva","Sal, pimienta negra","Pimentón dulce"],"en":["5 egg whites","60g ricotta","1 ripe tomato diced","Fresh basil","1 tsp olive oil","Salt, black pepper","Sweet paprika"]}',
'{"es":["Bate las claras con sal y pimienta hasta que espumen ligeramente","Calienta el aceite en sartén antiadherente a fuego medio","Vierte las claras y deja cuajar 1 min sin mover","Coloca la ricotta y el tomate sobre una mitad","Dobla y cocina 1-2 min más","Sirve con albahaca fresca y pimentón"],"en":["Beat whites with salt and pepper until slightly frothy","Heat oil in non-stick pan over medium heat","Pour in whites and let set 1 min without stirring","Place ricotta and tomato on one half","Fold and cook 1-2 min more","Serve with fresh basil and paprika"]}'
),

('bol_yogur_proteico_veg',318,'breakfast','🫐',
'{"es":"Bol de yogur griego con granola proteica y fruta","en":"Greek yogurt bowl with protein granola and fruit","fr":"Bowl de yaourt grec granola proteine et fruits","it":"Bowl di yogurt greco con granola proteica e frutta"}',
'{"es":"Desayuno rápido alto en proteína: yogur griego, fruta de temporada y granola casera con frutos secos","en":"Quick high protein breakfast: Greek yogurt, seasonal fruit and homemade nut granola"}',
5,0,420,22,46,14,4,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['dairy','nuts','gluten'],
'easy','under_20','low',
'{"es":["200g yogur griego 2% o 5% MG","100g fresas o frutos rojos frescos","30g granola con frutos secos (sin azúcar añadido)","1 cda semillas de chía","1 cda mantequilla de almendra","1 cdta miel o agave","Menta fresca"],"en":["200g 2% or 5% Greek yogurt","100g strawberries or fresh berries","30g nut granola (no added sugar)","1 tbsp chia seeds","1 tbsp almond butter","1 tsp honey or agave","Fresh mint"]}',
'{"es":["Coloca el yogur en un bol amplio","Distribuye la fruta encima","Añade la granola, las semillas de chía y la mantequilla de almendra","Termina con la miel y la menta fresca"],"en":["Place yogurt in a wide bowl","Arrange fruit on top","Add granola, chia seeds and almond butter","Finish with honey and fresh mint"]}'
),

('pasta_legumbres_pesto_veg',319,'dinner','🍝',
'{"es":"Pasta de legumbres con pesto y tomates secos","en":"Legume pasta with pesto and sun-dried tomatoes","fr":"Pates de legumineuses pesto et tomates sechees","it":"Pasta di legumi con pesto e pomodori secchi"}',
'{"es":"Pasta de garbanzos o lentejas (alta en proteína) con pesto de albahaca y tomates secos","en":"Chickpea or lentil pasta (protein-rich) with basil pesto and sun-dried tomatoes"}',
5,12,520,26,58,18,10,
ARRAY['vegetarian','gluten_free','high_protein','lactose_free','vegan'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','under_20','medium',
'{"es":["150g pasta de garbanzos o lentejas","Para el pesto: 30g albahaca, 30g piñones o nueces, 3 cdas aceite de oliva, 1 diente de ajo, zumo de limón, sal (sin queso para hacerlo vegan)","6 tomates secos en aceite picados","Rúcula para servir","Piñones tostados extra"],"en":["150g chickpea or lentil pasta","For pesto: 30g basil, 30g pine nuts or walnuts, 3 tbsp olive oil, 1 garlic clove, lemon juice, salt (no cheese to keep vegan)","6 sun-dried tomatoes in oil chopped","Rocket to serve","Extra toasted pine nuts"]}',
'{"es":["Cuece la pasta de legumbres según instrucciones (suele ser 7-9 min), escurre","Prepara el pesto triturando todos sus ingredientes","Mezcla la pasta caliente con el pesto y los tomates secos","Sirve sobre rúcula con piñones tostados"],"en":["Cook legume pasta according to instructions (usually 7-9 min), drain","Prepare pesto by blending all ingredients","Mix hot pasta with pesto and sun-dried tomatoes","Serve over rocket with toasted pine nuts"]}'
),

('falafel_ensalada_veg',320,'lunch','🧆',
'{"es":"Falafel al horno con ensalada y yogur de menta","en":"Baked falafel with salad and mint yogurt","fr":"Falafel au four salade et yaourt a la menthe","it":"Falafel al forno con insalata e yogurt alla menta"}',
'{"es":"Falafel horneado (no frito) de garbanzos con ensalada y salsa de yogur y menta","en":"Baked (not fried) chickpea falafel with salad and mint yogurt sauce"}',
15,25,480,20,56,16,10,
ARRAY['vegetarian','vegan','high_protein','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'medium','20_40','low',
'{"es":["400g garbanzos cocidos y escurridos","1/2 cebolla picada","2 dientes de ajo","Perejil y cilantro frescos abundantes","1 cdta comino","1 cdta coriandro","1/2 cdta pimentón","2 cdas harina (o harina de garbanzo para sin gluten)","Sal, pimienta","Para la salsa: 150g yogur, menta fresca picada, zumo de limón, sal"],"en":["400g cooked chickpeas drained","1/2 onion chopped","2 garlic cloves","Plenty of fresh parsley and coriander","1 tsp cumin","1 tsp coriander","1/2 tsp paprika","2 tbsp flour (or chickpea flour for gluten-free)","Salt, pepper","For sauce: 150g yogurt, chopped fresh mint, lemon juice, salt"]}',
'{"es":["Precalienta el horno a 200°C","Procesa los garbanzos, la cebolla, el ajo, las hierbas y las especias hasta obtener una masa granulada (no en puré)","Añade la harina, sal y pimienta, mezcla","Forma bolitas o croquetas y coloca en bandeja con papel","Pincela con aceite de oliva","Hornea 20-25 min dando la vuelta a mitad","Prepara la salsa mezclando el yogur con la menta y el limón","Sirve con ensalada verde y la salsa"],"en":["Preheat oven to 200°C","Process chickpeas, onion, garlic, herbs and spices until a grainy paste (not smooth puree)","Add flour, salt and pepper, mix","Shape into balls or patties and place on lined tray","Brush with olive oil","Bake 20-25 min turning halfway","Make sauce mixing yogurt with mint and lemon","Serve with green salad and sauce"]}'
),

('tosta_aguacate_huevo_veg',321,'breakfast','🥑',
'{"es":"Tosta de aguacate con huevo revuelto y semillas","en":"Avocado toast with scrambled egg and seeds","fr":"Toast avocat oeuf brouille et graines","it":"Toast avocado con uova strapazzate e semi"}',
'{"es":"El clásico brunch saludable elevado: tosta integral, aguacate cremoso y huevo revuelto proteico","en":"The elevated healthy brunch classic: wholegrain toast, creamy avocado and protein scrambled egg"}',
5,5,420,20,32,22,7,
ARRAY['vegetarian','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['gluten','eggs'],
'easy','under_20','low',
'{"es":["2 rebanadas de pan integral de masa madre","1 aguacate maduro","2 huevos","1 cda mantequilla o aceite de oliva","Zumo de limón","Sal en escamas","Pimienta negra recién molida","Pimentón ahumado","Semillas mixtas (lino, chía, sésamo)","Cebollino o rúcula"],"en":["2 slices wholegrain sourdough","1 ripe avocado","2 eggs","1 tbsp butter or olive oil","Lemon juice","Flaky salt","Freshly ground black pepper","Smoked paprika","Mixed seeds (flax, chia, sesame)","Chives or rocket"]}',
'{"es":["Tuesta el pan","Aplasta el aguacate con un tenedor, sazona con limón, sal y pimienta","Unta el aguacate sobre las tostadas","Prepara los huevos revueltos a fuego bajo con mantequilla, bien cremosos","Coloca los huevos sobre el aguacate","Espolvorea pimentón, semillas y cebollino"],"en":["Toast the bread","Mash avocado with a fork, season with lemon, salt and pepper","Spread avocado on the toasts","Make scrambled eggs over low heat with butter, very creamy","Place eggs over the avocado","Sprinkle paprika, seeds and chives"]}'
),

('garbanzos_espinacas_huevo_veg',322,'dinner','🍳',
'{"es":"Garbanzos con espinacas y huevo al plato","en":"Chickpeas with spinach and baked egg","fr":"Pois chiches epinards et oeuf au plat","it":"Ceci con spinaci e uovo al forno"}',
'{"es":"Plato andaluz reconvertido: garbanzos y espinacas con huevo pochado encima — alto en proteína","en":"Reworked Andalusian dish: chickpeas and spinach with poached egg on top — high in protein"}',
5,18,460,26,46,18,12,
ARRAY['vegetarian','gluten_free','high_protein','mediterranean','anti_inflammatory'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','pcos','anemia'],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["400g garbanzos cocidos","200g espinacas frescas","2 huevos","1 cebolla en dados","3 dientes de ajo laminados","400g tomate triturado","1 cdta comino","1 cdta pimentón","1 cdta cúrcuma","3 cdas aceite de oliva","Sal, pimienta","Perejil fresco"],"en":["400g cooked chickpeas","200g fresh spinach","2 eggs","1 onion diced","3 garlic cloves sliced","400g crushed tomato","1 tsp cumin","1 tsp paprika","1 tsp turmeric","3 tbsp olive oil","Salt, pepper","Fresh parsley"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade las especias y cocina 1 min","Incorpora el tomate y los garbanzos, cuece 8 min","Añade las espinacas y cocina 3 min hasta que se marchiten","Haz 2 huecos y rompe los huevos dentro","Tapa y cuece 4-5 min hasta que las claras estén cuajadas","Sirve con perejil fresco"],"en":["Sauté onion and garlic in oil 4 min","Add spices and cook 1 min","Add tomato and chickpeas, cook 8 min","Add spinach and cook 3 min until wilted","Make 2 wells and crack eggs in","Cover and cook 4-5 min until whites are set","Serve with fresh parsley"]}'
),

('batido_proteina_platano_veg',323,'snack','🍌',
'{"es":"Batido de proteína de vainilla con plátano y mantequilla de cacahuete","en":"Vanilla protein shake with banana and peanut butter","fr":"Shake proteine vanille banane et beurre de cacahuete","it":"Frullato proteico alla vaniglia con banana e burro di arachidi"}',
'{"es":"Snack o post-entreno: batido alto en proteína con plátano, mantequilla de cacahuete y proteína en polvo","en":"Snack or post-workout: high protein shake with banana, peanut butter and protein powder"}',
3,0,400,30,38,12,4,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['dairy','peanuts'],
'easy','under_20','low',
'{"es":["1 plátano (preferiblemente congelado)","30g proteína de vainilla en polvo (whey o vegetal)","1 cda mantequilla de cacahuete","250ml leche entera o de avena","1 cdta canela","1 cda semillas de chía","Cubitos de hielo"],"en":["1 banana (preferably frozen)","30g vanilla protein powder (whey or plant-based)","1 tbsp peanut butter","250ml whole milk or oat milk","1 tsp cinnamon","1 tbsp chia seeds","Ice cubes"]}',
'{"es":["Coloca todos los ingredientes en la batidora","Bate a velocidad alta 45-60 seg hasta que esté suave y cremoso","Ajusta la consistencia con más leche si lo prefieres más líquido","Bebe inmediatamente o refrigera hasta 4 horas"],"en":["Place all ingredients in the blender","Blend on high for 45-60 sec until smooth and creamy","Adjust consistency with more milk if you prefer it thinner","Drink immediately or refrigerate up to 4 hours"]}'
),

('crema_guisantes_menta_veg',324,'dinner','🫛',
'{"es":"Crema de guisantes frescos con menta y queso de cabra","en":"Fresh pea cream with mint and goat cheese","fr":"Creme de petits pois a la menthe et fromage de chevre","it":"Crema di piselli freschi con menta e formaggio di capra"}',
'{"es":"Sopa fría o templada vegetariana: guisantes frescos, menta y queso de cabra crujiente","en":"Cold or warm vegetarian soup: fresh peas, mint and crispy goat cheese"}',
5,12,340,18,38,12,8,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["400g guisantes frescos o congelados","500ml caldo de verduras","100g queso de cabra en rondas","Hojas de menta fresca abundantes","1 cebolleta en rodajas (solo la parte verde)","2 cdas aceite de oliva","Zumo de limón","Sal, pimienta blanca"],"en":["400g fresh or frozen peas","500ml vegetable stock","100g goat cheese in rounds","Plenty of fresh mint leaves","1 spring onion sliced (green part only)","2 tbsp olive oil","Lemon juice","Salt, white pepper"]}',
'{"es":["Cuece los guisantes en el caldo 8-10 min","Tritura con la menta, la cebolleta, el zumo de limón y el aceite hasta obtener una crema fina","Sazona con sal y pimienta blanca","Dora las rondas de queso de cabra en sartén 1 min por lado","Sirve la crema con las rondas de queso encima y menta fresca"],"en":["Cook peas in stock 8-10 min","Blend with mint, spring onion, lemon juice and oil until fine cream","Season with salt and white pepper","Sear goat cheese rounds in a pan 1 min per side","Serve cream with goat cheese on top and fresh mint"]}'
),

('bol_ricotta_frutas_veg',325,'breakfast','🍓',
'{"es":"Bol de ricotta con fresas y pistachos","en":"Ricotta bowl with strawberries and pistachios","fr":"Bowl de ricotta fraises et pistaches","it":"Bowl di ricotta con fragole e pistacchi"}',
'{"es":"Desayuno ligero y muy proteico: ricotta cremosa con fresas frescas, pistachos y miel","en":"Light and very protein-rich breakfast: creamy ricotta with fresh strawberries, pistachios and honey"}',
5,0,360,20,28,16,3,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['dairy','nuts'],
'easy','under_20','low',
'{"es":["250g queso ricotta fresco","150g fresas frescas en láminas","30g pistachos sin sal pelados","1 cda miel o agave","1 cdta extracto de vainilla","Ralladura de limón","Menta fresca para decorar"],"en":["250g fresh ricotta","150g fresh strawberries sliced","30g unsalted shelled pistachios","1 tbsp honey or agave","1 tsp vanilla extract","Lemon zest","Fresh mint to garnish"]}',
'{"es":["Mezcla la ricotta con la vainilla y la ralladura de limón","Coloca en un bol","Distribuye las fresas y los pistachos encima","Riega con la miel y decora con menta fresca"],"en":["Mix ricotta with vanilla and lemon zest","Place in a bowl","Arrange strawberries and pistachios on top","Drizzle with honey and garnish with fresh mint"]}'
)

ON CONFLICT (id) DO NOTHING;
