-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 14a (32) — display_order 391-422
-- 2 low_fodmap (cierre) + 30 standard
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── LOW FODMAP CIERRE (+2) ────────────────────────────────────────────────────

('crema_calabacin_menta_fodmap',391,'dinner','🥒',
'{"es":"Crema de calabacín y menta (low FODMAP)","en":"Courgette and mint cream soup (low FODMAP)","fr":"Creme de courgette a la menthe (low FODMAP)","it":"Crema di zucchine e menta (low FODMAP)"}',
'{"es":"Sopa suave y digestiva de calabacín con menta fresca — sin cebolla ni ajo, perfecta para días de digestión sensible","en":"Gentle digestive courgette soup with fresh mint — no onion or garlic, perfect for sensitive digestion days"}',
5,18,200,5,18,12,4,
ARRAY['low_fodmap','vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["4 calabacines medianos en dados","700ml caldo de verduras sin cebolla ni ajo","2 cdas aceite de ajo infusionado","Hojas de menta fresca abundantes","Zumo de 1/2 limón","Sal, pimienta blanca","Cebollino verde para decorar","Aceite de oliva para servir"],"en":["4 medium courgettes diced","700ml vegetable stock no onion or garlic","2 tbsp garlic-infused oil","Plenty of fresh mint leaves","Juice of 1/2 lemon","Salt, white pepper","Green chives to garnish","Olive oil to serve"]}',
'{"es":["Sofríe el calabacín en el aceite infusionado 4 min","Añade el caldo y cuece 12 min hasta que el calabacín esté tierno","Añade la menta fresca y el zumo de limón","Tritura hasta obtener una crema suave","Ajusta de sal y pimienta blanca","Sirve con cebollino verde y un hilo de aceite de oliva"],"en":["Sauté courgette in infused oil 4 min","Add stock and cook 12 min until courgette is tender","Add fresh mint and lemon juice","Blend until smooth","Adjust salt and white pepper","Serve with green chives and a drizzle of olive oil"]}'
),

('tortilla_zanahoria_pimiento_fodmap',392,'lunch','🥕',
'{"es":"Tortilla de zanahoria y pimiento rojo (low FODMAP)","en":"Carrot and red pepper omelette (low FODMAP)","fr":"Omelette carotte et poivron rouge (low FODMAP)","it":"Frittata di carote e peperone rosso (low FODMAP)"}',
'{"es":"Tortilla colorida y nutritiva low FODMAP: zanahoria, pimiento rojo y cebollino verde","en":"Colourful nutritious low FODMAP omelette: carrot, red pepper and green chives"}',
8,12,300,16,14,20,3,
ARRAY['low_fodmap','gluten_free','lactose_free','vegetarian','high_protein'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy','muscle'],
ARRAY['sibo','ibs'],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["4 huevos","1 zanahoria rallada","1/2 pimiento rojo en dados pequeños","Cebollino verde picado abundante","2 cdas aceite de ajo infusionado","Sal, pimienta","Pimentón dulce"],"en":["4 eggs","1 grated carrot","1/2 red pepper finely diced","Plenty of chopped green chives","2 tbsp garlic-infused oil","Salt, pepper","Sweet paprika"]}',
'{"es":["Sofríe el pimiento en el aceite infusionado 3 min","Añade la zanahoria rallada y saltea 2 min más","Bate los huevos con sal, pimienta y el cebollino","Vierte los huevos sobre las verduras a fuego medio-bajo","Cuaja 4-5 min, da la vuelta y cuaja 3 min más","Sirve con pimentón por encima"],"en":["Sauté pepper in infused oil 3 min","Add grated carrot and cook 2 min more","Beat eggs with salt, pepper and chives","Pour eggs over vegetables over medium-low heat","Set 4-5 min, flip and set 3 min more","Serve with paprika on top"]}'
),

-- ── STANDARD (30 recetas) ─────────────────────────────────────────────────────

('pasta_carbonara_std',393,'dinner','🍝',
'{"es":"Pasta carbonara clásica","en":"Classic pasta carbonara","fr":"Pates carbonara classiques","it":"Pasta carbonara classica"}',
'{"es":"La auténtica carbonara romana: guanciale, yema de huevo, pecorino y pimienta negra — sin nata","en":"Authentic Roman carbonara: guanciale, egg yolk, pecorino and black pepper — no cream"}',
5,12,620,28,72,24,3,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'medium','under_20','medium',
'{"es":["150g espagueti","80g guanciale o bacon en dados","2 yemas + 1 huevo entero","50g pecorino rallado (o mezcla pecorino-parmesano)","Pimienta negra recién molida abundante","Sal para el agua de cocción"],"en":["150g spaghetti","80g guanciale or bacon diced","2 yolks + 1 whole egg","50g grated pecorino (or pecorino-parmesan mix)","Plenty of freshly ground black pepper","Salt for pasta water"]}',
'{"es":["Cuece la pasta al dente en agua muy salada, reserva 1 taza del agua","Dora el guanciale en sartén seca a fuego medio hasta crujiente","Bate las yemas con el huevo entero, el pecorino y abundante pimienta","Mezcla la pasta escurrida con el guanciale fuera del fuego","Añade los huevos y el queso mezclando rápido, añade agua de cocción poco a poco hasta obtener una salsa cremosa","Sirve inmediatamente con más pecorino y pimienta"],"en":["Cook pasta al dente in well-salted water, reserve 1 cup","Brown guanciale in a dry pan over medium heat until crispy","Beat yolks with whole egg, pecorino and plenty of pepper","Toss drained pasta with guanciale off the heat","Add egg mixture tossing quickly, add cooking water little by little until creamy sauce","Serve immediately with more pecorino and pepper"]}'
),

('pollo_asado_domingo_std',394,'dinner','🍗',
'{"es":"Pollo asado al horno del domingo","en":"Sunday roast chicken","fr":"Poulet roti du dimanche","it":"Pollo arrosto della domenica"}',
'{"es":"Pollo entero al horno con mantequilla de hierbas, limón y ajo — el asado de siempre, perfecto","en":"Whole roast chicken with herb butter, lemon and garlic — the timeless perfect roast"}',
15,70,520,42,4,36,2,
ARRAY['standard','gluten_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','over_40','medium',
'{"es":["1 pollo entero (1,5-1,8 kg)","50g mantequilla blanda","3 dientes de ajo picados","Ralladura y zumo de 1 limón","Romero y tomillo frescos","Sal gruesa, pimienta negra","Aceite de oliva","1 cebolla y 1 limón en mitades (para el interior)"],"en":["1 whole chicken (1.5-1.8 kg)","50g soft butter","3 garlic cloves chopped","Zest and juice of 1 lemon","Fresh rosemary and thyme","Coarse salt, black pepper","Olive oil","1 onion and 1 lemon halved (for cavity)"]}',
'{"es":["Precalienta el horno a 200°C","Mezcla la mantequilla con el ajo, la ralladura de limón y las hierbas","Seca el pollo con papel y coloca en bandeja","Mete la mantequilla de hierbas bajo la piel del pecho","Rellena el interior con la cebolla y el limón cortados","Riega con aceite y zumo de limón, sazona con sal gruesa","Hornea 70-75 min, deja reposar 10 min antes de trinchar"],"en":["Preheat oven to 200°C","Mix butter with garlic, lemon zest and herbs","Pat chicken dry and place in roasting tin","Push herb butter under breast skin","Fill cavity with halved onion and lemon","Drizzle with oil and lemon juice, season with coarse salt","Roast 70-75 min, rest 10 min before carving"]}'
),

('huevos_benedictinos_std',395,'breakfast','🥚',
'{"es":"Huevos benedictinos con jamón y salsa holandesa","en":"Eggs Benedict with ham and hollandaise sauce","fr":"Oeufs benedictine jambon et sauce hollandaise","it":"Uova alla Benedict con prosciutto e salsa olandese"}',
'{"es":"El brunch más famoso: huevo escalfado sobre muffin inglés y jamón con salsa holandesa mantequillosa","en":"The most famous brunch: poached egg on English muffin and ham with buttery hollandaise sauce"}',
10,10,580,24,32,40,2,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'hard','under_20','medium',
'{"es":["2 huevos","2 muffins ingleses partidos","2 lonchas de jamón cocido o york","Para la holandesa: 2 yemas, 80g mantequilla clarificada, 1 cda zumo de limón, sal, pimienta de cayena","1 cda vinagre blanco","Cebollino para decorar"],"en":["2 eggs","2 English muffins halved","2 slices cooked ham","For hollandaise: 2 yolks, 80g clarified butter, 1 tbsp lemon juice, salt, cayenne","1 tbsp white vinegar","Chives to garnish"]}',
'{"es":["Prepara la holandesa al baño María: bate las yemas con el limón, añade la mantequilla en hilo hasta emulsionar, sazona","Tuesta los muffins y calienta el jamón","Escalfa los huevos en agua con vinagre 3 min","Monta: muffin, jamón, huevo escalfado, holandesa generosa y cebollino"],"en":["Make hollandaise in a double boiler: whisk yolks with lemon, add butter in a stream until emulsified, season","Toast muffins and warm ham","Poach eggs in water with vinegar 3 min","Build: muffin, ham, poached egg, generous hollandaise and chives"]}'
),

('risotto_setas_std',396,'dinner','🍄',
'{"es":"Risotto de setas mixtas con parmesano","en":"Mixed mushroom risotto with parmesan","fr":"Risotto de champignons mixtes au parmesan","it":"Risotto ai funghi misti con parmigiano"}',
'{"es":"Risotto cremoso de setas variadas: shiitake, portobello y champiñón con vino blanco y parmesano","en":"Creamy mixed mushroom risotto: shiitake, portobello and button mushrooms with white wine and parmesan"}',
8,28,560,16,72,20,4,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','20_40','medium',
'{"es":["300g arroz arborio","300g setas mixtas (shiitake, portobello, champiñón)","1 cebolla en dados","2 dientes de ajo","150ml vino blanco seco","1L caldo de verduras caliente","60g parmesano rallado","2 cdas mantequilla","2 cdas aceite de oliva","Tomillo fresco","Sal, pimienta negra"],"en":["300g arborio rice","300g mixed mushrooms (shiitake, portobello, button)","1 onion diced","2 garlic cloves","150ml dry white wine","1L hot vegetable stock","60g grated parmesan","2 tbsp butter","2 tbsp olive oil","Fresh thyme","Salt, black pepper"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite y mantequilla 4 min","Añade las setas y cocina 5 min hasta que suelten el agua","Incorpora el arroz y tuesta 2 min","Vierte el vino y deja evaporar","Añade el caldo caliente cucharón a cucharón, removiendo siempre, durante 20 min","Retira del fuego, añade el parmesano y la mantequilla restante, mezcla bien","Sirve con tomillo fresco y pimienta"],"en":["Sauté onion and garlic in oil and butter 4 min","Add mushrooms and cook 5 min until they release water","Add rice and toast 2 min","Pour wine and let evaporate","Add hot stock ladle by ladle, stirring constantly, for 20 min","Remove from heat, add parmesan and remaining butter, stir well","Serve with fresh thyme and pepper"]}'
),

('burger_clásica_std',397,'dinner','🍔',
'{"es":"Hamburguesa clásica con todos los acompañamientos","en":"Classic burger with all the toppings","fr":"Burger classique avec tous les accompagnements","it":"Hamburger classico con tutti gli accompagnamenti"}',
'{"es":"La hamburguesa perfecta: carne jugosa, queso cheddar fundido, lechuga, tomate y salsa especial","en":"The perfect burger: juicy beef, melted cheddar, lettuce, tomato and special sauce"}',
10,10,720,38,52,36,3,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'easy','under_20','medium',
'{"es":["2 hamburguesas de ternera (200g c/u, 80% magra)","2 lonchas de cheddar","2 panes de hamburguesa brioche","Lechuga iceberg","1 tomate en rodajas","1/2 cebolla roja en aros","Pepinillos","Para la salsa: 2 cdas mayonesa, 1 cda ketchup, 1 cdta mostaza, pepinillo picado, sal"],"en":["2 beef patties (200g each, 80% lean)","2 cheddar slices","2 brioche burger buns","Iceberg lettuce","1 tomato sliced","1/2 red onion in rings","Gherkins","For sauce: 2 tbsp mayo, 1 tbsp ketchup, 1 tsp mustard, chopped gherkin, salt"]}',
'{"es":["Forma las hamburguesas y haz una pequeña hendidura en el centro (evita que se hinchen)","Cocina en plancha muy caliente 3-4 min por lado para punto medio","Añade el cheddar en el último minuto y tapa para que se funda","Tuesta el pan en la misma plancha","Prepara la salsa mezclando todos los ingredientes","Monta: pan, salsa, lechuga, tomate, hamburguesa con queso, cebolla, pepinillos, pan"],"en":["Shape patties and make a small dent in the centre (prevents puffing)","Cook on very hot griddle 3-4 min per side for medium","Add cheddar in the last minute and cover to melt","Toast bun on the same griddle","Make sauce mixing all ingredients","Build: bun, sauce, lettuce, tomato, cheese burger, onion, gherkins, bun"]}'
),

('lasaña_boloñesa_std',398,'dinner','🍝',
'{"es":"Lasaña boloñesa clásica","en":"Classic beef lasagne","fr":"Lasagne bolognaise classique","it":"Lasagna alla bolognese classica"}',
'{"es":"Lasaña de domingo: ragu de ternera lento, bechamel cremosa y parmesano gratinado","en":"Sunday lasagne: slow beef ragu, creamy bechamel and gratinated parmesan"}',
20,90,620,30,54,28,5,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'hard','over_40','medium',
'{"es":["9 láminas de lasaña","300g carne picada de ternera","150g panceta en dados","1 cebolla, 1 zanahoria, 1 apio (sofrito)","200ml vino tinto","400g tomate triturado","Para la bechamel: 500ml leche, 40g mantequilla, 40g harina, nuez moscada","80g parmesano rallado","Sal, pimienta"],"en":["9 lasagne sheets","300g beef mince","150g pancetta diced","1 onion, 1 carrot, 1 celery (soffritto)","200ml red wine","400g crushed tomato","For bechamel: 500ml milk, 40g butter, 40g flour, nutmeg","80g grated parmesan","Salt, pepper"]}',
'{"es":["Prepara el ragu: sofríe la panceta, añade el sofrito y cocina 5 min, añade la carne y dórala, vierte el vino y deja evaporar, añade el tomate y cuece 45-60 min a fuego bajo","Prepara la bechamel: derrite mantequilla, añade harina, incorpora la leche caliente poco a poco removiendo hasta espesar, sazona con nuez moscada","Monta: bechamel, láminas, ragu, bechamel, repite; termina con bechamel y parmesano","Hornea a 180°C 30 min hasta gratinar"],"en":["Make ragu: brown pancetta, add soffritto and cook 5 min, add mince and brown, pour wine and evaporate, add tomato and cook 45-60 min on low","Make bechamel: melt butter, add flour, add hot milk gradually stirring until thick, season with nutmeg","Layer: bechamel, sheets, ragu, bechamel, repeat; finish with bechamel and parmesan","Bake at 180°C 30 min until golden"]}'
),

('tacos_pollo_std',399,'dinner','🌮',
'{"es":"Tacos de pollo con guacamole y pico de gallo","en":"Chicken tacos with guacamole and pico de gallo","fr":"Tacos de poulet guacamole et pico de gallo","it":"Tacos di pollo con guacamole e pico de gallo"}',
'{"es":"Tacos festivos de pollo marinado con guacamole casero y pico de gallo — perfectos para compartir","en":"Festive marinated chicken tacos with homemade guacamole and pico de gallo — perfect for sharing"}',
15,12,520,32,48,18,8,
ARRAY['standard','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','20_40','low',
'{"es":["300g pechuga de pollo marinada (zumo de lima, comino, pimentón, ajo, orégano)","Tortillas de maíz","Para el guacamole: 2 aguacates, zumo de lima, cilantro, sal, chile","Para el pico de gallo: 2 tomates, 1/4 cebolla, cilantro, zumo de lima, jalapeño, sal","Col morada rallada, crema agria"],"en":["300g chicken breast marinated (lime juice, cumin, paprika, garlic, oregano)","Corn tortillas","For guacamole: 2 avocados, lime juice, coriander, salt, chilli","For pico de gallo: 2 tomatoes, 1/4 onion, coriander, lime juice, jalapeño, salt","Shredded red cabbage, sour cream"]}',
'{"es":["Cocina el pollo marinado en plancha 5-6 min por lado, deja reposar y desmenuza","Prepara el guacamole machacando los aguacates con limón, cilantro y chile","Prepara el pico de gallo mezclando todos sus ingredientes","Calienta las tortillas en sartén seca","Monta los tacos con el pollo, el guacamole, el pico de gallo y la col morada"],"en":["Cook marinated chicken on griddle 5-6 min per side, rest and shred","Make guacamole mashing avocados with lime, coriander and chilli","Make pico de gallo mixing all ingredients","Warm tortillas in a dry pan","Build tacos with chicken, guacamole, pico de gallo and red cabbage"]}'
),

('crema_tomate_albahaca_std',400,'dinner','🍅',
'{"es":"Crema de tomate y albahaca al horno","en":"Roasted tomato and basil cream soup","fr":"Creme de tomates et basilic roties","it":"Crema di pomodori arrosto e basilico"}',
'{"es":"Sopa de tomate casera concentrada: tomates asados al horno con albahaca fresca y un toque de nata","en":"Concentrated homemade tomato soup: oven-roasted tomatoes with fresh basil and a touch of cream"}',
8,40,280,6,32,14,6,
ARRAY['standard','vegetarian','gluten_free'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','over_40','low',
'{"es":["800g tomates maduros en mitades","1 cebolla en cuartos","4 dientes de ajo con piel","3 cdas aceite de oliva","Albahaca fresca abundante","100ml nata para cocinar","500ml caldo de verduras","Sal, pimienta","Azúcar moreno (pizca, para equilibrar acidez)"],"en":["800g ripe tomatoes halved","1 onion quartered","4 garlic cloves unpeeled","3 tbsp olive oil","Plenty of fresh basil","100ml cooking cream","500ml vegetable stock","Salt, pepper","Brown sugar (pinch, to balance acidity)"]}',
'{"es":["Coloca los tomates, la cebolla y el ajo en bandeja con aceite, sal y pimienta","Hornea a 200°C 35-40 min hasta caramelizados","Exprime el ajo asado de su piel","Tritura todo con el caldo, la albahaca y la nata","Calienta y ajusta de sal, añade una pizca de azúcar si es muy ácida","Sirve con albahaca fresca y un hilo de aceite"],"en":["Place tomatoes, onion and garlic on a tray with oil, salt and pepper","Roast at 200°C 35-40 min until caramelised","Squeeze roasted garlic out of skin","Blend everything with stock, basil and cream","Heat and adjust salt, add a pinch of sugar if too acidic","Serve with fresh basil and a drizzle of oil"]}'
),

('bacón_huevos_fritos_std',401,'breakfast','🥚',
'{"es":"Bacon con huevos fritos y tostadas","en":"Bacon with fried eggs and toast","fr":"Bacon oeufs au plat et toasts","it":"Bacon con uova al tegamino e toast"}',
'{"es":"El desayuno inglés simplificado: bacon crujiente, huevos fritos a la perfección y tostadas de pan","en":"Simplified English breakfast: crispy bacon, perfectly fried eggs and bread toast"}',
3,8,520,28,28,30,2,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs'],
'easy','under_20','low',
'{"es":["4 lonchas de bacon","2 huevos","2 rebanadas de pan de molde o artesano","Mantequilla para las tostadas","Sal, pimienta negra","Ketchup o salsa Worcester (opcional)"],"en":["4 bacon rashers","2 eggs","2 slices white or artisan bread","Butter for toast","Salt, black pepper","Ketchup or Worcestershire sauce (optional)"]}',
'{"es":["Cocina el bacon en sartén seca a fuego medio hasta el punto deseado de crujiente","En la misma grasa fríe los huevos — para yema líquida a fuego bajo 3 min","Tuesta el pan y úntalo con mantequilla","Sazona los huevos con sal y pimienta negra generosa","Sirve todo junto inmediatamente"],"en":["Cook bacon in a dry pan over medium heat until desired crispiness","In the same fat fry eggs — for runny yolk over low heat 3 min","Toast bread and butter it","Season eggs with salt and generous black pepper","Serve everything together immediately"]}'
),

('pollo_tikka_masala_std',402,'dinner','🍛',
'{"es":"Pollo tikka masala","en":"Chicken tikka masala","fr":"Poulet tikka masala","it":"Pollo tikka masala"}',
'{"es":"El curry más popular del mundo: pollo marinado en yogur y especias en salsa de tomate y nata","en":"The world''s most popular curry: yogurt-spiced chicken in tomato cream sauce"}',
20,30,520,38,22,28,4,
ARRAY['standard','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','20_40','medium',
'{"es":["400g pechuga de pollo en dados","Para la marinada: 150g yogur, 1 cdta garam masala, 1 cdta cúrcuma, 1 cdta comino, 1 cdta pimentón, 1 diente de ajo, jengibre rallado, sal","Para la salsa: 1 cebolla, 3 dientes de ajo, jengibre, tomate triturado, 200ml nata, garam masala, pimentón, comino, cúrcuma, aceite, cilantro"],"en":["400g chicken breast diced","For marinade: 150g yogurt, 1 tsp garam masala, 1 tsp turmeric, 1 tsp cumin, 1 tsp paprika, 1 garlic clove, grated ginger, salt","For sauce: 1 onion, 3 garlic cloves, ginger, crushed tomato, 200ml cream, garam masala, paprika, cumin, turmeric, oil, coriander"]}',
'{"es":["Marina el pollo en el yogur y las especias mínimo 1 hora (mejor toda la noche)","Cocina el pollo marinado en plancha o en horno hasta dorado, reserva","Sofríe la cebolla, el ajo y el jengibre, añade las especias, incorpora el tomate y cuece 10 min","Añade la nata y el pollo, cuece 15 min a fuego bajo","Sirve con cilantro fresco y arroz basmati"],"en":["Marinate chicken in yogurt and spices minimum 1 hour (overnight is better)","Cook marinated chicken on griddle or in oven until golden, set aside","Sauté onion, garlic and ginger, add spices, add tomato and cook 10 min","Add cream and chicken, cook 15 min over low heat","Serve with fresh coriander and basmati rice"]}'
),

('croquetas_jamon_std',403,'snack','🍘',
'{"es":"Croquetas de jamón ibérico","en":"Iberian ham croquettes","fr":"Croquettes au jambon iberique","it":"Crocchette di prosciutto iberico"}',
'{"es":"Croquetas caseras cremosas de jamón ibérico: bechamel espesa, jamón de calidad y rebozado crujiente","en":"Creamy homemade ham croquettes: thick bechamel, quality ham and crispy coating"}',
20,20,380,14,32,22,2,
ARRAY['standard'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'hard','20_40','medium',
'{"es":["Para la masa: 500ml leche entera, 60g mantequilla, 80g harina, 150g jamón ibérico picado muy fino, sal, pimienta, nuez moscada","Para el rebozado: 2 huevos batidos, pan rallado, aceite para freír"],"en":["For the dough: 500ml whole milk, 60g butter, 80g flour, 150g finely chopped Iberian ham, salt, pepper, nutmeg","For coating: 2 beaten eggs, breadcrumbs, oil for frying"]}',
'{"es":["Derrite la mantequilla, añade la harina y cocina 2 min removiendo","Incorpora la leche caliente poco a poco sin parar de remover hasta obtener una bechamel muy espesa","Añade el jamón, sal, pimienta y nuez moscada","Extiende en bandeja, tapa con film y refrigera mínimo 3 horas","Forma las croquetas, pasa por huevo y pan rallado","Fríe en aceite caliente hasta doradas, escurre y sirve"],"en":["Melt butter, add flour and cook 2 min stirring","Add hot milk gradually stirring constantly until very thick bechamel","Add ham, salt, pepper and nutmeg","Spread on a tray, cover with film and refrigerate minimum 3 hours","Shape croquettes, coat in egg then breadcrumbs","Fry in hot oil until golden, drain and serve"]}'
),

('salmon_teriyaki_std',404,'dinner','🐟',
'{"es":"Salmón teriyaki con arroz y edamame","en":"Teriyaki salmon with rice and edamame","fr":"Saumon teriyaki riz et edamame","it":"Salmone teriyaki con riso ed edamame"}',
'{"es":"Salmón glaseado en salsa teriyaki casera sobre arroz de grano corto y edamame","en":"Salmon glazed in homemade teriyaki sauce over short grain rice and edamame"}',
5,15,560,38,60,14,5,
ARRAY['standard','gluten_free','lactose_free','high_protein','pescatarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','soy'],
'easy','under_20','medium',
'{"es":["2 filetes de salmón","Para el teriyaki: 3 cdas salsa de soja, 1 cda mirin, 1 cdta aceite de sésamo, 1 cda azúcar moreno","150g arroz de grano corto","100g edamame cocido","Sésamo, cebolleta verde"],"en":["2 salmon fillets","For teriyaki: 3 tbsp soy sauce, 1 tbsp mirin, 1 tsp sesame oil, 1 tbsp brown sugar","150g short grain rice","100g cooked edamame","Sesame, spring onion"]}',
'{"es":["Mezcla los ingredientes del teriyaki en un cazo pequeño y calienta hasta disolver el azúcar","Marina el salmón 10 min","Cocina el salmón en sartén antiadherente 4-5 min por lado pintando con el teriyaki","Cuece el arroz","Sirve el salmón sobre el arroz con el edamame, sésamo y cebolleta verde"],"en":["Mix teriyaki ingredients in a small saucepan and heat until sugar dissolves","Marinate salmon 10 min","Cook salmon in non-stick pan 4-5 min per side brushing with teriyaki","Cook rice","Serve salmon over rice with edamame, sesame and spring onion"]}'
),

('tortilla_española_std',405,'lunch','🥚',
'{"es":"Tortilla española clásica","en":"Classic Spanish omelette","fr":"Tortilla espagnole classique","it":"Tortilla spagnola classica"}',
'{"es":"La tortilla de siempre: patata, cebolla, huevo y aceite de oliva — cuajada o jugosa, como a ti te gusta","en":"The classic tortilla: potato, onion, egg and olive oil — set or runny, just how you like it"}',
10,20,440,18,38,24,4,
ARRAY['standard','gluten_free','lactose_free','vegetarian'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["5 huevos","3 patatas medianas peladas en rodajas finas","1 cebolla en rodajas finas","Aceite de oliva abundante (para pochar)","Sal"],"en":["5 eggs","3 medium potatoes peeled and thinly sliced","1 onion thinly sliced","Plenty of olive oil (for poaching)","Salt"]}',
'{"es":["Pocha la patata y la cebolla en aceite abundante a fuego muy bajo 15-18 min hasta tiernas (no doradas)","Escurre bien el aceite y mezcla con los huevos batidos y sal","Calienta 2 cdas del aceite en sartén antiadherente a fuego medio","Vierte la mezcla y cuaja 4-5 min","Da la vuelta con un plato y cuaja 3 min más (o menos si la quieres jugosa)"],"en":["Poach potato and onion in plenty of oil over very low heat 15-18 min until tender (not golden)","Drain oil well and mix with beaten eggs and salt","Heat 2 tbsp of the oil in a non-stick pan over medium heat","Pour in mixture and set 4-5 min","Flip with a plate and set 3 min more (or less for a runny centre)"]}'
),

('pad_thai_std',406,'dinner','🍜',
'{"es":"Pad thai de gambas","en":"Prawn pad thai","fr":"Pad thai aux crevettes","it":"Pad thai ai gamberi"}',
'{"es":"El pad thai auténtico: fideos de arroz, gambas, huevo, salsa tamarindo y cacahuetes tostados","en":"Authentic pad thai: rice noodles, prawns, egg, tamarind sauce and toasted peanuts"}',
15,12,540,28,68,16,4,
ARRAY['standard','gluten_free','lactose_free','pescatarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['shellfish','peanuts','soy'],
'medium','20_40','medium',
'{"es":["150g fideos de arroz planos","200g gambas peladas","2 huevos","Para la salsa: 2 cdas salsa de tamarindo, 2 cdas salsa de pescado, 1 cda azúcar","40g cacahuetes tostados picados","2 cebolletas","100g brotes de soja","2 cdas aceite vegetal","Lima, cilantro, guindilla"],"en":["150g flat rice noodles","200g peeled prawns","2 eggs","For sauce: 2 tbsp tamarind sauce, 2 tbsp fish sauce, 1 tbsp sugar","40g chopped toasted peanuts","2 spring onions","100g bean sprouts","2 tbsp vegetable oil","Lime, coriander, chilli"]}',
'{"es":["Remoja los fideos en agua caliente 8 min, escurre","Mezcla los ingredientes de la salsa","Calienta el wok al máximo con aceite, saltea las gambas 2 min, reserva","En el mismo wok fríe los huevos removiendo, añade los fideos y la salsa","Mezcla 2 min, incorpora las gambas y los brotes","Sirve con cacahuetes, lima, cilantro y guindilla"],"en":["Soak noodles in hot water 8 min, drain","Mix sauce ingredients","Heat wok on maximum with oil, stir-fry prawns 2 min, set aside","In same wok scramble eggs, add noodles and sauce","Toss 2 min, add prawns and bean sprouts","Serve with peanuts, lime, coriander and chilli"]}'
),

('caldo_cocido_std',407,'dinner','🍲',
'{"es":"Caldo de cocido madrileño","en":"Madrid-style chickpea and meat broth","fr":"Bouillon de pot-au-feu madrilene","it":"Brodo di bollito alla madrilena"}',
'{"es":"El caldo más reconfortante: hueso de ternera, pollo y verduras cocidas lentamente — nutrición ancestral","en":"The most comforting broth: beef bone, chicken and slowly cooked vegetables — ancestral nutrition"}',
10,120,340,26,24,14,5,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','over_40','low',
'{"es":["1 hueso de ternera con tuétano","200g muslo de pollo","200g garbanzos cocidos","2 zanahorias","2 patatas","1 puerro","2 ramas de apio","1 nabo","Sal, pimienta en grano","Perejil fresco"],"en":["1 beef bone with marrow","200g chicken thigh","200g cooked chickpeas","2 carrots","2 potatoes","1 leek","2 celery stalks","1 turnip","Salt, peppercorns","Fresh parsley"]}',
'{"es":["Coloca la carne y el hueso en olla grande con agua fría, lleva a ebullición y retira la espuma","Añade todas las verduras enteras y los garbanzos","Sazona con sal y pimienta en grano","Cuece a fuego muy bajo 90-100 min","Cuela el caldo y sirve con las verduras y la carne desmigada","Añade perejil fresco al final"],"en":["Place meat and bone in large pot with cold water, bring to boil and skim foam","Add all vegetables whole and chickpeas","Season with salt and peppercorns","Cook over very low heat 90-100 min","Strain broth and serve with vegetables and shredded meat","Add fresh parsley at the end"]}'
),

('tarta_queso_std',408,'snack','🧀',
'{"es":"Tarta de queso estilo La Viña (vasca)","en":"Basque burnt cheesecake","fr":"Cheesecake basque brule","it":"Cheesecake basco bruciato"}',
'{"es":"La tarta de queso quemada del País Vasco: cremosa, sin base y con exterior caramelizado — sencilla y perfecta","en":"The Basque burnt cheesecake: creamy, crustless and with a caramelised exterior — simple and perfect"}',
10,50,420,10,32,28,0,
ARRAY['standard','gluten_free','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy','eggs'],
'easy','over_40','medium',
'{"es":["600g queso crema tipo Philadelphia","200g azúcar","4 huevos","200ml nata para montar","1 cda harina (o maicena para sin gluten)","1 cdta extracto de vainilla"],"en":["600g cream cheese Philadelphia style","200g sugar","4 eggs","200ml heavy cream","1 tbsp flour (or cornstarch for gluten-free)","1 tsp vanilla extract"]}',
'{"es":["Precalienta el horno a 220°C","Bate el queso crema con el azúcar hasta suave","Añade los huevos uno a uno batiendo bien","Incorpora la nata, la harina y la vainilla","Forra un molde de 22cm con papel de horno dejando que sobresalga","Vierte la mezcla y hornea 50 min — debe quedar el exterior muy dorado y el centro tembloroso","Deja enfriar completamente antes de desmoldar"],"en":["Preheat oven to 220°C","Beat cream cheese with sugar until smooth","Add eggs one by one beating well","Add cream, flour and vanilla","Line a 22cm tin with baking paper letting it overhang","Pour mixture and bake 50 min — exterior should be very dark and centre should wobble","Cool completely before unmoulding"]}'
),

('patatas_bravas_std',409,'snack','🥔',
'{"es":"Patatas bravas con salsa brava y alioli","en":"Patatas bravas with bravas and alioli sauce","fr":"Pommes de terre bravas sauce brava et aioli","it":"Patatas bravas con salsa brava e alioli"}',
'{"es":"El clásico tapa español: patatas fritas o al horno con salsa brava picante y alioli cremoso","en":"The classic Spanish tapa: fried or oven potatoes with spicy bravas sauce and creamy alioli"}',
10,30,420,6,54,18,5,
ARRAY['standard','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["600g patatas en dados","Para la salsa brava: 200g tomate triturado, 1 cdta pimentón picante, 1 cdta pimentón dulce, 1 cdta vinagre, aceite de oliva, sal","Para el alioli: 2 dientes de ajo, 1 huevo, 200ml aceite de girasol, zumo de limón, sal","Aceite para hornear o freír"],"en":["600g potatoes diced","For bravas sauce: 200g crushed tomato, 1 tsp hot paprika, 1 tsp sweet paprika, 1 tsp vinegar, olive oil, salt","For alioli: 2 garlic cloves, 1 egg, 200ml sunflower oil, lemon juice, salt","Oil for baking or frying"]}',
'{"es":["Hornea las patatas a 210°C 25-30 min con aceite y sal hasta doradas y crujientes","Prepara la salsa brava: sofríe el pimentón en aceite 1 min, añade el tomate y el vinagre, cuece 8 min","Prepara el alioli: tritura el ajo con el huevo, añade el aceite en hilo hasta emulsionar, sazona","Sirve las patatas calientes con ambas salsas por encima"],"en":["Bake potatoes at 210°C 25-30 min with oil and salt until golden and crispy","Make bravas sauce: fry paprika in oil 1 min, add tomato and vinegar, cook 8 min","Make alioli: blend garlic with egg, add oil in a stream until emulsified, season","Serve hot potatoes with both sauces drizzled on top"]}'
),

('paella_valenciana_std',410,'dinner','🥘',
'{"es":"Paella valenciana con pollo y conejo","en":"Valencian paella with chicken and rabbit","fr":"Paella valencienne poulet et lapin","it":"Paella valenciana con pollo e coniglio"}',
'{"es":"La paella auténtica: pollo, conejo, judías verdes, garrofón y arroz bomba con socarrat","en":"The authentic paella: chicken, rabbit, green beans, garrofón beans and bomba rice with socarrat"}',
15,45,540,32,68,14,5,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'hard','over_40','medium',
'{"es":["300g pollo troceado","200g conejo troceado","150g judías verdes planas","100g garrofón o judía blanca cocida","300g arroz bomba","800ml caldo de pollo caliente","1 tomate rallado","1 cdta pimentón dulce","Unas hebras de azafrán","Aceite de oliva","Sal","Romero fresco"],"en":["300g chicken pieces","200g rabbit pieces","150g flat green beans","100g garrofón or white beans cooked","300g bomba rice","800ml hot chicken stock","1 grated tomato","1 tsp sweet paprika","A few saffron threads","Olive oil","Salt","Fresh rosemary"]}',
'{"es":["Dora el pollo y el conejo en aceite en la paellera a fuego alto 8-10 min","Añade las judías y sofríe 3 min","Añade el tomate y cocina 5 min hasta que se consuma el agua","Añade el pimentón y el azafrán (disuelto en caldo), vierte el caldo caliente","Cuando hierva distribuye el arroz uniformemente, no vuelvas a mezclar","Cuece a fuego fuerte 10 min, luego medio 8 min, sube al final 2 min para el socarrat","Reposa 5 min tapado con papel"],"en":["Brown chicken and rabbit in oil in the paella pan over high heat 8-10 min","Add beans and cook 3 min","Add tomato and cook 5 min until water evaporates","Add paprika and saffron (dissolved in stock), pour in hot stock","When boiling distribute rice evenly, do not stir again","Cook on high heat 10 min, then medium 8 min, raise heat last 2 min for socarrat","Rest 5 min covered with paper"]}'
),

('gazpacho_andaluz_std',411,'lunch','🍅',
'{"es":"Gazpacho andaluz","en":"Andalusian gazpacho","fr":"Gaspacho andalou","it":"Gazpacho andaluso"}',
'{"es":"El gazpacho de siempre: tomate, pepino, pimiento, ajo y aceite de oliva — frío, sabroso y saludable","en":"The classic gazpacho: tomato, cucumber, pepper, garlic and olive oil — cold, tasty and healthy"}',
12,0,180,3,22,8,4,
ARRAY['standard','vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["800g tomates maduros pelados","1 pepino pelado","1 pimiento verde","1/2 pimiento rojo","1 diente de ajo","100ml aceite de oliva virgen extra","2 cdas vinagre de jerez","Sal","Pan del día anterior (opcional, para espesar)","Agua fría"],"en":["800g ripe peeled tomatoes","1 peeled cucumber","1 green pepper","1/2 red pepper","1 garlic clove","100ml extra-virgin olive oil","2 tbsp sherry vinegar","Salt","Day-old bread (optional, to thicken)","Cold water"]}',
'{"es":["Tritura todos los ingredientes a velocidad alta hasta obtener una crema muy fina","Añade agua fría poco a poco hasta la consistencia deseada","Ajusta de sal y vinagre","Refrigera mínimo 2 horas antes de servir","Sirve muy frío con guarnición de pepino, pimiento y tomate en dados"],"en":["Blend all ingredients on high until very smooth","Add cold water gradually until desired consistency","Adjust salt and vinegar","Refrigerate minimum 2 hours before serving","Serve very cold with a garnish of diced cucumber, pepper and tomato"]}'
),

('arroz_tres_delicias_std',412,'dinner','🍚',
'{"es":"Arroz tres delicias","en":"Three-delights fried rice","fr":"Riz cantonnais trois delices","it":"Riso tre delizie"}',
'{"es":"El arroz frito chino de siempre: jamón, gambas, huevo y verduras — con arroz del día anterior","en":"The classic Chinese fried rice: ham, prawns, egg and vegetables — with day-old rice"}',
8,10,480,22,64,14,3,
ARRAY['standard','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['shellfish','eggs','soy'],
'easy','under_20','low',
'{"es":["300g arroz cocido del día anterior","100g gambas peladas","100g jamón cocido en dados","2 huevos batidos","80g guisantes congelados","2 cebolletas","2 cdas salsa de soja","1 cda aceite de sésamo","2 cdas aceite vegetal","Sal, pimienta"],"en":["300g day-old cooked rice","100g peeled prawns","100g cooked ham diced","2 beaten eggs","80g frozen peas","2 spring onions","2 tbsp soy sauce","1 tbsp sesame oil","2 tbsp vegetable oil","Salt, pepper"]}',
'{"es":["Calienta el wok al máximo con aceite vegetal","Saltea las gambas 1-2 min, reserva","Añade los huevos y revuelve hasta cuajar, reserva","Saltea los guisantes y las cebolletas 2 min","Añade el arroz desmenuzado y saltea 3 min a fuego muy alto","Incorpora el jamón, las gambas, el huevo, la soja y el sésamo","Saltea todo 1 min más y sirve"],"en":["Heat wok on maximum with vegetable oil","Stir-fry prawns 1-2 min, set aside","Add eggs and scramble until set, set aside","Stir-fry peas and spring onions 2 min","Add crumbled rice and stir-fry 3 min on very high heat","Add ham, prawns, egg, soy sauce and sesame oil","Toss everything 1 min more and serve"]}'
),

('crema_chocolate_std',413,'snack','🍫',
'{"es":"Mousse de chocolate con nata y frambuesas","en":"Chocolate mousse with cream and raspberries","fr":"Mousse au chocolat creme et framboises","it":"Mousse al cioccolato con panna e lamponi"}',
'{"es":"Mousse de chocolate elegante y esponjosa con nata montada y frambuesas frescas","en":"Elegant fluffy chocolate mousse with whipped cream and fresh raspberries"}',
15,5,380,6,28,26,3,
ARRAY['standard','vegetarian','gluten_free'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy','eggs'],
'medium','under_20','medium',
'{"es":["150g chocolate negro 70%","3 huevos separados","200ml nata para montar","2 cdas azúcar","1 cdta extracto de vainilla","Frambuesas frescas para servir"],"en":["150g 70% dark chocolate","3 eggs separated","200ml heavy cream","2 tbsp sugar","1 tsp vanilla extract","Fresh raspberries to serve"]}',
'{"es":["Derrite el chocolate al baño María, deja templar","Bate las yemas con el azúcar hasta blanquear, mezcla con el chocolate","Monta la nata a punto firme y las claras a punto de nieve por separado","Incorpora la nata al chocolate con movimientos envolventes, luego las claras","Refrigera 3 horas mínimo","Sirve con frambuesas frescas"],"en":["Melt chocolate in a double boiler, let cool slightly","Beat yolks with sugar until pale, mix with chocolate","Whip cream to stiff peaks and egg whites to stiff peaks separately","Fold cream into chocolate gently, then fold in whites","Refrigerate minimum 3 hours","Serve with fresh raspberries"]}'
),

('sopa_cebolla_std',414,'dinner','🧅',
'{"es":"Sopa de cebolla gratinada al estilo francés","en":"French onion soup gratinée","fr":"Soupe a l''oignon gratinee a la francaise","it":"Zuppa di cipolla gratinata alla francese"}',
'{"es":"Clásico francés: sopa de cebolla caramelizada con caldo, tostada de pan y gruyère gratinado","en":"French classic: caramelised onion soup with stock, bread crouton and gratinated gruyère"}',
10,45,420,14,42,20,4,
ARRAY['standard','vegetarian'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'medium','over_40','low',
'{"es":["4 cebollas grandes en juliana fina","50g mantequilla","1 cda aceite de oliva","150ml vino blanco o jerez seco","1L caldo de ternera o verduras","4 rebanadas de pan baguette","100g gruyère rallado","Tomillo fresco","Sal, pimienta"],"en":["4 large onions thinly sliced","50g butter","1 tbsp olive oil","150ml dry white wine or sherry","1L beef or vegetable stock","4 baguette slices","100g grated gruyère","Fresh thyme","Salt, pepper"]}',
'{"es":["Carameliza las cebollas en mantequilla y aceite a fuego muy bajo 35-40 min, removiendo con frecuencia, hasta doradas y dulces","Añade el vino y deja evaporar 3 min","Incorpora el caldo y el tomillo, cuece 10 min","Sirve en cazuelas individuales, coloca el pan encima y cubre con gruyère","Gratina bajo el grill del horno hasta dorado y burbujeante"],"en":["Caramelise onions in butter and oil over very low heat 35-40 min, stirring often, until golden and sweet","Add wine and evaporate 3 min","Add stock and thyme, cook 10 min","Serve in individual bowls, place bread on top and cover with gruyère","Gratinate under the grill until golden and bubbling"]}'
),

('pollo_pimientos_std',415,'dinner','🫑',
'{"es":"Pollo al chilindrón con pimientos","en":"Chicken al chilindrón with peppers","fr":"Poulet al chilindron aux poivrons","it":"Pollo al chilindrón con peperoni"}',
'{"es":"Guiso aragonés de pollo con pimientos rojos, tomate y jamón — sabor profundo y reconfortante","en":"Aragonese chicken stew with red peppers, tomato and ham — deep and comforting flavour"}',
10,35,460,38,16,22,5,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["4 muslos de pollo","2 pimientos rojos en tiras","2 pimientos verdes en tiras","100g jamón serrano en dados","1 cebolla en dados","3 dientes de ajo","400g tomate triturado","100ml vino blanco","2 cdas aceite de oliva","Laurel, sal, pimienta"],"en":["4 chicken thighs","2 red peppers in strips","2 green peppers in strips","100g cured ham diced","1 onion diced","3 garlic cloves","400g crushed tomato","100ml white wine","2 tbsp olive oil","Bay leaf, salt, pepper"]}',
'{"es":["Dora el pollo en aceite a fuego alto 4 min por lado, reserva","Sofríe la cebolla, el ajo y el jamón 4 min","Añade los pimientos y cocina 5 min","Vierte el vino y deja evaporar, añade el tomate y el laurel","Devuelve el pollo, tapa y cuece a fuego medio-bajo 25 min","Ajusta de sal y sirve con pan o arroz"],"en":["Brown chicken in oil over high heat 4 min per side, set aside","Sauté onion, garlic and ham 4 min","Add peppers and cook 5 min","Pour wine and evaporate, add tomato and bay leaf","Return chicken, cover and cook over medium-low heat 25 min","Adjust salt and serve with bread or rice"]}'
),

('crepes_dulces_std',416,'breakfast','🥞',
'{"es":"Crêpes dulces con mantequilla y azúcar","en":"Sweet crêpes with butter and sugar","fr":"Crepes sucrees beurre et sucre","it":"Crepes dolci con burro e zucchero"}',
'{"es":"Las crêpes francesas perfectas: finas, con bordes encaje y relleno de mantequilla, limón y azúcar","en":"Perfect French crêpes: thin, lacy edges and filled with butter, lemon and sugar"}',
5,15,380,10,54,14,2,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'easy','under_20','low',
'{"es":["200g harina","2 huevos","400ml leche","1 cdta extracto de vainilla","1 cda azúcar","Pizca de sal","20g mantequilla derretida","Para servir: mantequilla, azúcar, zumo de limón, mermelada o nutella"],"en":["200g flour","2 eggs","400ml milk","1 tsp vanilla extract","1 tbsp sugar","Pinch of salt","20g melted butter","To serve: butter, sugar, lemon juice, jam or nutella"]}',
'{"es":["Mezcla la harina, el azúcar y la sal. Añade los huevos, la leche y la vainilla removiendo hasta obtener una masa sin grumos. Añade la mantequilla derretida","Reposa 15-30 min (opcional pero mejora la textura)","Calienta sartén pequeña antiadherente con unas gotas de mantequilla","Vierte un cucharón de masa, mueve la sartén para cubrir el fondo fino","Cocina 1 min por lado","Sirve con el relleno elegido"],"en":["Mix flour, sugar and salt. Add eggs, milk and vanilla stirring until smooth. Add melted butter","Rest 15-30 min (optional but improves texture)","Heat small non-stick pan with a few drops of butter","Pour a ladleful of batter, swirl pan to thinly cover the base","Cook 1 min per side","Serve with chosen filling"]}'
),

('costillas_bbq_std',417,'dinner','🍖',
'{"es":"Costillas de cerdo con salsa BBQ","en":"BBQ pork ribs","fr":"Cotes de porc sauce BBQ","it":"Costine di maiale con salsa BBQ"}',
'{"es":"Costillas tiernas al horno bañadas en salsa BBQ casera — el placer de comer con las manos","en":"Tender oven ribs glazed in homemade BBQ sauce — the pleasure of eating with your hands"}',
10,90,580,34,28,36,3,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','medium',
'{"es":["600g costillas de cerdo en tira","Para el rub: pimentón, comino, ajo en polvo, cebolla en polvo, azúcar moreno, sal, pimienta","Para la salsa BBQ: ketchup, vinagre de manzana, salsa Worcester, mostaza, miel, ajo en polvo, pimentón ahumado"],"en":["600g pork spare ribs in a rack","For rub: paprika, cumin, garlic powder, onion powder, brown sugar, salt, pepper","For BBQ sauce: ketchup, apple cider vinegar, worcestershire, mustard, honey, garlic powder, smoked paprika"]}',
'{"es":["Frota las costillas con el rub y deja marinar 30 min","Envuelve en papel de aluminio y hornea a 150°C 75 min","Prepara la salsa BBQ mezclando todos sus ingredientes en un cazo y cocina 10 min","Destapa las costillas, unta generosamente con la salsa","Hornea a 200°C 15 min más hasta glaseadas","Sirve con más salsa y servilletas"],"en":["Rub ribs with the rub and marinate 30 min","Wrap in foil and bake at 150°C 75 min","Make BBQ sauce mixing all ingredients in a saucepan and cook 10 min","Unwrap ribs, brush generously with sauce","Bake at 200°C 15 min more until glazed","Serve with more sauce and napkins"]}'
),

('pan_francés_tostado_std',418,'breakfast','🍞',
'{"es":"Pan francés (torrija) con frutos rojos","en":"French toast with berries","fr":"Pain perdu aux fruits rouges","it":"French toast con frutti rossi"}',
'{"es":"Torrija al estilo francés: pan brioche empapado en huevo y leche, dorado en mantequilla con frutos rojos","en":"French-style torrija: brioche soaked in egg and milk, golden in butter with fresh berries"}',
8,6,460,14,56,18,4,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'easy','under_20','low',
'{"es":["4 rebanadas de pan brioche o de molde gruesas","2 huevos","100ml leche","1 cdta vainilla","1 cdta canela","1 cda azúcar","20g mantequilla","150g frutos rojos frescos","Sirope de arce o azúcar glas para servir"],"en":["4 thick brioche or white bread slices","2 eggs","100ml milk","1 tsp vanilla","1 tsp cinnamon","1 tbsp sugar","20g butter","150g fresh berries","Maple syrup or icing sugar to serve"]}',
'{"es":["Bate los huevos con la leche, la vainilla, la canela y el azúcar","Remoja cada rebanada en la mezcla de huevo 30 seg por lado","Derrite la mantequilla en sartén a fuego medio","Cocina las rebanadas 2-3 min por lado hasta doradas","Sirve con frutos rojos frescos y sirope de arce"],"en":["Beat eggs with milk, vanilla, cinnamon and sugar","Soak each slice in the egg mixture 30 sec per side","Melt butter in pan over medium heat","Cook slices 2-3 min per side until golden","Serve with fresh berries and maple syrup"]}'
),

('espárragos_trigueros_huevo_std',419,'lunch','🥚',
'{"es":"Espárragos trigueros con huevo roto y jamón","en":"Wild asparagus with broken egg and ham","fr":"Asperges sauvages oeuf casse et jambon","it":"Asparagi selvatici con uovo rotto e prosciutto"}',
'{"es":"Plato español sencillo y delicioso: espárragos a la plancha, huevo frito roto y jamón crujiente","en":"Simple delicious Spanish dish: griddled asparagus, broken fried egg and crispy ham"}',
5,10,380,22,8,28,4,
ARRAY['standard','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["400g espárragos trigueros limpios","4 lonchas de jamón ibérico o serrano","2 huevos","3 cdas aceite de oliva","Sal gruesa, pimienta","Zumo de limón"],"en":["400g wild asparagus trimmed","4 slices Iberian or cured ham","2 eggs","3 tbsp olive oil","Coarse salt, pepper","Lemon juice"]}',
'{"es":["Cocina los espárragos en plancha muy caliente con aceite 3-4 min, sazona con sal gruesa","Mientras, fríe los huevos en aceite caliente hasta que los bordes estén crujientes y la yema líquida","Coloca los espárragos en la base, el jamón encima","Añade los huevos y rómpelos con el tenedor al servir","Riega con el aceite de la fritura y un toque de limón"],"en":["Cook asparagus on very hot griddle with oil 3-4 min, season with coarse salt","Meanwhile fry eggs in hot oil until edges are crispy and yolk is runny","Place asparagus as base, ham on top","Add eggs and break with fork when serving","Drizzle with frying oil and a touch of lemon"]}'
),

('ceviche_mixto_std',420,'lunch','🍋',
'{"es":"Ceviche mixto de pescado y marisco","en":"Mixed fish and seafood ceviche","fr":"Ceviche mixte poisson et fruits de mer","it":"Ceviche misto di pesce e frutti di mare"}',
'{"es":"Ceviche peruano con merluza, gambas y pulpo en leche de tigre de lima — fresco y vibrante","en":"Peruvian ceviche with hake, prawns and octopus in lime tiger milk — fresh and vibrant"}',
20,0,280,28,12,10,2,
ARRAY['standard','gluten_free','lactose_free','pescatarian','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','shellfish'],
'medium','under_20','high',
'{"es":["200g merluza fresca en dados (muy frescos o congelada -20°C mínimo 24h)","150g gambas cocidas","100g pulpo cocido en rodajas","Zumo de 6 limas","1 ají amarillo o guindilla suave","1/4 cebolla roja en juliana fina","Cilantro fresco","Sal","1 cdta jengibre rallado","Canchita (maíz tostado) para acompañar"],"en":["200g fresh hake diced (very fresh or frozen -20°C minimum 24h)","150g cooked prawns","100g cooked octopus sliced","Juice of 6 limes","1 yellow chilli or mild chilli","1/4 red onion thinly sliced","Fresh coriander","Salt","1 tsp grated ginger","Toasted corn (canchita) to serve"]}',
'{"es":["Mezcla el zumo de lima con el jengibre y el ají, deja macerar 5 min — esta es la leche de tigre","Añade el pescado crudo y marina 10-12 min (se cocina en el ácido)","Incorpora las gambas, el pulpo, la cebolla y el cilantro","Sazona con sal","Sirve inmediatamente con canchita y más cilantro"],"en":["Mix lime juice with ginger and chilli, marinate 5 min — this is the tiger milk","Add raw fish and marinate 10-12 min (it cooks in the acid)","Add prawns, octopus, onion and coriander","Season with salt","Serve immediately with toasted corn and more coriander"]}'
),

('sándwich_club_std',421,'lunch','🥪',
'{"es":"Sándwich club triple","en":"Triple club sandwich","fr":"Sandwich club triple","it":"Sandwich club triplo"}',
'{"es":"El sándwich más completo: triple capa de pollo, bacon, lechuga, tomate, aguacate y mayonesa","en":"The most complete sandwich: triple layer of chicken, bacon, lettuce, tomato, avocado and mayo"}',
10,8,620,34,48,28,5,
ARRAY['standard','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'easy','under_20','low',
'{"es":["3 rebanadas de pan de molde tostado","100g pechuga de pollo cocida en lonchas","3 lonchas de bacon crujiente","Lechuga iceberg","2 rodajas de tomate","1/4 aguacate en láminas","2 cdas mayonesa","Sal, pimienta","Palillos para sujetar"],"en":["3 slices toasted white bread","100g cooked chicken breast sliced","3 crispy bacon rashers","Iceberg lettuce","2 tomato slices","1/4 avocado sliced","2 tbsp mayonnaise","Salt, pepper","Toothpicks to secure"]}',
'{"es":["Tuesta el pan","Unta mayonesa en todas las rebanadas","Primera capa: lechuga, tomate, sal y pimienta","Segunda capa de pan, pollo, bacon","Tercera capa de pan, aguacate, sal y pimienta","Sujeta con palillos y corta en 4 triángulos"],"en":["Toast the bread","Spread mayo on all slices","First layer: lettuce, tomato, salt and pepper","Second bread layer, chicken, bacon","Third bread layer, avocado, salt and pepper","Secure with toothpicks and cut into 4 triangles"]}'
),

('tiramisú_std',422,'snack','☕',
'{"es":"Tiramisú clásico","en":"Classic tiramisú","fr":"Tiramisu classique","it":"Tiramisu classico"}',
'{"es":"El postre italiano más famoso: bizcochos empapados en café, mascarpone y cacao — sin horno","en":"Italy''s most famous dessert: coffee-soaked ladyfingers, mascarpone and cocoa — no baking"}',
20,0,420,8,38,26,1,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs'],
'medium','under_20','medium',
'{"es":["24 bizcochos de soletilla","250g mascarpone","3 huevos separados","80g azúcar","200ml café espresso frío","2 cdas amaretto o ron (opcional)","Cacao en polvo sin azúcar para espolvorear"],"en":["24 ladyfinger biscuits","250g mascarpone","3 eggs separated","80g sugar","200ml cold espresso","2 tbsp amaretto or rum (optional)","Unsweetened cocoa powder to dust"]}',
'{"es":["Bate las yemas con el azúcar hasta blanquear y espesar","Mezcla con el mascarpone hasta obtener una crema suave","Monta las claras a punto de nieve e incorpóralas a la crema con movimientos envolventes","Mezcla el café con el licor","Moja los bizcochos en el café (rápido, que no se deshagan) y coloca en la base de la fuente","Cubre con la crema de mascarpone, repite una capa más","Espolvorea cacao generosamente y refrigera mínimo 4 horas"],"en":["Beat yolks with sugar until pale and thick","Mix with mascarpone until smooth cream","Whip whites to stiff peaks and fold into cream gently","Mix coffee with liqueur","Dip ladyfingers briefly in coffee (quick, don''t let them fall apart) and lay in dish","Cover with mascarpone cream, repeat one more layer","Dust generously with cocoa and refrigerate minimum 4 hours"]}'
)

ON CONFLICT (id) DO NOTHING;
