-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 11 (30) — display_order 326-355
-- Enfocado en: keto, vegan, paleo, mediterranean, pescatarian, low_fodmap, anti_inflammatory
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 10
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── KETO (cierre) ─────────────────────────────────────────────────────────────

('bacon_espinacas_keto',326,'breakfast','🥓',
'{"es":"Sartén de bacon, espinacas y huevo keto","en":"Bacon, spinach and egg keto skillet","fr":"Poele bacon epinards et oeuf keto","it":"Padella bacon spinaci e uovo keto"}',
'{"es":"Desayuno keto sin carbohidratos: bacon crujiente, espinacas salteadas y huevo frito","en":"Zero carb keto breakfast: crispy bacon, sautéed spinach and fried egg"}',
3,8,420,24,2,36,2,
ARRAY['keto','gluten_free','lactose_free','low_carb','high_protein','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["4 lonchas de bacon","2 huevos","150g espinacas baby","1 diente de ajo","Sal, pimienta negra","Pimentón ahumado"],"en":["4 bacon rashers","2 eggs","150g baby spinach","1 garlic clove","Salt, black pepper","Smoked paprika"]}',
'{"es":["Cocina el bacon en sartén sin aceite hasta crujiente, reserva","En la misma grasa sofríe el ajo 30 seg, añade las espinacas y saltea 2 min","Aparta las espinacas a un lado, fríe los huevos al gusto","Sirve todo en la sartén con pimentón ahumado"],"en":["Cook bacon in a dry pan until crispy, set aside","In the same fat sauté garlic 30 sec, add spinach and cook 2 min","Push spinach aside, fry eggs to your liking","Serve everything in the pan with smoked paprika"]}'
),

('aguacate_atun_keto',327,'lunch','🥑',
'{"es":"Aguacate relleno de atún y mayonesa","en":"Avocado stuffed with tuna mayo","fr":"Avocat farci au thon mayonnaise","it":"Avocado ripieno di tonno e maionese"}',
'{"es":"Almuerzo keto en 5 minutos: aguacate relleno de ensalada de atún con mayonesa y alcaparras","en":"5-minute keto lunch: avocado filled with tuna mayo salad with capers"}',
5,0,420,24,6,34,7,
ARRAY['keto','gluten_free','lactose_free','low_carb','high_protein','pescatarian'],
ARRAY['follicular','luteal'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'easy','under_20','low',
'{"es":["2 aguacates maduros","2 latas de atún en aceite de oliva","2 cdas mayonesa","1 cda alcaparras picadas","1 cda zumo de limón","Cebollino picado","Sal, pimienta","Pimentón dulce"],"en":["2 ripe avocados","2 cans tuna in olive oil","2 tbsp mayonnaise","1 tbsp chopped capers","1 tbsp lemon juice","Chopped chives","Salt, pepper","Sweet paprika"]}',
'{"es":["Parte los aguacates por la mitad y retira el hueso","Mezcla el atún escurrido con la mayonesa, las alcaparras, el limón y el cebollino","Sazona con sal y pimienta","Rellena cada mitad de aguacate con la mezcla de atún","Espolvorea pimentón por encima"],"en":["Halve avocados and remove stone","Mix drained tuna with mayo, capers, lemon and chives","Season with salt and pepper","Fill each avocado half with the tuna mixture","Sprinkle paprika on top"]}'
),

('pollo_ajo_crema_keto',328,'dinner','🍗',
'{"es":"Pollo en crema de ajo y parmesano","en":"Chicken in garlic parmesan cream","fr":"Poulet a la creme d''ail et parmesan","it":"Pollo in crema di aglio e parmigiano"}',
'{"es":"Pollo jugoso en salsa cremosa de ajo y parmesano — comfort food keto","en":"Juicy chicken in creamy garlic parmesan sauce — keto comfort food"}',
5,20,520,42,4,36,1,
ARRAY['keto','gluten_free','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','20_40','medium',
'{"es":["4 filetes de pechuga de pollo","3 dientes de ajo picados","200ml nata para cocinar","60g parmesano rallado","2 cdas mantequilla","1 cdta orégano","1 cdta tomillo","Sal, pimienta","Perejil fresco"],"en":["4 chicken breast fillets","3 garlic cloves chopped","200ml cooking cream","60g grated parmesan","2 tbsp butter","1 tsp oregano","1 tsp thyme","Salt, pepper","Fresh parsley"]}',
'{"es":["Sella el pollo en mantequilla a fuego alto 4 min por lado hasta dorado, reserva","En la misma sartén sofríe el ajo 1 min","Añade la nata, el parmesano y las hierbas, mezcla bien","Cuece a fuego medio 3-4 min hasta que la salsa espese","Devuelve el pollo y cocina 5 min más","Sirve con perejil fresco"],"en":["Sear chicken in butter over high heat 4 min per side until golden, set aside","In same pan sauté garlic 1 min","Add cream, parmesan and herbs, mix well","Cook over medium heat 3-4 min until sauce thickens","Return chicken and cook 5 min more","Serve with fresh parsley"]}'
),

('ensalada_caprese_keto',329,'lunch','🍅',
'{"es":"Caprese con mozzarella búfala y aceite de trufa","en":"Caprese with buffalo mozzarella and truffle oil","fr":"Caprese mozzarella de bufflonne et huile de truffe","it":"Caprese con mozzarella di bufala e olio al tartufo"}',
'{"es":"Ensalada caprese clásica elevada: mozzarella de búfala, tomate de temporada y aceite de trufa","en":"Elevated classic caprese: buffalo mozzarella, seasonal tomato and truffle oil"}',
8,0,360,18,8,30,2,
ARRAY['keto','gluten_free','low_carb','vegetarian','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','medium',
'{"es":["2 bolas de mozzarella de búfala","3 tomates de temporada maduros","Albahaca fresca abundante","3 cdas aceite de oliva virgen extra","Unas gotas de aceite de trufa blanca","Sal en escamas","Pimienta negra recién molida","Vinagre balsámico de Módena (opcional)"],"en":["2 balls buffalo mozzarella","3 ripe seasonal tomatoes","Plenty of fresh basil","3 tbsp extra-virgin olive oil","A few drops of white truffle oil","Flaky salt","Freshly ground black pepper","Balsamic vinegar from Modena (optional)"]}',
'{"es":["Corta la mozzarella y los tomates en rodajas gruesas","Alterna las rodajas en una fuente: tomate, mozzarella, tomate, mozzarella","Intercala hojas de albahaca fresca","Riega con el aceite de oliva y unas gotas de trufa","Sazona con sal en escamas y pimienta negra","Añade un hilo de balsámico si lo deseas"],"en":["Slice mozzarella and tomatoes into thick rounds","Alternate slices on a platter: tomato, mozzarella, tomato, mozzarella","Tuck fresh basil leaves between slices","Drizzle with olive oil and a few drops of truffle oil","Season with flaky salt and black pepper","Add a drizzle of balsamic if desired"]}'
),

('bacón_brie_ensalada_keto',330,'lunch','🧀',
'{"es":"Ensalada de brie, nueces y bacon","en":"Brie, walnut and bacon salad","fr":"Salade brie noix et bacon","it":"Insalata di brie, noci e bacon"}',
'{"es":"Ensalada keto satisfactoria: brie fundido, bacon crujiente y nueces sobre hojas verdes","en":"Satisfying keto salad: melted brie, crispy bacon and walnuts on green leaves"}',
5,8,480,24,6,42,3,
ARRAY['keto','gluten_free','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy','nuts'],
'easy','under_20','medium',
'{"es":["120g queso brie en lonchas","4 lonchas de bacon","40g nueces","Mezcla de hojas verdes (rúcula, espinacas)","Para la vinagreta: 2 cdas aceite de oliva, 1 cda vinagre de vino tinto, 1 cdta mostaza, sal, pimienta"],"en":["120g brie sliced","4 bacon rashers","40g walnuts","Mixed leaves (rocket, spinach)","For dressing: 2 tbsp olive oil, 1 tbsp red wine vinegar, 1 tsp mustard, salt, pepper"]}',
'{"es":["Cocina el bacon hasta crujiente, reserva y desmenúza","En la misma sartén tuesta las nueces 2 min, reserva","Funde el brie en sartén o microondas 30 seg hasta que empiece a fundirse","Prepara la vinagreta mezclando todos los ingredientes","Monta la ensalada con las hojas, el brie, el bacon y las nueces","Riega con la vinagreta"],"en":["Cook bacon until crispy, set aside and crumble","In the same pan toast walnuts 2 min, set aside","Melt brie in pan or microwave 30 sec until starting to melt","Prepare dressing mixing all ingredients","Build salad with leaves, brie, bacon and walnuts","Drizzle with dressing"]}'
),

-- ── VEGAN (cierre) ────────────────────────────────────────────────────────────

('bowl_remolacha_tahini_vegan',331,'lunch','🍠',
'{"es":"Bowl de remolacha asada con tahini y garbanzos","en":"Roasted beetroot bowl with tahini and chickpeas","fr":"Bowl betterave rotie tahini et pois chiches","it":"Bowl di barbabietola arrostita con tahini e ceci"}',
'{"es":"Bowl vegano colorido: remolacha asada, garbanzos especiados, tahini y granada","en":"Colourful vegan bowl: roasted beetroot, spiced chickpeas, tahini and pomegranate"}',
10,30,480,16,58,18,12,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory','mediterranean'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY['sesame'],
'medium','20_40','low',
'{"es":["3 remolachas medianas en dados","400g garbanzos cocidos","Semillas de granada","Hojas de rúcula","Para el tahini: 3 cdas tahini, zumo de 1 limón, 1 diente de ajo, agua, sal","1 cdta comino","1 cdta pimentón","3 cdas aceite de oliva"],"en":["3 medium beetroots diced","400g cooked chickpeas","Pomegranate seeds","Rocket leaves","For tahini: 3 tbsp tahini, juice of 1 lemon, 1 garlic clove, water, salt","1 tsp cumin","1 tsp paprika","3 tbsp olive oil"]}',
'{"es":["Mezcla la remolacha con 2 cdas de aceite, sal y pimienta, hornea a 200°C 25 min","Mezcla los garbanzos con 1 cda de aceite, el comino y el pimentón, hornea los últimos 15 min junto con la remolacha","Prepara el tahini mezclando todos sus ingredientes con agua hasta lograr una salsa fluida","Monta el bowl con rúcula, remolacha, garbanzos y granada","Riega con el tahini"],"en":["Toss beetroot with 2 tbsp oil, salt and pepper, roast at 200°C 25 min","Mix chickpeas with 1 tbsp oil, cumin and paprika, roast last 15 min alongside beetroot","Make tahini sauce mixing all ingredients with water until fluid","Build bowl with rocket, beetroot, chickpeas and pomegranate","Drizzle with tahini"]}'
),

('sopa_lentejas_tomate_vegan',332,'dinner','🍲',
'{"es":"Sopa de lentejas con tomate y especias","en":"Lentil and tomato spiced soup","fr":"Soupe de lentilles tomate et epices","it":"Zuppa di lenticchie con pomodoro e spezie"}',
'{"es":"Sopa espesa vegana de lentejas con tomate, comino y pimentón ahumado — reconfortante y nutritiva","en":"Hearty vegan lentil soup with tomato, cumin and smoked paprika — comforting and nutritious"}',
5,28,380,18,56,6,14,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory','mediterranean'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas pardinas o verdes","400g tomate triturado","1 cebolla en dados","3 dientes de ajo","1 zanahoria en dados","1 cdta comino","1 cdta pimentón ahumado","1/2 cdta cúrcuma","1L caldo de verduras","2 cdas aceite de oliva","Sal, pimienta","Zumo de limón, cilantro fresco"],"en":["200g green or brown lentils","400g crushed tomato","1 onion diced","3 garlic cloves","1 carrot diced","1 tsp cumin","1 tsp smoked paprika","1/2 tsp turmeric","1L vegetable stock","2 tbsp olive oil","Salt, pepper","Lemon juice, fresh coriander"]}',
'{"es":["Sofríe la cebolla, el ajo y la zanahoria en aceite 5 min","Añade las especias y cocina 1 min","Incorpora las lentejas, el tomate y el caldo","Cuece a fuego medio 22-25 min hasta que las lentejas estén tiernas","Ajusta de sal, exprime limón y sirve con cilantro fresco"],"en":["Sauté onion, garlic and carrot in oil 5 min","Add spices and cook 1 min","Add lentils, tomato and stock","Cook over medium heat 22-25 min until lentils are tender","Adjust salt, squeeze lemon and serve with fresh coriander"]}'
),

('tacos_coliflor_vegan',333,'dinner','🌮',
'{"es":"Tacos de coliflor asada con mango salsa","en":"Roasted cauliflower tacos with mango salsa","fr":"Tacos de chou-fleur roti salsa mangue","it":"Tacos di cavolfiore arrostito con salsa di mango"}',
'{"es":"Tacos veganos sorprendentes: coliflor especiada y dorada con salsa fresca de mango y lima","en":"Surprising vegan tacos: spiced golden cauliflower with fresh mango and lime salsa"}',
10,25,380,8,60,12,8,
ARRAY['vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["1 coliflor en flores pequeñas","1 cdta comino","1 cdta pimentón ahumado","1 cdta cúrcuma","3 cdas aceite de oliva","Tortillas de maíz","Para la salsa mango: 1 mango en dados, 1/2 cebolla roja, zumo de 1 lima, cilantro, jalapeño opcional, sal","Col morada rallada, aguacate"],"en":["1 cauliflower in small florets","1 tsp cumin","1 tsp smoked paprika","1 tsp turmeric","3 tbsp olive oil","Corn tortillas","For mango salsa: 1 mango diced, 1/2 red onion, juice of 1 lime, coriander, optional jalapeño, salt","Shredded red cabbage, avocado"]}',
'{"es":["Mezcla la coliflor con el aceite y las especias, hornea a 210°C 22-25 min hasta dorada y crujiente","Prepara la salsa de mango mezclando todos sus ingredientes","Calienta las tortillas en sartén seca","Monta los tacos: coliflor, col morada, aguacate y salsa de mango"],"en":["Toss cauliflower with oil and spices, roast at 210°C 22-25 min until golden and crispy","Prepare mango salsa mixing all ingredients","Warm tortillas in a dry pan","Build tacos: cauliflower, red cabbage, avocado and mango salsa"]}'
),

('pasta_aguacate_limon_vegan',334,'dinner','🍝',
'{"es":"Pasta con crema de aguacate y limón (vegan)","en":"Pasta with avocado lemon cream (vegan)","fr":"Pates creme d''avocat et citron (vegan)","it":"Pasta con crema di avocado e limone (vegan)"}',
'{"es":"Pasta vegana con salsa cremosa de aguacate y limón — lista en 15 minutos, sin cocinar la salsa","en":"Vegan pasta with creamy avocado lemon sauce — ready in 15 minutes, no cooking the sauce"}',
5,10,520,14,72,20,8,
ARRAY['vegan','vegetarian','lactose_free','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["150g pasta (espagueti o linguine)","2 aguacates maduros","Zumo de 1 limón grande","1 diente de ajo","2 cdas aceite de oliva","Albahaca fresca","Sal, pimienta negra","Guindilla en copos","Tomates cherry para servir","Levadura nutricional"],"en":["150g pasta (spaghetti or linguine)","2 ripe avocados","Juice of 1 large lemon","1 garlic clove","2 tbsp olive oil","Fresh basil","Salt, black pepper","Chilli flakes","Cherry tomatoes to serve","Nutritional yeast"]}',
'{"es":["Cuece la pasta al dente, reserva 1 taza del agua de cocción","Tritura los aguacates con el limón, el ajo, el aceite, la albahaca, sal y pimienta hasta obtener una crema","Si es muy espesa añade un poco del agua de cocción","Mezcla la pasta caliente con la crema de aguacate inmediatamente","Sirve con tomates cherry, guindilla y levadura nutricional"],"en":["Cook pasta al dente, reserve 1 cup cooking water","Blend avocados with lemon, garlic, oil, basil, salt and pepper until creamy","If too thick add some cooking water","Mix hot pasta with avocado cream immediately","Serve with cherry tomatoes, chilli and nutritional yeast"]}'
),

('granola_coco_semillas_vegan',335,'breakfast','🥥',
'{"es":"Granola de coco y semillas con leche vegetal","en":"Coconut and seed granola with plant milk","fr":"Granola coco et graines au lait vegetal","it":"Granola al cocco e semi con latte vegetale"}',
'{"es":"Granola vegana casera crujiente de coco, semillas y avena con leche de almendra","en":"Homemade crunchy vegan coconut, seed and oat granola with almond milk"}',
5,22,420,10,54,18,6,
ARRAY['vegan','vegetarian','lactose_free','gluten_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['nuts'],
'easy','20_40','low',
'{"es":["200g copos de avena sin gluten","50g coco rallado sin azúcar","40g semillas de calabaza","30g semillas de girasol","2 cdas semillas de chía","3 cdas aceite de coco derretido","3 cdas sirope de agave o arce","1 cdta canela","1 cdta extracto de vainilla","Pizca de sal","Leche de almendra o avena para servir","Fruta fresca"],"en":["200g gluten-free oat flakes","50g unsweetened desiccated coconut","40g pumpkin seeds","30g sunflower seeds","2 tbsp chia seeds","3 tbsp melted coconut oil","3 tbsp agave or maple syrup","1 tsp cinnamon","1 tsp vanilla extract","Pinch of salt","Almond or oat milk to serve","Fresh fruit"]}',
'{"es":["Precalienta el horno a 160°C","Mezcla la avena, el coco, las semillas y la canela","Añade el aceite de coco, el agave y la vainilla, mezcla bien","Extiende en bandeja con papel y presiona para compactar","Hornea 20-22 min hasta dorada (sin mover a mitad para que queden grumos)","Deja enfriar completamente antes de romper en trozos","Sirve con leche vegetal y fruta fresca"],"en":["Preheat oven to 160°C","Mix oats, coconut, seeds and cinnamon","Add coconut oil, agave and vanilla, mix well","Spread on lined tray and press to compact","Bake 20-22 min until golden (do not stir halfway so clusters form)","Cool completely before breaking into pieces","Serve with plant milk and fresh fruit"]}'
),

-- ── PALEO (cierre) ────────────────────────────────────────────────────────────

('pechuga_mango_paleo',336,'dinner','🥭',
'{"es":"Pechuga de pollo con salsa de mango y jengibre","en":"Chicken breast with mango ginger sauce","fr":"Blanc de poulet sauce mangue-gingembre","it":"Petto di pollo con salsa di mango e zenzero"}',
'{"es":"Pollo paleo con salsa tropical de mango fresco y jengibre — sin azúcares añadidos","en":"Paleo chicken with fresh mango ginger tropical sauce — no added sugars"}',
8,18,420,36,20,16,3,
ARRAY['paleo','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["2 pechugas de pollo","1 mango maduro en dados","1 cdta jengibre fresco rallado","Zumo de 1 lima","1 cda aceite de coco","1 cdta pimentón","Cilantro fresco","Sal, pimienta"],"en":["2 chicken breasts","1 ripe mango diced","1 tsp fresh grated ginger","Juice of 1 lime","1 tbsp coconut oil","1 tsp paprika","Fresh coriander","Salt, pepper"]}',
'{"es":["Sazona el pollo con pimentón, sal y pimienta","Cocina en sartén con aceite de coco 6-7 min por lado","Mientras, mezcla el mango con el jengibre, el zumo de lima y el cilantro","Deja reposar el pollo 3 min y lamina","Sirve con la salsa de mango encima"],"en":["Season chicken with paprika, salt and pepper","Cook in pan with coconut oil 6-7 min per side","Meanwhile mix mango with ginger, lime juice and coriander","Rest chicken 3 min and slice","Serve with mango sauce on top"]}'
),

('cordero_romero_paleo',337,'dinner','🍖',
'{"es":"Chuletas de cordero con romero y ajo","en":"Lamb chops with rosemary and garlic","fr":"Cotes d''agneau romarin et ail","it":"Costolette di agnello con rosmarino e aglio"}',
'{"es":"Chuletas de cordero a la plancha marinadas con romero, ajo y limón — paleo puro","en":"Grilled lamb chops marinated with rosemary, garlic and lemon — pure paleo"}',
10,10,480,36,2,36,1,
ARRAY['paleo','keto','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','high',
'{"es":["6 chuletas de cordero","3 dientes de ajo picados","2 ramas de romero fresco picadas","Zumo de 1 limón","3 cdas aceite de oliva","Sal gruesa, pimienta negra"],"en":["6 lamb chops","3 garlic cloves chopped","2 fresh rosemary sprigs chopped","Juice of 1 lemon","3 tbsp olive oil","Coarse salt, black pepper"]}',
'{"es":["Mezcla el ajo, el romero, el limón y el aceite","Marina las chuletas al menos 30 min (o toda la noche)","Calienta una plancha a fuego muy alto","Cocina las chuletas 2-3 min por lado para punto medio","Sazona con sal gruesa y deja reposar 2 min antes de servir"],"en":["Mix garlic, rosemary, lemon and oil","Marinate chops at least 30 min (or overnight)","Heat a griddle pan over very high heat","Cook chops 2-3 min per side for medium rare","Season with coarse salt and rest 2 min before serving"]}'
),

('salmón_costra_hierbas_paleo',338,'dinner','🌿',
'{"es":"Salmón en costra de hierbas y almendra","en":"Herb and almond crusted salmon","fr":"Saumon en croute d''herbes et amandes","it":"Salmone in crosta di erbe e mandorle"}',
'{"es":"Salmón al horno con costra crujiente de hierbas frescas y almendra molida — paleo elegante","en":"Baked salmon with crispy fresh herb and ground almond crust — elegant paleo"}',
8,15,480,36,6,34,3,
ARRAY['paleo','keto','gluten_free','lactose_free','high_protein','low_carb','pescatarian','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['fish','nuts'],
'easy','under_20','medium',
'{"es":["2 filetes de salmón gruesos","40g almendra molida","2 cdas perejil fresco picado","1 cda eneldo fresco picado","1 cdta pimentón","1 cdta ajo en polvo","2 cdas aceite de oliva","Sal, pimienta","Zumo de limón"],"en":["2 thick salmon fillets","40g ground almond","2 tbsp fresh parsley chopped","1 tbsp fresh dill chopped","1 tsp paprika","1 tsp garlic powder","2 tbsp olive oil","Salt, pepper","Lemon juice"]}',
'{"es":["Precalienta el horno a 200°C","Mezcla la almendra, las hierbas, el pimentón, el ajo, el aceite, sal y pimienta","Coloca el salmón en bandeja con papel","Cubre la superficie con la mezcla de almendra y hierbas, presionando","Hornea 14-16 min hasta que la costra esté dorada","Sirve con zumo de limón"],"en":["Preheat oven to 200°C","Mix almond, herbs, paprika, garlic, oil, salt and pepper","Place salmon on lined tray","Cover surface with almond herb mixture, pressing firmly","Bake 14-16 min until crust is golden","Serve with lemon juice"]}'
),

('ternera_boniato_paleo2',339,'dinner','🥩',
'{"es":"Solomillo de ternera con boniato caramelizado","en":"Beef tenderloin with caramelised sweet potato","fr":"Filet de boeuf patate douce caramelisee","it":"Filetto di manzo con patata dolce caramellata"}',
'{"es":"Cena paleo de lujo: solomillo de ternera con boniato caramelizado en aceite de coco","en":"Luxury paleo dinner: beef tenderloin with sweet potato caramelised in coconut oil"}',
8,20,540,38,24,28,4,
ARRAY['paleo','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','20_40','high',
'{"es":["2 medallones de solomillo de ternera (180g c/u)","1 boniato grande en rodajas","2 cdas aceite de coco","1 cdta canela","Sal gruesa, pimienta","Tomillo fresco","Aceite de oliva"],"en":["2 beef tenderloin medallions (180g each)","1 large sweet potato sliced","2 tbsp coconut oil","1 tsp cinnamon","Coarse salt, pepper","Fresh thyme","Olive oil"]}',
'{"es":["Carameliza el boniato en aceite de coco con canela a fuego medio 8-10 min por lado hasta dorado","Saca la carne de la nevera 20 min antes","Calienta una sartén de hierro a fuego muy alto con aceite de oliva","Sella el solomillo 2-3 min por lado para punto medio","Sazona con sal gruesa y tomillo, reposa 4 min","Sirve con el boniato caramelizado"],"en":["Caramelise sweet potato in coconut oil with cinnamon over medium heat 8-10 min per side until golden","Take meat out of fridge 20 min before","Heat a cast iron pan over very high heat with olive oil","Sear tenderloin 2-3 min per side for medium rare","Season with coarse salt and thyme, rest 4 min","Serve with caramelised sweet potato"]}'
),

('pollo_pepita_paleo',340,'lunch','🥗',
'{"es":"Ensalada de pollo con pepitas y vinagreta de naranja","en":"Chicken salad with pepitas and orange dressing","fr":"Salade de poulet pepitas vinaigrette orange","it":"Insalata di pollo con semi di zucca e vinaigrette all''arancia"}',
'{"es":"Ensalada paleo colorida con pollo asado, pepitas tostadas y vinagreta dulce de naranja","en":"Colourful paleo salad with roasted chicken, toasted pepitas and sweet orange dressing"}',
10,0,420,32,18,24,5,
ARRAY['paleo','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["250g pollo asado en tiras","Mezcla de hojas verdes","1 naranja en gajos","40g pepitas de calabaza tostadas","1/4 cebolla morada en aros finos","Para la vinagreta: zumo de 1 naranja, 2 cdas aceite de oliva, 1 cdta mostaza de Dijon, sal, pimienta"],"en":["250g roasted chicken in strips","Mixed green leaves","1 orange in segments","40g toasted pumpkin seeds","1/4 red onion in thin rings","For dressing: juice of 1 orange, 2 tbsp olive oil, 1 tsp Dijon mustard, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando el zumo de naranja, el aceite, la mostaza, sal y pimienta","Coloca las hojas en un bol amplio","Añade el pollo, los gajos de naranja, la cebolla morada y las pepitas","Riega con la vinagreta justo antes de servir"],"en":["Prepare dressing mixing orange juice, oil, mustard, salt and pepper","Place leaves in a wide bowl","Add chicken, orange segments, red onion and pepitas","Drizzle with dressing just before serving"]}'
),

-- ── MEDITERRANEAN (cierre) ───────────────────────────────────────────────────

('briam_griego',341,'dinner','🫑',
'{"es":"Briam griego (verduras al horno con hierbas)","en":"Greek briam (baked vegetables with herbs)","fr":"Briam grec legumes rotis aux herbes","it":"Briam greco verdure al forno con erbe"}',
'{"es":"El ratatouille griego: calabacín, berenjena, patata y tomate al horno con aceite de oliva y orégano","en":"The Greek ratatouille: courgette, aubergine, potato and tomato baked with olive oil and oregano"}',
12,50,320,6,42,14,8,
ARRAY['mediterranean','vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY[]::text[],
'easy','over_40','low',
'{"es":["2 calabacines en rodajas","1 berenjena en rodajas","2 patatas en rodajas finas","3 tomates en rodajas","1 cebolla en aros","4 cdas aceite de oliva virgen extra","2 cdtas orégano","1 cdta tomillo","2 dientes de ajo laminados","Sal, pimienta","Perejil fresco"],"en":["2 courgettes sliced","1 aubergine sliced","2 potatoes thinly sliced","3 tomatoes sliced","1 onion in rings","4 tbsp extra-virgin olive oil","2 tsp oregano","1 tsp thyme","2 garlic cloves sliced","Salt, pepper","Fresh parsley"]}',
'{"es":["Precalienta el horno a 180°C","Coloca todas las verduras en capas en una fuente de horno grande","Intercala el ajo entre las verduras","Riega generosamente con el aceite de oliva","Espolvorea el orégano, el tomillo, sal y pimienta","Tapa con papel de aluminio y hornea 35 min","Destapa y hornea 15 min más hasta que las verduras estén doradas","Sirve con perejil fresco"],"en":["Preheat oven to 180°C","Layer all vegetables in a large baking dish","Tuck garlic between the vegetables","Drizzle generously with olive oil","Sprinkle oregano, thyme, salt and pepper","Cover with foil and bake 35 min","Uncover and bake 15 min more until vegetables are golden","Serve with fresh parsley"]}'
),

('moussaka_ligera_med',342,'dinner','🍆',
'{"es":"Moussaka ligera de ternera y berenjena","en":"Light beef and aubergine moussaka","fr":"Moussaka legere boeuf et aubergine","it":"Moussaka leggera di manzo e melanzane"}',
'{"es":"Versión aligerada del clásico griego: berenjena, carne especiada y bechamel con yogur","en":"Lighter version of the Greek classic: aubergine, spiced meat and yogurt bechamel"}',
20,45,480,30,22,28,6,
ARRAY['mediterranean','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['dairy','eggs'],
'medium','over_40','medium',
'{"es":["2 berenjenas grandes en láminas","300g carne picada de ternera","400g tomate triturado","1 cebolla","2 dientes de ajo","1 cdta canela","1 cdta orégano","1 cdta pimentón","Para la bechamel ligera: 300g yogur griego, 2 huevos, 50g parmesano, nuez moscada, sal","Aceite de oliva"],"en":["2 large aubergines sliced","300g beef mince","400g crushed tomato","1 onion","2 garlic cloves","1 tsp cinnamon","1 tsp oregano","1 tsp paprika","For light bechamel: 300g Greek yogurt, 2 eggs, 50g parmesan, nutmeg, salt","Olive oil"]}',
'{"es":["Sala las berenjenas 10 min, escurre y asa en plancha o en horno a 200°C 15 min","Sofríe la cebolla y el ajo, añade la carne y dórala, incorpora el tomate y las especias, cuece 12 min","Mezcla el yogur con los huevos, el parmesano y la nuez moscada para la bechamel","Monta en bandeja: berenjena, carne, berenjena, bechamel","Hornea a 180°C 30-35 min hasta dorada"],"en":["Salt aubergines 10 min, drain and grill or bake at 200°C 15 min","Sauté onion and garlic, add mince and brown, add tomato and spices, cook 12 min","Mix yogurt with eggs, parmesan and nutmeg for bechamel","Layer in dish: aubergine, meat, aubergine, bechamel","Bake at 180°C 30-35 min until golden"]}'
),

('dolmades_arroz_med',343,'lunch','🍃',
'{"es":"Dolmades de arroz y hierbas (hojas de parra)","en":"Rice and herb dolmades (grape leaves)","fr":"Dolmades riz et herbes feuilles de vigne","it":"Dolmades di riso ed erbe con foglie di vite"}',
'{"es":"Hojas de parra rellenas de arroz, hierbas frescas y limón — aperitivo mediterráneo vegano","en":"Grape leaves stuffed with rice, fresh herbs and lemon — vegan Mediterranean appetiser"}',
25,30,340,6,56,10,4,
ARRAY['mediterranean','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','medium',
'{"es":["20 hojas de parra en conserva","150g arroz de grano corto","1 cebolla finamente picada","Perejil y menta frescos abundantes","Zumo de 2 limones","4 cdas aceite de oliva","Sal, pimienta negra","Agua o caldo para cocer"],"en":["20 preserved grape leaves","150g short grain rice","1 onion finely chopped","Plenty of fresh parsley and mint","Juice of 2 lemons","4 tbsp olive oil","Salt, black pepper","Water or stock for cooking"]}',
'{"es":["Aclara las hojas de parra con agua fría","Mezcla el arroz crudo con la cebolla, las hierbas, 2 cdas de aceite, sal y pimienta","Coloca una cda de relleno al final de cada hoja, dobla los lados y enrolla","Coloca en cacerola con el cierre hacia abajo, bien apretados","Cubre con el zumo de limón, el aceite y agua suficiente","Tapa y cuece a fuego bajo 30-35 min","Sirve tibios o a temperatura ambiente"],"en":["Rinse grape leaves in cold water","Mix raw rice with onion, herbs, 2 tbsp oil, salt and pepper","Place 1 tbsp filling at base of each leaf, fold sides and roll","Place in saucepan seam-side down, packed tight","Cover with lemon juice, oil and enough water","Cover and cook over low heat 30-35 min","Serve warm or at room temperature"]}'
),

('ensalada_griega_clasica_v2',344,'lunch','🫒',
'{"es":"Ensalada griega con atún y aceitunas kalamata","en":"Greek salad with tuna and kalamata olives","fr":"Salade grecque thon et olives kalamata","it":"Insalata greca con tonno e olive kalamata"}',
'{"es":"Versión proteica de la ensalada griega: con atún, feta, olivas kalamata y verduras frescas","en":"Protein version of Greek salad: with tuna, feta, kalamata olives and fresh vegetables"}',
10,0,400,28,12,28,4,
ARRAY['mediterranean','gluten_free','high_protein','pescatarian','low_carb'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['fish','dairy'],
'easy','under_20','low',
'{"es":["2 latas de atún en aceite de oliva","80g queso feta","80g aceitunas kalamata","2 tomates maduros en dados","1/2 pepino en dados","1/4 cebolla roja en aros","1 pimiento verde en dados","3 cdas aceite de oliva","1 cda vinagre de vino","Orégano seco","Sal, pimienta"],"en":["2 cans tuna in olive oil","80g feta","80g kalamata olives","2 ripe tomatoes diced","1/2 cucumber diced","1/4 red onion in rings","1 green pepper diced","3 tbsp olive oil","1 tbsp wine vinegar","Dried oregano","Salt, pepper"]}',
'{"es":["Coloca el tomate, el pepino, el pimiento y la cebolla en una fuente","Añade el atún desmenuzado, el feta en trozos y las aceitunas","Riega con aceite de oliva y vinagre","Espolvorea generosamente con orégano, sal y pimienta","Mezcla suavemente y sirve inmediatamente"],"en":["Place tomato, cucumber, pepper and onion in a dish","Add flaked tuna, feta in chunks and olives","Drizzle with olive oil and vinegar","Sprinkle generously with oregano, salt and pepper","Toss gently and serve immediately"]}'
),

('pollo_aceitunas_med',345,'dinner','🫒',
'{"es":"Pollo con aceitunas, alcaparras y tomate","en":"Chicken with olives, capers and tomato","fr":"Poulet olives capres et tomate","it":"Pollo con olive, capperi e pomodoro"}',
'{"es":"Pollo estofado mediterráneo con aceitunas verdes, alcaparras y tomate — sabores del sur","en":"Mediterranean braised chicken with green olives, capers and tomato — southern flavours"}',
8,30,460,38,12,28,4,
ARRAY['mediterranean','gluten_free','lactose_free','high_protein','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','medium',
'{"es":["4 muslos de pollo","80g aceitunas verdes sin hueso","2 cdas alcaparras","400g tomate triturado","1 cebolla en dados","3 dientes de ajo","1 cdta orégano","1 cdta tomillo","2 cdas aceite de oliva","100ml vino blanco (opcional)","Sal, pimienta","Perejil fresco"],"en":["4 chicken thighs","80g pitted green olives","2 tbsp capers","400g crushed tomato","1 onion diced","3 garlic cloves","1 tsp oregano","1 tsp thyme","2 tbsp olive oil","100ml white wine (optional)","Salt, pepper","Fresh parsley"]}',
'{"es":["Sella el pollo en aceite a fuego alto 4 min por lado, reserva","Sofríe la cebolla y el ajo 4 min","Añade el vino y deja evaporar 2 min","Incorpora el tomate, el orégano, el tomillo, las aceitunas y las alcaparras","Devuelve el pollo, tapa y cuece a fuego medio-bajo 22 min","Sirve con perejil fresco"],"en":["Sear chicken in oil over high heat 4 min per side, set aside","Sauté onion and garlic 4 min","Add wine and let evaporate 2 min","Add tomato, oregano, thyme, olives and capers","Return chicken, cover and cook over medium-low heat 22 min","Serve with fresh parsley"]}'
),

-- ── PESCATARIAN (cierre) ─────────────────────────────────────────────────────

('bacalao_pisto_med',346,'dinner','🐟',
'{"es":"Bacalao con pisto andaluz","en":"Cod with Andalusian pisto","fr":"Cabillaud avec pisto andalou","it":"Merluzzo con pisto andaluso"}',
'{"es":"Bacalao fresco sobre un pisto de verduras con tomate y pimiento — sencillo y sabroso","en":"Fresh cod on a vegetable pisto with tomato and pepper — simple and flavourful"}',
8,25,380,34,18,16,6,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["2 lomos de bacalao fresco","2 calabacines en dados","2 pimientos rojos en dados","1 berenjena en dados","400g tomate triturado","1 cebolla en dados","3 dientes de ajo","3 cdas aceite de oliva","1 cdta pimentón","Sal, pimienta, orégano"],"en":["2 fresh cod loins","2 courgettes diced","2 red peppers diced","1 aubergine diced","400g crushed tomato","1 onion diced","3 garlic cloves","3 tbsp olive oil","1 tsp paprika","Salt, pepper, oregano"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade los pimientos y la berenjena, cocina 8 min","Incorpora el calabacín, el tomate, el pimentón, sal y orégano","Cuece a fuego medio 10 min hasta que el pisto esté espeso","Coloca el bacalao encima, tapa y cuece 8-10 min hasta que esté listo","Sirve directamente de la sartén"],"en":["Sauté onion and garlic in oil 4 min","Add peppers and aubergine, cook 8 min","Add courgette, tomato, paprika, salt and oregano","Cook over medium heat 10 min until pisto is thick","Place cod on top, cover and cook 8-10 min until done","Serve directly from the pan"]}'
),

('mejillones_marinera_pesc',347,'dinner','🦪',
'{"es":"Mejillones en salsa marinera","en":"Mussels in marinara sauce","fr":"Moules sauce mariniere","it":"Cozze alla marinara"}',
'{"es":"Mejillones cocinados en salsa de tomate y vino blanco con ajo y perejil — clásico marinero","en":"Mussels cooked in tomato and white wine sauce with garlic and parsley — classic seafood"}',
8,15,320,28,14,12,3,
ARRAY['pescatarian','gluten_free','lactose_free','mediterranean','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','low',
'{"es":["1kg mejillones frescos limpios","400g tomate triturado","150ml vino blanco seco","1 cebolla en dados","4 dientes de ajo laminados","3 cdas aceite de oliva","1 cdta pimentón","Guindilla (opcional)","Perejil fresco abundante","Pan para mojar (opcional)"],"en":["1kg fresh mussels cleaned","400g crushed tomato","150ml dry white wine","1 onion diced","4 garlic cloves sliced","3 tbsp olive oil","1 tsp paprika","Chilli (optional)","Plenty of fresh parsley","Bread for dipping (optional)"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade el pimentón y la guindilla, cocina 1 min","Incorpora el tomate y el vino, cuece 8 min a fuego medio","Sube el fuego, añade los mejillones y tapa","Cocina 4-5 min sacudiendo la olla hasta que todos abran","Descarta los que no se abran","Sirve con abundante perejil fresco"],"en":["Sauté onion and garlic in oil 4 min","Add paprika and chilli, cook 1 min","Add tomato and wine, cook 8 min over medium heat","Turn up heat, add mussels and cover","Cook 4-5 min shaking the pot until all open","Discard any that do not open","Serve with plenty of fresh parsley"]}'
),

('brochetas_atun_pesc',348,'dinner','🍢',
'{"es":"Brochetas de atún fresco con pimiento y limón","en":"Fresh tuna skewers with pepper and lemon","fr":"Brochettes de thon frais poivron et citron","it":"Spiedini di tonno fresco con peperone e limone"}',
'{"es":"Brochetas de atún fresco a la plancha marinadas en limón, orégano y aceite — keto y paleo","en":"Grilled fresh tuna skewers marinated in lemon, oregano and oil — keto and paleo"}',
15,8,380,36,4,24,2,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','keto','paleo','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','under_20','high',
'{"es":["400g atún fresco en dados grandes","2 pimientos (rojo y verde) en cuadrados","Zumo de 2 limones","3 cdas aceite de oliva","2 cdtas orégano seco","1 cdta pimentón","Sal gruesa, pimienta","Brochetas de madera (remojadas) o metal"],"en":["400g fresh tuna in large cubes","2 peppers (red and green) in squares","Juice of 2 lemons","3 tbsp olive oil","2 tsp dried oregano","1 tsp paprika","Coarse salt, pepper","Wooden skewers (soaked) or metal"]}',
'{"es":["Marina el atún con el limón, el aceite, el orégano y el pimentón 15 min","Ensarta alternando el atún con los pimientos en las brochetas","Sazona con sal gruesa","Cocina en plancha muy caliente 2-3 min por lado (el atún debe quedar rosado dentro)","Sirve inmediatamente con una ensalada verde"],"en":["Marinate tuna with lemon, oil, oregano and paprika 15 min","Thread alternating tuna and peppers onto skewers","Season with coarse salt","Cook on very hot griddle 2-3 min per side (tuna should remain pink inside)","Serve immediately with a green salad"]}'
),

('tagliatelle_almejas_pesc',349,'dinner','🍝',
'{"es":"Tagliatelle con almejas y vino blanco","en":"Tagliatelle with clams and white wine","fr":"Tagliatelles aux palourdes et vin blanc","it":"Tagliatelle alle vongole e vino bianco"}',
'{"es":"Clásico italiano costero: pasta con almejas frescas, vino blanco, ajo y perejil","en":"Italian coastal classic: pasta with fresh clams, white wine, garlic and parsley"}',
8,15,520,28,68,12,3,
ARRAY['pescatarian','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','shellfish'],
'medium','under_20','medium',
'{"es":["150g tagliatelle o espagueti","500g almejas frescas (en agua con sal para purgarlas 1h)","150ml vino blanco seco","3 dientes de ajo laminados","3 cdas aceite de oliva","Guindilla seca","Perejil fresco abundante","Sal, pimienta negra"],"en":["150g tagliatelle or spaghetti","500g fresh clams (soaked in salted water 1h to purge)","150ml dry white wine","3 garlic cloves sliced","3 tbsp olive oil","Dried chilli","Plenty of fresh parsley","Salt, black pepper"]}',
'{"es":["Cuece la pasta al dente, reserva 1 taza del agua de cocción","Sofríe el ajo y la guindilla en aceite 2 min","Añade las almejas y el vino blanco, sube el fuego y tapa 3-4 min hasta que abran","Descarta las que no se abran","Añade la pasta y un poco del agua de cocción, mezcla bien","Sirve con abundante perejil fresco y pimienta negra"],"en":["Cook pasta al dente, reserve 1 cup cooking water","Sauté garlic and chilli in oil 2 min","Add clams and white wine, turn up heat and cover 3-4 min until they open","Discard any that do not open","Add pasta and a little cooking water, toss well","Serve with plenty of fresh parsley and black pepper"]}'
),

('ceviche_gambas_pesc',350,'lunch','🍋',
'{"es":"Ceviche de gambas con mango y lima","en":"Prawn ceviche with mango and lime","fr":"Ceviche de crevettes mangue et citron vert","it":"Ceviche di gamberi con mango e lime"}',
'{"es":"Ceviche fresco y tropical de gambas cocidas con mango, pepino y leche de tigre de lima","en":"Fresh tropical prawn ceviche with mango, cucumber and lime tiger milk"}',
15,0,280,24,18,10,3,
ARRAY['pescatarian','gluten_free','lactose_free','low_carb','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','lose_weight'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["300g gambas cocidas y peladas","1 mango en dados pequeños","1/2 pepino en dados pequeños","1/4 cebolla morada en brunoise","Zumo de 3 limas","1 cdta jengibre rallado","Cilantro fresco","1 jalapeño o guindilla suave (opcional)","Sal, pimienta","Tostadas de maíz para acompañar"],"en":["300g cooked peeled prawns","1 mango in small dice","1/2 cucumber in small dice","1/4 red onion finely diced","Juice of 3 limes","1 tsp grated ginger","Fresh coriander","1 jalapeño or mild chilli (optional)","Salt, pepper","Corn tortilla chips to serve"]}',
'{"es":["Mezcla el zumo de lima con el jengibre, la cebolla y el jalapeño, deja macerar 5 min","Añade las gambas, el mango y el pepino","Mezcla bien, sazona con sal y pimienta","Deja reposar 5-10 min en nevera para que los sabores se integren","Sirve con cilantro fresco y tostadas de maíz"],"en":["Mix lime juice with ginger, onion and jalapeño, marinate 5 min","Add prawns, mango and cucumber","Mix well, season with salt and pepper","Rest 5-10 min in fridge to let flavours meld","Serve with fresh coriander and corn chips"]}'
),

-- ── LOW FODMAP + ANTI-INFLAMMATORY (cierre) ──────────────────────────────────

('pollo_cúrcuma_coco_fodmap',351,'dinner','🟡',
'{"es":"Pollo en salsa de cúrcuma y leche de coco (low FODMAP)","en":"Chicken in turmeric coconut sauce (low FODMAP)","fr":"Poulet sauce curcuma et lait de coco (low FODMAP)","it":"Pollo in salsa di curcuma e latte di cocco (low FODMAP)"}',
'{"es":"Curry suave low FODMAP: sin cebolla ni ajo, con aceite infusionado y leche de coco antiinflamatoria","en":"Mild low FODMAP curry: no onion or garlic, with infused oil and anti-inflammatory coconut milk"}',
5,22,460,36,16,28,2,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','anti_inflammatory','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["400g pechuga de pollo en dados","400ml leche de coco","1 cdta cúrcuma","1 cdta jengibre rallado","1 cdta comino","1/2 cdta cardamomo","2 cdas aceite de ajo infusionado","Sal, pimienta","Cebollino verde (solo la parte verde)","Cilantro fresco","Arroz basmati para servir"],"en":["400g chicken breast diced","400ml coconut milk","1 tsp turmeric","1 tsp grated ginger","1 tsp cumin","1/2 tsp cardamom","2 tbsp garlic-infused oil","Salt, pepper","Green chives (green part only)","Fresh coriander","Basmati rice to serve"]}',
'{"es":["Sofríe el pollo en el aceite infusionado a fuego alto 4-5 min","Añade la cúrcuma, el jengibre, el comino y el cardamomo, cocina 1 min","Incorpora la leche de coco, tapa y cuece a fuego medio 15 min","Ajusta de sal, sirve con cebollino verde y cilantro sobre arroz basmati"],"en":["Sauté chicken in infused oil over high heat 4-5 min","Add turmeric, ginger, cumin and cardamom, cook 1 min","Add coconut milk, cover and cook over medium heat 15 min","Adjust salt, serve with green chives and coriander over basmati rice"]}'
),

('salmón_jengibre_sésamo_anti',352,'dinner','🫚',
'{"es":"Salmón glaseado con jengibre y sésamo","en":"Ginger sesame glazed salmon","fr":"Saumon glace gingembre-sesame","it":"Salmone glassato allo zenzero e sesamo"}',
'{"es":"Salmón antiinflamatorio con glaseado de jengibre, tamari y sésamo — omega-3 y antioxidantes","en":"Anti-inflammatory salmon with ginger, tamari and sesame glaze — omega-3 and antioxidants"}',
5,12,460,36,8,30,1,
ARRAY['anti_inflammatory','gluten_free','lactose_free','pescatarian','low_carb','keto','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY['fish','soy','sesame'],
'easy','under_20','medium',
'{"es":["2 filetes de salmón","2 cdas tamari o salsa de soja sin gluten","1 cda aceite de sésamo","1 cdta jengibre fresco rallado","1 cdta miel o sirope de agave","Semillas de sésamo","Cebolleta verde","Zumo de limón"],"en":["2 salmon fillets","2 tbsp tamari or gluten-free soy sauce","1 tbsp sesame oil","1 tsp fresh grated ginger","1 tsp honey or agave syrup","Sesame seeds","Spring onion","Lemon juice"]}',
'{"es":["Mezcla el tamari, el aceite de sésamo, el jengibre y la miel para el glaseado","Marina el salmón 10 min","Cocina en sartén a fuego medio-alto 4-5 min por lado pintando con el glaseado","Sirve con semillas de sésamo, cebolleta verde y zumo de limón"],"en":["Mix tamari, sesame oil, ginger and honey for the glaze","Marinate salmon 10 min","Cook in pan over medium-high heat 4-5 min per side brushing with glaze","Serve with sesame seeds, spring onion and lemon juice"]}'
),

('crema_calabaza_coco_anti',353,'dinner','🎃',
'{"es":"Crema de calabaza con leche de coco y cúrcuma","en":"Pumpkin cream with coconut milk and turmeric","fr":"Creme de potimarron lait de coco et curcuma","it":"Crema di zucca con latte di cocco e curcuma"}',
'{"es":"Sopa cremosa antiinflamatoria de calabaza: cúrcuma, jengibre, leche de coco y pimienta negra","en":"Anti-inflammatory creamy pumpkin soup: turmeric, ginger, coconut milk and black pepper"}',
8,22,280,5,36,12,5,
ARRAY['anti_inflammatory','vegan','vegetarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["600g calabaza en dados","400ml leche de coco","400ml caldo de verduras (sin cebolla ni ajo para low FODMAP)","1 cdta cúrcuma","1 cdta jengibre fresco rallado","1/2 cdta pimienta negra (potencia la cúrcuma)","2 cdas aceite de oliva","Sal","Semillas de calabaza tostadas","Aceite de coco para decorar"],"en":["600g pumpkin diced","400ml coconut milk","400ml vegetable stock (no onion or garlic for low FODMAP)","1 tsp turmeric","1 tsp fresh grated ginger","1/2 tsp black pepper (enhances turmeric)","2 tbsp olive oil","Salt","Toasted pumpkin seeds","Coconut oil to garnish"]}',
'{"es":["Sofríe la calabaza en aceite 3 min","Añade la cúrcuma, el jengibre y la pimienta, cocina 1 min","Incorpora el caldo y cuece 18 min hasta que la calabaza esté tierna","Añade la leche de coco y tritura hasta obtener una crema suave","Ajusta de sal y sirve con semillas de calabaza y un hilo de aceite de coco"],"en":["Sauté pumpkin in oil 3 min","Add turmeric, ginger and pepper, cook 1 min","Add stock and cook 18 min until pumpkin is tender","Add coconut milk and blend until smooth","Adjust salt and serve with pumpkin seeds and a drizzle of coconut oil"]}'
),

('bowl_sardinas_anti',354,'lunch','🐟',
'{"es":"Bowl de sardinas con quinoa y verduras antiinflamatorias","en":"Sardine bowl with quinoa and anti-inflammatory vegetables","fr":"Bowl de sardines quinoa et legumes anti-inflammatoires","it":"Bowl di sardine con quinoa e verdure anti-infiammatorie"}',
'{"es":"Bowl proteico antiinflamatorio: sardinas en aceite de oliva, quinoa, espinacas y limón","en":"Anti-inflammatory protein bowl: sardines in olive oil, quinoa, spinach and lemon"}',
8,15,460,28,48,16,8,
ARRAY['anti_inflammatory','pescatarian','gluten_free','lactose_free','high_protein','mediterranean'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["2 latas de sardinas en aceite de oliva","160g quinoa cocida","150g espinacas baby","150g tomates cherry en mitades","1/2 aguacate","Zumo de 1 limón","2 cdas aceite de oliva","Sal, pimienta","Semillas de girasol","Eneldo fresco"],"en":["2 cans sardines in olive oil","160g cooked quinoa","150g baby spinach","150g cherry tomatoes halved","1/2 avocado","Juice of 1 lemon","2 tbsp olive oil","Salt, pepper","Sunflower seeds","Fresh dill"]}',
'{"es":["Cuece la quinoa si no está lista, deja templar","Prepara la vinagreta con aceite, limón, sal y pimienta","Monta el bowl: quinoa, espinacas, tomates cherry, aguacate","Coloca las sardinas encima","Riega con la vinagreta y decora con semillas y eneldo"],"en":["Cook quinoa if not ready, let cool slightly","Prepare dressing with oil, lemon, salt and pepper","Build bowl: quinoa, spinach, cherry tomatoes, avocado","Place sardines on top","Drizzle with dressing and garnish with seeds and dill"]}'
),

('golden_milk_chia_anti',355,'snack','🌟',
'{"es":"Golden milk con pudín de chía","en":"Golden milk chia pudding","fr":"Lait dore pudding chia","it":"Latte dorato con budino di chia"}',
'{"es":"Snack antiinflamatorio estrella: pudín de chía con golden milk de cúrcuma, canela y jengibre","en":"Star anti-inflammatory snack: chia pudding with golden milk of turmeric, cinnamon and ginger"}',
5,0,280,8,28,16,12,
ARRAY['anti_inflammatory','vegan','vegetarian','gluten_free','lactose_free','low_fodmap'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["300ml leche de coco o almendra","4 cdas semillas de chía","1 cdta cúrcuma","1/2 cdta canela","1/4 cdta jengibre en polvo","Pizca de pimienta negra","1-2 cdtas miel de agave o stevia","1 cdta extracto de vainilla","Mango o frutos rojos para decorar"],"en":["300ml coconut or almond milk","4 tbsp chia seeds","1 tsp turmeric","1/2 tsp cinnamon","1/4 tsp ground ginger","Pinch of black pepper","1-2 tsp agave honey or stevia","1 tsp vanilla extract","Mango or berries to garnish"]}',
'{"es":["Mezcla la leche con la cúrcuma, la canela, el jengibre, la pimienta, la vainilla y el endulzante","Añade las semillas de chía y mezcla bien","Refrigera al menos 4 horas o toda la noche removiendo una vez al principio","Sirve con mango o frutos rojos por encima"],"en":["Mix milk with turmeric, cinnamon, ginger, pepper, vanilla and sweetener","Add chia seeds and mix well","Refrigerate at least 4 hours or overnight stirring once at the start","Serve with mango or berries on top"]}'
)

ON CONFLICT (id) DO NOTHING;
