-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 8 (30) — display_order 251-280
-- Enfocado en: keto, vegan, paleo
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 7
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── KETO ─────────────────────────────────────────────────────────────────────

('aguacate_huevo_keto',251,'breakfast','🥑',
'{"es":"Aguacate relleno de huevo al horno","en":"Baked egg in avocado","fr":"Avocat farci aux oeufs au four","it":"Avocado ripieno di uovo al forno"}',
'{"es":"Desayuno keto perfecto: aguacate al horno con huevo, proteína y grasa saludable","en":"Perfect keto breakfast: baked avocado with egg, protein and healthy fat"}',
3,15,380,14,6,34,7,
ARRAY['keto','paleo','gluten_free','lactose_free','low_carb','vegetarian'],
ARRAY['follicular','luteal'],
ARRAY['lose_weight','maintain'],
ARRAY['pcos'],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["1 aguacate maduro","2 huevos pequeños","Sal, pimienta","Pimentón ahumado","Cebollino picado","Zumo de limón"],"en":["1 ripe avocado","2 small eggs","Salt, pepper","Smoked paprika","Chopped chives","Lemon juice"]}',
'{"es":["Precalienta el horno a 200°C","Parte el aguacate y retira un poco de pulpa para hacer hueco","Coloca en una bandeja y rompe un huevo en cada mitad","Sazona con sal, pimienta y pimentón","Hornea 12-15 min hasta que la clara esté cuajada","Sirve con cebollino y limón"],"en":["Preheat oven to 200°C","Halve avocado and scoop out a little flesh to make room","Place on a tray and crack one egg into each half","Season with salt, pepper and paprika","Bake 12-15 min until white is set","Serve with chives and lemon"]}'
),

('pollo_parmesano_keto',252,'dinner','🧀',
'{"es":"Pollo empanado con parmesano (keto)","en":"Parmesan crusted chicken (keto)","fr":"Poulet pane au parmesan (keto)","it":"Pollo impanato al parmigiano (keto)"}',
'{"es":"Pollo crujiente sin harina: empanado con parmesano y almendra molida","en":"Crispy chicken without flour: coated in parmesan and ground almond"}',
10,20,460,42,4,28,2,
ARRAY['keto','gluten_free','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy','eggs','nuts'],
'easy','20_40','medium',
'{"es":["2 pechugas de pollo aplanadas","60g parmesano rallado fino","40g almendra molida","1 huevo batido","1 cdta ajo en polvo","1 cdta orégano","Sal, pimienta","Aceite de oliva para cocinar"],"en":["2 chicken breasts flattened","60g finely grated parmesan","40g ground almond","1 beaten egg","1 tsp garlic powder","1 tsp oregano","Salt, pepper","Olive oil for cooking"]}',
'{"es":["Mezcla el parmesano, la almendra, el ajo en polvo y el orégano","Pasa el pollo por el huevo batido y luego por la mezcla de parmesano","Presiona bien para que se adhiera","Cocina en sartén con aceite a fuego medio 8-10 min por lado","Sirve con ensalada verde"],"en":["Mix parmesan, almond, garlic powder and oregano","Dip chicken in beaten egg then coat in parmesan mixture","Press firmly so it sticks","Cook in pan with oil over medium heat 8-10 min per side","Serve with green salad"]}'
),

('wrap_lechuga_keto',253,'lunch','🥬',
'{"es":"Wrap de lechuga con pollo y aguacate","en":"Lettuce wrap with chicken and avocado","fr":"Wrap de laitue poulet-avocat","it":"Wrap di lattuga con pollo e avocado"}',
'{"es":"El wrap keto: hojas de lechuga crujientes en lugar de tortilla, rellenas de pollo y aguacate","en":"The keto wrap: crispy lettuce leaves instead of tortilla, filled with chicken and avocado"}',
10,0,320,28,6,20,5,
ARRAY['keto','paleo','gluten_free','lactose_free','low_carb','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['lose_weight','maintain','muscle'],
ARRAY['pcos'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["200g pollo cocido desmenuzado","1 aguacate en dados","4-6 hojas grandes de lechuga romana o iceberg","1/2 pimiento rojo en tiras","Cebolleta picada","Zumo de lima","Cilantro fresco","Sal, pimienta","Salsa sriracha o guacamole (opcional)"],"en":["200g cooked chicken shredded","1 avocado diced","4-6 large romaine or iceberg lettuce leaves","1/2 red pepper in strips","Spring onion chopped","Lime juice","Fresh coriander","Salt, pepper","Sriracha or guacamole (optional)"]}',
'{"es":["Mezcla el pollo con el aguacate, pimiento, cebolleta, lima y cilantro","Sazona con sal y pimienta","Coloca el relleno en el centro de cada hoja de lechuga","Dobla los bordes y come como un taco","Añade sriracha al gusto"],"en":["Mix chicken with avocado, pepper, spring onion, lime and coriander","Season with salt and pepper","Place filling in the centre of each lettuce leaf","Fold the edges and eat like a taco","Add sriracha to taste"]}'
),

('bol_atun_keto',254,'lunch','🐟',
'{"es":"Bol de atún con huevo y aceitunas","en":"Tuna bowl with egg and olives","fr":"Bol de thon oeuf et olives","it":"Bowl di tonno con uovo e olive"}',
'{"es":"Bol keto proteico: atún, huevo cocido, aceitunas y verdura fresca sin carbohidratos","en":"Protein keto bowl: tuna, boiled egg, olives and fresh vegetables without carbs"}',
8,10,380,34,6,24,4,
ARRAY['keto','gluten_free','lactose_free','low_carb','high_protein'],
ARRAY['follicular','luteal'],
ARRAY['lose_weight','maintain','muscle'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'easy','under_20','low',
'{"es":["2 latas de atún en aceite de oliva","2 huevos cocidos en mitades","60g aceitunas negras","100g tomates cherry","1/4 pepino en rodajas","Rúcula o espinacas baby","2 cdas aceite de oliva","1 cda vinagre de vino","Sal, pimienta, orégano"],"en":["2 cans tuna in olive oil","2 boiled eggs halved","60g black olives","100g cherry tomatoes","1/4 cucumber sliced","Rocket or baby spinach","2 tbsp olive oil","1 tbsp wine vinegar","Salt, pepper, oregano"]}',
'{"es":["Coloca la rúcula en el fondo del bol","Distribuye el atún, los huevos, las aceitunas, el tomate y el pepino","Aliña con aceite, vinagre, orégano, sal y pimienta","Mezcla suavemente antes de comer"],"en":["Place rocket in the bottom of the bowl","Arrange tuna, eggs, olives, tomato and cucumber","Dress with oil, vinegar, oregano, salt and pepper","Toss gently before eating"]}'
),

('huevos_revueltos_keto',255,'breakfast','🥚',
'{"es":"Huevos revueltos con salmón ahumado y queso crema","en":"Scrambled eggs with smoked salmon and cream cheese","fr":"Oeufs brouilles saumon fume et fromage frais","it":"Uova strapazzate con salmone affumicato e formaggio fresco"}',
'{"es":"Desayuno keto de lujo: huevos cremosos con salmón ahumado y queso crema","en":"Luxury keto breakfast: creamy eggs with smoked salmon and cream cheese"}',
5,5,420,28,4,32,1,
ARRAY['keto','gluten_free','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','fish','dairy'],
'easy','under_20','medium',
'{"es":["3 huevos","80g salmón ahumado en tiras","2 cdas queso crema","1 cda mantequilla","Cebollino picado","Eneldo fresco","Sal, pimienta negra"],"en":["3 eggs","80g smoked salmon in strips","2 tbsp cream cheese","1 tbsp butter","Chopped chives","Fresh dill","Salt, black pepper"]}',
'{"es":["Bate los huevos con sal y pimienta","Derrite la mantequilla en sartén a fuego bajo","Añade los huevos y remueve lentamente con espátula","Cuando estén casi cuajados incorpora el queso crema y el salmón","Retira del fuego, acaban de cuajar solos","Sirve con cebollino y eneldo"],"en":["Beat eggs with salt and pepper","Melt butter in pan over low heat","Add eggs and stir slowly with spatula","When nearly set add cream cheese and salmon","Remove from heat, they finish setting on their own","Serve with chives and dill"]}'
),

('costillas_horno_keto',256,'dinner','🍖',
'{"es":"Costillas al horno con especias BBQ keto","en":"Oven BBQ ribs keto style","fr":"Cotes de porc au four style BBQ keto","it":"Costine al forno in stile BBQ keto"}',
'{"es":"Costillas tiernas al horno con salsa BBQ casera sin azúcar — keto y adictivas","en":"Tender oven ribs with homemade sugar-free BBQ sauce — keto and addictive"}',
15,90,580,38,6,42,2,
ARRAY['keto','paleo','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','medium',
'{"es":["600g costillas de cerdo","Para el rub: pimentón ahumado, comino, ajo en polvo, sal, pimienta","Para la salsa BBQ sin azúcar: tomate concentrado, vinagre de manzana, salsa Worcester, mostaza, eritritol o stevia, ajo en polvo, pimentón"],"en":["600g pork ribs","For the rub: smoked paprika, cumin, garlic powder, salt, pepper","For sugar-free BBQ sauce: tomato paste, apple cider vinegar, worcestershire sauce, mustard, erythritol or stevia, garlic powder, paprika"]}',
'{"es":["Mezcla el rub y frota bien las costillas","Envuelve en papel de aluminio y hornea a 150°C 75 min","Prepara la salsa BBQ mezclando todos los ingredientes en un cazo y cocina 10 min","Destapa las costillas, unta con la salsa y hornea 15 min más a 200°C","Deja reposar 5 min antes de cortar"],"en":["Mix rub and coat ribs well","Wrap in foil and bake at 150°C 75 min","Make BBQ sauce by combining all ingredients in a saucepan and cook 10 min","Unwrap ribs, brush with sauce and bake 15 min more at 200°C","Rest 5 min before cutting"]}'
),

('pizza_base_coliflor_keto',257,'dinner','🍕',
'{"es":"Pizza con base de coliflor (keto)","en":"Cauliflower base pizza (keto)","fr":"Pizza a la base de chou-fleur (keto)","it":"Pizza con base di cavolfiore (keto)"}',
'{"es":"Pizza keto con base crujiente de coliflor, mozzarella y toppings a elegir","en":"Keto pizza with crispy cauliflower base, mozzarella and toppings of choice"}',
20,25,380,24,12,26,5,
ARRAY['keto','gluten_free','low_carb','vegetarian'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy','eggs'],
'medium','20_40','low',
'{"es":["400g coliflor rallada (o en procesador)","100g mozzarella rallada","1 huevo","1 cdta orégano","1 cdta ajo en polvo","Sal","Para los toppings: salsa de tomate, mozzarella extra, albahaca, aceitunas o lo que prefieras"],"en":["400g cauliflower grated (or food processor)","100g grated mozzarella","1 egg","1 tsp oregano","1 tsp garlic powder","Salt","For toppings: tomato sauce, extra mozzarella, basil, olives or your preference"]}',
'{"es":["Cocina la coliflor rallada en microondas 5 min, deja enfriar","Escurre bien toda el agua posible con un paño limpio (este paso es clave)","Mezcla con el huevo, la mozzarella, el orégano, el ajo y la sal","Extiende en una bandeja con papel, forma un círculo fino","Hornea a 220°C 15 min hasta dorada","Añade los toppings y hornea 8 min más"],"en":["Microwave grated cauliflower 5 min, let cool","Squeeze out as much water as possible in a clean cloth (this step is key)","Mix with egg, mozzarella, oregano, garlic and salt","Spread on a lined tray into a thin circle","Bake at 220°C 15 min until golden","Add toppings and bake 8 min more"]}'
),

('sopa_pollo_keto',258,'dinner','🍲',
'{"es":"Sopa de pollo con verduras keto","en":"Keto chicken vegetable soup","fr":"Soupe de poulet aux legumes keto","it":"Zuppa di pollo e verdure keto"}',
'{"es":"Caldo de pollo reconfortante con verduras bajas en carbohidratos — sin pasta ni arroz","en":"Comforting chicken broth with low-carb vegetables — no pasta or rice"}',
10,25,300,32,8,14,4,
ARRAY['keto','paleo','gluten_free','lactose_free','low_carb','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','lose_weight','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g pollo cocido desmenuzado","1 apio en rodajas","2 zanahorias en rodajas","1 calabacín en dados","1 cebolla en dados","3 dientes de ajo","1L caldo de pollo","2 cdas aceite de oliva","Tomillo, laurel, perejil","Sal, pimienta"],"en":["300g cooked shredded chicken","1 celery stalk sliced","2 carrots sliced","1 courgette diced","1 onion diced","3 garlic cloves","1L chicken broth","2 tbsp olive oil","Thyme, bay leaf, parsley","Salt, pepper"]}',
'{"es":["Sofríe la cebolla, el ajo y el apio en aceite 4 min","Añade las zanahorias y el calabacín, saltea 3 min","Incorpora el caldo, el tomillo y el laurel","Cuece a fuego medio 15 min","Añade el pollo desmenuzado y cuece 5 min más","Sirve con perejil fresco"],"en":["Sauté onion, garlic and celery in oil 4 min","Add carrots and courgette, cook 3 min","Add broth, thyme and bay leaf","Cook over medium heat 15 min","Add shredded chicken and cook 5 min more","Serve with fresh parsley"]}'
),

('mousse_chocolate_keto',259,'snack','🍫',
'{"es":"Mousse de chocolate negro keto","en":"Dark chocolate keto mousse","fr":"Mousse au chocolat noir keto","it":"Mousse al cioccolato fondente keto"}',
'{"es":"Postre keto: mousse aireada de chocolate negro con nata montada sin azúcar","en":"Keto dessert: fluffy dark chocolate mousse with unsweetened whipped cream"}',
10,5,280,4,8,26,3,
ARRAY['keto','gluten_free','low_carb','vegetarian'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["200ml nata para montar (35% MG)","60g chocolate negro 85% en trozos","2 cdas cacao en polvo sin azúcar","2 cdas eritritol o stevia en polvo","1 cdta extracto de vainilla","Pizca de sal"],"en":["200ml heavy cream (35% fat)","60g 85% dark chocolate pieces","2 tbsp unsweetened cocoa powder","2 tbsp erythritol or powdered stevia","1 tsp vanilla extract","Pinch of salt"]}',
'{"es":["Derrite el chocolate al baño María o en microondas, deja enfriar un poco","Monta la nata con el eritritol y la vainilla hasta picos firmes","Mezcla el cacao con una cucharada de la nata montada hasta integrar","Incorpora el chocolate derretido y el cacao en la nata con movimientos envolventes","Refrigera al menos 1 hora antes de servir"],"en":["Melt chocolate in a double boiler or microwave, let cool slightly","Whip cream with erythritol and vanilla to stiff peaks","Mix cocoa with a spoonful of whipped cream until incorporated","Fold melted chocolate and cocoa into whipped cream gently","Refrigerate at least 1 hour before serving"]}'
),

('ternera_mantequilla_keto',260,'dinner','🥩',
'{"es":"Filete de ternera con mantequilla de hierbas","en":"Beef steak with herb butter","fr":"Steak de boeuf au beurre aux herbes","it":"Bistecca di manzo al burro alle erbe"}',
'{"es":"Filete a la plancha con mantequilla aromatizada de ajo y hierbas — keto de lujo","en":"Pan-seared steak with garlic herb butter — luxury keto"}',
5,12,520,42,1,38,0,
ARRAY['keto','paleo','gluten_free','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','under_20','high',
'{"es":["2 filetes de ternera (200g c/u, entrecot o solomillo)","Para la mantequilla de hierbas: 50g mantequilla blanda, 2 dientes de ajo rallados, perejil y cebollino picados, sal, pimienta","Aceite de oliva","Sal gruesa, pimienta negra recién molida"],"en":["2 beef steaks (200g each, ribeye or sirloin)","For herb butter: 50g soft butter, 2 garlic cloves grated, chopped parsley and chives, salt, pepper","Olive oil","Coarse salt, freshly ground black pepper"]}',
'{"es":["Prepara la mantequilla mezclando todos sus ingredientes, reserva","Saca la carne de la nevera 20 min antes","Calienta una sartén de hierro a fuego muy alto","Pincela el filete con aceite, sazona con sal gruesa y pimienta","Cocina 2-3 min por lado para punto medio","Retira del fuego y coloca la mantequilla de hierbas encima inmediatamente","Deja reposar 3 min antes de servir"],"en":["Make herb butter mixing all its ingredients, set aside","Take meat out of fridge 20 min before","Heat a cast iron pan over very high heat","Brush steak with oil, season with coarse salt and pepper","Cook 2-3 min per side for medium rare","Remove from heat and place herb butter on top immediately","Rest 3 min before serving"]}'
),

-- ── VEGAN ─────────────────────────────────────────────────────────────────────

('dal_lentejas_rojas_vegan',261,'dinner','🌱',
'{"es":"Dal de lentejas rojas con cúrcuma","en":"Red lentil dal with turmeric","fr":"Dal de lentilles rouges au curcuma","it":"Dal di lenticchie rosse con curcuma"}',
'{"es":"Curry suave de lentejas rojas al estilo indio — proteína vegetal, cúrcuma antiinflamatoria","en":"Mild Indian-style red lentil curry — plant protein, anti-inflammatory turmeric"}',
5,25,380,18,54,8,12,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory','mediterranean'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas rojas","1 cebolla en dados","3 dientes de ajo","1 cdta jengibre fresco rallado","1 cdta cúrcuma","1 cdta comino","1 cdta garam masala","400ml leche de coco","400ml caldo de verduras","1 cda aceite de coco o oliva","Sal, cilantro fresco"],"en":["200g red lentils","1 onion diced","3 garlic cloves","1 tsp fresh ginger grated","1 tsp turmeric","1 tsp cumin","1 tsp garam masala","400ml coconut milk","400ml vegetable broth","1 tbsp coconut or olive oil","Salt, fresh coriander"]}',
'{"es":["Sofríe la cebolla, el ajo y el jengibre en aceite 4 min","Añade las especias y cocina 1 min más","Incorpora las lentejas, la leche de coco y el caldo","Cuece a fuego medio 20-22 min removiendo de vez en cuando","Ajusta de sal y sirve con cilantro fresco y arroz basmati"],"en":["Sauté onion, garlic and ginger in oil 4 min","Add spices and cook 1 min more","Add lentils, coconut milk and broth","Cook over medium heat 20-22 min stirring occasionally","Adjust salt and serve with fresh coriander and basmati rice"]}'
),

('buddha_bowl_vegan',262,'lunch','🥗',
'{"es":"Buddha bowl proteico vegan","en":"Vegan protein buddha bowl","fr":"Buddha bowl vegan proteine","it":"Buddha bowl vegano proteico"}',
'{"es":"Bol completo con garbanzos asados, quinoa, verduras asadas y tahini","en":"Complete bowl with roasted chickpeas, quinoa, roasted vegetables and tahini"}',
10,30,520,20,66,16,12,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY['pcos'],
ARRAY['sesame'],
'medium','20_40','low',
'{"es":["150g quinoa cocida","200g garbanzos cocidos","1 boniato en dados","1 pimiento rojo en tiras","1 cdta pimentón","2 cdas aceite de oliva","Para el tahini: 2 cdas tahini, zumo de 1 limón, agua, ajo, sal","Espinacas baby, aguacate, semillas"],"en":["150g cooked quinoa","200g cooked chickpeas","1 sweet potato diced","1 red pepper in strips","1 tsp paprika","2 tbsp olive oil","For tahini: 2 tbsp tahini, juice of 1 lemon, water, garlic, salt","Baby spinach, avocado, seeds"]}',
'{"es":["Mezcla los garbanzos y las verduras con aceite y pimentón","Hornea a 200°C 25 min removiendo a mitad","Prepara el tahini mezclando todos sus ingredientes hasta obtener una salsa","Monta el bol: quinoa, espinacas, verduras asadas, aguacate","Riega con la salsa de tahini y espolvorea semillas"],"en":["Mix chickpeas and vegetables with oil and paprika","Roast at 200°C 25 min tossing halfway","Make tahini sauce mixing all its ingredients into a dressing","Build the bowl: quinoa, spinach, roasted veg, avocado","Drizzle with tahini sauce and sprinkle seeds"]}'
),

('curry_garbanzos_espinacas_vegan',263,'dinner','🍛',
'{"es":"Curry de garbanzos y espinacas","en":"Chickpea and spinach curry","fr":"Curry de pois chiches aux epinards","it":"Curry di ceci e spinaci"}',
'{"es":"Curry cremoso de garbanzos con espinacas y leche de coco — chana masala vegano","en":"Creamy chickpea curry with spinach and coconut milk — vegan chana masala"}',
5,22,420,16,52,14,12,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['pcos','endometriosis'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["400g garbanzos cocidos","200g espinacas frescas","400ml leche de coco","1 cebolla en dados","3 dientes de ajo","1 cdta jengibre rallado","2 cdtas curry en polvo","1 cdta cúrcuma","1 cdta comino","2 cdas aceite de oliva","Sal, cilantro, arroz para acompañar"],"en":["400g cooked chickpeas","200g fresh spinach","400ml coconut milk","1 onion diced","3 garlic cloves","1 tsp grated ginger","2 tsp curry powder","1 tsp turmeric","1 tsp cumin","2 tbsp olive oil","Salt, coriander, rice to serve"]}',
'{"es":["Sofríe la cebolla, el ajo y el jengibre en aceite 4 min","Añade las especias y cocina 2 min","Incorpora los garbanzos y la leche de coco","Cuece 15 min a fuego medio","Añade las espinacas los últimos 3 min hasta que se marchiten","Sirve con arroz y cilantro fresco"],"en":["Sauté onion, garlic and ginger in oil 4 min","Add spices and cook 2 min","Add chickpeas and coconut milk","Cook 15 min over medium heat","Add spinach in the last 3 min until wilted","Serve with rice and fresh coriander"]}'
),

('tacos_jackfruit_vegan',264,'dinner','🌮',
'{"es":"Tacos de jackfruit desmenuzado","en":"Pulled jackfruit tacos","fr":"Tacos de jackfruit effile","it":"Tacos di jackfruit sfilacciato"}',
'{"es":"Tacos veganos con jackfruit joven desmenuzado estilo pulled pork con especias BBQ","en":"Vegan tacos with young jackfruit shredded in pulled pork BBQ style"}',
10,25,380,8,62,10,8,
ARRAY['vegan','vegetarian','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten'],
'medium','20_40','low',
'{"es":["400g jackfruit joven en conserva (escurrido)","1 cebolla en dados","3 dientes de ajo","2 cdas pasta de tomate","1 cdta pimentón ahumado","1 cdta comino","1 cdta orégano","1 cda vinagre de manzana","Tortillas de maíz o trigo","Repollo rallado, aguacate, salsa, lima"],"en":["400g young canned jackfruit (drained)","1 onion diced","3 garlic cloves","2 tbsp tomato paste","1 tsp smoked paprika","1 tsp cumin","1 tsp oregano","1 tbsp apple cider vinegar","Corn or wheat tortillas","Shredded cabbage, avocado, salsa, lime"]}',
'{"es":["Escurre y desmenúza el jackfruit con los dedos o un tenedor","Sofríe la cebolla y el ajo en aceite 4 min","Añade el jackfruit y las especias, cocina 5 min","Incorpora la pasta de tomate, el vinagre y 100ml agua","Cuece 12-15 min a fuego medio hasta que la salsa espese","Sirve en tortillas con repollo, aguacate y lima"],"en":["Drain and shred jackfruit with fingers or a fork","Sauté onion and garlic in oil 4 min","Add jackfruit and spices, cook 5 min","Add tomato paste, vinegar and 100ml water","Cook 12-15 min over medium heat until sauce thickens","Serve in tortillas with cabbage, avocado and lime"]}'
),

('bowl_quinoa_mango_vegan',265,'lunch','🥭',
'{"es":"Bowl de quinoa con mango y edamame","en":"Quinoa bowl with mango and edamame","fr":"Bowl de quinoa mangue-edamame","it":"Bowl di quinoa con mango e edamame"}',
'{"es":"Bowl fresco tropical con quinoa, mango, edamame y vinagreta de limón y jengibre","en":"Fresh tropical bowl with quinoa, mango, edamame and lemon ginger dressing"}',
10,15,460,18,64,12,8,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['soy'],
'easy','20_40','medium',
'{"es":["160g quinoa","1 mango en dados","100g edamame cocido","1/4 pepino en dados","1/2 aguacate","Hojas de menta","Para la vinagreta: zumo de 1 lima, 1 cdta jengibre rallado, 1 cda tamari, 1 cda aceite de sésamo, 1 cdta miel de agave"],"en":["160g quinoa","1 mango diced","100g cooked edamame","1/4 cucumber diced","1/2 avocado","Mint leaves","For dressing: juice of 1 lime, 1 tsp grated ginger, 1 tbsp tamari, 1 tbsp sesame oil, 1 tsp agave honey"]}',
'{"es":["Cuece la quinoa según las instrucciones, deja enfriar","Prepara la vinagreta mezclando todos los ingredientes","Monta el bowl con la quinoa, el mango, el edamame, el pepino y el aguacate","Riega con la vinagreta y decora con menta"],"en":["Cook quinoa according to instructions, let cool","Prepare dressing by mixing all ingredients","Build bowl with quinoa, mango, edamame, cucumber and avocado","Drizzle with dressing and garnish with mint"]}'
),

('wrap_hummus_verduras_vegan',266,'lunch','🫓',
'{"es":"Wrap integral con hummus y verduras asadas","en":"Wholegrain wrap with hummus and roasted vegetables","fr":"Wrap complet hummus et legumes rotis","it":"Wrap integrale con hummus e verdure arrostite"}',
'{"es":"Wrap vegano saciante con hummus cremoso, pimiento asado, rúcula y zanahoria rallada","en":"Satisfying vegan wrap with creamy hummus, roasted pepper, rocket and grated carrot"}',
10,15,420,14,56,14,8,
ARRAY['vegan','vegetarian','lactose_free','anti_inflammatory'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy','lose_weight'],
ARRAY['pcos'],
ARRAY['gluten','sesame'],
'easy','under_20','low',
'{"es":["2 tortillas integrales grandes","4 cdas hummus","1 pimiento rojo asado en tiras","1 zanahoria rallada","Rúcula fresca","1/2 aguacate en láminas","Zumo de limón","Sal, pimienta, comino"],"en":["2 large wholegrain tortillas","4 tbsp hummus","1 roasted red pepper in strips","1 grated carrot","Fresh rocket","1/2 avocado sliced","Lemon juice","Salt, pepper, cumin"]}',
'{"es":["Calienta las tortillas en sartén seca 30 seg por lado","Unta el hummus sobre cada tortilla","Distribuye el pimiento, la zanahoria, la rúcula y el aguacate","Exprime un poco de limón y sazona con comino","Enrolla apretando bien y corta por la mitad"],"en":["Warm tortillas in a dry pan 30 sec per side","Spread hummus over each tortilla","Layer pepper, carrot, rocket and avocado","Squeeze a little lemon and season with cumin","Roll tightly and cut in half"]}'
),

('porridge_avena_vegan',267,'breakfast','🥣',
'{"es":"Porridge de avena con frutos rojos y semillas","en":"Oat porridge with berries and seeds","fr":"Porridge d''avoine aux fruits rouges et graines","it":"Porridge di avena con frutti rossi e semi"}',
'{"es":"Desayuno vegano reconfortante: avena cremosa con frutos rojos frescos y semillas de chía","en":"Comforting vegan breakfast: creamy oats with fresh berries and chia seeds"}',
2,8,380,12,58,10,8,
ARRAY['vegan','vegetarian','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["80g copos de avena","250ml leche de avena o almendra","100ml agua","150g frutos rojos mixtos (fresas, arándanos, frambuesas)","1 cda semillas de chía","1 cda mantequilla de almendra","1 cdta extracto de vainilla","Canela al gusto","Miel de agave opcional"],"en":["80g oat flakes","250ml oat or almond milk","100ml water","150g mixed berries (strawberries, blueberries, raspberries)","1 tbsp chia seeds","1 tbsp almond butter","1 tsp vanilla extract","Cinnamon to taste","Agave honey optional"]}',
'{"es":["Lleva la leche y el agua a ebullición","Añade los copos de avena, la vainilla y la canela","Cuece a fuego bajo 5-6 min removiendo hasta que espese","Sirve en bol, coloca los frutos rojos encima","Añade las semillas de chía, la mantequilla de almendra y el agave"],"en":["Bring milk and water to a boil","Add oats, vanilla and cinnamon","Cook over low heat 5-6 min stirring until thick","Serve in a bowl, place berries on top","Add chia seeds, almond butter and agave"]}'
),

('pasta_tomate_fresco_vegan',268,'dinner','🍅',
'{"es":"Pasta con tomate fresco y albahaca","en":"Pasta with fresh tomato and basil","fr":"Pates tomate fraiche et basilic","it":"Pasta al pomodoro fresco e basilico"}',
'{"es":"La pasta más sencilla y perfecta: tomate cherry, ajo, albahaca fresca y aceite de oliva","en":"The simplest and most perfect pasta: cherry tomato, garlic, fresh basil and olive oil"}',
5,15,480,14,74,14,5,
ARRAY['vegan','vegetarian','lactose_free','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["150g pasta (espagueti o penne)","300g tomates cherry","3 dientes de ajo laminados","4 cdas aceite de oliva virgen extra","Albahaca fresca abundante","Sal, pimienta negra","Guindilla en copos (opcional)","Levadura nutricional (opcional, para sabor queso)"],"en":["150g pasta (spaghetti or penne)","300g cherry tomatoes","3 garlic cloves sliced","4 tbsp extra-virgin olive oil","Plenty of fresh basil","Salt, black pepper","Chilli flakes (optional)","Nutritional yeast (optional, for cheesy flavour)"]}',
'{"es":["Cuece la pasta al dente, reserva 1 taza del agua de cocción","Calienta el aceite con el ajo y la guindilla 2 min","Añade los tomates cherry, sube el fuego y cocina 5-7 min hasta que se rompan","Añade la pasta y un poco del agua de cocción, mezcla bien","Retira del fuego y añade la albahaca fresca rasgada"],"en":["Cook pasta al dente, reserve 1 cup cooking water","Heat oil with garlic and chilli 2 min","Add cherry tomatoes, turn up heat and cook 5-7 min until they burst","Add pasta and a little cooking water, toss well","Remove from heat and add torn fresh basil"]}'
),

('smoothie_verde_proteico_vegan',269,'breakfast','🥤',
'{"es":"Smoothie verde proteico con espirulina","en":"Green protein smoothie with spirulina","fr":"Smoothie vert proteine a la spiruline","it":"Smoothie verde proteico con spirulina"}',
'{"es":"Batido verde cargado de nutrientes: espinacas, plátano, proteína de guisante y espirulina","en":"Nutrient-packed green smoothie: spinach, banana, pea protein and spirulina"}',
5,0,320,22,42,6,5,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["2 puñados de espinacas baby","1 plátano congelado","30g proteína de guisante en polvo","1 cdta espirulina en polvo","250ml leche de almendra sin azúcar","1 cda mantequilla de almendra","1 cdta jengibre rallado","Cubitos de hielo"],"en":["2 handfuls baby spinach","1 frozen banana","30g pea protein powder","1 tsp spirulina powder","250ml unsweetened almond milk","1 tbsp almond butter","1 tsp grated ginger","Ice cubes"]}',
'{"es":["Coloca todos los ingredientes en la batidora","Bate a velocidad alta 60 seg hasta que esté suave","Añade más leche si lo quieres más líquido","Bebe inmediatamente para aprovechar los nutrientes"],"en":["Place all ingredients in the blender","Blend on high for 60 sec until smooth","Add more milk if you want it thinner","Drink immediately to get the most nutrients"]}'
),

('stir_fry_tofu_vegan',270,'dinner','🥦',
'{"es":"Salteado de tofu con brócoli y sésamo","en":"Tofu and broccoli stir-fry with sesame","fr":"Sauté de tofu brocoli-sesame","it":"Saltato di tofu con broccoli e sesamo"}',
'{"es":"Salteado asiático de tofu crujiente, brócoli y zanahoria con salsa de soja y sésamo","en":"Asian stir-fry of crispy tofu, broccoli and carrot with soy sauce and sesame"}',
15,12,380,22,28,18,7,
ARRAY['vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['soy','sesame'],
'medium','20_40','low',
'{"es":["300g tofu firme en dados","200g brócoli en flores","2 zanahorias en juliana","3 dientes de ajo","1 cdta jengibre rallado","3 cdas tamari o salsa de soja","1 cda aceite de sésamo","1 cda aceite de oliva","1 cdta fécula de maíz disuelto en agua","Semillas de sésamo, cebolleta verde"],"en":["300g firm tofu cubed","200g broccoli florets","2 carrots julienned","3 garlic cloves","1 tsp grated ginger","3 tbsp tamari or soy sauce","1 tbsp sesame oil","1 tbsp olive oil","1 tsp cornstarch dissolved in water","Sesame seeds, spring onion"]}',
'{"es":["Presiona el tofu con papel de cocina para eliminar el exceso de agua","Dora el tofu en aceite de oliva a fuego alto 5-6 min hasta crujiente, reserva","En el mismo wok saltea el ajo y el jengibre 1 min","Añade el brócoli y la zanahoria, saltea 4 min","Incorpora el tofu, el tamari, el aceite de sésamo y la fécula","Cocina 2 min más hasta que la salsa espese","Sirve con sésamo y cebolleta"],"en":["Press tofu with paper towels to remove excess water","Brown tofu in olive oil over high heat 5-6 min until crispy, set aside","In the same wok sauté garlic and ginger 1 min","Add broccoli and carrot, stir-fry 4 min","Add tofu, tamari, sesame oil and cornstarch","Cook 2 min more until sauce thickens","Serve with sesame and spring onion"]}'
),

-- ── PALEO ─────────────────────────────────────────────────────────────────────

('pollo_boniato_paleo',271,'dinner','🍠',
'{"es":"Pollo asado con boniato y romero","en":"Roasted chicken with sweet potato and rosemary","fr":"Poulet roti patate douce et romarin","it":"Pollo arrosto con patata dolce e rosmarino"}',
'{"es":"Bandeja de horno paleo: pollo, boniato y cebolla roja con romero y ajo","en":"Paleo sheet pan: chicken, sweet potato and red onion with rosemary and garlic"}',
10,35,480,36,34,14,5,
ARRAY['paleo','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["4 muslos de pollo con piel","2 boniatos en dados grandes","1 cebolla roja en gajos","4 dientes de ajo enteros","3 ramas de romero fresco","3 cdas aceite de oliva","Sal gruesa, pimienta negra","Pimentón dulce"],"en":["4 chicken thighs skin-on","2 sweet potatoes in large dice","1 red onion in wedges","4 whole garlic cloves","3 fresh rosemary sprigs","3 tbsp olive oil","Coarse salt, black pepper","Sweet paprika"]}',
'{"es":["Precalienta el horno a 200°C","Mezcla el boniato, la cebolla y el ajo con aceite, sal, pimienta y pimentón","Extiende en una bandeja grande","Coloca el pollo encima, sazona y añade el romero","Hornea 35-40 min hasta que el pollo esté dorado y el boniato tierno"],"en":["Preheat oven to 200°C","Mix sweet potato, onion and garlic with oil, salt, pepper and paprika","Spread on a large tray","Place chicken on top, season and add rosemary","Roast 35-40 min until chicken is golden and sweet potato tender"]}'
),

('hamburguesa_paleo',272,'dinner','🍔',
'{"es":"Hamburguesa paleo en hoja de lechuga","en":"Paleo burger in lettuce wrap","fr":"Burger paleo en feuille de laitue","it":"Burger paleo in foglia di lattuga"}',
'{"es":"Hamburguesa de ternera con todas las salsas pero sin pan — envuelta en lechuga crujiente","en":"Beef burger with all the toppings but no bun — wrapped in crispy lettuce"}',
10,10,460,36,10,30,4,
ARRAY['paleo','keto','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["400g carne picada de ternera (80% magra)","1 cdta ajo en polvo","1 cdta cebolla en polvo","Sal, pimienta","4 hojas grandes de lechuga iceberg","1 tomate en rodajas","1/2 cebolla roja en aros","1 aguacate en láminas","Mostaza, ketchup sin azúcar (opcional)"],"en":["400g beef mince (80% lean)","1 tsp garlic powder","1 tsp onion powder","Salt, pepper","4 large iceberg lettuce leaves","1 tomato sliced","1/2 red onion in rings","1 avocado sliced","Mustard, sugar-free ketchup (optional)"]}',
'{"es":["Mezcla la carne con el ajo, la cebolla, la sal y la pimienta","Forma 2 hamburguesas gruesas","Cocina en sartén o plancha 4-5 min por lado","Monta la hamburguesa en la hoja de lechuga con el tomate, la cebolla, el aguacate y la salsa","Dobla la lechuga como si fuera un bun"],"en":["Mix mince with garlic, onion, salt and pepper","Form 2 thick burgers","Cook in pan or griddle 4-5 min per side","Build burger in lettuce leaf with tomato, onion, avocado and sauce","Fold lettuce as if it were a bun"]}'
),

('carne_especiada_paleo',273,'dinner','🥩',
'{"es":"Carne picada especiada estilo köfte","en":"Spiced minced meat köfte style","fr":"Viande hachee epicee style kofte","it":"Carne macinata speziata in stile kofte"}',
'{"es":"Albóndigas aplastadas de cordero y ternera con especias orientales — paleo y sin gluten","en":"Flattened lamb and beef meatballs with Middle Eastern spices — paleo and gluten-free"}',
10,12,440,32,6,32,2,
ARRAY['paleo','gluten_free','lactose_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','medium',
'{"es":["300g carne picada mixta (cordero y ternera)","1 cdta comino","1 cdta pimentón","1/2 cdta canela","1/2 cdta cilantro molido","1 diente de ajo rallado","1 cda perejil picado","Sal, pimienta","Aceite de oliva para cocinar"],"en":["300g mixed mince (lamb and beef)","1 tsp cumin","1 tsp paprika","1/2 tsp cinnamon","1/2 tsp ground coriander","1 garlic clove grated","1 tbsp chopped parsley","Salt, pepper","Olive oil for cooking"]}',
'{"es":["Mezcla bien la carne con todas las especias, el ajo y el perejil","Forma óvalos alargados o cilindros y aplástalos ligeramente","Cocina en sartén con aceite a fuego medio-alto 4-5 min por lado","Sirve con ensalada verde y tahini si no es estrictamente paleo"],"en":["Mix meat well with all spices, garlic and parsley","Shape into elongated ovals or cylinders and flatten slightly","Cook in pan with oil over medium-high heat 4-5 min per side","Serve with green salad and tahini if not strictly paleo"]}'
),

('salmón_esparragos_paleo',274,'dinner','🐠',
'{"es":"Salmón con espárragos y limón al horno","en":"Baked salmon with asparagus and lemon","fr":"Saumon aux asperges et citron au four","it":"Salmone con asparagi e limone al forno"}',
'{"es":"Bandeja de horno paleo con salmón y espárragos — omega-3, proteína y sabor mediterráneo","en":"Paleo sheet pan with salmon and asparagus — omega-3, protein and Mediterranean flavour"}',
5,18,440,36,6,30,4,
ARRAY['paleo','pescatarian','gluten_free','lactose_free','high_protein','low_carb','keto','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["2 filetes de salmón (160g c/u)","300g espárragos verdes","3 cdas aceite de oliva","Zumo de 1 limón","2 dientes de ajo laminados","Eneldo fresco o seco","Sal, pimienta"],"en":["2 salmon fillets (160g each)","300g green asparagus","3 tbsp olive oil","Juice of 1 lemon","2 garlic cloves sliced","Fresh or dried dill","Salt, pepper"]}',
'{"es":["Precalienta el horno a 200°C","Coloca los espárragos en una bandeja, aliña con aceite, ajo, sal y pimienta","Hornea los espárragos 8 min","Coloca el salmón encima, riega con limón, aceite y eneldo","Hornea 12-15 min más hasta que el salmón esté listo"],"en":["Preheat oven to 200°C","Place asparagus on a tray, dress with oil, garlic, salt and pepper","Roast asparagus 8 min","Place salmon on top, drizzle with lemon, oil and dill","Roast 12-15 min more until salmon is cooked"]}'
),

('ensalada_pollo_mango_paleo',275,'lunch','🥭',
'{"es":"Ensalada de pollo asado con mango y aguacate","en":"Roasted chicken salad with mango and avocado","fr":"Salade de poulet roti mangue-avocat","it":"Insalata di pollo arrosto con mango e avocado"}',
'{"es":"Ensalada fresca y saciante con pollo, mango, aguacate y vinagreta de lima y jengibre","en":"Fresh and satisfying salad with chicken, mango, avocado and lime ginger dressing"}',
12,0,420,34,22,20,6,
ARRAY['paleo','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['pcos'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["250g pollo asado o cocido en tiras","1 mango maduro en dados","1 aguacate en dados","Lechuga romana o mezcla de hojas","1/4 pepino en rodajas","Cebolleta picada","Para la vinagreta: zumo de 2 limas, 1 cdta jengibre rallado, 2 cdas aceite de oliva, 1 cdta miel, sal, pimienta"],"en":["250g roasted or cooked chicken in strips","1 ripe mango diced","1 avocado diced","Romaine lettuce or mixed leaves","1/4 cucumber sliced","Spring onion chopped","For dressing: juice of 2 limes, 1 tsp grated ginger, 2 tbsp olive oil, 1 tsp honey, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando todos los ingredientes","Coloca las hojas en el fondo de un bol grande","Distribuye el pollo, el mango, el aguacate, el pepino y la cebolleta","Riega con la vinagreta justo antes de servir"],"en":["Prepare dressing by mixing all ingredients","Place leaves in the bottom of a large bowl","Arrange chicken, mango, avocado, cucumber and spring onion","Drizzle with dressing just before serving"]}'
),

('chili_carne_paleo',276,'dinner','🌶️',
'{"es":"Chili con carne paleo (sin legumbres)","en":"Paleo chili con carne (no beans)","fr":"Chili con carne paleo (sans legumes)","it":"Chili con carne paleo (senza legumi)"}',
'{"es":"Chili intenso de ternera y verduras sin alubias — versión paleo con pimientos y boniato","en":"Rich beef and vegetable chili with no beans — paleo version with peppers and sweet potato"}',
10,35,420,32,22,20,6,
ARRAY['paleo','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','20_40','low',
'{"es":["400g carne picada de ternera","1 boniato en dados pequeños","1 pimiento rojo en dados","1 pimiento verde en dados","1 cebolla en dados","3 dientes de ajo","400g tomate triturado","2 cdas pasta de tomate","1 cdta comino","1 cdta pimentón ahumado","1 cdta orégano","1/2 cdta guindilla","Sal, aceite de oliva"],"en":["400g beef mince","1 sweet potato diced small","1 red pepper diced","1 green pepper diced","1 onion diced","3 garlic cloves","400g crushed tomato","2 tbsp tomato paste","1 tsp cumin","1 tsp smoked paprika","1 tsp oregano","1/2 tsp chilli","Salt, olive oil"]}',
'{"es":["Dora la carne en aceite a fuego alto 5 min, reserva","Sofríe la cebolla, el ajo y los pimientos 5 min","Añade el boniato y cocina 3 min","Incorpora la carne, las especias, el tomate y la pasta de tomate","Cuece a fuego medio 25 min hasta que el boniato esté tierno","Ajusta de sal y sirve con aguacate o guacamole"],"en":["Brown mince in oil over high heat 5 min, set aside","Sauté onion, garlic and peppers 5 min","Add sweet potato and cook 3 min","Add mince, spices, tomato and tomato paste","Cook over medium heat 25 min until sweet potato is tender","Adjust salt and serve with avocado or guacamole"]}'
),

('tortilla_española_paleo',277,'lunch','🥚',
'{"es":"Tortilla de boniato y espinacas (paleo)","en":"Sweet potato and spinach frittata (paleo)","fr":"Frittata patate douce et epinards (paleo)","it":"Frittata di patata dolce e spinaci (paleo)"}',
'{"es":"Variante paleo de la tortilla española: boniato en lugar de patata, con espinacas","en":"Paleo version of Spanish omelette: sweet potato instead of potato, with spinach"}',
10,20,340,18,22,18,4,
ARRAY['paleo','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["4 huevos","1 boniato mediano en rodajas finas","100g espinacas frescas","1 cebolla en rodajas finas","2 cdas aceite de oliva","Sal, pimienta","Pimentón dulce (opcional)"],"en":["4 eggs","1 medium sweet potato thinly sliced","100g fresh spinach","1 onion thinly sliced","2 tbsp olive oil","Salt, pepper","Sweet paprika (optional)"]}',
'{"es":["Cuece el boniato en sartén con aceite a fuego bajo 10 min hasta tierno","Añade la cebolla y cocina 3 min más","Añade las espinacas hasta que se marchiten","Bate los huevos con sal y pimienta, vierte sobre las verduras","Cuaja a fuego bajo 5 min, dale la vuelta con un plato y cuaja 3 min más"],"en":["Cook sweet potato in pan with oil over low heat 10 min until tender","Add onion and cook 3 min more","Add spinach until wilted","Beat eggs with salt and pepper, pour over vegetables","Set over low heat 5 min, flip with a plate and set 3 min more"]}'
),

('pollo_curry_coco_paleo',278,'dinner','🥥',
'{"es":"Curry de pollo con leche de coco (paleo)","en":"Coconut milk chicken curry (paleo)","fr":"Curry de poulet au lait de coco (paleo)","it":"Curry di pollo al latte di cocco (paleo)"}',
'{"es":"Curry ligero de pollo con leche de coco y verduras paleo — sin cereales ni legumbres","en":"Light chicken and coconut milk curry with paleo vegetables — no grains or legumes"}',
10,25,460,36,16,28,4,
ARRAY['paleo','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["400g pechuga de pollo en dados","400ml leche de coco","1 cebolla en dados","3 dientes de ajo","1 cdta jengibre rallado","2 cdtas curry en polvo","1 cdta cúrcuma","1 cdta comino","1 pimiento rojo en dados","1 calabacín en dados","2 cdas aceite de coco","Sal, cilantro fresco"],"en":["400g chicken breast diced","400ml coconut milk","1 onion diced","3 garlic cloves","1 tsp grated ginger","2 tsp curry powder","1 tsp turmeric","1 tsp cumin","1 red pepper diced","1 courgette diced","2 tbsp coconut oil","Salt, fresh coriander"]}',
'{"es":["Sofríe la cebolla, el ajo y el jengibre en aceite de coco 4 min","Añade las especias y cocina 2 min","Sube el fuego, añade el pollo y dora 4 min","Incorpora el pimiento, el calabacín y la leche de coco","Cuece a fuego medio 15 min","Sirve con cilantro fresco y coliflor en arroz si quieres"],"en":["Sauté onion, garlic and ginger in coconut oil 4 min","Add spices and cook 2 min","Turn up heat, add chicken and brown 4 min","Add pepper, courgette and coconut milk","Cook over medium heat 15 min","Serve with fresh coriander and cauliflower rice if desired"]}'
),

('ensalada_remolachaa_nueces_paleo',279,'lunch','🥗',
'{"es":"Ensalada de remolacha, nueces y naranja","en":"Beetroot, walnut and orange salad","fr":"Salade de betterave, noix et orange","it":"Insalata di barbabietola, noci e arancia"}',
'{"es":"Ensalada paleo colorida con remolacha asada, nueces tostadas y gajos de naranja","en":"Colourful paleo salad with roasted beetroot, toasted walnuts and orange segments"}',
10,0,340,8,30,20,6,
ARRAY['paleo','vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["200g remolacha cocida en dados","1 naranja en gajos","40g nueces tostadas","Hojas de rúcula o espinacas baby","Para la vinagreta: 2 cdas aceite de oliva, 1 cda vinagre balsámico, 1 cdta mostaza de Dijon, sal, pimienta"],"en":["200g cooked beetroot diced","1 orange segmented","40g toasted walnuts","Rocket or baby spinach leaves","For dressing: 2 tbsp olive oil, 1 tbsp balsamic vinegar, 1 tsp Dijon mustard, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando todos los ingredientes","Coloca las hojas en un bol","Añade la remolacha, los gajos de naranja y las nueces","Aliña con la vinagreta y sirve inmediatamente"],"en":["Prepare dressing by mixing all ingredients","Place leaves in a bowl","Add beetroot, orange segments and walnuts","Dress and serve immediately"]}'
),

('frittata_verduras_paleo',280,'breakfast','🥚',
'{"es":"Frittata de verduras al horno","en":"Baked vegetable frittata","fr":"Frittata de legumes au four","it":"Frittata di verdure al forno"}',
'{"es":"Frittata paleo de huevos con verduras de temporada — perfecta para preparar con antelación","en":"Paleo egg frittata with seasonal vegetables — perfect for meal prep"}',
10,20,300,20,10,20,4,
ARRAY['paleo','gluten_free','lactose_free','high_protein','anti_inflammatory','vegetarian'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos','endometriosis'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["6 huevos","1 calabacín en dados pequeños","1 pimiento rojo en dados","100g espinacas baby","1 cebolla en dados","2 dientes de ajo","2 cdas aceite de oliva","Sal, pimienta","Hierbas provenzales o tomillo"],"en":["6 eggs","1 courgette diced small","1 red pepper diced","100g baby spinach","1 onion diced","2 garlic cloves","2 tbsp olive oil","Salt, pepper","Herbes de Provence or thyme"]}',
'{"es":["Precalienta el horno a 180°C","Sofríe la cebolla, el ajo y las verduras en una sartén apta para horno 6-7 min","Añade las espinacas y mezcla hasta que se marchiten","Bate los huevos con sal, pimienta y hierbas","Vierte los huevos sobre las verduras en la sartén","Hornea 15-18 min hasta que esté cuajada y dorada"],"en":["Preheat oven to 180°C","Sauté onion, garlic and vegetables in an oven-safe pan 6-7 min","Add spinach and stir until wilted","Beat eggs with salt, pepper and herbs","Pour eggs over vegetables in the pan","Bake 15-18 min until set and golden"]}'
)

ON CONFLICT (id) DO NOTHING;
