-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 7 (30) — display_order 221-250
-- Enfocado en: mediterranean, pescatarian
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 6
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── MEDITERRANEAN ────────────────────────────────────────────────────────────

('ensalada_griega_clasica',221,'lunch','🫒',
'{"es":"Ensalada griega clásica","en":"Classic Greek salad","fr":"Salade grecque classique","it":"Insalata greca classica"}',
'{"es":"Tomate, pepino, aceitunas y feta — fresca, sencilla y antiinflamatoria","en":"Tomato, cucumber, olives and feta — fresh, simple and anti-inflammatory"}',
10,0,310,10,14,24,4,
ARRAY['mediterranean','vegetarian','gluten_free','anti_inflammatory','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight'],
ARRAY['pcos','endometriosis'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["3 tomates en gajos","1 pepino en medias lunas","1/2 cebolla roja en tiras","100g aceitunas kalamata","150g queso feta en dados","3 cdas aceite de oliva virgen","1 cda zumo de limón","Orégano seco, sal, pimienta"],"en":["3 tomatoes in wedges","1 cucumber in half moons","1/2 red onion in strips","100g kalamata olives","150g feta cheese diced","3 tbsp extra-virgin olive oil","1 tbsp lemon juice","Dried oregano, salt, pepper"]}',
'{"es":["Coloca tomate, pepino y cebolla en un bol","Añade las aceitunas y el feta por encima","Aliña con aceite, limón, orégano, sal y pimienta","Mezcla suavemente y sirve al momento"],"en":["Place tomato, cucumber and onion in a bowl","Add olives and feta on top","Dress with oil, lemon, oregano, salt and pepper","Toss gently and serve immediately"]}'
),

('pollo_limon_oregano_med',222,'dinner','🍋',
'{"es":"Pollo al limón y orégano estilo mediterráneo","en":"Mediterranean lemon oregano chicken","fr":"Poulet citron-origan méditerranéen","it":"Pollo al limone e origano mediterraneo"}',
'{"es":"Marinado en limón, ajo y orégano — el sabor del Mediterráneo en 30 minutos","en":"Marinated in lemon, garlic and oregano — Mediterranean flavour in 30 minutes"}',
10,22,390,38,6,22,2,
ARRAY['mediterranean','paleo','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["2 pechugas de pollo (300g total)","Zumo de 2 limones","3 dientes de ajo laminados","2 cdas orégano seco","4 cdas aceite de oliva","Sal, pimienta negra","Perejil fresco para servir"],"en":["2 chicken breasts (300g total)","Juice of 2 lemons","3 garlic cloves sliced","2 tbsp dried oregano","4 tbsp olive oil","Salt, black pepper","Fresh parsley to serve"]}',
'{"es":["Marina el pollo con limón, ajo, orégano, aceite, sal y pimienta al menos 10 min","Calienta una sartén a fuego medio-alto","Cocina el pollo 10-12 min por lado hasta dorado","Deja reposar 3 min y sirve con perejil"],"en":["Marinate chicken with lemon, garlic, oregano, oil, salt and pepper at least 10 min","Heat a pan over medium-high heat","Cook chicken 10-12 min per side until golden","Rest 3 min and serve with parsley"]}'
),

('hummus_casero_med',223,'snack','🫘',
'{"es":"Hummus casero con crudités","en":"Homemade hummus with crudités","fr":"Houmous maison et crudités","it":"Hummus fatto in casa con crudités"}',
'{"es":"Hummus cremoso de garbanzos con tahini y limón — snack nutritivo y saciante","en":"Creamy chickpea hummus with tahini and lemon — nutritious and satisfying snack"}',
10,0,280,10,28,14,7,
ARRAY['mediterranean','vegan','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY['pcos','endometriosis'],
ARRAY['sesame'],
'easy','under_20','low',
'{"es":["400g garbanzos cocidos (1 bote)","3 cdas tahini","Zumo de 1 limón","1 diente de ajo","3 cdas aceite de oliva + extra para servir","Sal, comino molido","Pimentón para decorar","Palitos de zanahoria, pepino y apio"],"en":["400g cooked chickpeas (1 can)","3 tbsp tahini","Juice of 1 lemon","1 garlic clove","3 tbsp olive oil + extra to serve","Salt, ground cumin","Paprika to garnish","Carrot, cucumber and celery sticks"]}',
'{"es":["Escurre los garbanzos y reserva el líquido","Tritura garbanzos, tahini, limón, ajo, aceite y sal con una batidora","Añade líquido de los garbanzos hasta obtener la textura deseada","Sirve en bol con aceite, pimentón y crudités al lado"],"en":["Drain chickpeas and reserve the liquid","Blend chickpeas, tahini, lemon, garlic, oil and salt","Add chickpea liquid until desired consistency","Serve in bowl with oil, paprika and crudités on the side"]}'
),

('pisto_manchego_med',224,'lunch','🍅',
'{"es":"Pisto manchego con huevo","en":"Spanish ratatouille with egg","fr":"Pisto manchego avec oeuf","it":"Pisto manchego con uovo"}',
'{"es":"Calabacín, pimiento y tomate al estilo mediterráneo con huevo pochado encima","en":"Courgette, pepper and tomato Mediterranean style with poached egg on top"}',
10,25,320,14,22,18,7,
ARRAY['mediterranean','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','lose_weight','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["1 calabacín en dados","1 pimiento rojo en dados","1 pimiento verde en dados","400g tomate triturado","1 cebolla en dados","2 dientes de ajo","2 cdas aceite de oliva","2 huevos","Sal, pimienta, comino"],"en":["1 courgette diced","1 red pepper diced","1 green pepper diced","400g crushed tomato","1 onion diced","2 garlic cloves","2 tbsp olive oil","2 eggs","Salt, pepper, cumin"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 3 min","Añade los pimientos y el calabacín, saltea 8 min","Incorpora el tomate, sal, pimienta y comino","Cuece a fuego medio 12-15 min hasta que espese","Haz huecos y añade los huevos, tapa 4-5 min hasta cuajar"],"en":["Sauté onion and garlic in oil 3 min","Add peppers and courgette, cook 8 min","Add crushed tomato, salt, pepper and cumin","Cook over medium heat 12-15 min until thick","Make wells and add eggs, cover 4-5 min until set"]}'
),

('fattoush_ensalada_med',225,'lunch','🥗',
'{"es":"Fattoush con pan de pita crujiente","en":"Fattoush with crispy pita","fr":"Fattoush au pain pita croustillant","it":"Fattoush con pita croccante"}',
'{"es":"Ensalada levantina con verduras frescas, sumac y pan de pita tostado","en":"Levantine salad with fresh vegetables, sumac and toasted pita bread"}',
12,8,340,9,42,14,6,
ARRAY['mediterranean','vegetarian','vegan','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','lose_weight'],
ARRAY['pcos'],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["2 panes de pita pequeños","3 tomates en dados","1 pepino en dados","1 pimiento rojo en dados","4 rábanos laminados","Hojas de lechuga romana","3 cdas aceite de oliva","2 cdas zumo de limón","1 cdta sumac","Menta fresca, perejil, sal"],"en":["2 small pita breads","3 tomatoes diced","1 cucumber diced","1 red pepper diced","4 radishes sliced","Romaine lettuce leaves","3 tbsp olive oil","2 tbsp lemon juice","1 tsp sumac","Fresh mint, parsley, salt"]}',
'{"es":["Parte el pita en trozos y tuesta en horno a 200°C 7-8 min hasta crujiente","Mezcla las verduras en un bol grande","Aliña con aceite, limón, sumac y sal","Añade el pita tostado justo antes de servir para que no se ablande","Decora con menta y perejil fresco"],"en":["Tear pita into pieces and toast in oven at 200°C 7-8 min until crispy","Mix vegetables in a large bowl","Dress with oil, lemon, sumac and salt","Add toasted pita just before serving so it stays crispy","Garnish with fresh mint and parsley"]}'
),

('pollo_harissa_cous_med',226,'dinner','🌶️',
'{"es":"Pollo con harissa y cuscús","en":"Harissa chicken with couscous","fr":"Poulet harissa et couscous","it":"Pollo harissa con cuscus"}',
'{"es":"Pollo especiado al estilo del Magreb con cuscús integral y menta fresca","en":"Spiced North African chicken with wholegrain couscous and fresh mint"}',
10,20,490,38,46,12,5,
ARRAY['mediterranean','high_protein','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['gluten'],
'easy','20_40','low',
'{"es":["2 contramuslos de pollo sin hueso","2 cdas harissa (pasta de chile)","1 cdta comino","1 cdta cilantro molido","180g cuscús integral","300ml caldo de pollo","1 cda aceite de oliva","Menta fresca, limón, sal"],"en":["2 boneless chicken thighs","2 tbsp harissa paste","1 tsp cumin","1 tsp ground coriander","180g wholegrain couscous","300ml chicken broth","1 tbsp olive oil","Fresh mint, lemon, salt"]}',
'{"es":["Mezcla harissa, comino, cilantro y aceite. Cubre el pollo","Cocina el pollo en sartén 8-10 min por lado","Vierte el caldo hirviendo sobre el cuscús, tapa 5 min y esponja con tenedor","Sirve el pollo sobre el cuscús con menta y limón"],"en":["Mix harissa, cumin, coriander and oil. Coat chicken","Cook chicken in pan 8-10 min per side","Pour boiling broth over couscous, cover 5 min and fluff with fork","Serve chicken over couscous with mint and lemon"]}'
),

('tabbouleh_med',227,'lunch','🌿',
'{"es":"Tabbouleh de bulgur con menta","en":"Bulgur tabbouleh with mint","fr":"Taboulé de boulgour à la menthe","it":"Tabbouleh di bulgur con menta"}',
'{"es":"Ensalada levantina de bulgur y hierbas frescas — ligera, antiinflamatoria y llena de sabor","en":"Levantine bulgur and fresh herb salad — light, anti-inflammatory and full of flavour"}',
15,10,290,8,48,8,6,
ARRAY['mediterranean','vegan','vegetarian','anti_inflammatory','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight','energy'],
ARRAY['endometriosis','pcos'],
ARRAY['gluten'],
'easy','under_20','low',
'{"es":["150g bulgur fino","Agua hirviendo para cubrir el bulgur","4 tomates en dados pequeños","1 pepino en dados pequeños","1 manojo de perejil fresco picado","10 hojas de menta fresca picada","3 cdas aceite de oliva","Zumo de 2 limones","Sal, pimienta"],"en":["150g fine bulgur","Boiling water to cover","4 tomatoes finely diced","1 cucumber finely diced","1 bunch fresh parsley chopped","10 fresh mint leaves chopped","3 tbsp olive oil","Juice of 2 lemons","Salt, pepper"]}',
'{"es":["Cubre el bulgur con agua hirviendo, tapa y deja reposar 10 min","Escurre bien el bulgur y deja enfriar","Mezcla con el tomate, pepino, perejil y menta","Aliña con aceite, limón, sal y pimienta","Refrigera 15 min antes de servir para que se integren los sabores"],"en":["Cover bulgur with boiling water, cover and rest 10 min","Drain bulgur well and let cool","Mix with tomato, cucumber, parsley and mint","Dress with oil, lemon, salt and pepper","Refrigerate 15 min before serving to let flavours meld"]}'
),

('berenjenas_asadas_med',228,'dinner','🍆',
'{"es":"Berenjenas asadas con yogur de ajo","en":"Roasted aubergines with garlic yoghurt","fr":"Aubergines rôties au yaourt à l''ail","it":"Melanzane arrosto con yogurt all''aglio"}',
'{"es":"Berenjenas al horno con aliño de yogur, ajo y menta — plato turco-mediterráneo","en":"Oven-roasted aubergines with yoghurt, garlic and mint dressing — Turkish-Mediterranean"}',
5,30,280,8,22,16,8,
ARRAY['mediterranean','vegetarian','gluten_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','lose_weight'],
ARRAY['endometriosis','pcos'],
ARRAY['dairy'],
'easy','20_40','low',
'{"es":["2 berenjenas medianas","3 cdas aceite de oliva","150g yogur griego","2 dientes de ajo rallados","Zumo de 1/2 limón","Menta fresca picada","Pimentón ahumado, sal, pimienta","Semillas de granada (opcional)"],"en":["2 medium aubergines","3 tbsp olive oil","150g Greek yoghurt","2 garlic cloves grated","Juice of 1/2 lemon","Fresh mint chopped","Smoked paprika, salt, pepper","Pomegranate seeds (optional)"]}',
'{"es":["Corta las berenjenas en mitades, marca la pulpa en cuadrícula","Pincela con aceite, sal y pimentón","Hornea a 200°C 25-30 min hasta tiernas y doradas","Mezcla el yogur con ajo rallado, limón y sal","Sirve las berenjenas con el yogur y menta fresca encima"],"en":["Halve the aubergines and score the flesh in a grid","Brush with oil, salt and paprika","Roast at 200°C 25-30 min until tender and golden","Mix yoghurt with grated garlic, lemon and salt","Serve aubergines topped with yoghurt and fresh mint"]}'
),

('shakshuka_med',229,'breakfast','🍳',
'{"es":"Shakshuka de tomate y pimiento","en":"Tomato and pepper shakshuka","fr":"Shakshuka tomates et poivrons","it":"Shakshuka di pomodoro e peperoni"}',
'{"es":"Huevos pochados en salsa especiada de tomate — el desayuno mediterráneo por excelencia","en":"Eggs poached in spiced tomato sauce — the quintessential Mediterranean breakfast"}',
5,20,320,16,20,18,5,
ARRAY['mediterranean','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['endometriosis','pcos'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["2 huevos","400g tomate triturado","1 pimiento rojo en dados","1 cebolla en dados","2 dientes de ajo","1 cdta comino","1 cdta pimentón","1/2 cdta guindilla (opcional)","2 cdas aceite de oliva","Perejil o cilantro fresco, sal"],"en":["2 eggs","400g crushed tomato","1 red pepper diced","1 onion diced","2 garlic cloves","1 tsp cumin","1 tsp paprika","1/2 tsp chilli (optional)","2 tbsp olive oil","Fresh parsley or coriander, salt"]}',
'{"es":["Sofríe la cebolla, el ajo y el pimiento en aceite 5 min","Añade las especias y cocina 1 min más","Incorpora el tomate y cuece 8-10 min hasta espesar","Haz huecos y rompe los huevos dentro","Tapa y cuece 4-5 min hasta que la clara esté cuajada","Sirve con pan o solo, decorado con hierbas frescas"],"en":["Sauté onion, garlic and pepper in oil 5 min","Add spices and cook 1 min more","Add tomato and cook 8-10 min until thick","Make wells and crack eggs in","Cover and cook 4-5 min until whites are set","Serve with bread or on its own, garnished with fresh herbs"]}'
),

('lentejas_espinacas_med',230,'lunch','🌱',
'{"es":"Lentejas con espinacas y limón","en":"Lentils with spinach and lemon","fr":"Lentilles aux épinards et citron","it":"Lenticchie con spinaci e limone"}',
'{"es":"Potaje de lentejas rojas con espinacas al estilo del Medio Oriente — proteína vegetal completa","en":"Red lentil stew with spinach Middle Eastern style — complete plant protein"}',
5,25,380,18,52,8,12,
ARRAY['mediterranean','vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['pcos','endometriosis','anemia'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas rojas","100g espinacas frescas o congeladas","1 cebolla en dados","3 dientes de ajo","1 cdta comino","1 cdta cúrcuma","Zumo de 1 limón","2 cdas aceite de oliva","700ml caldo de verduras","Sal, pimienta"],"en":["200g red lentils","100g fresh or frozen spinach","1 onion diced","3 garlic cloves","1 tsp cumin","1 tsp turmeric","Juice of 1 lemon","2 tbsp olive oil","700ml vegetable broth","Salt, pepper"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade el comino y la cúrcuma, cocina 1 min","Incorpora las lentejas y el caldo, cuece 20 min","Añade las espinacas los últimos 3 min","Exprime el limón, ajusta de sal y sirve"],"en":["Sauté onion and garlic in oil 4 min","Add cumin and turmeric, cook 1 min","Add lentils and broth, cook 20 min","Add spinach in the last 3 min","Squeeze in lemon, adjust salt and serve"]}'
),

-- ── PESCATARIAN ──────────────────────────────────────────────────────────────

('gambas_ajillo_med',231,'dinner','🦐',
'{"es":"Gambas al ajillo mediterráneas","en":"Mediterranean garlic prawns","fr":"Crevettes à l''ail méditerranéennes","it":"Gamberi all''aglio mediterranei"}',
'{"es":"Gambas salteadas con ajo, guindilla y vino blanco — listo en 10 minutos","en":"Prawns sautéed with garlic, chilli and white wine — ready in 10 minutes"}',
5,10,280,28,4,16,1,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','low_carb','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["300g gambas peladas","4 dientes de ajo laminados","1 guindilla seca","4 cdas aceite de oliva","50ml vino blanco seco","Zumo de 1/2 limón","Perejil fresco picado","Sal, pimienta"],"en":["300g peeled prawns","4 garlic cloves sliced","1 dried chilli","4 tbsp olive oil","50ml dry white wine","Juice of 1/2 lemon","Fresh parsley chopped","Salt, pepper"]}',
'{"es":["Calienta el aceite con el ajo y la guindilla a fuego medio hasta que el ajo empiece a dorarse","Sube el fuego y añade las gambas, saltea 2 min","Añade el vino blanco y deja evaporar 1 min","Exprime el limón, añade el perejil y sirve inmediatamente"],"en":["Heat oil with garlic and chilli over medium heat until garlic starts to colour","Turn up heat and add prawns, sauté 2 min","Add white wine and let evaporate 1 min","Squeeze in lemon, add parsley and serve immediately"]}'
),

('atun_tomate_med',232,'lunch','🐟',
'{"es":"Ensalada de atún con tomate y alcaparras","en":"Tuna salad with tomato and capers","fr":"Salade de thon tomate-câpres","it":"Insalata di tonno con pomodori e capperi"}',
'{"es":"Ensalada mediterránea de atún con tomates cherry, aceitunas y alcaparras","en":"Mediterranean tuna salad with cherry tomatoes, olives and capers"}',
10,0,340,30,12,18,4,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','low_carb','anti_inflammatory'],
ARRAY['follicular','luteal'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['pcos'],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["2 latas de atún en aceite de oliva (160g escurrido)","200g tomates cherry en mitades","50g aceitunas negras","2 cdas alcaparras","1/2 cebolla roja laminada","Hojas de rúcula o lechuga","3 cdas aceite de oliva","1 cda vinagre de vino tinto","Sal, pimienta, orégano"],"en":["2 cans tuna in olive oil (160g drained)","200g cherry tomatoes halved","50g black olives","2 tbsp capers","1/2 red onion sliced","Rocket or lettuce leaves","3 tbsp olive oil","1 tbsp red wine vinegar","Salt, pepper, oregano"]}',
'{"es":["Escurre el atún y desmenúzalo en un bol","Añade los tomates, aceitunas, alcaparras y cebolla roja","Coloca sobre una cama de rúcula","Aliña con aceite, vinagre, orégano, sal y pimienta"],"en":["Drain tuna and flake into a bowl","Add tomatoes, olives, capers and red onion","Place over a bed of rocket","Dress with oil, vinegar, oregano, salt and pepper"]}'
),

('bacalao_pisto_med',233,'dinner','🐟',
'{"es":"Bacalao al horno sobre pisto","en":"Baked cod over ratatouille","fr":"Cabillaud rôti sur ratatouille","it":"Merluzzo al forno su ratatouille"}',
'{"es":"Lomo de bacalao jugoso al horno sobre cama de verduras mediterráneas","en":"Juicy baked cod fillet over a bed of Mediterranean vegetables"}',
10,25,360,36,18,14,6,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','lose_weight','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 lomos de bacalao (180g c/u)","1 calabacín en dados","1 pimiento rojo en dados","200g tomate cherry","1 cebolla en dados","3 dientes de ajo","3 cdas aceite de oliva","Tomillo, romero, sal, pimienta","Zumo de limón"],"en":["2 cod fillets (180g each)","1 courgette diced","1 red pepper diced","200g cherry tomatoes","1 onion diced","3 garlic cloves","3 tbsp olive oil","Thyme, rosemary, salt, pepper","Lemon juice"]}',
'{"es":["Sofríe la cebolla, el ajo, el pimiento y el calabacín en aceite 8 min","Añade los tomates cherry y las hierbas, cuece 5 min más","Coloca el bacalao encima de las verduras","Riega con aceite y zumo de limón","Hornea a 200°C 15-18 min"],"en":["Sauté onion, garlic, pepper and courgette in oil 8 min","Add cherry tomatoes and herbs, cook 5 min more","Place cod on top of the vegetables","Drizzle with oil and lemon juice","Bake at 200°C 15-18 min"]}'
),

('ceviche_clasico_pesc',234,'lunch','🍋',
'{"es":"Ceviche de merluza clásico","en":"Classic hake ceviche","fr":"Ceviche de merlu classique","it":"Ceviche di nasello classico"}',
'{"es":"Pescado marinado en limón con cebolla morada, cilantro y ají — fresco y proteico","en":"Fish marinated in lime with red onion, coriander and chilli — fresh and protein-packed"}',
20,0,220,30,8,6,2,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'medium','under_20','medium',
'{"es":["400g merluza fresca en dados de 1cm","Zumo de 4 limas (o limones)","1/2 cebolla morada en juliana fina","1 ají o guindilla fresca en rodajas","Cilantro fresco picado","Sal, pimienta","Aguacate y chips de maíz para acompañar (opcional)"],"en":["400g fresh hake diced 1cm","Juice of 4 limes","1/2 red onion finely julienned","1 fresh chilli sliced","Fresh coriander chopped","Salt, pepper","Avocado and corn chips to serve (optional)"]}',
'{"es":["Mezcla el pescado con la cebolla, el ají y el zumo de lima","Añade sal y pimienta, mezcla bien","Marina en la nevera 15-20 min (el ácido cocina el pescado)","Añade el cilantro justo antes de servir","Sirve frío con aguacate"],"en":["Mix fish with onion, chilli and lime juice","Add salt and pepper, mix well","Marinate in fridge 15-20 min (the acid cooks the fish)","Add coriander just before serving","Serve cold with avocado"]}'
),

('mejillones_vapor_pesc',235,'dinner','🦪',
'{"es":"Mejillones al vapor con vino blanco y perejil","en":"Steamed mussels with white wine and parsley","fr":"Moules vapeur vin blanc-persil","it":"Cozze al vapore con vino bianco e prezzemolo"}',
'{"es":"Mejillones al vapor en salsa de vino blanco y ajo — económicos, proteicos y deliciosos","en":"Steamed mussels in white wine and garlic sauce — cheap, protein-rich and delicious"}',
10,8,260,28,10,8,1,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','mediterranean'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','muscle','energy'],
ARRAY['anemia'],
ARRAY['shellfish'],
'easy','under_20','low',
'{"es":["1kg mejillones frescos limpios","3 dientes de ajo laminados","150ml vino blanco seco","2 cdas aceite de oliva","Perejil fresco picado abundante","1/2 limón","Pimienta negra"],"en":["1kg fresh mussels cleaned","3 garlic cloves sliced","150ml dry white wine","2 tbsp olive oil","Plenty of fresh parsley chopped","1/2 lemon","Black pepper"]}',
'{"es":["Sofríe el ajo en aceite 1-2 min en una olla grande","Añade el vino blanco y lleva a ebullición","Incorpora los mejillones, tapa y cuece 4-5 min agitando la olla","Descarta los mejillones que no se hayan abierto","Sirve con el caldo, perejil fresco y un chorro de limón"],"en":["Sauté garlic in oil 1-2 min in a large pot","Add white wine and bring to a boil","Add mussels, cover and cook 4-5 min shaking the pot","Discard any mussels that have not opened","Serve with the broth, fresh parsley and a squeeze of lemon"]}'
),

('salmon_miso_jengibre_pesc',236,'dinner','🐠',
'{"es":"Salmón glaseado con miso y jengibre","en":"Miso and ginger glazed salmon","fr":"Saumon glacé miso-gingembre","it":"Salmone glassato al miso e zenzero"}',
'{"es":"Filete de salmón con glaseado umami de miso blanco y jengibre fresco","en":"Salmon fillet with white miso and fresh ginger umami glaze"}',
5,15,440,36,12,26,1,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['pcos','endometriosis'],
ARRAY['fish','soy'],
'easy','under_20','high',
'{"es":["2 filetes de salmón (160g c/u)","2 cdas miso blanco (shiro miso)","1 cda mirin","1 cda salsa de soja o tamari","1 cdta jengibre fresco rallado","1 cda aceite de sésamo","Semillas de sésamo y cebolleta verde para servir"],"en":["2 salmon fillets (160g each)","2 tbsp white miso (shiro miso)","1 tbsp mirin","1 tbsp soy sauce or tamari","1 tsp fresh ginger grated","1 tbsp sesame oil","Sesame seeds and spring onion to serve"]}',
'{"es":["Mezcla el miso, mirin, tamari, jengibre y aceite de sésamo","Cubre los filetes con el glaseado y deja marinar 10 min","Cocina en sartén a fuego medio 4-5 min por lado","Sirve con semillas de sésamo y cebolleta verde"],"en":["Mix miso, mirin, tamari, ginger and sesame oil","Coat fillets with the glaze and marinate 10 min","Cook in pan over medium heat 4-5 min per side","Serve with sesame seeds and spring onion"]}'
),

('pasta_gambas_tomate_pesc',237,'dinner','🍝',
'{"es":"Pasta con gambas y tomate cherry","en":"Pasta with prawns and cherry tomatoes","fr":"Pâtes aux crevettes et tomates cerises","it":"Pasta con gamberi e pomodorini"}',
'{"es":"Pasta rápida con gambas salteadas, tomate cherry y ajo — cena mediterránea en 20 min","en":"Quick pasta with sautéed prawns, cherry tomatoes and garlic — Mediterranean dinner in 20 min"}',
5,18,510,34,62,12,4,
ARRAY['pescatarian','mediterranean','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','shellfish'],
'easy','20_40','medium',
'{"es":["150g pasta espagueti o linguine","200g gambas peladas","200g tomates cherry en mitades","3 dientes de ajo laminados","3 cdas aceite de oliva","50ml vino blanco","Guindilla en copos (opcional)","Perejil fresco, sal, pimienta"],"en":["150g spaghetti or linguine","200g peeled prawns","200g cherry tomatoes halved","3 garlic cloves sliced","3 tbsp olive oil","50ml white wine","Chilli flakes (optional)","Fresh parsley, salt, pepper"]}',
'{"es":["Cuece la pasta al dente, reserva 1/2 taza del agua","Sofríe el ajo con guindilla en aceite 1-2 min","Añade las gambas, saltea 2 min. Retira","Añade los tomates cherry y el vino, cuece 5 min","Mezcla la pasta con la salsa y las gambas. Añade agua de pasta si necesitas"],"en":["Cook pasta al dente, reserve 1/2 cup water","Sauté garlic and chilli in oil 1-2 min","Add prawns, sauté 2 min. Remove","Add cherry tomatoes and wine, cook 5 min","Toss pasta with sauce and prawns. Add pasta water if needed"]}'
),

('tartar_salmon_pesc',238,'lunch','🐟',
'{"es":"Tartar de salmón con aguacate","en":"Salmon tartare with avocado","fr":"Tartare de saumon à l''avocat","it":"Tartare di salmone con avocado"}',
'{"es":"Tartar fresco de salmón salvaje con aguacate cremoso, alcaparras y cebolleta","en":"Fresh wild salmon tartare with creamy avocado, capers and spring onion"}',
15,0,380,28,8,26,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','paleo','keto','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['pcos','endometriosis'],
ARRAY['fish'],
'medium','under_20','high',
'{"es":["250g salmón fresco para sushi en dados pequeños","1 aguacate maduro en dados","1 cdta alcaparras picadas","2 cebolletas en rodajas finas","1 cdta mostaza de Dijon","2 cdas aceite de oliva","Zumo de 1/2 limón","Sal, pimienta, eneldo fresco"],"en":["250g sushi-grade fresh salmon diced small","1 ripe avocado diced","1 tsp capers chopped","2 spring onions thinly sliced","1 tsp Dijon mustard","2 tbsp olive oil","Juice of 1/2 lemon","Salt, pepper, fresh dill"]}',
'{"es":["Mezcla el salmón con la mostaza, el aceite, el limón y las alcaparras","Sazona con sal, pimienta y eneldo","Mezcla el aguacate por separado con un poco de limón y sal","Monta el tartar: base de aguacate y salmón encima","Decora con cebolleta y eneldo"],"en":["Mix salmon with mustard, oil, lemon and capers","Season with salt, pepper and dill","Mash avocado separately with a little lemon and salt","Plate: avocado base and salmon on top","Garnish with spring onion and dill"]}'
),

('merluza_verduras_horno_pesc',239,'dinner','🐟',
'{"es":"Merluza al horno con verduras de temporada","en":"Baked hake with seasonal vegetables","fr":"Merlu au four et légumes de saison","it":"Nasello al forno con verdure di stagione"}',
'{"es":"Merluza al horno con pimiento, calabacín y tomate — cena completa en una sola bandeja","en":"Baked hake with pepper, courgette and tomato — complete dinner on one tray"}',
10,22,320,34,14,12,5,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','lose_weight','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["2 lomos de merluza (170g c/u)","1 pimiento rojo en tiras","1 calabacín en rodajas","200g tomates cherry","1 cebolla en gajos","3 cdas aceite de oliva","Zumo de 1 limón","Tomillo, perejil, ajo en polvo, sal, pimienta"],"en":["2 hake fillets (170g each)","1 red pepper in strips","1 courgette sliced","200g cherry tomatoes","1 onion in wedges","3 tbsp olive oil","Juice of 1 lemon","Thyme, parsley, garlic powder, salt, pepper"]}',
'{"es":["Coloca las verduras en una bandeja, aliña con aceite, sal y hierbas","Hornea a 200°C 10 min","Coloca la merluza encima de las verduras","Riega con limón y un poco más de aceite","Hornea 12-15 min más hasta que el pescado esté listo"],"en":["Place vegetables in a tray, dress with oil, salt and herbs","Bake at 200°C 10 min","Place hake on top of the vegetables","Drizzle with lemon and a little more oil","Bake 12-15 min more until fish is done"]}'
),

('bowl_atun_arroz_pesc',240,'lunch','🍚',
'{"es":"Bowl de atún con arroz y aguacate","en":"Tuna rice bowl with avocado","fr":"Bowl thon riz-avocat","it":"Bowl di tonno con riso e avocado"}',
'{"es":"Bowl proteico de atún fresco, arroz, aguacate y edamame estilo poke","en":"Protein poke-style bowl with fresh tuna, rice, avocado and edamame"}',
10,15,520,36,54,14,6,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','soy'],
'easy','20_40','high',
'{"es":["200g arroz para sushi cocido","150g atún fresco en dados","1/2 aguacate en láminas","80g edamame cocido","1/4 pepino en rodajas","1 cdta sésamo","2 cdas salsa de soja o tamari","1 cdta aceite de sésamo","Zumo de 1/2 lima"],"en":["200g cooked sushi rice","150g fresh tuna diced","1/2 avocado sliced","80g cooked edamame","1/4 cucumber sliced","1 tsp sesame","2 tbsp soy sauce or tamari","1 tsp sesame oil","Juice of 1/2 lime"]}',
'{"es":["Coloca el arroz en el fondo del bowl","Distribuye el atún, aguacate, edamame y pepino encima","Mezcla la salsa de soja, aceite de sésamo y lima","Vierte la salsa sobre el bowl","Espolvorea sésamo y sirve"],"en":["Place rice in the bottom of the bowl","Arrange tuna, avocado, edamame and cucumber on top","Mix soy sauce, sesame oil and lime","Drizzle sauce over the bowl","Sprinkle sesame and serve"]}'
),

('tortilla_gambas_pesc',241,'lunch','🥚',
'{"es":"Tortilla de gambas y cebolleta","en":"Prawn and spring onion omelette","fr":"Omelette crevettes-ciboulette","it":"Frittata di gamberi e cipollotto"}',
'{"es":"Tortilla jugosa rellena de gambas salteadas y cebolleta fresca — proteína pura","en":"Juicy omelette filled with sautéed prawns and fresh spring onion — pure protein"}',
5,8,320,32,4,18,1,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','shellfish'],
'easy','under_20','medium',
'{"es":["3 huevos","120g gambas peladas","2 cebolletas en rodajas","1 cda aceite de oliva","Sal, pimienta","Perejil o eneldo fresco"],"en":["3 eggs","120g peeled prawns","2 spring onions sliced","1 tbsp olive oil","Salt, pepper","Fresh parsley or dill"]}',
'{"es":["Saltea las gambas con un poco de aceite 2-3 min. Reserva","Bate los huevos con sal y pimienta","En la misma sartén, vierte los huevos batidos a fuego medio","Cuando empiece a cuajar añade gambas y cebolleta","Dobla la tortilla y sirve con hierbas frescas"],"en":["Sauté prawns with a little oil 2-3 min. Set aside","Beat eggs with salt and pepper","In the same pan, pour beaten eggs over medium heat","When starting to set add prawns and spring onion","Fold omelette and serve with fresh herbs"]}'
),

('vieiras_pure_guisante_pesc',242,'dinner','🦪',
'{"es":"Vieiras a la plancha con puré de guisante","en":"Seared scallops with pea purée","fr":"Saint-Jacques poêlées et purée de petits pois","it":"Capesante scottate con purée di piselli"}',
'{"es":"Vieiras doradas a la plancha sobre puré cremoso de guisante y menta","en":"Golden pan-seared scallops over creamy pea and mint purée"}',
10,10,310,28,18,12,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['shellfish'],
'medium','under_20','high',
'{"es":["8 vieiras frescas","200g guisantes congelados","1 cda aceite de oliva","1 cda mantequilla (opcional)","Hojas de menta fresca","Zumo de 1/2 limón","Sal, pimienta","Microgreens para decorar"],"en":["8 fresh scallops","200g frozen peas","1 tbsp olive oil","1 tbsp butter (optional)","Fresh mint leaves","Juice of 1/2 lemon","Salt, pepper","Microgreens to garnish"]}',
'{"es":["Cuece los guisantes 3 min en agua salada. Escurre","Tritura los guisantes con menta, limón, sal y un poco de aceite hasta obtener un puré suave","Seca bien las vieiras y sazóna con sal y pimienta","Dora en sartén muy caliente 1-2 min por lado hasta que estén doradas","Sirve las vieiras sobre el puré decoradas con microgreens"],"en":["Cook peas 3 min in salted water. Drain","Blend peas with mint, lemon, salt and a little oil until smooth purée","Pat scallops dry and season with salt and pepper","Sear in very hot pan 1-2 min per side until golden","Serve scallops over purée garnished with microgreens"]}'
),

('ensalada_nicoise_pesc',243,'lunch','🥗',
'{"es":"Ensalada Niçoise con atún fresco","en":"Niçoise salad with fresh tuna","fr":"Salade Niçoise au thon frais","it":"Insalata Nizzarda con tonno fresco"}',
'{"es":"La clásica ensalada de Niza con atún fresco, judías verdes, huevo y anchoas","en":"The classic Nice salad with fresh tuna, green beans, egg and anchovies"}',
15,12,420,34,22,20,6,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'medium','20_40','medium',
'{"es":["200g atún fresco en filete","100g judías verdes","2 huevos cocidos en mitades","100g tomates cherry","50g aceitunas negras","4 anchoas en aceite","Lechuga de roble o romana","3 cdas aceite de oliva","1 cda vinagre de vino tinto","Mostaza de Dijon, sal, pimienta"],"en":["200g fresh tuna fillet","100g green beans","2 boiled eggs halved","100g cherry tomatoes","50g black olives","4 anchovy fillets in oil","Oak leaf or romaine lettuce","3 tbsp olive oil","1 tbsp red wine vinegar","Dijon mustard, salt, pepper"]}',
'{"es":["Cuece las judías verdes 4 min en agua salada. Enfría en agua con hielo","Marca el atún en sartén muy caliente 2 min por lado (debe quedar rosado)","Prepara la vinagreta con aceite, vinagre, mostaza, sal y pimienta","Monta la ensalada con la lechuga, verduras, huevos, aceitunas y anchoas","Coloca el atún en lonchas encima y aliña"],"en":["Cook green beans 4 min in salted water. Refresh in ice water","Sear tuna in very hot pan 2 min per side (should remain pink)","Make vinaigrette with oil, vinegar, mustard, salt and pepper","Build salad with lettuce, vegetables, eggs, olives and anchovies","Place sliced tuna on top and dress"]}'
),

('brochetas_camarones_med',244,'dinner','🍢',
'{"es":"Brochetas de langostinos con chimichurri","en":"King prawn skewers with chimichurri","fr":"Brochettes de langoustines chimichurri","it":"Spiedini di gamberi al chimichurri"}',
'{"es":"Langostinos a la plancha en brocheta con salsa chimichurri de hierbas frescas","en":"Grilled king prawns on skewers with fresh herb chimichurri sauce"}',
15,8,260,26,4,14,2,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','paleo','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["400g langostinos pelados","3 cdas aceite de oliva","Ajo en polvo, pimentón, sal, pimienta","Para el chimichurri: perejil, ajo, orégano, aceite de oliva, vinagre de vino rojo, guindilla, sal"],"en":["400g king prawns peeled","3 tbsp olive oil","Garlic powder, paprika, salt, pepper","For chimichurri: parsley, garlic, oregano, olive oil, red wine vinegar, chilli, salt"]}',
'{"es":["Prepara el chimichurri picando finamente el perejil, el ajo, el orégano y mezcla con aceite, vinagre y guindilla","Marina los langostinos con aceite, ajo en polvo, pimentón, sal y pimienta","Ensarta en brochetas y cocina a la plancha 2-3 min por lado","Sirve con el chimichurri por encima"],"en":["Make chimichurri by finely chopping parsley, garlic, oregano and mixing with oil, vinegar and chilli","Marinate prawns with oil, garlic powder, paprika, salt and pepper","Thread onto skewers and grill 2-3 min per side","Serve with chimichurri drizzled over"]}'
),

('dorada_papillote_med',245,'dinner','🐟',
'{"es":"Dorada al papillote con limón y tomillo","en":"Sea bream en papillote with lemon and thyme","fr":"Daurade en papillote citron-thym","it":"Orata al cartoccio con limone e timo"}',
'{"es":"Dorada entera al papillote con aromáticas mediterráneas — jugosa y sin esfuerzo","en":"Whole sea bream en papillote with Mediterranean aromatics — juicy and effortless"}',
10,25,340,38,4,18,2,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','low_carb','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['endometriosis'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["1 dorada entera limpia (aprox 400g)","1 limón en rodajas","4 ramas de tomillo fresco","3 dientes de ajo laminados","2 cdas aceite de oliva","Sal, pimienta negra","Papel de horno o papel de aluminio"],"en":["1 whole cleaned sea bream (approx 400g)","1 lemon sliced","4 fresh thyme sprigs","3 garlic cloves sliced","2 tbsp olive oil","Salt, black pepper","Parchment or aluminium foil"]}',
'{"es":["Precalienta el horno a 200°C","Coloca la dorada sobre papel de horno, rellena el interior con limón, tomillo y ajo","Riega con aceite, sal y pimienta","Cierra el papillote herméticamente y hornea 22-25 min","Abre en la mesa para que salga todo el aroma"],"en":["Preheat oven to 200°C","Place sea bream on parchment, fill cavity with lemon, thyme and garlic","Drizzle with oil, salt and pepper","Seal papillote tightly and bake 22-25 min","Open at the table so all the aroma escapes"]}'
),

('risotto_gambas_med',246,'dinner','🍚',
'{"es":"Risotto de gambas y azafrán","en":"Prawn and saffron risotto","fr":"Risotto aux crevettes et safran","it":"Risotto con gamberi e zafferano"}',
'{"es":"Risotto cremoso de arroz arborio con gambas y el color dorado del azafrán","en":"Creamy arborio rice risotto with prawns and the golden colour of saffron"}',
5,30,520,28,68,12,2,
ARRAY['pescatarian','mediterranean','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['shellfish','dairy'],
'medium','20_40','medium',
'{"es":["200g arroz arborio","200g gambas peladas","1 cebolla en dados finos","1 diente de ajo","100ml vino blanco seco","700ml caldo de pescado caliente","1 sobre de azafrán","2 cdas mantequilla","2 cdas aceite de oliva","Sal, pimienta, perejil fresco"],"en":["200g arborio rice","200g peeled prawns","1 onion finely diced","1 garlic clove","100ml dry white wine","700ml hot fish broth","1 sachet saffron","2 tbsp butter","2 tbsp olive oil","Salt, pepper, fresh parsley"]}',
'{"es":["Disuelve el azafrán en un poco de caldo caliente","Sofríe la cebolla y el ajo en aceite y mantequilla 3 min","Añade el arroz y tuesta 2 min","Incorpora el vino y deja evaporar","Añade el caldo cazo a cazo removiendo constantemente hasta que el arroz lo absorba (18-20 min)","Añade las gambas los últimos 3 min. Manteca con un poco de mantequilla"],"en":["Dissolve saffron in a little hot broth","Sauté onion and garlic in oil and butter 3 min","Add rice and toast 2 min","Add wine and let evaporate","Add broth ladle by ladle stirring constantly until absorbed (18-20 min)","Add prawns in the last 3 min. Finish with a knob of butter"]}'
),

('bocadillo_caballa_med',247,'lunch','🫓',
'{"es":"Tosta de caballa ahumada con remolacha","en":"Smoked mackerel toast with beetroot","fr":"Toast de maquereau fumé et betterave","it":"Toast di sgombro affumicato con barbabietola"}',
'{"es":"Tosta con caballa ahumada, remolacha, queso fresco y rúcula — omega-3 y sabor","en":"Toast with smoked mackerel, beetroot, cream cheese and rocket — omega-3 and flavour"}',
8,0,360,24,28,16,4,
ARRAY['pescatarian','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY['fish','gluten','dairy'],
'easy','under_20','low',
'{"es":["2 rebanadas de pan de centeno o integral","150g caballa ahumada desmenuzada","80g remolacha cocida en láminas","2 cdas queso fresco batido","Rúcula fresca","Zumo de limón","Cebollino picado","Pimienta negra"],"en":["2 slices rye or wholegrain bread","150g smoked mackerel flaked","80g cooked beetroot sliced","2 tbsp soft cream cheese","Fresh rocket","Lemon juice","Chopped chives","Black pepper"]}',
'{"es":["Tuesta el pan","Unta el queso fresco sobre cada rebanada","Coloca las láminas de remolacha encima","Distribuye la caballa ahumada desmenuzada","Añade la rúcula, el zumo de limón, el cebollino y pimienta"],"en":["Toast the bread","Spread cream cheese on each slice","Layer the beetroot slices on top","Distribute the flaked smoked mackerel","Add rocket, lemon juice, chives and pepper"]}'
),

('sardinas_pan_tomate_med',248,'lunch','🐟',
'{"es":"Sardinas en pan con tomate","en":"Sardines on tomato bread","fr":"Sardines sur pain à la tomate","it":"Sardine su pane al pomodoro"}',
'{"es":"Sardinas asadas o en conserva sobre pan con tomate al estilo catalán — omega-3 puro","en":"Grilled or tinned sardines on Catalan tomato bread — pure omega-3"}',
5,8,380,26,32,14,3,
ARRAY['pescatarian','mediterranean','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['fish','gluten'],
'easy','under_20','low',
'{"es":["200g sardinas (frescas o en conserva en aceite de oliva)","2 rebanadas de pan de masa madre","2 tomates maduros para frotar","1 diente de ajo","3 cdas aceite de oliva","Sal gruesa","Perejil o rúcula para servir"],"en":["200g sardines (fresh or tinned in olive oil)","2 slices sourdough bread","2 ripe tomatoes to rub","1 garlic clove","3 tbsp olive oil","Coarse salt","Parsley or rocket to serve"]}',
'{"es":["Tuesta el pan. Frota con ajo y luego con el tomate cortado por la mitad","Riega con aceite de oliva y sal gruesa","Si son sardinas frescas, ásalas en plancha 3-4 min por lado","Coloca las sardinas sobre el pan con tomate","Sirve con perejil o rúcula y un chorro de limón"],"en":["Toast bread. Rub with garlic then with tomato halved","Drizzle with olive oil and coarse salt","If using fresh sardines, grill 3-4 min per side","Place sardines on the tomato bread","Serve with parsley or rocket and a squeeze of lemon"]}'
),

('sopa_pescado_azafran_med',249,'dinner','🍲',
'{"es":"Sopa de pescado al azafrán","en":"Saffron fish soup","fr":"Soupe de poisson au safran","it":"Zuppa di pesce allo zafferano"}',
'{"es":"Caldo de pescado aromático con azafrán, tomate y trozos de pescado blanco — reconfortante","en":"Aromatic fish broth with saffron, tomato and chunks of white fish — comforting"}',
10,25,300,32,16,10,3,
ARRAY['pescatarian','mediterranean','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','lose_weight','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['fish'],
'medium','20_40','medium',
'{"es":["400g pescado blanco (merluza, rape o bacalao) en dados","1 puerro en rodajas","2 tomates en dados","2 dientes de ajo","1 sobre de azafrán","750ml caldo de pescado","100ml vino blanco","2 cdas aceite de oliva","Sal, pimienta","Perejil fresco"],"en":["400g white fish (hake, monkfish or cod) diced","1 leek sliced","2 tomatoes diced","2 garlic cloves","1 sachet saffron","750ml fish broth","100ml white wine","2 tbsp olive oil","Salt, pepper","Fresh parsley"]}',
'{"es":["Sofríe el puerro y el ajo en aceite 4 min","Añade el tomate y cuece 3 min","Incorpora el vino, deja reducir 2 min","Añade el caldo y el azafrán, lleva a ebullición","Incorpora el pescado y cuece 8-10 min a fuego suave","Sirve con perejil fresco"],"en":["Sauté leek and garlic in oil 4 min","Add tomato and cook 3 min","Add wine, reduce 2 min","Add broth and saffron, bring to a boil","Add fish and cook 8-10 min over low heat","Serve with fresh parsley"]}'
),

('poke_salmon_pesc',250,'lunch','🍱',
'{"es":"Poke bowl de salmón con mango","en":"Salmon and mango poke bowl","fr":"Poke bowl saumon-mangue","it":"Poke bowl di salmone e mango"}',
'{"es":"Bowl fresco de salmón marinado, mango, arroz y edamame — proteína y sabor tropical","en":"Fresh bowl of marinated salmon, mango, rice and edamame — protein and tropical flavour"}',
12,15,530,34,56,14,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','soy'],
'easy','20_40','high',
'{"es":["200g salmón fresco en dados","1/2 mango en dados","180g arroz para sushi cocido","70g edamame cocido","1/4 pepino en rodajas","1 cda salsa de soja o tamari","1 cda aceite de sésamo","Zumo de 1/2 lima","Semillas de sésamo, aguacate en láminas"],"en":["200g fresh salmon diced","1/2 mango diced","180g cooked sushi rice","70g cooked edamame","1/4 cucumber sliced","1 tbsp soy sauce or tamari","1 tbsp sesame oil","Juice of 1/2 lime","Sesame seeds, sliced avocado"]}',
'{"es":["Marina el salmón con tamari, aceite de sésamo y lima 5 min","Coloca el arroz en el fondo del bowl","Distribuye el salmón, el mango, el edamame, el pepino y el aguacate","Espolvorea sésamo y sirve con el resto del marinado como salsa"],"en":["Marinate salmon with tamari, sesame oil and lime 5 min","Place rice in the bottom of the bowl","Arrange salmon, mango, edamame, cucumber and avocado","Sprinkle sesame and serve remaining marinade as sauce"]}'
)

ON CONFLICT (id) DO NOTHING;
