-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 13 (20) — display_order 371-390
-- Cierre definitivo: low_fodmap (+17), pescatarian (+7), mediterranean (+2), paleo (+1)
-- Muchas recetas llevan tags múltiples para cubrir todo en un solo lote
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── LOW FODMAP + PESCATARIAN ──────────────────────────────────────────────────

('trucha_limon_fodmap',371,'dinner','🐟',
'{"es":"Trucha al horno con limón y cebollino (low FODMAP)","en":"Baked trout with lemon and chives (low FODMAP)","fr":"Truite au four citron et ciboulette (low FODMAP)","it":"Trota al forno con limone ed erba cipollina (low FODMAP)"}',
'{"es":"Trucha entera o en filetes al horno, con limón y cebollino verde — digestiva, omega-3 y sin irritantes","en":"Whole or fillet trout baked with lemon and green chives — digestive, omega-3 and no triggers"}',
5,18,380,34,2,24,1,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','keto','paleo','high_protein','low_carb'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["2 filetes de trucha (o 1 trucha entera)","Zumo de 2 limones","Ralladura de 1 limón","Cebollino verde picado abundante (solo la parte verde)","3 cdas aceite de oliva","Eneldo fresco","Sal, pimienta blanca"],"en":["2 trout fillets (or 1 whole trout)","Juice of 2 lemons","Zest of 1 lemon","Plenty of chopped green chives (green part only)","3 tbsp olive oil","Fresh dill","Salt, white pepper"]}',
'{"es":["Precalienta el horno a 190°C","Coloca la trucha en bandeja con papel","Mezcla el zumo, la ralladura, el aceite, el cebollino y el eneldo","Vierte sobre el pescado y sazona con sal y pimienta","Hornea 16-18 min hasta que la carne se desmigue fácilmente","Sirve inmediatamente con más cebollino fresco"],"en":["Preheat oven to 190°C","Place trout on lined tray","Mix juice, zest, oil, chives and dill","Pour over fish and season with salt and pepper","Bake 16-18 min until flesh flakes easily","Serve immediately with more fresh chives"]}'
),

('bacalao_tomate_zanahoria_fodmap',372,'dinner','🐟',
'{"es":"Bacalao en salsa de tomate y zanahoria (low FODMAP)","en":"Cod in tomato and carrot sauce (low FODMAP)","fr":"Cabillaud sauce tomate et carotte (low FODMAP)","it":"Baccala in salsa di pomodoro e carote (low FODMAP)"}',
'{"es":"Bacalao fresco cocinado en salsa ligera de tomate sin cebolla ni ajo — digestivo y reconfortante","en":"Fresh cod cooked in light tomato sauce without onion or garlic — digestive and comforting"}',
8,20,360,32,16,14,5,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','mediterranean','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["2 lomos de bacalao fresco","400g tomate triturado (sin cebolla ni ajo añadidos)","2 zanahorias en rodajas finas","2 cdas aceite de ajo infusionado","1 cdta orégano","1 cdta pimentón","Sal, pimienta","Cebollino verde, perejil fresco"],"en":["2 fresh cod loins","400g crushed tomato (no added onion or garlic)","2 carrots thinly sliced","2 tbsp garlic-infused oil","1 tsp oregano","1 tsp paprika","Salt, pepper","Green chives, fresh parsley"]}',
'{"es":["Calienta el aceite infusionado en sartén ancha","Añade la zanahoria y sofríe 4 min","Incorpora el tomate, el orégano y el pimentón, cuece 6 min a fuego medio","Coloca el bacalao sobre la salsa, tapa y cuece 10-12 min","Sirve con cebollino verde y perejil fresco"],"en":["Heat infused oil in a wide pan","Add carrot and sauté 4 min","Add tomato, oregano and paprika, cook 6 min over medium heat","Place cod on the sauce, cover and cook 10-12 min","Serve with green chives and fresh parsley"]}'
),

('gambas_calabacin_fodmap',373,'dinner','🦐',
'{"es":"Gambas con calabacín y tomate (low FODMAP)","en":"Prawns with courgette and tomato (low FODMAP)","fr":"Crevettes courgette et tomate (low FODMAP)","it":"Gamberi con zucchine e pomodoro (low FODMAP)"}',
'{"es":"Salteado rápido low FODMAP de gambas, calabacín y tomate cherry con aceite infusionado","en":"Quick low FODMAP sauté of prawns, courgette and cherry tomato with infused oil"}',
5,10,300,24,10,16,3,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','keto','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['sibo','ibs'],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["250g gambas peladas","1 calabacín en dados","150g tomates cherry en mitades","2 cdas aceite de ajo infusionado","Zumo de 1/2 limón","Albahaca fresca","Sal, pimienta"],"en":["250g peeled prawns","1 courgette diced","150g cherry tomatoes halved","2 tbsp garlic-infused oil","Juice of 1/2 lemon","Fresh basil","Salt, pepper"]}',
'{"es":["Calienta el aceite infusionado en sartén a fuego alto","Saltea el calabacín 3 min, añade los tomates cherry y cocina 2 min más","Incorpora las gambas y saltea 2-3 min hasta que estén rosadas","Exprime el limón, añade la albahaca y sazona","Sirve inmediatamente"],"en":["Heat infused oil in pan over high heat","Sauté courgette 3 min, add cherry tomatoes and cook 2 min more","Add prawns and sauté 2-3 min until pink","Squeeze lemon, add basil and season","Serve immediately"]}'
),

('salmón_patata_vapor_fodmap',374,'dinner','🐠',
'{"es":"Salmón y patatas al vapor con salsa de limón y eneldo (low FODMAP)","en":"Steamed salmon and potatoes with lemon dill sauce (low FODMAP)","fr":"Saumon et pommes de terre vapeur sauce citron-aneth (low FODMAP)","it":"Salmone e patate al vapore con salsa al limone e aneto (low FODMAP)"}',
'{"es":"Duo clásico low FODMAP: salmón y patatas al vapor con salsa ligera de limón, aceite y eneldo","en":"Classic low FODMAP duo: steamed salmon and potatoes with light lemon, oil and dill sauce"}',
5,22,460,34,36,14,4,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 filetes de salmón","2 patatas medianas en dados","Para la salsa: 3 cdas aceite de oliva, zumo de 1 limón, eneldo fresco picado, cebollino verde, sal, pimienta"],"en":["2 salmon fillets","2 medium potatoes diced","For sauce: 3 tbsp olive oil, juice of 1 lemon, chopped fresh dill, green chives, salt, pepper"]}',
'{"es":["Coloca las patatas en la cesta del vapor","Cuece 10 min, luego añade el salmón encima","Cuece 12-14 min más hasta que el salmón esté listo y las patatas tiernas","Mezcla todos los ingredientes de la salsa","Sirve el salmón y las patatas con la salsa por encima"],"en":["Place potatoes in the steamer basket","Steam 10 min, then add salmon on top","Steam 12-14 min more until salmon is done and potatoes tender","Mix all sauce ingredients","Serve salmon and potatoes with sauce drizzled over"]}'
),

('atún_pimiento_arroz_fodmap',375,'lunch','🍚',
'{"es":"Bol de arroz con atún y pimiento asado (low FODMAP)","en":"Rice bowl with tuna and roasted pepper (low FODMAP)","fr":"Bowl de riz thon et poivron roti (low FODMAP)","it":"Bowl di riso con tonno e peperone arrostito (low FODMAP)"}',
'{"es":"Bol completo low FODMAP: arroz basmati, atún, pimiento asado y aceite infusionado","en":"Complete low FODMAP bowl: basmati rice, tuna, roasted pepper and infused oil"}',
8,15,440,28,54,10,4,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','high_protein','mediterranean'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy','muscle'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["150g arroz basmati","2 latas de atún en aceite de oliva","1 pimiento rojo asado (de conserva o casero, sin ajo)","Hojas de rúcula o espinacas","2 cdas aceite de ajo infusionado","Zumo de 1/2 limón","Cebollino verde picado","Sal, pimienta, orégano"],"en":["150g basmati rice","2 cans tuna in olive oil","1 roasted red pepper (jarred or homemade, no garlic)","Rocket or spinach leaves","2 tbsp garlic-infused oil","Juice of 1/2 lemon","Chopped green chives","Salt, pepper, oregano"]}',
'{"es":["Cuece el arroz basmati","Prepara la vinagreta con el aceite infusionado, el limón, el orégano, sal y pimienta","Monta el bol: arroz, rúcula, atún desmenuzado, pimiento asado en tiras","Riega con la vinagreta y decora con cebollino verde"],"en":["Cook basmati rice","Make dressing with infused oil, lemon, oregano, salt and pepper","Build bowl: rice, rocket, flaked tuna, roasted pepper strips","Drizzle with dressing and garnish with green chives"]}'
),

('caldo_pescado_verduras_fodmap',376,'dinner','🍲',
'{"es":"Caldo de pescado con verduras (low FODMAP)","en":"Fish broth with vegetables (low FODMAP)","fr":"Bouillon de poisson aux legumes (low FODMAP)","it":"Brodo di pesce con verdure (low FODMAP)"}',
'{"es":"Caldo reconfortante low FODMAP: pescado blanco, zanahoria, apio y patata en caldo suave","en":"Comforting low FODMAP broth: white fish, carrot, celery and potato in gentle stock"}',
8,22,300,26,24,8,4,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["300g merluza o bacalao fresco en dados","2 zanahorias en rodajas","2 tallos de apio en rodajas","1 patata en dados","1L caldo de pescado sin cebolla ni ajo","2 cdas aceite de ajo infusionado","Sal, pimienta blanca","Perejil fresco, cebollino verde"],"en":["300g hake or fresh cod diced","2 carrots sliced","2 celery stalks sliced","1 potato diced","1L fish stock no onion or garlic","2 tbsp garlic-infused oil","Salt, white pepper","Fresh parsley, green chives"]}',
'{"es":["Calienta el caldo con el aceite infusionado","Añade la zanahoria, el apio y la patata, cuece 12 min","Incorpora el pescado en dados y cuece 6-8 min más hasta que esté listo","Sazona con sal y pimienta blanca","Sirve con perejil fresco y cebollino verde"],"en":["Heat stock with infused oil","Add carrot, celery and potato, cook 12 min","Add diced fish and cook 6-8 min more until done","Season with salt and white pepper","Serve with fresh parsley and green chives"]}'
),

('dorada_limon_papillote_fodmap',377,'dinner','🐡',
'{"es":"Dorada en papillote con limón y hierbas (low FODMAP)","en":"Sea bream in papillote with lemon and herbs (low FODMAP)","fr":"Daurade en papillote citron et herbes (low FODMAP)","it":"Orata al cartoccio con limone ed erbe (low FODMAP)"}',
'{"es":"Dorada en papillote low FODMAP: todo el sabor concentrado sin cebolla, sin irritantes","en":"Low FODMAP papillote sea bream: all the flavour concentrated without onion or triggers"}',
8,20,380,34,4,22,2,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','mediterranean','paleo','keto','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 doradas limpias (o 2 filetes)","1 limón en rodajas","Eneldo y perejil frescos","3 cdas aceite de oliva","Cebollino verde","Sal gruesa, pimienta","1 tomate en rodajas (opcional)"],"en":["2 cleaned sea breams (or 2 fillets)","1 lemon sliced","Fresh dill and parsley","3 tbsp olive oil","Green chives","Coarse salt, pepper","1 tomato sliced (optional)"]}',
'{"es":["Precalienta el horno a 200°C","Coloca cada dorada sobre un trozo grande de papel de horno","Rellena el interior con limón, eneldo y cebollino","Riega con aceite de oliva, sazona con sal gruesa y pimienta","Cierra bien el papillote y hornea 18-20 min","Abre en la mesa para que el cliente disfrute del vapor"],"en":["Preheat oven to 200°C","Place each sea bream on a large piece of baking paper","Stuff inside with lemon, dill and chives","Drizzle with olive oil, season with coarse salt and pepper","Seal the papillote tightly and bake 18-20 min","Open at the table so the steam is released"]}'
),

-- ── LOW FODMAP PUROS ──────────────────────────────────────────────────────────

('wrap_pavo_lechuga_fodmap',378,'lunch','🥬',
'{"es":"Wrap de pavo en lechuga con mostaza (low FODMAP)","en":"Turkey lettuce wrap with mustard (low FODMAP)","fr":"Wrap de dinde en laitue moutarde (low FODMAP)","it":"Wrap di tacchino in lattuga con senape (low FODMAP)"}',
'{"es":"Almuerzo express low FODMAP: fiambre de pavo, mostaza, pepino y zanahoria en hojas de lechuga","en":"Express low FODMAP lunch: turkey deli meat, mustard, cucumber and carrot in lettuce leaves"}',
8,0,260,22,8,14,3,
ARRAY['low_fodmap','gluten_free','lactose_free','low_carb','keto','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['sibo','ibs'],
ARRAY['mustard'],
'easy','under_20','low',
'{"es":["6 hojas grandes de lechuga iceberg o romana","120g fiambre de pavo en lonchas (sin aditivos con cebolla o ajo)","1 cdta mostaza de Dijon","1/2 pepino en bastones","1 zanahoria rallada","Cebollino verde picado","Pimienta negra"],"en":["6 large iceberg or romaine lettuce leaves","120g sliced turkey deli meat (no additives with onion or garlic)","1 tsp Dijon mustard","1/2 cucumber in sticks","1 grated carrot","Chopped green chives","Black pepper"]}',
'{"es":["Unta cada hoja de lechuga con un poco de mostaza","Coloca las lonchas de pavo encima","Distribuye el pepino, la zanahoria y el cebollino","Sazona con pimienta negra","Dobla como un taco y come inmediatamente"],"en":["Spread a little mustard on each lettuce leaf","Place turkey slices on top","Distribute cucumber, carrot and chives","Season with black pepper","Fold like a taco and eat immediately"]}'
),

('arroz_calabacin_huevo_fodmap',379,'lunch','🥚',
'{"es":"Arroz salteado con calabacín y huevo (low FODMAP)","en":"Stir-fried rice with courgette and egg (low FODMAP)","fr":"Riz saute courgette et oeuf (low FODMAP)","it":"Riso saltato con zucchine e uova (low FODMAP)"}',
'{"es":"Versión low FODMAP del arroz frito: sin cebolla ni ajo, con calabacín, huevo y aceite infusionado","en":"Low FODMAP version of fried rice: no onion or garlic, with courgette, egg and infused oil"}',
5,12,380,14,54,10,3,
ARRAY['low_fodmap','gluten_free','lactose_free','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY['sibo','ibs'],
ARRAY['eggs','soy'],
'easy','under_20','low',
'{"es":["200g arroz cocido (del día anterior es ideal)","1 calabacín en dados pequeños","2 huevos batidos","2 cdas aceite de ajo infusionado","1 cda tamari sin gluten","Cebollino verde picado","Sal, pimienta","Sésamo tostado (opcional)"],"en":["200g cooked rice (day-old is ideal)","1 courgette finely diced","2 beaten eggs","2 tbsp garlic-infused oil","1 tbsp gluten-free tamari","Chopped green chives","Salt, pepper","Toasted sesame (optional)"]}',
'{"es":["Calienta el aceite infusionado en wok o sartén grande a fuego muy alto","Saltea el calabacín 3 min","Aparta hacia un lado, vierte los huevos batidos y revuelve hasta cuajar","Añade el arroz y el tamari, saltea todo 3 min a fuego alto","Sirve con cebollino verde y sésamo"],"en":["Heat infused oil in wok or large pan over very high heat","Sauté courgette 3 min","Push to one side, pour in beaten eggs and scramble until set","Add rice and tamari, stir-fry everything 3 min over high heat","Serve with green chives and sesame"]}'
),

('pechuga_rellena_espinacas_fodmap',380,'dinner','🍗',
'{"es":"Pechuga rellena de espinacas y queso (low FODMAP)","en":"Chicken breast stuffed with spinach and cheese (low FODMAP)","fr":"Blanc de poulet farci epinards et fromage (low FODMAP)","it":"Petto di pollo ripieno di spinaci e formaggio (low FODMAP)"}',
'{"es":"Pechuga abierta en mariposa, rellena de espinacas y queso curado bajo en lactosa — low FODMAP elegante","en":"Butterflied chicken breast stuffed with spinach and aged low-lactose cheese — elegant low FODMAP"}',
10,22,460,44,4,28,2,
ARRAY['low_fodmap','gluten_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY['sibo','ibs'],
ARRAY['dairy','eggs'],
'medium','20_40','medium',
'{"es":["2 pechugas de pollo grandes","100g espinacas baby salteadas y escurridas","50g parmesano o cheddar curado rallado","Sal, pimienta","1 cdta orégano","2 cdas aceite de ajo infusionado","Palillos para cerrar"],"en":["2 large chicken breasts","100g sautéed and drained baby spinach","50g grated parmesan or aged cheddar","Salt, pepper","1 tsp oregano","2 tbsp garlic-infused oil","Toothpicks to seal"]}',
'{"es":["Precalienta el horno a 200°C","Corta las pechugas en mariposa (por el centro sin llegar al final)","Sazona el interior con sal, pimienta y orégano","Rellena con las espinacas y el queso","Cierra con palillos y sella en sartén con el aceite 3 min por lado","Hornea 15-18 min hasta que estén cocidas"],"en":["Preheat oven to 200°C","Butterfly the chicken breasts (cut through centre without going all the way)","Season inside with salt, pepper and oregano","Fill with spinach and cheese","Seal with toothpicks and sear in pan with oil 3 min per side","Bake 15-18 min until cooked through"]}'
),

('crema_patata_puerro_verde_fodmap',381,'dinner','🥔',
'{"es":"Vichyssoise low FODMAP (solo la parte verde del puerro)","en":"Low FODMAP vichyssoise (green leek tops only)","fr":"Vichyssoise low FODMAP (vert de poireau uniquement)","it":"Vichyssoise low FODMAP (solo il verde del porro)"}',
'{"es":"Vichyssoise adaptada low FODMAP: solo las hojas verdes del puerro (toleradas) con patata y caldo suave","en":"Low FODMAP adapted vichyssoise: only green leek tops (tolerated) with potato and gentle stock"}',
8,22,280,6,42,10,4,
ARRAY['low_fodmap','gluten_free','lactose_free','vegan','vegetarian'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["Solo las hojas verdes de 2 puerros (las hojas verdes oscuras son low FODMAP, descartar la parte blanca)","2 patatas medianas en dados","800ml caldo de verduras sin cebolla ni ajo","2 cdas aceite de oliva","Sal, pimienta blanca","Cebollino verde para decorar"],"en":["Green tops only of 2 leeks (dark green leaves are low FODMAP, discard the white part)","2 medium potatoes diced","800ml vegetable stock no onion or garlic","2 tbsp olive oil","Salt, white pepper","Green chives to garnish"]}',
'{"es":["Sofríe las hojas verdes del puerro en aceite 3-4 min","Añade las patatas y el caldo","Cuece 18 min hasta que las patatas estén muy tiernas","Tritura hasta obtener una crema fina","Ajusta de sal y pimienta blanca","Sirve fría o templada con cebollino verde"],"en":["Sauté green leek tops in oil 3-4 min","Add potatoes and stock","Cook 18 min until potatoes are very tender","Blend until smooth","Adjust salt and white pepper","Serve cold or warm with green chives"]}'
),

('pasta_atun_alcaparras_fodmap',382,'dinner','🍝',
'{"es":"Pasta de arroz con atún y alcaparras (low FODMAP)","en":"Rice pasta with tuna and capers (low FODMAP)","fr":"Pates de riz thon et capres (low FODMAP)","it":"Pasta di riso con tonno e capperi (low FODMAP)"}',
'{"es":"Pasta sin gluten low FODMAP con atún, alcaparras y tomate fresco — sabores mediterráneos sin irritantes","en":"Gluten-free low FODMAP pasta with tuna, capers and fresh tomato — Mediterranean flavours without triggers"}',
8,12,460,26,58,12,4,
ARRAY['low_fodmap','pescatarian','gluten_free','lactose_free','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["150g pasta de arroz","2 latas de atún en aceite de oliva","2 cdas alcaparras","2 tomates maduros en dados","2 cdas aceite de ajo infusionado","Zumo de 1/2 limón","Albahaca fresca","Sal, pimienta negra"],"en":["150g rice pasta","2 cans tuna in olive oil","2 tbsp capers","2 ripe tomatoes diced","2 tbsp garlic-infused oil","Juice of 1/2 lemon","Fresh basil","Salt, black pepper"]}',
'{"es":["Cuece la pasta de arroz según instrucciones, escurre","En una sartén calienta el aceite infusionado","Añade el tomate y cocina 3-4 min hasta que se ablande","Incorpora el atún desmenuzado, las alcaparras y el zumo de limón","Mezcla con la pasta caliente y la albahaca fresca","Sazona y sirve"],"en":["Cook rice pasta according to instructions, drain","Heat infused oil in a pan","Add tomato and cook 3-4 min until softened","Add flaked tuna, capers and lemon juice","Toss with hot pasta and fresh basil","Season and serve"]}'
),

('ensalada_rúcula_naranja_fodmap',383,'lunch','🍊',
'{"es":"Ensalada de rúcula con naranja y nueces (low FODMAP)","en":"Rocket salad with orange and walnuts (low FODMAP)","fr":"Salade de roquette orange et noix (low FODMAP)","it":"Insalata di rucola con arancia e noci (low FODMAP)"}',
'{"es":"Ensalada ligera low FODMAP: rúcula, gajos de naranja, nueces tostadas y vinagreta de limón","en":"Light low FODMAP salad: rocket, orange segments, toasted walnuts and lemon dressing"}',
8,0,280,6,22,18,4,
ARRAY['low_fodmap','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','menstrual'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs','anemia'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["80g rúcula","1 naranja grande en gajos (sin la membrana)","30g nueces tostadas","Para la vinagreta: 2 cdas aceite de oliva, 1 cda zumo de limón, 1 cdta mostaza de Dijon, sal, pimienta"],"en":["80g rocket","1 large orange in segments (without membrane)","30g toasted walnuts","For dressing: 2 tbsp olive oil, 1 tbsp lemon juice, 1 tsp Dijon mustard, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando todos sus ingredientes","Coloca la rúcula en un bol","Añade los gajos de naranja y las nueces","Riega con la vinagreta justo antes de servir"],"en":["Prepare dressing by mixing all ingredients","Place rocket in a bowl","Add orange segments and walnuts","Drizzle with dressing just before serving"]}'
),

('yogur_sin_lactosa_fruta_fodmap',384,'breakfast','🍓',
'{"es":"Yogur sin lactosa con frutos rojos y copos de avena (low FODMAP)","en":"Lactose-free yogurt with berries and oat flakes (low FODMAP)","fr":"Yaourt sans lactose fruits rouges et flocons d''avoine (low FODMAP)","it":"Yogurt senza lattosio con frutti rossi e fiocchi d''avena (low FODMAP)"}',
'{"es":"Desayuno low FODMAP sencillo y rápido: yogur sin lactosa, frutos rojos tolerados y avena sin gluten","en":"Simple and quick low FODMAP breakfast: lactose-free yogurt, tolerated berries and gluten-free oats"}',
3,0,280,12,40,8,4,
ARRAY['low_fodmap','gluten_free','lactose_free','vegetarian'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["200g yogur natural sin lactosa","100g fresas o arándanos frescos (tolerados en low FODMAP en porciones normales)","30g copos de avena sin gluten","1 cda semillas de chía","1 cdta sirope de arce","Canela al gusto"],"en":["200g plain lactose-free yogurt","100g fresh strawberries or blueberries (tolerated in low FODMAP at normal portions)","30g gluten-free oat flakes","1 tbsp chia seeds","1 tsp maple syrup","Cinnamon to taste"]}',
'{"es":["Coloca el yogur en un bol","Añade los frutos rojos encima","Espolvorea los copos de avena y las semillas de chía","Riega con el sirope de arce y espolvorea canela"],"en":["Place yogurt in a bowl","Add berries on top","Sprinkle oat flakes and chia seeds","Drizzle with maple syrup and sprinkle cinnamon"]}'
),

('pollo_paprika_arroz_fodmap',385,'dinner','🍗',
'{"es":"Pollo al pimentón con arroz y pimiento rojo (low FODMAP)","en":"Paprika chicken with rice and red pepper (low FODMAP)","fr":"Poulet au paprika riz et poivron rouge (low FODMAP)","it":"Pollo alla paprica con riso e peperone rosso (low FODMAP)"}',
'{"es":"Pollo sabroso low FODMAP marinado en pimentón con arroz y pimiento — sin cebolla ni ajo real","en":"Flavourful low FODMAP chicken marinated in paprika with rice and pepper — no real onion or garlic"}',
10,25,460,34,52,10,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g muslos de pollo deshuesados en dados","150g arroz basmati","1 pimiento rojo en tiras","2 cdtas pimentón dulce","1 cdta pimentón ahumado","2 cdas aceite de ajo infusionado","Sal, pimienta","Cebollino verde, perejil fresco"],"en":["300g boneless chicken thighs diced","150g basmati rice","1 red pepper in strips","2 tsp sweet paprika","1 tsp smoked paprika","2 tbsp garlic-infused oil","Salt, pepper","Green chives, fresh parsley"]}',
'{"es":["Mezcla el pollo con el pimentón, sal, pimienta y la mitad del aceite infusionado, marina 10 min","Cuece el arroz basmati","Dora el pollo a fuego alto en el resto del aceite 6-7 min","Añade el pimiento y cocina 4 min más","Sirve sobre el arroz con cebollino y perejil"],"en":["Mix chicken with paprika, salt, pepper and half the infused oil, marinate 10 min","Cook basmati rice","Brown chicken over high heat in remaining oil 6-7 min","Add pepper and cook 4 min more","Serve over rice with chives and parsley"]}'
),

-- ── MEDITERRANEAN + PALEO (cierre final) ──────────────────────────────────────

('lubina_salsa_verde_med',386,'dinner','🐟',
'{"es":"Lubina a la plancha con salsa verde mediterránea","en":"Grilled sea bass with Mediterranean green sauce","fr":"Loup de mer grille sauce verte mediterraneenne","it":"Branzino alla griglia con salsa verde mediterranea"}',
'{"es":"Lubina jugosa a la plancha con salsa verde de perejil, alcaparras y limón — paleo y mediterránea","en":"Juicy grilled sea bass with green parsley, caper and lemon sauce — paleo and Mediterranean"}',
8,12,400,36,4,26,2,
ARRAY['mediterranean','paleo','pescatarian','gluten_free','lactose_free','keto','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','under_20','high',
'{"es":["2 filetes de lubina","Para la salsa verde: 1 manojo de perejil, 2 cdas alcaparras, zumo de 1 limón, 1 diente de ajo, 4 cdas aceite de oliva, sal, pimienta","Aceite de oliva para cocinar","Sal gruesa"],"en":["2 sea bass fillets","For green sauce: 1 bunch parsley, 2 tbsp capers, juice of 1 lemon, 1 garlic clove, 4 tbsp olive oil, salt, pepper","Olive oil for cooking","Coarse salt"]}',
'{"es":["Tritura todos los ingredientes de la salsa verde hasta obtener una salsa texturizada (no muy fina)","Sazona la lubina con sal gruesa por la piel","Cocina en plancha muy caliente con aceite, piel hacia abajo, 4-5 min sin mover","Da la vuelta y cocina 2 min más","Sirve con la salsa verde encima"],"en":["Blend all green sauce ingredients into a textured sauce (not too smooth)","Season sea bass skin with coarse salt","Cook on very hot griddle with oil, skin side down, 4-5 min without moving","Flip and cook 2 min more","Serve with green sauce on top"]}'
),

('espárragos_prosciutto_med',387,'lunch','🥓',
'{"es":"Espárragos envueltos en prosciutto con parmesano","en":"Asparagus wrapped in prosciutto with parmesan","fr":"Asperges enveloppees de prosciutto parmesan","it":"Asparagi avvolti nel prosciutto con parmigiano"}',
'{"es":"Aperitivo o acompañamiento mediterráneo: espárragos crujientes con prosciutto y parmesano","en":"Mediterranean appetiser or side: crispy asparagus with prosciutto and parmesan"}',
5,10,280,20,6,20,3,
ARRAY['mediterranean','keto','gluten_free','low_carb','high_protein','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','medium',
'{"es":["400g espárragos verdes limpios","8 lonchas finas de prosciutto o jamón serrano","40g parmesano rallado","2 cdas aceite de oliva","Pimienta negra","Zumo de limón"],"en":["400g green asparagus trimmed","8 thin slices prosciutto or Iberian ham","40g grated parmesan","2 tbsp olive oil","Black pepper","Lemon juice"]}',
'{"es":["Precalienta el horno a 200°C o calienta una plancha","Envuelve cada 3-4 espárragos con una loncha de prosciutto","Coloca en bandeja, riega con aceite y espolvorea parmesano","Hornea 10-12 min o cocina en plancha 4-5 min girando","Termina con pimienta negra y zumo de limón"],"en":["Preheat oven to 200°C or heat a griddle","Wrap every 3-4 asparagus spears with a slice of prosciutto","Place on tray, drizzle with oil and sprinkle parmesan","Bake 10-12 min or cook on griddle 4-5 min turning","Finish with black pepper and lemon juice"]}'
),

('pulpo_patatas_med',388,'dinner','🐙',
'{"es":"Pulpo a la gallega con pimentón y aceite de oliva","en":"Galician-style octopus with paprika and olive oil","fr":"Poulpe a la galicienne paprika et huile d''olive","it":"Polpo alla galiziana con paprica e olio d''oliva"}',
'{"es":"Pulpo tierno sobre patata cocida con pimentón ahumado y aceite de oliva — clásico mediterráneo","en":"Tender octopus on boiled potato with smoked paprika and olive oil — Mediterranean classic"}',
5,50,380,32,28,10,3,
ARRAY['mediterranean','pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['shellfish'],
'medium','over_40','medium',
'{"es":["600g pulpo cocido (o fresco, que se cuece 40-45 min)","2 patatas medianas cocidas en rodajas gruesas","2 cdas aceite de oliva virgen extra","1 cdta pimentón dulce","1/2 cdta pimentón picante","Sal gruesa","Cebollino verde picado"],"en":["600g cooked octopus (or fresh, boiled 40-45 min)","2 medium potatoes boiled in thick slices","2 tbsp extra-virgin olive oil","1 tsp sweet paprika","1/2 tsp hot paprika","Coarse salt","Chopped green chives"]}',
'{"es":["Si el pulpo es fresco: congela y descongela para ablandarlo, luego cuece en agua hirviendo 40-45 min hasta tierno","Corta el pulpo en rodajas de 1-2 cm","Coloca las patatas en el fondo de la fuente","Distribuye el pulpo encima","Riega con aceite de oliva generoso, espolvorea ambos pimentones y sal gruesa","Sirve con cebollino verde"],"en":["If fresh octopus: freeze and thaw to tenderise, then boil in water 40-45 min until tender","Slice octopus into 1-2 cm rounds","Place potatoes on the bottom of the dish","Arrange octopus on top","Drizzle with generous olive oil, sprinkle both paprikas and coarse salt","Serve with green chives"]}'
),

('ensalada_lentejas_med',389,'lunch','🫘',
'{"es":"Ensalada tibia de lentejas con verduras mediterráneas","en":"Warm lentil salad with Mediterranean vegetables","fr":"Salade tiede de lentilles aux legumes mediterraneens","it":"Insalata tiepida di lenticchie con verdure mediterranee"}',
'{"es":"Lentejas tibias con pimiento asado, tomate, pepino y vinagreta de jerez — proteína vegetal mediterránea","en":"Warm lentils with roasted pepper, tomato, cucumber and sherry dressing — Mediterranean plant protein"}',
8,22,420,18,56,12,14,
ARRAY['mediterranean','vegan','vegetarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos','anemia'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["200g lentejas pardinas","1 pimiento rojo asado en tiras","150g tomates cherry en mitades","1/2 pepino en dados","Rúcula o espinacas","Para la vinagreta: 3 cdas aceite de oliva, 1 cda vinagre de jerez, 1 cdta comino, sal, pimienta","Perejil fresco"],"en":["200g green lentils","1 roasted red pepper in strips","150g cherry tomatoes halved","1/2 cucumber diced","Rocket or spinach","For dressing: 3 tbsp olive oil, 1 tbsp sherry vinegar, 1 tsp cumin, salt, pepper","Fresh parsley"]}',
'{"es":["Cuece las lentejas en agua con sal 18-20 min hasta tiernas pero enteras, escurre","Prepara la vinagreta mezclando todos sus ingredientes","Mezcla las lentejas tibias con el pimiento, el tomate y el pepino","Riega con la vinagreta y remueve bien","Sirve sobre rúcula con perejil fresco"],"en":["Cook lentils in salted water 18-20 min until tender but whole, drain","Prepare dressing by mixing all ingredients","Mix warm lentils with pepper, tomato and cucumber","Drizzle with dressing and toss well","Serve over rocket with fresh parsley"]}'
),

('pollo_romesco_med',390,'dinner','🍗',
'{"es":"Pollo con salsa romesco","en":"Chicken with romesco sauce","fr":"Poulet sauce romesco","it":"Pollo con salsa romesco"}',
'{"es":"Pollo jugoso con salsa romesco catalana: pimiento asado, almendra y tomate — mediterráneo puro","en":"Juicy chicken with Catalan romesco sauce: roasted pepper, almond and tomato — pure Mediterranean"}',
10,20,480,38,14,28,4,
ARRAY['mediterranean','gluten_free','lactose_free','high_protein','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['nuts'],
'medium','20_40','medium',
'{"es":["4 muslos de pollo deshuesados","Para el romesco: 2 pimientos rojos asados, 2 tomates asados, 50g almendras tostadas, 2 dientes de ajo asados, 3 cdas aceite de oliva, 1 cda vinagre de vino, 1 cdta pimentón ahumado, sal"],"en":["4 boneless chicken thighs","For romesco: 2 roasted red peppers, 2 roasted tomatoes, 50g toasted almonds, 2 roasted garlic cloves, 3 tbsp olive oil, 1 tbsp wine vinegar, 1 tsp smoked paprika, salt"]}',
'{"es":["Prepara el romesco triturando los pimientos asados, los tomates, las almendras, el ajo, el aceite, el vinagre y el pimentón hasta obtener una salsa texturizada","Sazona el pollo con sal y pimienta","Dora en sartén con aceite 6-7 min por lado","Cubre con la salsa romesco y cuece 5 min más a fuego bajo","Sirve con pan o patatas si no es paleo, o con verduras"],"en":["Make romesco by blending roasted peppers, tomatoes, almonds, garlic, oil, vinegar and paprika into a textured sauce","Season chicken with salt and pepper","Brown in pan with oil 6-7 min per side","Cover with romesco sauce and cook 5 min more over low heat","Serve with bread or potatoes if not paleo, or with vegetables"]}'
)

ON CONFLICT (id) DO NOTHING;
