-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 14b (26) — display_order 423-448
-- 26 recetas standard (cierre definitivo)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

('shakshuka_std',423,'breakfast','🍅',
'{"es":"Shakshuka con queso feta y pan de pita","en":"Shakshuka with feta and pita bread","fr":"Shakshuka feta et pain pita","it":"Shakshuka con feta e pane pita"}',
'{"es":"Huevos pochados en salsa de tomate especiada con comino, pimentón y queso feta desmenuzado","en":"Eggs poached in spiced tomato sauce with cumin, paprika and crumbled feta cheese"}',
5,18,420,20,32,22,5,
ARRAY['standard','vegetarian','gluten_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["4 huevos","800g tomate triturado","1 cebolla en dados","4 dientes de ajo","1 pimiento rojo en dados","1 cdta comino","1 cdta pimentón ahumado","1/2 cdta guindilla","80g queso feta desmenuzado","3 cdas aceite de oliva","Sal, cilantro o perejil fresco","Pan de pita para mojar"],"en":["4 eggs","800g crushed tomato","1 onion diced","4 garlic cloves","1 red pepper diced","1 tsp cumin","1 tsp smoked paprika","1/2 tsp chilli","80g crumbled feta","3 tbsp olive oil","Salt, fresh coriander or parsley","Pita bread for dipping"]}',
'{"es":["Sofríe la cebolla, el ajo y el pimiento en aceite 5 min","Añade el comino, el pimentón y la guindilla, cocina 1 min","Incorpora el tomate, sazona y cuece 8-10 min hasta espesar","Haz 4 huecos y rompe un huevo en cada uno","Tapa y cuece 4-5 min hasta que las claras estén cuajadas","Añade el feta y las hierbas, sirve con pita"],"en":["Sauté onion, garlic and pepper in oil 5 min","Add cumin, paprika and chilli, cook 1 min","Add tomato, season and cook 8-10 min until thick","Make 4 wells and crack one egg in each","Cover and cook 4-5 min until whites are set","Add feta and herbs, serve with pita"]}'
),

('cochinita_pibil_std',424,'dinner','🌮',
'{"es":"Cochinita pibil con tortillas y cebolla encurtida","en":"Cochinita pibil with tortillas and pickled onion","fr":"Cochinita pibil tortillas et oignons marines","it":"Cochinita pibil con tortillas e cipolle in agrodolce"}',
'{"es":"Cerdo marinado en achiote y naranja agria, cocinado lentamente hasta deshacerse — tacos mexicanos auténticos","en":"Pork marinated in achiote and sour orange, slow cooked until it falls apart — authentic Mexican tacos"}',
15,180,560,36,32,30,3,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','low',
'{"es":["600g paleta de cerdo","Para la marinada: 2 cdas pasta de achiote, zumo de 2 naranjas agrias (o mezcla naranja+limón), comino, orégano, ajo, sal","Hojas de plátano o papel de aluminio","Tortillas de maíz","Para la cebolla encurtida: cebolla morada, zumo de lima, sal, orégano"],"en":["600g pork shoulder","For marinade: 2 tbsp achiote paste, juice of 2 sour oranges (or orange+lemon mix), cumin, oregano, garlic, salt","Banana leaves or aluminium foil","Corn tortillas","For pickled onion: red onion, lime juice, salt, oregano"]}',
'{"es":["Marina el cerdo en la mezcla de achiote y cítricos mínimo 2 horas","Envuelve en hoja de plátano o aluminio con la marinada","Hornea a 150°C 2,5-3 horas hasta que la carne se deshaga","Desmenuza con dos tenedores","Prepara la cebolla encurtida con lima y sal 30 min antes","Sirve en tortillas con cebolla encurtida y cilantro"],"en":["Marinate pork in achiote and citrus mixture minimum 2 hours","Wrap in banana leaf or foil with marinade","Bake at 150°C 2.5-3 hours until meat falls apart","Shred with two forks","Make pickled onion with lime and salt 30 min before","Serve in tortillas with pickled onion and coriander"]}'
),

('boquerones_vinagre_std',425,'snack','🐟',
'{"es":"Boquerones en vinagre con ajo y perejil","en":"White anchovies in vinegar with garlic and parsley","fr":"Anchois marines vinaigre ail et persil","it":"Acciughe marinate con aglio e prezzemolo"}',
'{"es":"Tapa española clásica: boquerones frescos marinados en vinagre, ajo y perejil — aperitivo perfecto","en":"Classic Spanish tapa: fresh anchovies marinated in vinegar, garlic and parsley — perfect aperitivo"}',
15,0,220,20,2,14,1,
ARRAY['standard','gluten_free','lactose_free','pescatarian','low_carb','keto'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["400g boquerones frescos limpiados y en filetes","150ml vinagre de vino blanco","Zumo de 1 limón","3 dientes de ajo laminados","Perejil fresco picado abundante","4 cdas aceite de oliva virgen extra","Sal"],"en":["400g fresh anchovies cleaned and filleted","150ml white wine vinegar","Juice of 1 lemon","3 garlic cloves sliced","Plenty of chopped fresh parsley","4 tbsp extra-virgin olive oil","Salt"]}',
'{"es":["Coloca los filetes de boquerón en una fuente, cúbrelos con el vinagre y el limón","Refrigera mínimo 4-6 horas hasta que la carne esté blanca (marinado en ácido)","Escurre el vinagre, añade el aceite, el ajo y el perejil","Sazona con sal","Refrigera 1 hora más antes de servir"],"en":["Place anchovy fillets in a dish, cover with vinegar and lemon","Refrigerate minimum 4-6 hours until flesh is white (acid marinade)","Drain vinegar, add oil, garlic and parsley","Season with salt","Refrigerate 1 more hour before serving"]}'
),

('albóndigas_tomate_std',426,'dinner','🍝',
'{"es":"Albóndigas en salsa de tomate casera","en":"Meatballs in homemade tomato sauce","fr":"Boulettes de viande sauce tomate maison","it":"Polpette in salsa di pomodoro fatta in casa"}',
'{"es":"Albóndigas jugosas de ternera en salsa de tomate lenta — un plato que enamora a toda la familia","en":"Juicy beef meatballs in slow tomato sauce — a dish that wins over the whole family"}',
15,30,520,30,42,22,5,
ARRAY['standard','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs','dairy'],
'medium','20_40','low',
'{"es":["400g carne picada mixta (ternera y cerdo)","1 huevo","3 cdas pan rallado","2 cdas parmesano","1 diente de ajo picado","Perejil picado","Sal, pimienta","Para la salsa: 800g tomate triturado, 1 cebolla, 3 dientes de ajo, aceite, orégano, sal, azúcar","Pasta o pan para acompañar"],"en":["400g mixed mince (beef and pork)","1 egg","3 tbsp breadcrumbs","2 tbsp parmesan","1 garlic clove chopped","Chopped parsley","Salt, pepper","For sauce: 800g crushed tomato, 1 onion, 3 garlic cloves, oil, oregano, salt, sugar","Pasta or bread to serve"]}',
'{"es":["Mezcla la carne con el huevo, el pan rallado, el parmesano, el ajo, el perejil, sal y pimienta","Forma albóndigas del tamaño de una pelota de golf","Dóralas en aceite 3-4 min por todos los lados, reserva","Sofríe la cebolla y el ajo para la salsa, añade el tomate, el orégano y una pizca de azúcar, cuece 12 min","Incorpora las albóndigas a la salsa y cuece a fuego bajo 15 min","Sirve con pasta o pan y parmesano"],"en":["Mix mince with egg, breadcrumbs, parmesan, garlic, parsley, salt and pepper","Shape into golf ball-sized meatballs","Brown in oil 3-4 min on all sides, set aside","Sauté onion and garlic for sauce, add tomato, oregano and a pinch of sugar, cook 12 min","Add meatballs to sauce and cook over low heat 15 min","Serve with pasta or bread and parmesan"]}'
),

('pisto_huevo_std',427,'dinner','🍳',
'{"es":"Pisto manchego con huevo frito","en":"Manchego pisto with fried egg","fr":"Pisto manchego oeuf au plat","it":"Pisto manchego con uovo fritto"}',
'{"es":"El pisto más sabroso: calabacín, pimiento, berenjena y tomate en aceite de oliva, coronado de huevo frito","en":"The most flavourful pisto: courgette, pepper, aubergine and tomato in olive oil, topped with fried egg"}',
10,30,380,14,28,22,8,
ARRAY['standard','vegetarian','gluten_free','lactose_free'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["2 calabacines en dados","1 berenjena en dados","2 pimientos rojos en dados","1 pimiento verde en dados","800g tomate triturado","1 cebolla en dados","3 dientes de ajo","3 cdas aceite de oliva","Sal, pimienta, orégano","2 huevos fritos para servir","Azúcar (pizca)"],"en":["2 courgettes diced","1 aubergine diced","2 red peppers diced","1 green pepper diced","800g crushed tomato","1 onion diced","3 garlic cloves","3 tbsp olive oil","Salt, pepper, oregano","2 fried eggs to serve","Sugar (pinch)"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade los pimientos y la berenjena, cocina 8 min","Incorpora el calabacín y cocina 5 min más","Añade el tomate, el orégano, sal, pimienta y una pizca de azúcar","Cuece a fuego medio 15 min hasta que el pisto espese","Sirve con huevo frito encima y pan"],"en":["Sauté onion and garlic in oil 4 min","Add peppers and aubergine, cook 8 min","Add courgette and cook 5 min more","Add tomato, oregano, salt, pepper and a pinch of sugar","Cook over medium heat 15 min until pisto thickens","Serve with fried egg on top and bread"]}'
),

('fideuá_std',428,'dinner','🍝',
'{"es":"Fideuá de marisco","en":"Seafood fideuà","fr":"Fideuà aux fruits de mer","it":"Fideuà ai frutti di mare"}',
'{"es":"La fideuá valenciana: fideos finos con gambas, mejillones y calamar cocinados en caldo de marisco","en":"Valencian fideuà: thin noodles with prawns, mussels and squid cooked in seafood stock"}',
15,20,520,28,64,14,4,
ARRAY['standard','pescatarian','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['gluten','shellfish','fish'],
'medium','20_40','medium',
'{"es":["200g fideos del nº 2 o fideos para fideuá","200g gambas peladas","200g mejillones limpios","150g calamares en anillas","1 tomate rallado","1 cebolla en dados","3 dientes de ajo","700ml caldo de marisco caliente","Unas hebras de azafrán","Pimentón dulce","3 cdas aceite de oliva","Sal","Alioli para acompañar"],"en":["200g thin noodles or fideuà noodles","200g peeled prawns","200g clean mussels","150g squid rings","1 grated tomato","1 onion diced","3 garlic cloves","700ml hot seafood stock","A few saffron threads","Sweet paprika","3 tbsp olive oil","Salt","Alioli to serve"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade el calamar y saltea 3 min","Añade el tomate y el pimentón, cocina 3 min","Incorpora los fideos y tuesta 2 min removiendo","Vierte el caldo caliente con el azafrán, añade gambas y mejillones","Cuece sin remover a fuego medio-alto 10-12 min hasta que el caldo se consuma","Gratina 2 min en el horno si quieres los fideos caídos y crujientes","Sirve con alioli"],"en":["Sauté onion and garlic in oil 4 min","Add squid and cook 3 min","Add tomato and paprika, cook 3 min","Add noodles and toast 2 min stirring","Pour hot stock with saffron, add prawns and mussels","Cook without stirring over medium-high heat 10-12 min until stock is absorbed","Gratinate 2 min in oven if you want the noodles toasted and crispy","Serve with alioli"]}'
),

('tortilla_francesa_queso_std',429,'breakfast','🧀',
'{"es":"Tortilla francesa con queso gruyère","en":"French omelette with gruyère","fr":"Omelette francaise au gruyere","it":"Omelette francese con gruyere"}',
'{"es":"La tortilla francesa perfecta: suave, sin color, enrollada y rellena de queso gruyère fundido","en":"The perfect French omelette: smooth, no colour, rolled and filled with melted gruyère"}',
3,4,320,20,2,26,0,
ARRAY['standard','vegetarian','gluten_free','low_carb','keto','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'medium','under_20','low',
'{"es":["3 huevos","30g gruyère rallado","10g mantequilla","Sal, pimienta blanca","Cebollino fresco picado"],"en":["3 eggs","30g grated gruyère","10g butter","Salt, white pepper","Fresh chopped chives"]}',
'{"es":["Bate los huevos con sal y pimienta blanca 30 seg — no demasiado","Derrite la mantequilla en sartén antiadherente pequeña a fuego medio-alto","Vierte los huevos y remueve rápidamente con una espátula mientras sacudes la sartén durante 45 seg","Deja cuajar la base 20 seg","Añade el gruyère en el centro","Inclina la sartén y enrolla la tortilla sobre sí misma","Sirve inmediatamente con cebollino"],"en":["Beat eggs with salt and white pepper 30 sec — not too much","Melt butter in small non-stick pan over medium-high heat","Pour in eggs and stir quickly with a spatula while shaking the pan for 45 sec","Let base set 20 sec","Add gruyère in the centre","Tilt pan and roll omelette over itself","Serve immediately with chives"]}'
),

('pollo_marsala_std',430,'dinner','🍷',
'{"es":"Pollo al marsala con champiñones","en":"Chicken marsala with mushrooms","fr":"Poulet au marsala et champignons","it":"Pollo al marsala con funghi"}',
'{"es":"Pollo italiano clásico: pechugas empanadas en harina y cocinadas en salsa de vino marsala y champiñones","en":"Classic Italian chicken: flour-dredged breasts cooked in marsala wine and mushroom sauce"}',
8,18,480,36,20,24,3,
ARRAY['standard','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'medium','20_40','medium',
'{"es":["2 pechugas de pollo aplastadas finas","4 cdas harina","200g champiñones en láminas","150ml vino Marsala (o jerez semiseco)","150ml caldo de pollo","2 cdas mantequilla","2 cdas aceite de oliva","2 dientes de ajo","Perejil fresco","Sal, pimienta"],"en":["2 chicken breasts flattened thin","4 tbsp flour","200g mushrooms sliced","150ml Marsala wine (or medium sherry)","150ml chicken stock","2 tbsp butter","2 tbsp olive oil","2 garlic cloves","Fresh parsley","Salt, pepper"]}',
'{"es":["Pasa el pollo por harina sazonada","Dora en aceite y mantequilla a fuego alto 3 min por lado, reserva","Sofríe el ajo y los champiñones en la misma sartén 4 min","Vierte el Marsala y deja evaporar 2 min","Añade el caldo y reduce 3 min hasta que espese","Devuelve el pollo y calienta 2 min","Sirve con perejil fresco y puré de patata"],"en":["Coat chicken in seasoned flour","Brown in oil and butter over high heat 3 min per side, set aside","Sauté garlic and mushrooms in same pan 4 min","Pour Marsala and evaporate 2 min","Add stock and reduce 3 min until thickened","Return chicken and heat 2 min","Serve with fresh parsley and mashed potato"]}'
),

('tostada_anchoas_std',431,'snack','🐟',
'{"es":"Tostada de anchoas con mantequilla y limón","en":"Anchovy toast with butter and lemon","fr":"Toast aux anchois beurre et citron","it":"Toast con acciughe burro e limone"}',
'{"es":"Aperitivo elegante y sencillo: pan tostado crujiente con mantequilla fría, anchoas y limón","en":"Elegant and simple appetiser: crispy toasted bread with cold butter, anchovies and lemon"}',
3,3,240,10,22,12,2,
ARRAY['standard','pescatarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','fish'],
'easy','under_20','low',
'{"es":["4 rebanadas de pan de baguette o artesano","8 filetes de anchoa en aceite de oliva","30g mantequilla fría en láminas","Zumo de limón","Perejil fresco picado","Pimienta negra recién molida","Aceite de oliva virgen extra"],"en":["4 baguette or artisan bread slices","8 anchovy fillets in olive oil","30g cold butter sliced","Lemon juice","Fresh chopped parsley","Freshly ground black pepper","Extra-virgin olive oil"]}',
'{"es":["Tuesta el pan en tostadora o en sartén con un poco de aceite hasta muy crujiente","Coloca una lámina de mantequilla fría sobre cada tostada caliente (se derrite ligeramente)","Añade 2 filetes de anchoa encima","Exprime unas gotas de limón, espolvorea perejil y pimienta negra"],"en":["Toast bread in a toaster or pan with a little oil until very crispy","Place a slice of cold butter on each hot toast (it melts slightly)","Add 2 anchovy fillets on top","Squeeze a few drops of lemon, sprinkle parsley and black pepper"]}'
),

('steak_salsa_chimichurri_std',432,'dinner','🥩',
'{"es":"Entraña a la parrilla con chimichurri","en":"Grilled skirt steak with chimichurri","fr":"Bavette grillee au chimichurri","it":"Entraña alla griglia con chimichurri"}',
'{"es":"Corte argentino por excelencia: entraña a la parrilla con chimichurri de perejil, ajo y orégano","en":"Argentina''s signature cut: skirt steak on the grill with parsley, garlic and oregano chimichurri"}',
10,10,520,38,4,38,2,
ARRAY['standard','gluten_free','lactose_free','high_protein','low_carb','paleo'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','high',
'{"es":["400g entraña o falda de ternera","Para el chimichurri: 1 manojo de perejil, 4 dientes de ajo, 1 cdta orégano, 1/2 cdta guindilla, 4 cdas aceite de oliva, 2 cdas vinagre de vino tinto, sal","Sal gruesa"],"en":["400g skirt or flank steak","For chimichurri: 1 bunch parsley, 4 garlic cloves, 1 tsp oregano, 1/2 tsp chilli, 4 tbsp olive oil, 2 tbsp red wine vinegar, salt","Coarse salt"]}',
'{"es":["Prepara el chimichurri picando muy fino el perejil y el ajo, mezclando con el resto de ingredientes (mejor si reposa 30 min)","Saca la carne de la nevera 20 min antes","Calienta la parrilla o plancha a fuego muy alto","Sazona con sal gruesa y cocina 3-4 min por lado para punto medio","Reposa 5 min y corta en contra de la fibra","Sirve con chimichurri generoso"],"en":["Make chimichurri by very finely chopping parsley and garlic, mixing with remaining ingredients (better if rested 30 min)","Take meat out of fridge 20 min before","Heat grill or griddle over very high heat","Season with coarse salt and cook 3-4 min per side for medium rare","Rest 5 min and cut against the grain","Serve with generous chimichurri"]}'
),

('crema_guisantes_bacon_std',433,'dinner','🫛',
'{"es":"Crema de guisantes con bacon crujiente","en":"Pea cream soup with crispy bacon","fr":"Creme de petits pois au bacon croustillant","it":"Crema di piselli con bacon croccante"}',
'{"es":"Sopa cremosa verde vibrante de guisantes frescos con bacon crujiente y menta — rápida y elegante","en":"Vibrant green creamy pea soup with crispy bacon and mint — quick and elegant"}',
5,15,340,16,32,16,8,
ARRAY['standard','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["400g guisantes frescos o congelados","1 cebolla en dados","2 dientes de ajo","600ml caldo de pollo o verduras","100ml nata para cocinar","4 lonchas de bacon crujiente","Menta fresca","2 cdas aceite de oliva","Sal, pimienta"],"en":["400g fresh or frozen peas","1 onion diced","2 garlic cloves","600ml chicken or vegetable stock","100ml cooking cream","4 crispy bacon rashers","Fresh mint","2 tbsp olive oil","Salt, pepper"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade los guisantes y el caldo, cuece 8 min","Incorpora la nata y la menta, tritura hasta obtener una crema suave","Ajusta de sal y pimienta","Sirve con el bacon crujiente desmenuzado encima y hojas de menta fresca"],"en":["Sauté onion and garlic in oil 4 min","Add peas and stock, cook 8 min","Add cream and mint, blend until smooth","Adjust salt and pepper","Serve with crumbled crispy bacon on top and fresh mint leaves"]}'
),

('anchoas_pimientos_asados_std',434,'snack','🫑',
'{"es":"Pimientos asados con anchoas y alcaparras","en":"Roasted peppers with anchovies and capers","fr":"Poivrons rotis anchois et capres","it":"Peperoni arrostiti con acciughe e capperi"}',
'{"es":"Tapa mediterránea sabrosa: pimientos asados en aceite de oliva con anchoas, alcaparras y ajo","en":"Flavourful Mediterranean tapa: peppers roasted in olive oil with anchovies, capers and garlic"}',
5,40,220,8,18,14,5,
ARRAY['standard','gluten_free','lactose_free','pescatarian','mediterranean','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','over_40','low',
'{"es":["4 pimientos rojos","6 filetes de anchoa en aceite","2 cdas alcaparras","2 dientes de ajo laminados","4 cdas aceite de oliva virgen extra","Perejil fresco","Sal"],"en":["4 red peppers","6 anchovy fillets in oil","2 tbsp capers","2 garlic cloves sliced","4 tbsp extra-virgin olive oil","Fresh parsley","Salt"]}',
'{"es":["Asa los pimientos directamente en el fuego o en el horno a 220°C 35-40 min hasta que la piel esté quemada","Mételos en una bolsa o bol tapado 10 min para que suden","Pélalos, retira las semillas y córtalos en tiras","Coloca en fuente con el ajo, las alcaparras y las anchoas","Riega con el aceite y añade perejil fresco","Sirve a temperatura ambiente o templado"],"en":["Char peppers directly over flame or in oven at 220°C 35-40 min until skin is charred","Place in a bag or covered bowl 10 min to steam","Peel, remove seeds and cut into strips","Arrange on a dish with garlic, capers and anchovies","Drizzle with oil and add fresh parsley","Serve at room temperature or warm"]}'
),

('pollo_korma_std',435,'dinner','🍛',
'{"es":"Pollo korma con almendras y nata","en":"Chicken korma with almonds and cream","fr":"Poulet korma amandes et creme","it":"Pollo korma con mandorle e panna"}',
'{"es":"Curry suave y cremoso de la India: pollo en salsa de almendra, yogur y especias suaves","en":"Mild and creamy Indian curry: chicken in almond, yogurt and gentle spice sauce"}',
12,25,520,36,18,32,3,
ARRAY['standard','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['dairy','nuts'],
'medium','20_40','medium',
'{"es":["400g pechuga de pollo en dados","Para la salsa: 1 cebolla, 3 dientes de ajo, 1 cdta jengibre, 50g almendras blanqueadas, 150g yogur, 100ml nata, 1 cdta garam masala, 1 cdta comino, 1 cdta coriandro, 1/4 cdta cardamomo, pizca de cayena","2 cdas aceite vegetal","Almendras fileteadas tostadas, cilantro, arroz basmati"],"en":["400g chicken breast diced","For sauce: 1 onion, 3 garlic cloves, 1 tsp ginger, 50g blanched almonds, 150g yogurt, 100ml cream, 1 tsp garam masala, 1 tsp cumin, 1 tsp coriander, 1/4 tsp cardamom, pinch of cayenne","2 tbsp vegetable oil","Toasted flaked almonds, coriander, basmati rice"]}',
'{"es":["Tritura la cebolla, el ajo, el jengibre y las almendras con un poco de agua hasta obtener una pasta","Sofríe la pasta en aceite 5 min","Añade las especias y cocina 2 min","Incorpora el pollo y dora 4 min","Añade el yogur, la nata y 100ml de agua","Cuece a fuego bajo 18-20 min","Sirve con almendras fileteadas, cilantro y arroz basmati"],"en":["Blend onion, garlic, ginger and almonds with a little water into a paste","Fry paste in oil 5 min","Add spices and cook 2 min","Add chicken and brown 4 min","Add yogurt, cream and 100ml water","Cook over low heat 18-20 min","Serve with flaked almonds, coriander and basmati rice"]}'
),

('brownie_chocolate_std',436,'snack','🍫',
'{"es":"Brownie de chocolate con nueces","en":"Chocolate walnut brownie","fr":"Brownie au chocolat et noix","it":"Brownie al cioccolato con noci"}',
'{"es":"El brownie perfecto: exterior crujiente, interior húmedo y fondant con nueces — irresistible","en":"The perfect brownie: crispy exterior, moist fudgy interior with walnuts — irresistible"}',
10,25,420,6,46,24,3,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy','eggs','nuts'],
'easy','20_40','medium',
'{"es":["150g chocolate negro 70%","100g mantequilla","150g azúcar","2 huevos","80g harina","30g cacao en polvo","80g nueces troceadas","1 cdta extracto de vainilla","Pizca de sal"],"en":["150g 70% dark chocolate","100g butter","150g sugar","2 eggs","80g flour","30g cocoa powder","80g chopped walnuts","1 tsp vanilla extract","Pinch of salt"]}',
'{"es":["Precalienta el horno a 180°C","Derrite el chocolate con la mantequilla al baño María o microondas","Bate el azúcar con los huevos hasta blanquear, añade la vainilla","Incorpora el chocolate derretido","Añade la harina, el cacao y la sal tamizados, mezcla justo hasta integrar","Añade las nueces","Vierte en molde cuadrado engrasado 20x20cm","Hornea 22-25 min (el centro debe quedar húmedo)","Deja enfriar completamente antes de cortar"],"en":["Preheat oven to 180°C","Melt chocolate with butter in a double boiler or microwave","Beat sugar with eggs until pale, add vanilla","Add melted chocolate","Add sifted flour, cocoa and salt, mix just until combined","Add walnuts","Pour into greased 20x20cm square tin","Bake 22-25 min (centre should remain moist)","Cool completely before cutting"]}'
),

('carrilleras_vino_tinto_std',437,'dinner','🍷',
'{"es":"Carrilleras de cerdo al vino tinto","en":"Pork cheeks in red wine","fr":"Joues de porc au vin rouge","it":"Guance di maiale al vino rosso"}',
'{"es":"Carrilleras estofadas en vino tinto con verduras hasta quedar melosas y tiernas — cocina de domingo","en":"Pork cheeks braised in red wine with vegetables until meltingly tender — Sunday cooking"}',
15,90,540,36,18,30,4,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','medium',
'{"es":["600g carrilleras de cerdo","1 botella de vino tinto (Rioja o similar)","1 cebolla, 2 zanahorias, 2 ajos puerros","3 dientes de ajo","400g tomate triturado","Tomillo, laurel, romero","2 cdas aceite de oliva","Sal, pimienta","Puré de patata o patatas paja para servir"],"en":["600g pork cheeks","1 bottle red wine (Rioja or similar)","1 onion, 2 carrots, 2 leeks","3 garlic cloves","400g crushed tomato","Thyme, bay, rosemary","2 tbsp olive oil","Salt, pepper","Mashed or straw potatoes to serve"]}',
'{"es":["Marina las carrilleras en el vino con las verduras y las hierbas mínimo 2 horas (mejor toda la noche)","Escurre y seca las carrilleras, dora en aceite a fuego alto 3-4 min por lado, reserva","Sofríe las verduras de la marinada 5 min","Añade la marinada, el tomate y las carrilleras","Cuece tapado a fuego muy bajo 70-80 min hasta que estén muy tiernas","Saca las carrilleras y reduce la salsa, cuela si quieres","Sirve con puré de patata"],"en":["Marinate cheeks in wine with vegetables and herbs minimum 2 hours (overnight is better)","Drain and dry cheeks, brown in oil over high heat 3-4 min per side, set aside","Sauté vegetables from marinade 5 min","Add marinade, tomato and cheeks","Cook covered over very low heat 70-80 min until very tender","Remove cheeks and reduce sauce, strain if desired","Serve with mashed potato"]}'
),

('pizza_margherita_std',438,'dinner','🍕',
'{"es":"Pizza margarita casera","en":"Homemade margherita pizza","fr":"Pizza margherita maison","it":"Pizza margherita fatta in casa"}',
'{"es":"La pizza italiana perfecta en casa: masa fina y crujiente, tomate San Marzano, mozzarella fresca y albahaca","en":"The perfect Italian pizza at home: thin crispy dough, San Marzano tomato, fresh mozzarella and basil"}',
20,12,560,20,78,16,4,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'medium','20_40','low',
'{"es":["Para la masa: 250g harina de fuerza, 4g levadura seca, 160ml agua tibia, 1 cdta sal, 1 cdta aceite de oliva","Para la pizza: 3 cdas tomate triturado (San Marzano si es posible), 125g mozzarella fresca, albahaca fresca, aceite de oliva, sal"],"en":["For dough: 250g strong flour, 4g dry yeast, 160ml warm water, 1 tsp salt, 1 tsp olive oil","For pizza: 3 tbsp crushed tomato (San Marzano if possible), 125g fresh mozzarella, fresh basil, olive oil, salt"]}',
'{"es":["Disuelve la levadura en el agua tibia, mezcla con la harina y la sal hasta obtener una masa, añade el aceite","Amasa 8-10 min hasta elástica, deja levar 1-2 horas","Precalienta el horno al máximo (250°C o más) con piedra o bandeja dentro","Estira la masa muy fina sobre papel de horno","Unta con tomate, añade la mozzarella en trozos","Hornea 8-10 min hasta que los bordes estén dorados","Añade la albahaca fresca y un hilo de aceite al sacar"],"en":["Dissolve yeast in warm water, mix with flour and salt until dough forms, add oil","Knead 8-10 min until elastic, let rise 1-2 hours","Preheat oven to maximum (250°C or above) with stone or tray inside","Stretch dough very thin on baking paper","Spread tomato, add mozzarella in pieces","Bake 8-10 min until edges are golden","Add fresh basil and a drizzle of oil when out of oven"]}'
),

('lentejas_estofadas_std',439,'dinner','🫘',
'{"es":"Lentejas estofadas con chorizo y verduras","en":"Lentil stew with chorizo and vegetables","fr":"Lentilles mijotees chorizo et legumes","it":"Lenticchie in umido con chorizo e verdure"}',
'{"es":"El guiso de cuchara más querido: lentejas con chorizo, zanahoria, patata y especias de siempre","en":"The most beloved spoon stew: lentils with chorizo, carrot, potato and classic spices"}',
10,35,520,28,58,16,14,
ARRAY['standard','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal','follicular'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["250g lentejas pardinas","80g chorizo en rodajas","2 zanahorias en rodajas","1 patata en dados","1 pimiento verde en dados","1 cebolla en dados","3 dientes de ajo","1 tomate maduro rallado","1L agua o caldo","1 cdta pimentón","Laurel, comino","3 cdas aceite de oliva","Sal"],"en":["250g green lentils","80g chorizo sliced","2 carrots sliced","1 potato diced","1 green pepper diced","1 onion diced","3 garlic cloves","1 grated ripe tomato","1L water or stock","1 tsp paprika","Bay leaf, cumin","3 tbsp olive oil","Salt"]}',
'{"es":["Sofríe la cebolla, el ajo, el pimiento y el chorizo en aceite 5 min","Añade el tomate y el pimentón, cocina 2 min","Incorpora las lentejas, la zanahoria, la patata, el laurel, el comino y el agua","Cuece a fuego medio 28-30 min hasta que las lentejas estén tiernas","Ajusta de sal y sirve"],"en":["Sauté onion, garlic, pepper and chorizo in oil 5 min","Add tomato and paprika, cook 2 min","Add lentils, carrot, potato, bay leaf, cumin and water","Cook over medium heat 28-30 min until lentils are tender","Adjust salt and serve"]}'
),

('tarta_manzana_std',440,'snack','🍎',
'{"es":"Tarta de manzana casera","en":"Homemade apple tart","fr":"Tarte aux pommes maison","it":"Torta di mele fatta in casa"}',
'{"es":"La tarta más reconfortante: manzanas caramelizadas sobre hojaldre crujiente con canela y azúcar moreno","en":"The most comforting tart: caramelised apples on crispy puff pastry with cinnamon and brown sugar"}',
15,30,380,4,52,16,3,
ARRAY['standard','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'easy','20_40','medium',
'{"es":["1 lámina de hojaldre","4 manzanas golden peladas y en láminas","3 cdas azúcar moreno","1 cdta canela","1 cda mantequilla en trocitos","1 huevo batido (para pintar)","Mermelada de albaricoque para glasear (opcional)"],"en":["1 puff pastry sheet","4 golden apples peeled and sliced","3 tbsp brown sugar","1 tsp cinnamon","1 tbsp butter in pieces","1 beaten egg (for glazing)","Apricot jam for glazing (optional)"]}',
'{"es":["Precalienta el horno a 200°C","Extiende el hojaldre en bandeja con papel, pincha con un tenedor","Mezcla las manzanas con el azúcar y la canela","Coloca las láminas de manzana solapadas sobre el hojaldre dejando 1cm de borde","Distribuye la mantequilla en trocitos encima","Pinta el borde con huevo batido","Hornea 25-30 min hasta que el hojaldre esté dorado","Glasea con mermelada si quieres"],"en":["Preheat oven to 200°C","Spread pastry on lined tray, prick with a fork","Mix apples with sugar and cinnamon","Arrange apple slices overlapping on pastry leaving 1cm border","Scatter butter pieces on top","Brush border with beaten egg","Bake 25-30 min until pastry is golden","Glaze with jam if desired"]}'
),

('poke_bowl_std',441,'lunch','🍚',
'{"es":"Poke bowl de salmón y aguacate","en":"Salmon and avocado poke bowl","fr":"Poke bowl saumon et avocat","it":"Poke bowl di salmone e avocado"}',
'{"es":"El poke bowl hawaiano: salmón crudo marinado, arroz de sushi, aguacate, edamame y salsa ponzu","en":"The Hawaiian poke bowl: marinated raw salmon, sushi rice, avocado, edamame and ponzu sauce"}',
15,15,580,30,64,18,6,
ARRAY['standard','gluten_free','lactose_free','pescatarian','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['fish','soy','sesame'],
'medium','20_40','high',
'{"es":["160g arroz de sushi cocido con vinagre de arroz","200g salmón fresco sashimi en dados (muy fresco o ultracongelado)","1/2 aguacate en dados","60g edamame cocido","1/2 pepino en rodajas","Para la salsa: 2 cdas salsa de soja, 1 cda aceite de sésamo, 1 cdta miel, zumo de 1/2 lima","Sésamo tostado, nori, cebolleta verde"],"en":["160g cooked sushi rice seasoned with rice vinegar","200g fresh sashimi-grade salmon diced (very fresh or flash-frozen)","1/2 avocado diced","60g cooked edamame","1/2 cucumber sliced","For sauce: 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tsp honey, juice of 1/2 lime","Toasted sesame, nori, spring onion"]}',
'{"es":["Marina el salmón en la salsa 10 min","Monta el bowl: arroz, encima el salmón, el aguacate, el edamame, el pepino","Añade el resto de la salsa por encima","Decora con sésamo, tiras de nori y cebolleta verde"],"en":["Marinate salmon in the sauce 10 min","Build the bowl: rice, then salmon, avocado, edamame, cucumber on top","Drizzle remaining sauce over","Garnish with sesame, nori strips and spring onion"]}'
),

('croquetas_bacalao_std',442,'snack','🐟',
'{"es":"Croquetas de bacalao y patata","en":"Salt cod and potato croquettes","fr":"Croquettes de morue et pomme de terre","it":"Crocchette di baccala e patate"}',
'{"es":"Croquetas portuguesas de bacalao: suaves por dentro, crujientes por fuera — brandade en forma de croqueta","en":"Portuguese cod croquettes: soft inside, crispy outside — brandade in croquette form"}',
20,15,340,16,30,16,2,
ARRAY['standard','pescatarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten','eggs','fish'],
'medium','20_40','medium',
'{"es":["300g bacalao desalado cocido y desmenuzado","400g patata cocida y aplastada","2 dientes de ajo","Perejil fresco picado","1 huevo","Sal, pimienta, nuez moscada","Para el rebozado: harina, huevo batido, pan rallado","Aceite para freír"],"en":["300g desalted cod cooked and flaked","400g cooked mashed potato","2 garlic cloves","Fresh chopped parsley","1 egg","Salt, pepper, nutmeg","For coating: flour, beaten egg, breadcrumbs","Oil for frying"]}',
'{"es":["Mezcla el bacalao con la patata, el ajo picado, el perejil, el huevo, sal, pimienta y nuez moscada","Refrigera 1 hora para que sea más fácil de manejar","Forma croquetas con las manos húmedas","Pasa por harina, huevo y pan rallado","Fríe en aceite caliente hasta doradas y crujientes","Escurre sobre papel"],"en":["Mix cod with potato, chopped garlic, parsley, egg, salt, pepper and nutmeg","Refrigerate 1 hour to make them easier to handle","Shape croquettes with damp hands","Coat in flour, egg then breadcrumbs","Fry in hot oil until golden and crispy","Drain on paper"]}'
),

('macarrones_boloñesa_std',443,'dinner','🍝',
'{"es":"Macarrones con carne y tomate","en":"Macaroni with meat and tomato","fr":"Macaronis viande et tomate","it":"Maccheroni con carne e pomodoro"}',
'{"es":"Los macarrones de toda la vida: salsa de tomate y carne picada especiada con parmesano gratinado","en":"Classic everyday macaroni: tomato and spiced minced meat sauce with gratinated parmesan"}',
8,25,560,28,68,16,5,
ARRAY['standard','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY['gluten','dairy'],
'easy','20_40','low',
'{"es":["200g macarrones","250g carne picada mixta","400g tomate triturado","1 cebolla en dados","3 dientes de ajo","1 cdta orégano","1 cdta pimentón","100ml vino tinto (opcional)","40g parmesano rallado para gratinar","2 cdas aceite de oliva","Sal, pimienta"],"en":["200g macaroni","250g mixed mince","400g crushed tomato","1 onion diced","3 garlic cloves","1 tsp oregano","1 tsp paprika","100ml red wine (optional)","40g grated parmesan for gratin","2 tbsp olive oil","Salt, pepper"]}',
'{"es":["Cuece los macarrones al dente, escurre","Sofríe la cebolla y el ajo en aceite 4 min","Añade la carne y dórala 5 min desmigando","Vierte el vino y evapora, añade el tomate, el orégano, el pimentón, sal y pimienta","Cuece 15 min a fuego medio","Mezcla con los macarrones en una fuente de horno","Espolvorea parmesano y gratina 5 min"],"en":["Cook macaroni al dente, drain","Sauté onion and garlic in oil 4 min","Add mince and brown 5 min breaking it up","Pour wine and evaporate, add tomato, oregano, paprika, salt and pepper","Cook 15 min over medium heat","Mix with macaroni in a baking dish","Sprinkle parmesan and gratinate 5 min"]}'
),

('potaje_garbanzos_espinacas_std',444,'dinner','🫘',
'{"es":"Potaje de garbanzos y espinacas con huevo duro","en":"Chickpea and spinach potaje with hard-boiled egg","fr":"Potaje pois chiches epinards et oeuf dur","it":"Zuppa di ceci e spinaci con uovo sodo"}',
'{"es":"El potaje de cuaresma español: garbanzos, espinacas, ajo y pimentón con huevo duro desmenuzado","en":"Spanish lenten potaje: chickpeas, spinach, garlic and paprika with crumbled hard-boiled egg"}',
10,25,460,22,58,14,14,
ARRAY['standard','vegetarian','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['anemia','endometriosis'],
ARRAY['eggs'],
'easy','20_40','low',
'{"es":["400g garbanzos cocidos","300g espinacas frescas","2 huevos duros","1 cebolla en dados","4 dientes de ajo laminados","1 cdta comino","1 cdta pimentón","400ml caldo de verduras","3 cdas aceite de oliva","Sal, pimienta"],"en":["400g cooked chickpeas","300g fresh spinach","2 hard-boiled eggs","1 onion diced","4 garlic cloves sliced","1 tsp cumin","1 tsp paprika","400ml vegetable stock","3 tbsp olive oil","Salt, pepper"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 5 min","Añade el comino y el pimentón, cocina 1 min","Incorpora los garbanzos y el caldo, cuece 10 min","Añade las espinacas y cocina 5 min hasta que se marchiten","Chafa unos garbanzos con la espátula para espesar","Sirve con el huevo duro desmenuzado por encima"],"en":["Sauté onion and garlic in oil 5 min","Add cumin and paprika, cook 1 min","Add chickpeas and stock, cook 10 min","Add spinach and cook 5 min until wilted","Mash some chickpeas with a spatula to thicken","Serve with crumbled hard-boiled egg on top"]}'
),

('merluza_salsa_verde_std',445,'dinner','🐟',
'{"es":"Merluza en salsa verde con almejas","en":"Hake in green sauce with clams","fr":"Merlu en sauce verte aux palourdes","it":"Nasello in salsa verde con vongole"}',
'{"es":"Clásico vasco: merluza en salsa verde de perejil, ajo y vino blanco con almejas — elegante y sencillo","en":"Basque classic: hake in green parsley, garlic and white wine sauce with clams — elegant and simple"}',
8,18,380,36,8,18,2,
ARRAY['standard','gluten_free','lactose_free','pescatarian','high_protein','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['fish','shellfish'],
'medium','20_40','medium',
'{"es":["2 lomos de merluza","200g almejas (purgadas en agua con sal 1h)","4 dientes de ajo laminados","100ml vino blanco seco","200ml caldo de pescado","3 cdas aceite de oliva","2 cdas perejil fresco muy picado","Sal, pimienta","1 cdta harina (para ligar la salsa)"],"en":["2 hake loins","200g clams (purged in salted water 1h)","4 garlic cloves sliced","100ml dry white wine","200ml fish stock","3 tbsp olive oil","2 tbsp very finely chopped fresh parsley","Salt, pepper","1 tsp flour (to thicken sauce)"]}',
'{"es":["Calienta el aceite y sofríe el ajo 2 min sin que tome color","Añade la harina y cocina 1 min","Vierte el vino y deja evaporar, añade el caldo","Coloca la merluza con la piel hacia arriba, añade las almejas","Tapa y cuece a fuego medio-bajo 10-12 min sacudiendo la cazuela ocasionalmente","Añade el perejil generosamente y sirve"],"en":["Heat oil and sauté garlic 2 min without colouring","Add flour and cook 1 min","Pour wine and evaporate, add stock","Place hake skin-side up, add clams","Cover and cook over medium-low heat 10-12 min shaking the pan occasionally","Add parsley generously and serve"]}'
),

('ensaladilla_rusa_std',446,'snack','🥔',
'{"es":"Ensaladilla rusa con atún y mayonesa","en":"Russian salad with tuna and mayonnaise","fr":"Salade russe thon et mayonnaise","it":"Insalata russa con tonno e maionese"}',
'{"es":"La ensaladilla más popular de España: patata, zanahoria, guisantes, atún y mayonesa casera","en":"Spain''s most popular salad: potato, carrot, peas, tuna and homemade mayonnaise"}',
20,15,380,14,32,22,5,
ARRAY['standard','pescatarian','gluten_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs','fish'],
'easy','20_40','low',
'{"es":["3 patatas medianas cocidas en dados","2 zanahorias cocidas en dados","100g guisantes cocidos","2 latas de atún en aceite","3 huevos duros picados","Para la mayonesa: 1 huevo, 200ml aceite de girasol, zumo de limón, sal","Pepinillos, aceitunas para decorar"],"en":["3 medium potatoes boiled and diced","2 carrots boiled and diced","100g cooked peas","2 cans tuna in oil","3 hard-boiled eggs chopped","For mayo: 1 egg, 200ml sunflower oil, lemon juice, salt","Gherkins, olives to garnish"]}',
'{"es":["Prepara la mayonesa triturando el huevo con el limón y la sal, añade el aceite en hilo muy fino hasta emulsionar","Mezcla las patatas, las zanahorias, los guisantes, el atún escurrido y los huevos","Añade la mayonesa y mezcla suavemente","Refrigera 1 hora mínimo","Sirve decorado con pepinillos y aceitunas"],"en":["Make mayo by blending egg with lemon and salt, add oil in very thin stream until emulsified","Mix potatoes, carrots, peas, drained tuna and eggs","Add mayonnaise and mix gently","Refrigerate minimum 1 hour","Serve garnished with gherkins and olives"]}'
),

('pollo_francés_mostaza_std',447,'dinner','🍗',
'{"es":"Pollo a la francesa con mostaza y estragón","en":"French chicken with mustard and tarragon","fr":"Poulet a la francaise moutarde et estragon","it":"Pollo alla francese con senape ed estragone"}',
'{"es":"Pollo al estilo bistró francés: salsa cremosa de mostaza de Dijon, nata y estragón fresco","en":"French bistro-style chicken: creamy Dijon mustard, cream and fresh tarragon sauce"}',
8,22,480,38,4,32,1,
ARRAY['standard','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['dairy','mustard'],
'easy','20_40','medium',
'{"es":["4 filetes de pechuga de pollo","2 cdas mostaza de Dijon","200ml nata para cocinar","100ml vino blanco","1 chalota en dados finos","1 diente de ajo","Estragón fresco (o tomillo si no encuentras)","2 cdas aceite de oliva","Sal, pimienta"],"en":["4 chicken breast fillets","2 tbsp Dijon mustard","200ml cooking cream","100ml white wine","1 shallot finely diced","1 garlic clove","Fresh tarragon (or thyme if unavailable)","2 tbsp olive oil","Salt, pepper"]}',
'{"es":["Sella el pollo en aceite a fuego alto 3 min por lado hasta dorado, reserva","Sofríe la chalota y el ajo 2 min","Vierte el vino y deja evaporar 2 min","Añade la mostaza y la nata, mezcla bien","Devuelve el pollo y cuece a fuego bajo 12 min","Añade el estragón fresco al final y sirve"],"en":["Sear chicken in oil over high heat 3 min per side until golden, set aside","Sauté shallot and garlic 2 min","Pour wine and evaporate 2 min","Add mustard and cream, mix well","Return chicken and cook over low heat 12 min","Add fresh tarragon at the end and serve"]}'
),

('tarta_santiago_std',448,'snack','⭐',
'{"es":"Tarta de Santiago","en":"Tarta de Santiago almond cake","fr":"Gateau aux amandes Tarte de Santiago","it":"Torta di Santiago alle mandorle"}',
'{"es":"El postre gallego más famoso: tarta de almendra sin harina, húmeda y fragante con canela y limón","en":"Galicia''s most famous dessert: flourless almond cake, moist and fragrant with cinnamon and lemon"}',
10,35,420,10,38,26,4,
ARRAY['standard','vegetarian','gluten_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['eggs','nuts'],
'easy','20_40','medium',
'{"es":["250g almendra molida","200g azúcar","3 huevos","Ralladura de 1 limón","1 cdta canela molida","Azúcar glas para decorar (y plantilla de la cruz de Santiago si quieres)"],"en":["250g ground almond","200g sugar","3 eggs","Zest of 1 lemon","1 tsp ground cinnamon","Icing sugar to decorate (and Santiago cross stencil if you want)"]}',
'{"es":["Precalienta el horno a 180°C","Bate los huevos con el azúcar hasta blanquear","Añade la almendra, la ralladura de limón y la canela, mezcla","Vierte en molde de 22cm engrasado y forrado","Hornea 30-35 min hasta que al pinchar salga limpio pero quede húmeda","Deja enfriar completamente y espolvorea azúcar glas con la plantilla de la cruz"],"en":["Preheat oven to 180°C","Beat eggs with sugar until pale","Add almond, lemon zest and cinnamon, mix","Pour into greased and lined 22cm tin","Bake 30-35 min until a skewer comes out clean but it remains moist","Cool completely and dust icing sugar with the cross stencil"]}'
)

ON CONFLICT (id) DO NOTHING;
