-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 9 (30) — display_order 281-310
-- Enfocado en: low_fodmap, low_carb
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 8
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── LOW FODMAP ────────────────────────────────────────────────────────────────

('pollo_limon_fodmap',281,'dinner','🍋',
'{"es":"Pollo al limón con aceite de ajo infusionado","en":"Lemon chicken with garlic-infused oil","fr":"Poulet citron a l''huile d''ail infusee","it":"Pollo al limone con olio all''aglio"}',
'{"es":"Low FODMAP: el aceite infusionado da sabor a ajo sin el fructano que causa síntomas","en":"Low FODMAP: infused oil gives garlic flavour without the fructans that cause symptoms"}',
5,20,400,36,4,26,1,
ARRAY['low_fodmap','gluten_free','lactose_free','keto','paleo','high_protein','low_carb'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','muscle'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["4 muslos de pollo deshuesados","Zumo de 2 limones","Ralladura de 1 limón","3 cdas aceite de ajo infusionado (calienta aceite de oliva con ajo, retira el ajo antes de usar)","1 cdta orégano","1 cdta pimentón","Sal, pimienta","Cebollino fresco (solo la parte verde)"],"en":["4 boneless chicken thighs","Juice of 2 lemons","Zest of 1 lemon","3 tbsp garlic-infused oil (heat olive oil with garlic, remove garlic before using)","1 tsp oregano","1 tsp paprika","Salt, pepper","Fresh chives (green part only)"]}',
'{"es":["Mezcla el zumo, la ralladura de limón, el aceite, el orégano, el pimentón, sal y pimienta","Marina el pollo al menos 20 min (o toda la noche)","Cocina en sartén a fuego medio-alto 8-10 min por lado","Deja reposar 3 min y sirve con cebollino verde picado"],"en":["Mix lemon juice, zest, oil, oregano, paprika, salt and pepper","Marinate chicken at least 20 min (or overnight)","Cook in pan over medium-high heat 8-10 min per side","Rest 3 min and serve with chopped green chives"]}'
),

('pasta_arroz_gambas_fodmap',282,'dinner','🍤',
'{"es":"Pasta de arroz con gambas y calabacín","en":"Rice pasta with prawns and courgette","fr":"Pates de riz crevettes et courgette","it":"Pasta di riso con gamberi e zucchine"}',
'{"es":"Pasta sin gluten low FODMAP: gambas, calabacín y aceite de ajo infusionado","en":"Gluten-free low FODMAP pasta: prawns, courgette and garlic-infused oil"}',
8,15,440,28,52,10,4,
ARRAY['low_fodmap','gluten_free','lactose_free','pescatarian'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY['sibo','ibs'],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["150g pasta de arroz","200g gambas peladas","1 calabacín en dados","2 tomates maduros pelados y picados","2 cdas aceite de ajo infusionado","Albahaca fresca","Sal, pimienta","Guindilla en copos (opcional)"],"en":["150g rice pasta","200g peeled prawns","1 courgette diced","2 ripe tomatoes peeled and chopped","2 tbsp garlic-infused oil","Fresh basil","Salt, pepper","Chilli flakes (optional)"]}',
'{"es":["Cuece la pasta de arroz según instrucciones, escurre","Saltea las gambas en el aceite 2-3 min hasta rosadas, reserva","En el mismo aceite cocina el calabacín 4 min","Añade el tomate y cocina 3 min más","Incorpora la pasta y las gambas, mezcla bien","Sirve con albahaca fresca"],"en":["Cook rice pasta according to instructions, drain","Sauté prawns in oil 2-3 min until pink, set aside","In same oil cook courgette 4 min","Add tomato and cook 3 min more","Add pasta and prawns, mix well","Serve with fresh basil"]}'
),

('tortilla_espinacas_fodmap',283,'breakfast','🥚',
'{"es":"Tortilla francesa con espinacas y queso sin lactosa","en":"French omelette with spinach and lactose-free cheese","fr":"Omelette aux epinards et fromage sans lactose","it":"Omelette con spinaci e formaggio senza lattosio"}',
'{"es":"Tortilla esponjosa low FODMAP: espinacas y queso curado (bajo en lactosa por naturaleza)","en":"Fluffy low FODMAP omelette: spinach and aged cheese (naturally low in lactose)"}',
5,6,340,22,4,26,2,
ARRAY['low_fodmap','gluten_free','low_carb','keto','vegetarian','high_protein'],
ARRAY['follicular','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['sibo','ibs'],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["3 huevos","60g espinacas baby","30g queso parmesano o cheddar curado rallado","1 cda aceite de oliva","Sal, pimienta","Cebollino verde picado"],"en":["3 eggs","60g baby spinach","30g grated parmesan or aged cheddar","1 tbsp olive oil","Salt, pepper","Chopped green chives"]}',
'{"es":["Bate los huevos con sal y pimienta","Calienta el aceite en sartén antiadherente a fuego medio","Añade las espinacas y sofríe 1 min hasta que se marchiten","Vierte los huevos batidos, deja cuajar 1 min","Añade el queso sobre la mitad de la tortilla","Dobla y cocina 1 min más","Sirve con cebollino"],"en":["Beat eggs with salt and pepper","Heat oil in non-stick pan over medium heat","Add spinach and sauté 1 min until wilted","Pour in beaten eggs, let set 1 min","Add cheese to one half","Fold and cook 1 min more","Serve with chives"]}'
),

('salmón_pure_zanahoria_fodmap',284,'dinner','🥕',
'{"es":"Salmón al vapor con puré de zanahoria y jengibre","en":"Steamed salmon with carrot and ginger puree","fr":"Saumon vapeur puree carotte-gingembre","it":"Salmone al vapore con purea di carote e zenzero"}',
'{"es":"Plato digestivo low FODMAP: salmón suave al vapor, puré de zanahoria antiinflamatorio","en":"Digestive low FODMAP dish: gentle steamed salmon, anti-inflammatory carrot puree"}',
8,20,420,34,18,22,5,
ARRAY['low_fodmap','gluten_free','lactose_free','pescatarian','anti_inflammatory','keto','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','muscle'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 filetes de salmón","3 zanahorias en rodajas","1 cdta jengibre fresco rallado","2 cdas aceite de oliva","Zumo de limón","Eneldo fresco","Sal, pimienta","100ml caldo de verduras (sin cebolla ni ajo)"],"en":["2 salmon fillets","3 carrots sliced","1 tsp fresh grated ginger","2 tbsp olive oil","Lemon juice","Fresh dill","Salt, pepper","100ml vegetable stock (no onion or garlic)"]}',
'{"es":["Cuece las zanahorias en el caldo 15 min hasta blandas","Tritura con el jengibre, 1 cda aceite, sal y pimienta hasta obtener un puré suave","Cuece el salmón al vapor o en papel de horno a 180°C 12-15 min","Sirve el salmón sobre el puré con eneldo y zumo de limón"],"en":["Cook carrots in stock 15 min until soft","Blend with ginger, 1 tbsp oil, salt and pepper until smooth puree","Steam salmon or bake in parchment at 180°C 12-15 min","Serve salmon on the puree with dill and lemon juice"]}'
),

('bol_arroz_pavo_fodmap',285,'lunch','🍚',
'{"es":"Bol de arroz basmati con pavo y verduras toleradas","en":"Basmati rice bowl with turkey and low-FODMAP vegetables","fr":"Bowl riz basmati dinde et legumes toleres","it":"Bowl di riso basmati con tacchino e verdure tollerate"}',
'{"es":"Bol reconfortante y digestivo: arroz basmati, pavo magro y verduras sin fructanos","en":"Comforting and digestive bowl: basmati rice, lean turkey and vegetables without fructans"}',
8,20,460,36,52,8,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["150g arroz basmati","200g filete de pavo en dados","1 pimiento rojo en tiras","1 calabacín en dados","Aceite de ajo infusionado","1 cda tamari o salsa de soja sin gluten","Jengibre rallado","Cebollino verde","Sal, pimienta"],"en":["150g basmati rice","200g turkey steak diced","1 red pepper in strips","1 courgette diced","Garlic-infused oil","1 tbsp tamari or gluten-free soy sauce","Grated ginger","Green chives","Salt, pepper"]}',
'{"es":["Cuece el arroz basmati según instrucciones","Saltea el pavo en aceite de ajo infusionado 5-6 min, reserva","En el mismo aceite saltea el pimiento y el calabacín 4 min","Añade el tamari, el jengibre y el pavo, mezcla","Sirve sobre el arroz con cebollino verde picado"],"en":["Cook basmati rice according to instructions","Sauté turkey in garlic-infused oil 5-6 min, set aside","In same oil sauté pepper and courgette 4 min","Add tamari, ginger and turkey, mix","Serve over rice with chopped green chives"]}'
),

('sopa_zanahoria_jengibre_fodmap',286,'dinner','🥕',
'{"es":"Sopa de zanahoria y jengibre (low FODMAP)","en":"Carrot and ginger soup (low FODMAP)","fr":"Soupe carotte-gingembre (low FODMAP)","it":"Zuppa di carote e zenzero (low FODMAP)"}',
'{"es":"Sopa cremosa antiinflamatoria sin cebolla ni ajo — ideal para días difíciles del ciclo","en":"Creamy anti-inflammatory soup with no onion or garlic — ideal for tough cycle days"}',
8,20,240,4,32,10,6,
ARRAY['low_fodmap','vegan','vegetarian','gluten_free','lactose_free','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["500g zanahorias en rodajas","1 cdta jengibre fresco rallado","1/2 cdta cúrcuma","400ml caldo de verduras (sin cebolla ni ajo)","200ml leche de coco","2 cdas aceite de oliva","Sal, pimienta","Semillas de calabaza para decorar","Cebollino verde"],"en":["500g carrots sliced","1 tsp fresh grated ginger","1/2 tsp turmeric","400ml vegetable stock (no onion or garlic)","200ml coconut milk","2 tbsp olive oil","Salt, pepper","Pumpkin seeds to garnish","Green chives"]}',
'{"es":["Sofríe las zanahorias en aceite 3 min","Añade el jengibre y la cúrcuma, cocina 1 min","Incorpora el caldo y cuece 15 min hasta que las zanahorias estén blandas","Añade la leche de coco y tritura hasta obtener una sopa suave","Ajusta de sal y sirve con semillas y cebollino"],"en":["Sauté carrots in oil 3 min","Add ginger and turmeric, cook 1 min","Add stock and cook 15 min until carrots are soft","Add coconut milk and blend until smooth","Adjust salt and serve with seeds and chives"]}'
),

('quinoa_verduras_fodmap',287,'lunch','🥗',
'{"es":"Ensalada templada de quinoa con verduras low FODMAP","en":"Warm quinoa salad with low FODMAP vegetables","fr":"Salade tiede de quinoa aux legumes low FODMAP","it":"Insalata tiepida di quinoa con verdure low FODMAP"}',
'{"es":"Quinoa con pimiento, pepino, zanahoria y vinagreta de limón — sin alimentos que inflamen","en":"Quinoa with pepper, cucumber, carrot and lemon dressing — no inflammatory triggers"}',
10,15,380,12,56,10,6,
ARRAY['low_fodmap','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["160g quinoa","1 pimiento rojo en dados","1/2 pepino en dados","2 zanahorias ralladas","2 cdas aceite de oliva","Zumo de 1 limón","1 cdta comino","Perejil fresco picado","Sal, pimienta","Semillas de girasol"],"en":["160g quinoa","1 red pepper diced","1/2 cucumber diced","2 carrots grated","2 tbsp olive oil","Juice of 1 lemon","1 tsp cumin","Fresh chopped parsley","Salt, pepper","Sunflower seeds"]}',
'{"es":["Cuece la quinoa según instrucciones, escurre y deja enfriar un poco","Prepara la vinagreta con aceite, limón, comino, sal y pimienta","Mezcla la quinoa con el pimiento, el pepino y la zanahoria","Riega con la vinagreta, añade el perejil y las semillas"],"en":["Cook quinoa according to instructions, drain and let cool slightly","Prepare dressing with oil, lemon, cumin, salt and pepper","Mix quinoa with pepper, cucumber and carrot","Drizzle with dressing, add parsley and seeds"]}'
),

('pollo_arroz_caldo_fodmap',288,'dinner','🍜',
'{"es":"Caldo de pollo con arroz y verduras (low FODMAP)","en":"Chicken broth with rice and vegetables (low FODMAP)","fr":"Bouillon de poulet riz et legumes (low FODMAP)","it":"Brodo di pollo con riso e verdure (low FODMAP)"}',
'{"es":"El plato más reconfortante y digestivo: caldo de pollo sin cebolla ni ajo, con arroz y zanahoria","en":"The most comforting and digestive dish: chicken broth without onion or garlic, with rice and carrot"}',
5,25,340,28,38,6,3,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g pollo cocido desmenuzado","80g arroz","2 zanahorias en rodajas","2 tallos de apio en rodajas","1L caldo de pollo casero (sin cebolla ni ajo, solo el hueso)","Cebollino verde picado","Perejil fresco","Sal, pimienta"],"en":["300g cooked shredded chicken","80g rice","2 carrots sliced","2 celery stalks sliced","1L homemade chicken stock (no onion or garlic, bone only)","Chopped green chives","Fresh parsley","Salt, pepper"]}',
'{"es":["Lleva el caldo a ebullición","Añade las zanahorias y el apio, cuece 10 min","Incorpora el arroz y cuece 15 min más","Añade el pollo desmenuzado los últimos 3 min","Sirve con perejil fresco y cebollino verde"],"en":["Bring stock to a boil","Add carrots and celery, cook 10 min","Add rice and cook 15 min more","Add shredded chicken in the last 3 min","Serve with fresh parsley and green chives"]}'
),

('huevos_espinacas_tomate_fodmap',289,'breakfast','🍅',
'{"es":"Huevos al plato con espinacas y tomate (low FODMAP)","en":"Baked eggs with spinach and tomato (low FODMAP)","fr":"Oeufs au plat epinards et tomate (low FODMAP)","it":"Uova al forno con spinaci e pomodoro (low FODMAP)"}',
'{"es":"Shakshuka simplificada low FODMAP: sin cebolla ni ajo, con aceite infusionado","en":"Simplified low FODMAP shakshuka: without onion or garlic, with infused oil"}',
5,15,320,18,12,22,4,
ARRAY['low_fodmap','gluten_free','lactose_free','keto','vegetarian','low_carb'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["3 huevos","200g espinacas frescas","300g tomates maduros pelados y troceados (o en conserva sin ajo ni cebolla)","2 cdas aceite de ajo infusionado","1 cdta pimentón","1/2 cdta comino","1/2 cdta cúrcuma","Sal, pimienta","Cebollino verde, perejil"],"en":["3 eggs","200g fresh spinach","300g ripe tomatoes peeled and chopped (or canned without garlic or onion)","2 tbsp garlic-infused oil","1 tsp paprika","1/2 tsp cumin","1/2 tsp turmeric","Salt, pepper","Green chives, parsley"]}',
'{"es":["Calienta el aceite en sartén, añade el pimentón, comino y cúrcuma, cocina 1 min","Añade el tomate y cocina 5-6 min hasta que espese","Incorpora las espinacas y mezcla hasta que se marchiten","Haz 3 huecos y rompe un huevo en cada uno","Cubre y cocina 4-5 min hasta que las claras estén cuajadas","Sirve con cebollino y perejil"],"en":["Heat oil in pan, add paprika, cumin and turmeric, cook 1 min","Add tomato and cook 5-6 min until thickened","Add spinach and stir until wilted","Make 3 wells and crack an egg in each","Cover and cook 4-5 min until whites are set","Serve with chives and parsley"]}'
),

('ternera_zanahoria_fodmap',290,'dinner','🥩',
'{"es":"Estofado de ternera y zanahoria (low FODMAP)","en":"Beef and carrot stew (low FODMAP)","fr":"Ragout de boeuf et carotte (low FODMAP)","it":"Stufato di manzo e carote (low FODMAP)"}',
'{"es":"Estofado reconfortante sin cebolla ni ajo: ternera tierna, zanahorias y caldo suave","en":"Comforting stew without onion or garlic: tender beef, carrots and gentle broth"}',
12,60,480,36,18,26,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','paleo'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'medium','over_40','low',
'{"es":["500g ternera para guisar en dados","4 zanahorias en rodajas gruesas","2 tallos de apio en rodajas","400ml caldo de ternera sin cebolla ni ajo","200ml agua","2 cdas aceite de ajo infusionado","1 cdta tomillo seco","1 cdta romero","1 cda pasta de tomate","Sal, pimienta","Perejil fresco"],"en":["500g stewing beef diced","4 carrots in thick slices","2 celery stalks sliced","400ml beef stock no onion or garlic","200ml water","2 tbsp garlic-infused oil","1 tsp dried thyme","1 tsp rosemary","1 tbsp tomato paste","Salt, pepper","Fresh parsley"]}',
'{"es":["Dora la ternera en el aceite a fuego alto 5-6 min, reserva","Añade el apio y las zanahorias, saltea 3 min","Incorpora la pasta de tomate, el caldo, el agua y las hierbas","Devuelve la carne al pot, tapa y cuece a fuego bajo 50-55 min","Sirve con perejil fresco y arroz basmati si quieres"],"en":["Brown beef in oil over high heat 5-6 min, set aside","Add celery and carrots, sauté 3 min","Add tomato paste, stock, water and herbs","Return meat to pot, cover and cook over low heat 50-55 min","Serve with fresh parsley and basmati rice if desired"]}'
),

-- ── LOW CARB ─────────────────────────────────────────────────────────────────

('bol_coliflor_arroz_pollo',291,'dinner','🥦',
'{"es":"Bol de arroz de coliflor con pollo teriyaki","en":"Cauliflower rice bowl with teriyaki chicken","fr":"Bowl de riz de chou-fleur poulet teriyaki","it":"Bowl di riso di cavolfiore con pollo teriyaki"}',
'{"es":"Arroz de coliflor como base low carb, con pollo glaseado en salsa teriyaki casera sin azúcar","en":"Cauliflower rice as low carb base, with chicken glazed in homemade sugar-free teriyaki"}',
10,18,360,36,12,20,4,
ARRAY['low_carb','keto','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY['soy'],
'medium','under_20','low',
'{"es":["2 pechugas de pollo en dados","1/2 coliflor grande rallada o procesada","2 cdas tamari","1 cda aceite de sésamo","1 cdta eritritol o stevia","1 cdta jengibre rallado","1 diente de ajo rallado","1 cdta maicena disuelta en agua","Sésamo, cebolleta verde"],"en":["2 chicken breasts diced","1/2 large cauliflower grated or processed","2 tbsp tamari","1 tbsp sesame oil","1 tsp erythritol or stevia","1 tsp grated ginger","1 garlic clove grated","1 tsp cornstarch dissolved in water","Sesame, spring onion"]}',
'{"es":["Prepara el arroz de coliflor: saltea la coliflor rallada en sartén seca 4-5 min, reserva","Mezcla el tamari, el sésamo, el eritritol, el jengibre y el ajo para la salsa","Dora el pollo en aceite 6-7 min","Vierte la salsa y la maicena, cocina 2 min más hasta que espese","Sirve el pollo sobre el arroz de coliflor con sésamo y cebolleta"],"en":["Make cauliflower rice: sauté grated cauliflower in dry pan 4-5 min, set aside","Mix tamari, sesame, erythritol, ginger and garlic for sauce","Brown chicken in oil 6-7 min","Pour sauce and cornstarch, cook 2 min more until thickened","Serve chicken over cauliflower rice with sesame and spring onion"]}'
),

('espagueti_calabacin_bolonesa',292,'dinner','🍝',
'{"es":"Espagueti de calabacín con boloñesa de ternera","en":"Courgette spaghetti with beef bolognese","fr":"Spaghetti de courgette bolognaise de boeuf","it":"Spaghetti di zucchine con bolognese di manzo"}',
'{"es":"Pasta zero carbs: espaguetis hechos de calabacín con boloñesa de ternera casera","en":"Zero carb pasta: courgette spaghetti with homemade beef bolognese"}',
10,25,380,32,14,22,5,
ARRAY['low_carb','keto','gluten_free','lactose_free','high_protein','paleo'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY[]::text[],
'medium','20_40','low',
'{"es":["3 calabacines grandes (espiralizados o con pelador en tiras)","300g carne picada de ternera","300g tomate triturado","1 cebolla picada","2 dientes de ajo","1 cdta orégano","1 cdta pimentón","2 cdas aceite de oliva","Sal, pimienta","Albahaca fresca"],"en":["3 large courgettes (spiralised or peeled into strips)","300g beef mince","300g crushed tomato","1 onion chopped","2 garlic cloves","1 tsp oregano","1 tsp paprika","2 tbsp olive oil","Salt, pepper","Fresh basil"]}',
'{"es":["Dora la carne en aceite a fuego alto 5 min, reserva","Sofríe la cebolla y el ajo 4 min","Añade el tomate, el orégano, el pimentón y la carne","Cuece a fuego medio 15 min","Saltea el calabacín en sartén seca 2-3 min (no sobrecocines)","Sirve la boloñesa sobre el calabacín con albahaca fresca"],"en":["Brown mince in oil over high heat 5 min, set aside","Sauté onion and garlic 4 min","Add tomato, oregano, paprika and mince","Cook over medium heat 15 min","Sauté courgette in dry pan 2-3 min (do not overcook)","Serve bolognese over courgette with fresh basil"]}'
),

('ensalada_pollo_cesar_lowcarb',293,'lunch','🥗',
'{"es":"Ensalada César con pollo a la plancha (low carb)","en":"Caesar salad with grilled chicken (low carb)","fr":"Salade Cesar poulet grille (low carb)","it":"Insalata Caesar con pollo alla griglia (low carb)"}',
'{"es":"César clásica sin picatostes: pollo jugoso, romana, parmesano y salsa césar casera","en":"Classic caesar without croutons: juicy chicken, romaine, parmesan and homemade caesar dressing"}',
10,12,440,40,6,28,2,
ARRAY['low_carb','keto','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','fish','dairy'],
'easy','under_20','medium',
'{"es":["2 pechugas de pollo","1 lechuga romana grande","40g parmesano en láminas","Para la salsa: 2 yemas de huevo, 1 cdta mostaza, 2 cdas aceite de oliva, 1 cda zumo de limón, 1 cdta pasta de anchoas, 1 diente de ajo, sal, pimienta"],"en":["2 chicken breasts","1 large romaine lettuce","40g parmesan shavings","For the dressing: 2 egg yolks, 1 tsp mustard, 2 tbsp olive oil, 1 tbsp lemon juice, 1 tsp anchovy paste, 1 garlic clove, salt, pepper"]}',
'{"es":["Cocina el pollo a la plancha 5-6 min por lado, deja reposar y corta en tiras","Prepara la salsa mezclando la yema, la mostaza, el limón y la pasta de anchoa, luego emulsiona con el aceite","Lava y trocea la romana, mezcla con la salsa","Distribuye el pollo y el parmesano encima"],"en":["Grill chicken 5-6 min per side, rest and slice","Make dressing by mixing yolk, mustard, lemon and anchovy paste, then emulsify with oil","Wash and chop romaine, toss with dressing","Arrange chicken and parmesan on top"]}'
),

('tortitas_proteina_lowcarb',294,'breakfast','🥞',
'{"es":"Tortitas de proteína y huevo (low carb)","en":"Protein egg pancakes (low carb)","fr":"Pancakes proteines aux oeufs (low carb)","it":"Pancakes proteici con uova (low carb)"}',
'{"es":"Tortitas esponjosas sin harina: solo huevo, queso crema y proteína — 3g de carbos por ración","en":"Fluffy flourless pancakes: egg, cream cheese and protein — 3g carbs per serving"}',
5,8,380,28,3,28,1,
ARRAY['low_carb','keto','gluten_free','vegetarian','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["3 huevos","80g queso crema","30g proteína de vainilla en polvo (sin azúcar)","1/2 cdta levadura","1 cdta canela","Aceite de coco para cocinar","Frutos rojos frescos para servir"],"en":["3 eggs","80g cream cheese","30g vanilla protein powder (no sugar)","1/2 tsp baking powder","1 tsp cinnamon","Coconut oil for cooking","Fresh berries to serve"]}',
'{"es":["Bate todos los ingredientes en batidora hasta obtener una masa suave","Calienta una sartén con aceite de coco a fuego medio","Vierte cucharadas de masa y cocina 2 min por lado","Repite con el resto de la masa","Sirve con frutos rojos frescos"],"en":["Blend all ingredients until you have a smooth batter","Heat a pan with coconut oil over medium heat","Pour spoonfuls of batter and cook 2 min per side","Repeat with remaining batter","Serve with fresh berries"]}'
),

('pizza_portobello_lowcarb',295,'dinner','🍕',
'{"es":"Pizza en sombrero portobello","en":"Portobello mushroom pizza","fr":"Pizza sur champignon portobello","it":"Pizza su fungo portobello"}',
'{"es":"Base de pizza zero carbs: sombrero de portobello con salsa, mozzarella y toppings","en":"Zero carb pizza base: portobello cap with sauce, mozzarella and toppings"}',
5,15,280,18,8,20,3,
ARRAY['low_carb','keto','gluten_free','vegetarian','low_fodmap'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["4 sombreros grandes de portobello","100g mozzarella rallada","4 cdas salsa de tomate casera sin azúcar","Orégano, pimentón","Toppings al gusto: pimiento, aceitunas, jamón serrano, rúcula","Sal, pimienta","Aceite de oliva"],"en":["4 large portobello caps","100g grated mozzarella","4 tbsp homemade sugar-free tomato sauce","Oregano, paprika","Toppings of choice: pepper, olives, cured ham, rocket","Salt, pepper","Olive oil"]}',
'{"es":["Precalienta el horno a 200°C","Limpia los portobellos y quita el pie","Coloca cara arriba en bandeja con papel, pincela con aceite y sazona","Hornea 5 min boca arriba","Rellena con la salsa de tomate, la mozzarella y los toppings","Hornea 8-10 min hasta que el queso burbujee"],"en":["Preheat oven to 200°C","Clean portobello caps and remove stems","Place gill-side up on lined tray, brush with oil and season","Bake 5 min gill-side up","Fill with tomato sauce, mozzarella and toppings","Bake 8-10 min until cheese bubbles"]}'
),

('sopa_miso_tofu_lowcarb',296,'dinner','🍜',
'{"es":"Sopa de miso con tofu y algas","en":"Miso soup with tofu and seaweed","fr":"Soupe miso tofu et algues","it":"Zuppa di miso con tofu e alghe"}',
'{"es":"Sopa japonesa reconfortante low carb: miso, tofu sedoso, alga wakame y cebolleta","en":"Comforting Japanese low carb soup: miso, silken tofu, wakame seaweed and spring onion"}',
5,8,180,14,8,10,2,
ARRAY['low_carb','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["2 cdas pasta de miso blanca","700ml agua o dashi vegetal","150g tofu sedoso en dados","5g alga wakame seca (se hidrata en agua fría)","Cebolleta verde en rodajas finas","1 cdta aceite de sésamo","Semillas de sésamo"],"en":["2 tbsp white miso paste","700ml water or vegetable dashi","150g silken tofu diced","5g dried wakame seaweed (soak in cold water)","Spring onion green part finely sliced","1 tsp sesame oil","Sesame seeds"]}',
'{"es":["Hidrata el alga wakame en agua fría 5 min, escurre","Calienta el agua o dashi sin hervir","Disuelve el miso en un poco de agua templada, añade al caldo","No hiervas el miso (destruye los probióticos)","Añade el tofu y el alga, calienta 2 min","Sirve con cebolleta, aceite de sésamo y sésamo"],"en":["Soak wakame in cold water 5 min, drain","Heat water or dashi without boiling","Dissolve miso in a little warm water, add to broth","Do not boil the miso (destroys probiotics)","Add tofu and seaweed, heat 2 min","Serve with spring onion, sesame oil and sesame seeds"]}'
),

('pollo_pesto_espirales_calabacin',297,'dinner','🌿',
'{"es":"Espirales de calabacín con pesto y pollo","en":"Courgette spirals with pesto and chicken","fr":"Spirales de courgette pesto et poulet","it":"Spirali di zucchine al pesto con pollo"}',
'{"es":"Low carb y mediterráneo: espirales de calabacín con pesto casero de albahaca y pollo","en":"Low carb and Mediterranean: courgette spirals with homemade basil pesto and chicken"}',
12,12,420,36,8,28,4,
ARRAY['low_carb','keto','gluten_free','high_protein','mediterranean'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['nuts','dairy'],
'easy','under_20','medium',
'{"es":["2 pechugas de pollo","3 calabacines grandes espiralizados","Para el pesto: 30g albahaca fresca, 30g parmesano, 30g piñones o nueces, 1 diente de ajo, 5 cdas aceite de oliva, sal, zumo de limón","Tomates cherry para servir"],"en":["2 chicken breasts","3 large courgettes spiralised","For pesto: 30g fresh basil, 30g parmesan, 30g pine nuts or walnuts, 1 garlic clove, 5 tbsp olive oil, salt, lemon juice","Cherry tomatoes to serve"]}',
'{"es":["Prepara el pesto triturando todos los ingredientes hasta obtener una salsa","Cocina el pollo a la plancha 5-6 min por lado, deja reposar y lamina","Saltea los espirales de calabacín en sartén seca 2 min (deben quedar al dente)","Mezcla con el pesto y el pollo","Sirve con tomates cherry y parmesano extra"],"en":["Make pesto by blending all ingredients into a sauce","Grill chicken 5-6 min per side, rest and slice","Sauté courgette spirals in dry pan 2 min (keep al dente)","Toss with pesto and chicken","Serve with cherry tomatoes and extra parmesan"]}'
),

('huevos_rancheros_lowcarb',298,'breakfast','🌶️',
'{"es":"Huevos rancheros low carb (sin tortilla)","en":"Low carb rancheros eggs (no tortilla)","fr":"Oeufs rancheros low carb (sans tortilla)","it":"Uova rancheros low carb (senza tortilla)"}',
'{"es":"Rancheros sin tortilla: huevos sobre salsa ranchera picante con aguacate y queso","en":"Rancheros without tortilla: eggs on spicy rancher sauce with avocado and cheese"}',
5,15,380,20,10,28,5,
ARRAY['low_carb','keto','gluten_free','vegetarian'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','under_20','low',
'{"es":["3 huevos","400g tomate triturado","1 pimiento rojo en dados","1 jalapeño o guindilla (opcional)","1 cdta comino","1 cdta pimentón ahumado","1 cda aceite de oliva","1/2 aguacate en láminas","30g queso cheddar rallado","Cilantro fresco","Sal, pimienta"],"en":["3 eggs","400g crushed tomato","1 red pepper diced","1 jalapeño or chilli (optional)","1 tsp cumin","1 tsp smoked paprika","1 tbsp olive oil","1/2 avocado sliced","30g grated cheddar","Fresh coriander","Salt, pepper"]}',
'{"es":["Sofríe el pimiento y la guindilla en aceite 3 min","Añade el tomate, el comino, el pimentón, sal y pimienta","Cuece 5-6 min hasta que la salsa espese","Haz 3 huecos, rompe los huevos dentro","Cubre y cuece 4-5 min","Sirve con aguacate, cheddar y cilantro"],"en":["Sauté pepper and chilli in oil 3 min","Add tomato, cumin, paprika, salt and pepper","Cook 5-6 min until sauce thickens","Make 3 wells, break eggs in","Cover and cook 4-5 min","Serve with avocado, cheddar and coriander"]}'
),

('ensalada_atun_aguacate_lowcarb',299,'lunch','🥑',
'{"es":"Ensalada de atún con aguacate y pepino","en":"Tuna avocado and cucumber salad","fr":"Salade de thon avocat-concombre","it":"Insalata di tonno con avocado e cetriolo"}',
'{"es":"Ensalada cremosa low carb: atún mezclado con aguacate en lugar de mayonesa","en":"Creamy low carb salad: tuna mixed with avocado instead of mayonnaise"}',
8,0,380,30,8,26,7,
ARRAY['low_carb','keto','gluten_free','lactose_free','high_protein','pescatarian'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','lose_weight','muscle'],
ARRAY['pcos'],
ARRAY['fish'],
'easy','under_20','low',
'{"es":["2 latas de atún en aceite de oliva","1 aguacate maduro machacado","1/2 pepino en dados pequeños","1/4 cebolla roja en brunoise fina","Zumo de 1 lima","Cilantro fresco picado","Sal, pimienta","Hojas de lechuga o endivias para servir"],"en":["2 cans tuna in olive oil","1 ripe avocado mashed","1/2 cucumber finely diced","1/4 red onion finely diced","Juice of 1 lime","Fresh chopped coriander","Salt, pepper","Lettuce leaves or endive to serve"]}',
'{"es":["Escurre el atún y desmenúza en un bol","Añade el aguacate machacado y mezcla bien","Incorpora el pepino, la cebolla, la lima y el cilantro","Sazona con sal y pimienta","Sirve en hojas de lechuga o endivias como cucharas"],"en":["Drain tuna and flake in a bowl","Add mashed avocado and mix well","Add cucumber, onion, lime and coriander","Season with salt and pepper","Serve in lettuce leaves or endive as scoops"]}'
),

('filete_merluza_pure_apio_lowcarb',300,'dinner','🐟',
'{"es":"Merluza con puré de apio nabo y mantequilla","en":"Hake with celeriac and butter mash","fr":"Cabillaud puree de celeri-rave au beurre","it":"Nasello con purea di sedano rapa e burro"}',
'{"es":"Merluza suave sobre puré cremoso de apio nabo — alternativa low carb a la patata","en":"Gentle hake on creamy celeriac mash — low carb alternative to potato"}',
10,22,400,34,14,22,5,
ARRAY['low_carb','gluten_free','pescatarian','low_fodmap','keto'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','muscle'],
ARRAY['sibo','ibs'],
ARRAY['fish','dairy'],
'medium','20_40','medium',
'{"es":["2 filetes de merluza","400g apio nabo pelado y en dados","2 cdas mantequilla","50ml leche sin lactosa o nata","Sal, pimienta blanca","Eneldo fresco","Zumo de limón","1 cda aceite de oliva"],"en":["2 hake fillets","400g celeriac peeled and diced","2 tbsp butter","50ml lactose-free milk or cream","Salt, white pepper","Fresh dill","Lemon juice","1 tbsp olive oil"]}',
'{"es":["Cuece el apio nabo en agua con sal 15-18 min hasta que esté tierno","Tritura con la mantequilla, la leche, sal y pimienta blanca hasta obtener un puré suave","Cocina la merluza en sartén con aceite de oliva 3-4 min por lado","Sirve sobre el puré con eneldo y zumo de limón"],"en":["Cook celeriac in salted water 15-18 min until tender","Blend with butter, milk, salt and white pepper until smooth mash","Cook hake in pan with olive oil 3-4 min per side","Serve on the mash with dill and lemon juice"]}'
),

('bol_huevo_verduras_lowcarb',301,'lunch','🥚',
'{"es":"Bol de huevo escalfado con verduras salteadas","en":"Poached egg bowl with sautéed vegetables","fr":"Bowl oeuf poche et legumes sautes","it":"Bowl di uova in camicia con verdure saltate"}',
'{"es":"Bol low carb versátil: huevo escalfado sobre lecho de verduras salteadas y espinacas","en":"Versatile low carb bowl: poached egg over sautéed vegetable and spinach bed"}',
5,10,280,16,8,20,5,
ARRAY['low_carb','keto','gluten_free','vegetarian','lactose_free'],
ARRAY['follicular','ovulation','luteal','menstrual'],
ARRAY['maintain','energy','lose_weight'],
ARRAY['pcos'],
ARRAY['eggs'],
'medium','under_20','low',
'{"es":["2 huevos","150g espinacas baby","1 calabacín en dados","1 pimiento rojo en tiras","2 cdas aceite de oliva","1 cdta vinagre blanco (para el huevo escalfado)","Sal, pimienta","Pimentón ahumado"],"en":["2 eggs","150g baby spinach","1 courgette diced","1 red pepper in strips","2 tbsp olive oil","1 tsp white vinegar (for poached egg)","Salt, pepper","Smoked paprika"]}',
'{"es":["Saltea el calabacín y el pimiento en aceite 5 min, añade las espinacas y cocina 2 min más","Lleva a ebullición agua con el vinagre en una cacerola pequeña","Baja el fuego al mínimo, crea un remolino y deja caer el huevo suavemente","Cuece 3 min, retira con espumadera","Sirve el huevo sobre las verduras con pimentón, sal y pimienta"],"en":["Sauté courgette and pepper in oil 5 min, add spinach and cook 2 min more","Bring a small saucepan of water with vinegar to a boil","Lower to a gentle simmer, create a swirl and drop in egg gently","Cook 3 min, remove with slotted spoon","Serve egg over vegetables with paprika, salt and pepper"]}'
),

('carne_picada_boniato_lowcarb',302,'dinner','🍠',
'{"es":"Sartén de carne picada con boniato y especias","en":"Minced meat and sweet potato skillet","fr":"Poele viande hachee et patate douce","it":"Padella di carne macinata e patata dolce"}',
'{"es":"Sartén one-pan: carne picada especiada con boniato en dados — equilibrio low carb nutritivo","en":"One-pan skillet: spiced minced meat with diced sweet potato — balanced nutritious low carb"}',
8,20,460,30,28,22,5,
ARRAY['low_carb','paleo','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g carne picada de ternera","1 boniato mediano en dados pequeños","1 pimiento rojo en dados","1 cebolla en dados","2 dientes de ajo","1 cdta comino","1 cdta pimentón ahumado","1 cdta orégano","2 cdas aceite de oliva","Sal, pimienta","Cilantro o perejil fresco"],"en":["300g beef mince","1 medium sweet potato diced small","1 red pepper diced","1 onion diced","2 garlic cloves","1 tsp cumin","1 tsp smoked paprika","1 tsp oregano","2 tbsp olive oil","Salt, pepper","Fresh coriander or parsley"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 3 min","Añade el boniato y cocina 5 min removiendo","Sube el fuego, añade la carne y desmiga mientras se dora 5 min","Añade el pimiento y las especias, cocina 5 min más","Ajusta de sal y sirve con cilantro fresco"],"en":["Sauté onion and garlic in oil 3 min","Add sweet potato and cook 5 min stirring","Turn up heat, add mince and break up while browning 5 min","Add pepper and spices, cook 5 min more","Adjust salt and serve with fresh coriander"]}'
),

('crema_brocoli_lowcarb',303,'dinner','🥦',
'{"es":"Crema de brócoli y queso (low carb)","en":"Broccoli and cheese cream soup (low carb)","fr":"Creme de brocoli au fromage (low carb)","it":"Crema di broccoli e formaggio (low carb)"}',
'{"es":"Sopa cremosa low carb: brócoli, nata y cheddar — reconfortante y sin patata","en":"Creamy low carb soup: broccoli, cream and cheddar — comforting and potato-free"}',
5,18,320,14,12,24,5,
ARRAY['low_carb','keto','gluten_free','vegetarian'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["500g brócoli en flores","100ml nata para cocinar","80g cheddar curado rallado","500ml caldo de verduras","1 cebolla en dados","2 dientes de ajo","2 cdas aceite de oliva","Sal, pimienta","Nuez moscada","Más cheddar para decorar"],"en":["500g broccoli florets","100ml cooking cream","80g aged cheddar grated","500ml vegetable stock","1 onion diced","2 garlic cloves","2 tbsp olive oil","Salt, pepper","Nutmeg","More cheddar to garnish"]}',
'{"es":["Sofríe la cebolla y el ajo en aceite 4 min","Añade el brócoli y el caldo, cuece 12-15 min hasta que el brócoli esté tierno","Tritura hasta obtener una crema","Incorpora la nata y el cheddar, mezcla hasta que se derrita","Ajusta de sal, pimienta y nuez moscada","Sirve con cheddar extra rallado por encima"],"en":["Sauté onion and garlic in oil 4 min","Add broccoli and stock, cook 12-15 min until broccoli is tender","Blend until smooth","Add cream and cheddar, stir until melted","Adjust salt, pepper and nutmeg","Serve with extra grated cheddar on top"]}'
),

('wrap_lechuga_hummus_verduras_lowcarb',304,'lunch','🥬',
'{"es":"Wrap de lechuga con hummus y verduras crudas","en":"Lettuce wrap with hummus and raw vegetables","fr":"Wrap de laitue hummus et crudites","it":"Wrap di lattuga con hummus e verdure crude"}',
'{"es":"Snack-almuerzo low carb: hojas de lechuga rellenas de hummus, zanahoria y pepino crujiente","en":"Low carb snack-lunch: lettuce leaves filled with hummus, carrot and crunchy cucumber"}',
8,0,240,8,18,16,6,
ARRAY['low_carb','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy','lose_weight'],
ARRAY['pcos'],
ARRAY['sesame'],
'easy','under_20','low',
'{"es":["6 hojas grandes de lechuga romana o iceberg","4 cdas hummus","1 zanahoria en bastones","1/2 pepino en bastones","1/2 pimiento rojo en tiras","Rábanos en láminas","Zumo de limón","Pimentón para decorar","Semillas de sésamo"],"en":["6 large romaine or iceberg lettuce leaves","4 tbsp hummus","1 carrot in sticks","1/2 cucumber in sticks","1/2 red pepper in strips","Radishes sliced","Lemon juice","Paprika to garnish","Sesame seeds"]}',
'{"es":["Unta cada hoja de lechuga con hummus","Distribuye las verduras crudas en bastones sobre el hummus","Exprime un poco de limón y espolvorea pimentón y sésamo","Come inmediatamente para que la lechuga quede crujiente"],"en":["Spread hummus on each lettuce leaf","Arrange raw vegetables as sticks over the hummus","Squeeze a little lemon and sprinkle paprika and sesame","Eat immediately so the lettuce stays crunchy"]}'
),

('salmón_verduras_horno_lowcarb',305,'dinner','🐠',
'{"es":"Salmón con espinacas y tomate cherry al horno","en":"Baked salmon with spinach and cherry tomato","fr":"Saumon epinards et tomates cerises au four","it":"Salmone con spinaci e pomodorini al forno"}',
'{"es":"Bandeja low carb de salmón y verduras al horno en 20 minutos, sin complicaciones","en":"Low carb sheet pan of salmon and vegetables baked in 20 minutes, no fuss"}',
5,18,440,36,8,28,4,
ARRAY['low_carb','keto','gluten_free','lactose_free','pescatarian','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY['fish'],
'easy','under_20','medium',
'{"es":["2 filetes de salmón","200g espinacas baby","200g tomates cherry","3 cdas aceite de oliva","2 dientes de ajo laminados","Zumo de 1 limón","Tomillo fresco","Sal, pimienta"],"en":["2 salmon fillets","200g baby spinach","200g cherry tomatoes","3 tbsp olive oil","2 garlic cloves sliced","Juice of 1 lemon","Fresh thyme","Salt, pepper"]}',
'{"es":["Precalienta el horno a 200°C","Coloca las espinacas en el centro de una bandeja con papel","Distribuye los tomates cherry y el ajo alrededor","Coloca el salmón encima de las espinacas","Riega todo con aceite, limón y tomillo, sazona","Hornea 18-20 min"],"en":["Preheat oven to 200°C","Place spinach in the centre of a lined tray","Scatter cherry tomatoes and garlic around","Place salmon on top of spinach","Drizzle everything with oil, lemon and thyme, season","Bake 18-20 min"]}'
),

('bol_proteico_queso_cottage_lowcarb',306,'breakfast','🥛',
'{"es":"Bol de queso cottage con frutos rojos y semillas","en":"Cottage cheese bowl with berries and seeds","fr":"Bowl fromage blanc fruits rouges et graines","it":"Bowl di fiocchi di latte con frutti rossi e semi"}',
'{"es":"Desayuno proteico low carb: queso cottage cremoso con frutos rojos, linaza y frutos secos","en":"Low carb protein breakfast: creamy cottage cheese with berries, flaxseed and nuts"}',
5,0,300,22,14,16,4,
ARRAY['low_carb','gluten_free','vegetarian','high_protein','keto'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['pcos'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["200g queso cottage","100g frutos rojos mixtos frescos o congelados","1 cda semillas de linaza molidas","1 cda nueces picadas","1 cdta canela","Extracto de vainilla","Miel o stevia al gusto"],"en":["200g cottage cheese","100g fresh or frozen mixed berries","1 tbsp ground flaxseed","1 tbsp chopped walnuts","1 tsp cinnamon","Vanilla extract","Honey or stevia to taste"]}',
'{"es":["Coloca el queso cottage en un bol","Añade la vainilla y la canela, mezcla suavemente","Cubre con los frutos rojos, la linaza y las nueces","Endulza al gusto con miel o stevia"],"en":["Place cottage cheese in a bowl","Add vanilla and cinnamon, mix gently","Top with berries, flaxseed and walnuts","Sweeten to taste with honey or stevia"]}'
),

('pollo_verduras_wok_lowcarb',307,'dinner','🥢',
'{"es":"Wok de pollo con verduras y salsa de jengibre","en":"Chicken and vegetable wok with ginger sauce","fr":"Wok de poulet legumes-sauce gingembre","it":"Wok di pollo con verdure e salsa allo zenzero"}',
'{"es":"Wok express low carb: pollo, brócoli, pimiento y zanahoria con salsa ligera de jengibre","en":"Express low carb wok: chicken, broccoli, pepper and carrot with light ginger sauce"}',
10,12,380,36,14,18,5,
ARRAY['low_carb','gluten_free','lactose_free','high_protein','low_fodmap'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['pcos'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["300g pechuga de pollo en tiras","150g brócoli en flores pequeñas","1 pimiento rojo en tiras","2 zanahorias en juliana","1 cdta jengibre fresco rallado","2 cdas tamari o salsa de soja sin gluten","1 cda aceite de sésamo","1 cda aceite de oliva","Cebolleta verde, sésamo"],"en":["300g chicken breast in strips","150g broccoli in small florets","1 red pepper in strips","2 carrots julienned","1 tsp fresh grated ginger","2 tbsp tamari or gluten-free soy sauce","1 tbsp sesame oil","1 tbsp olive oil","Spring onion, sesame"]}',
'{"es":["Calienta el wok o sartén grande a fuego muy alto","Saltea el pollo en aceite de oliva 4-5 min hasta dorado, reserva","Saltea las verduras 4 min a fuego alto (que queden al dente)","Devuelve el pollo, añade el tamari, el sésamo y el jengibre","Mezcla 1 min a fuego alto","Sirve con cebolleta verde y sésamo tostado"],"en":["Heat wok or large pan over very high heat","Sauté chicken in olive oil 4-5 min until golden, set aside","Stir-fry vegetables 4 min on high heat (keep them al dente)","Return chicken, add tamari, sesame oil and ginger","Toss 1 min over high heat","Serve with spring onion and toasted sesame"]}'
),

('panacotta_coco_lowcarb',308,'snack','🥥',
'{"es":"Panna cotta de coco sin azúcar","en":"Sugar-free coconut panna cotta","fr":"Panna cotta coco sans sucre","it":"Panna cotta al cocco senza zucchero"}',
'{"es":"Postre low carb cremoso con leche de coco y gelatina — sin azúcar, sin lactosa","en":"Creamy low carb dessert with coconut milk and gelatine — no sugar, no lactose"}',
5,5,220,4,6,20,1,
ARRAY['low_carb','keto','gluten_free','lactose_free','vegan'],
ARRAY['follicular','luteal'],
ARRAY['maintain','reduce_symptoms'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["400ml leche de coco entera en conserva","1 cdta agar-agar en polvo (o 2 láminas de gelatina si no es vegan)","2-3 cdas eritritol o stevia al gusto","1 cdta extracto de vainilla","Frutos rojos frescos para servir","Menta fresca"],"en":["400ml full-fat canned coconut milk","1 tsp agar-agar powder (or 2 gelatine sheets if not vegan)","2-3 tbsp erythritol or stevia to taste","1 tsp vanilla extract","Fresh berries to serve","Fresh mint"]}',
'{"es":["Mezcla la leche de coco, el agar-agar, el eritritol y la vainilla en un cazo","Calienta a fuego medio removiendo hasta que el agar-agar se disuelva (2-3 min), no hiervas","Vierte en moldes individuales o vasos","Refrigera al menos 3 horas hasta cuajar","Sirve con frutos rojos y menta fresca"],"en":["Mix coconut milk, agar-agar, erythritol and vanilla in a saucepan","Heat over medium heat stirring until agar-agar dissolves (2-3 min), do not boil","Pour into individual moulds or glasses","Refrigerate at least 3 hours until set","Serve with fresh berries and mint"]}'
),

('ensalada_col_salmón_lowcarb',309,'lunch','🥗',
'{"es":"Ensalada de col rizada con salmón y vinagreta de mostaza","en":"Kale salad with salmon and mustard dressing","fr":"Salade de chou frise saumon et vinaigrette moutarde","it":"Insalata di cavolo riccio con salmone e vinaigrette alla senape"}',
'{"es":"Col rizada masajeada con vinagreta de mostaza, salmón asado y semillas — superalimento low carb","en":"Massaged kale with mustard dressing, roasted salmon and seeds — low carb superfood"}',
10,15,480,36,12,30,5,
ARRAY['low_carb','keto','gluten_free','lactose_free','pescatarian','high_protein','anti_inflammatory'],
ARRAY['menstrual','follicular'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['endometriosis','anemia'],
ARRAY['fish','mustard'],
'medium','under_20','medium',
'{"es":["2 filetes de salmón","150g col rizada (kale) sin tallos","Para la vinagreta: 2 cdas aceite de oliva, 1 cda mostaza Dijon, 1 cda zumo de limón, 1 cdta miel, sal, pimienta","Pepino en dados","30g semillas mixtas (girasol, calabaza)"],"en":["2 salmon fillets","150g kale without stems","For dressing: 2 tbsp olive oil, 1 tbsp Dijon mustard, 1 tbsp lemon juice, 1 tsp honey, salt, pepper","Cucumber diced","30g mixed seeds (sunflower, pumpkin)"]}',
'{"es":["Hornea el salmón a 200°C 15 min con aceite, sal y pimienta","Prepara la vinagreta mezclando todos los ingredientes","Masajea la col rizada con la mitad de la vinagreta durante 1-2 min (ablanda las hojas)","Monta la ensalada con la col, el pepino y las semillas","Coloca el salmón encima y riega con el resto de la vinagreta"],"en":["Roast salmon at 200°C 15 min with oil, salt and pepper","Prepare dressing by mixing all ingredients","Massage kale with half the dressing for 1-2 min (softens the leaves)","Build salad with kale, cucumber and seeds","Place salmon on top and drizzle with remaining dressing"]}'
),

('pimientos_rellenos_lowcarb',310,'dinner','🫑',
'{"es":"Pimientos rellenos de carne y verduras","en":"Peppers stuffed with meat and vegetables","fr":"Poivrons farcis viande et legumes","it":"Peperoni ripieni di carne e verdure"}',
'{"es":"Pimientos rellenos clásicos sin arroz: carne picada especiada con verduras y tomate","en":"Classic stuffed peppers without rice: spiced minced meat with vegetables and tomato"}',
12,35,420,28,18,24,6,
ARRAY['low_carb','keto','gluten_free','lactose_free','paleo','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY[]::text[],
ARRAY[]::text[],
'medium','over_40','low',
'{"es":["4 pimientos grandes (rojo, amarillo o verde)","300g carne picada de ternera o pollo","1 cebolla picada","2 dientes de ajo","200g tomate triturado","1 calabacín pequeño en dados","1 cdta comino","1 cdta orégano","1 cdta pimentón","2 cdas aceite de oliva","Sal, pimienta","Perejil fresco"],"en":["4 large peppers (red, yellow or green)","300g beef or chicken mince","1 onion chopped","2 garlic cloves","200g crushed tomato","1 small courgette diced","1 tsp cumin","1 tsp oregano","1 tsp paprika","2 tbsp olive oil","Salt, pepper","Fresh parsley"]}',
'{"es":["Precalienta el horno a 190°C","Corta la tapa de los pimientos y vacíalos con cuidado","Sofríe la cebolla y el ajo en aceite 4 min","Añade la carne y dórala 5 min","Incorpora el calabacín, el tomate y las especias, cuece 8 min","Rellena los pimientos con la mezcla","Coloca en bandeja y hornea 30 min tapados con su tapa","Sirve con perejil fresco"],"en":["Preheat oven to 190°C","Cut the tops off the peppers and hollow them out","Sauté onion and garlic in oil 4 min","Add mince and brown 5 min","Add courgette, tomato and spices, cook 8 min","Stuff peppers with the mixture","Place on tray and bake 30 min covered with their tops","Serve with fresh parsley"]}'
)

ON CONFLICT (id) DO NOTHING;
