-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 5 (+30) — display_order 161-190
-- Enfocado en: pescatarian, paleo, standard, snacks pre-entreno
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 4
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

-- ── SNACKS PRE-ENTRENO ────────────────────────────────────────────────────────

('datiles_tahini_snack',161,'morning_snack','🌴',
'{"es":"Dátiles rellenos de tahini y almendras","en":"Dates stuffed with tahini and almonds","fr":"Dattes farcies au tahini et amandes","it":"Datteri ripieni di tahini e mandorle"}',
'{"es":"Snack de energía rápida: azúcar natural + grasas y proteína para aguantar","en":"Quick energy snack: natural sugar + fats and protein to sustain you"}',
3,0,180,4,28,7,3,
ARRAY['vegan','gluten_free','vegetarian','paleo'],
ARRAY['ovulation','follicular'],
ARRAY['energy','muscle'],
ARRAY[]::text[],
ARRAY['nuts','sesame'],
'easy','under_20','low',
'{"es":["4 dátiles Medjool grandes","2 cdas tahini","4 almendras enteras","Sal marina"],"en":["4 large Medjool dates","2 tbsp tahini","4 whole almonds","Sea salt"]}',
'{"es":["Abre los dátiles por la mitad y retira el hueso","Rellena cada uno con media cucharadita de tahini y una almendra","Espolvorea una pizca de sal marina"],"en":["Open dates in half and remove the stone","Fill each one with half a teaspoon of tahini and one almond","Sprinkle a pinch of sea salt"]}'
),

('batido_preentrenamiento',162,'morning_snack','💪',
'{"es":"Batido pre-entreno de plátano y café","en":"Banana and coffee pre-workout shake","fr":"Shake pré-entraînement banane-café","it":"Shake pre-allenamento banana e caffè"}',
'{"es":"Cafeína + glucosa rápida + proteína = energía óptima para entrenar","en":"Caffeine + fast glucose + protein = optimal energy to train"}',
3,0,290,24,38,3,3,
ARRAY['vegetarian','gluten_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','energy'],
ARRAY['fatigue'],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["1 plátano congelado","1 espresso frío (o 100ml café)","1 scoop proteína de suero","150ml leche desnatada o vegetal","1 cdta cacao puro"],"en":["1 frozen banana","1 cold espresso (or 100ml coffee)","1 scoop whey protein","150ml skimmed or plant milk","1 tsp pure cocoa"]}',
'{"es":["Mezcla todos los ingredientes en la batidora","Tritura 30-45 segundos","Consume 30 min antes del entrenamiento"],"en":["Add all ingredients to blender","Blend 30-45 seconds","Consume 30 min before workout"]}'
),

('tostada_aguacate_huevo',163,'morning_snack','🥑',
'{"es":"Tostada de aguacate y huevo cocido","en":"Avocado toast with boiled egg","fr":"Toast avocat-oeuf dur","it":"Toast avocado e uovo sodo"}',
'{"es":"Clásico saciante: fibra + proteína + grasas saludables en 10 min","en":"Satisfying classic: fibre + protein + healthy fats in 10 min"}',
3,7,310,14,26,16,7,
ARRAY['vegetarian','mediterranean'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['energy','muscle','maintain'],
ARRAY[]::text[],
ARRAY['gluten','eggs'],
'easy','under_20','low',
'{"es":["2 rebanadas pan integral","1/2 aguacate","1 huevo","Sal, pimienta, copos de chile (opt)","Zumo de limón"],"en":["2 slices wholegrain bread","1/2 avocado","1 egg","Salt, pepper, chilli flakes (opt)","Lemon juice"]}',
'{"es":["Cuece el huevo 7 min en agua hirviendo para yema cremosa","Tuesta el pan","Aplasta el aguacate con limón, sal y pimienta","Extiende sobre el pan y coloca el huevo en rodajas encima"],"en":["Boil egg 7 min in boiling water for creamy yolk","Toast the bread","Mash avocado with lemon, salt and pepper","Spread on toast and top with sliced egg"]}'
),

-- ── DESAYUNOS ─────────────────────────────────────────────────────────────────

('granola_casera_sin_azucar',164,'breakfast','🥣',
'{"es":"Granola casera sin azúcar añadido","en":"Homemade sugar-free granola","fr":"Granola maison sans sucre ajouté","it":"Granola casalinga senza zuccheri aggiunti"}',
'{"es":"Granola crujiente de avena, semillas y frutos secos sin azúcar añadido","en":"Crunchy oat, seed and nut granola with no added sugar"}',
5,25,380,10,42,18,6,
ARRAY['vegan','vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['gluten','nuts'],
'easy','20_40','low',
'{"es":["200g copos de avena","50g nueces picadas","30g semillas de calabaza","30g semillas de girasol","3 cdas aceite de coco derretido","2 cdas sirope de arce","1 cdta canela","1 pizca sal","50g arándanos secos (opt)"],"en":["200g rolled oats","50g chopped walnuts","30g pumpkin seeds","30g sunflower seeds","3 tbsp melted coconut oil","2 tbsp maple syrup","1 tsp cinnamon","1 pinch salt","50g dried blueberries (opt)"]}',
'{"es":["Mezcla avena, frutos secos, semillas, canela y sal","Añade aceite de coco y sirope, mezcla bien","Extiende en bandeja de horno","Hornea 20-25 min a 170°C, removiendo a mitad","Deja enfriar completamente (se endurece). Añade arándanos secos"],"en":["Mix oats, nuts, seeds, cinnamon and salt","Add coconut oil and maple syrup, mix well","Spread on baking tray","Bake 20-25 min at 170°C, stirring halfway","Cool completely (it will crisp up). Add dried blueberries"]}'
),

('crepes_trigo_sarraceno',165,'breakfast','🥞',
'{"es":"Crêpes de trigo sarraceno","en":"Buckwheat crepes","fr":"Crêpes au sarrasin","it":"Crêpe al grano saraceno"}',
'{"es":"Sin gluten, ricas en fibra — sirve con frutas o con relleno salado","en":"Gluten-free, rich in fibre — serve with fruit or savoury filling"}',
5,10,300,10,42,10,5,
ARRAY['vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['eggs'],
'easy','under_20','low',
'{"es":["100g harina de trigo sarraceno","200ml leche vegetal","1 huevo","1 pizca sal","Aceite de coco para la sartén","Relleno: plátano + mantequilla de almendras"],"en":["100g buckwheat flour","200ml plant milk","1 egg","1 pinch salt","Coconut oil for pan","Filling: banana + almond butter"]}',
'{"es":["Bate harina, leche, huevo y sal hasta masa sin grumos","Deja reposar 10 min","Calienta sartén con aceite y vierte una cucharón de masa","Cocina 2 min por lado. Repite","Rellena con plátano y mantequilla de almendras"],"en":["Whisk flour, milk, egg and salt to smooth batter","Rest 10 min","Heat pan with oil and pour one ladle of batter","Cook 2 min per side. Repeat","Fill with banana and almond butter"]}'
),

('huevos_turcos',166,'breakfast','🍳',
'{"es":"Huevos turcos con yogur y chile","en":"Turkish eggs with yogurt and chilli","fr":"Oeufs turcs au yaourt et piment","it":"Uova turche con yogurt e peperoncino"}',
'{"es":"Cilbir: huevo escalfado sobre yogur de ajo con mantequilla de chile — espectacular","en":"Cilbir: poached egg on garlic yogurt with chilli butter — spectacular"}',
5,5,280,16,10,18,1,
ARRAY['vegetarian','gluten_free'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['energy','muscle'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'medium','under_20','low',
'{"es":["2 huevos muy frescos","150g yogur griego","1 diente ajo picado fino","1 cda mantequilla","1 cdta pimentón ahumado o chile en copos","Vinagre blanco, sal, eneldo fresco"],"en":["2 very fresh eggs","150g Greek yogurt","1 garlic clove finely minced","1 tbsp butter","1 tsp smoked paprika or chilli flakes","White vinegar, salt, fresh dill"]}',
'{"es":["Mezcla yogur con ajo y sal, extiende en el plato","Hierve agua con un chorro de vinagre para escalfar huevos","Escafa los huevos 3-4 min, coloca sobre el yogur","Funde la mantequilla con el pimentón y vierte encima","Decora con eneldo"],"en":["Mix yogurt with garlic and salt, spread on plate","Boil water with splash of vinegar for poaching","Poach eggs 3-4 min, place over yogurt","Melt butter with paprika and drizzle on top","Garnish with dill"]}'
),

-- ── ALMUERZOS ─────────────────────────────────────────────────────────────────

('ensalada_nicoise',167,'lunch','🫒',
'{"es":"Ensalada Niçoise","en":"Niçoise salad","fr":"Salade niçoise","it":"Insalata Niçoise"}',
'{"es":"La ensalada mediterránea por excelencia: atún, judías y huevo","en":"The quintessential Mediterranean salad: tuna, beans and egg"}',
15,8,420,30,28,18,7,
ARRAY['pescatarian','gluten_free','lactose_free','mediterranean','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'easy','20_40','medium',
'{"es":["2 huevos","150g atún al natural (lata)","100g judías verdes","150g patata pequeña hervida","Tomates cherry","Aceitunas negras","Alcaparras","Vinagreta: aceite, limón, mostaza, sal"],"en":["2 eggs","150g tuna in water (can)","100g green beans","150g small boiled potato","Cherry tomatoes","Black olives","Capers","Dressing: oil, lemon, mustard, salt"]}',
'{"es":["Cuece los huevos 8 min y las judías 4 min","Prepara la vinagreta mezclando sus ingredientes","Coloca todos los elementos en una fuente amplia","Aliña y sirve a temperatura ambiente"],"en":["Boil eggs 8 min and green beans 4 min","Make vinaigrette by mixing its ingredients","Arrange all elements on a large plate","Dress and serve at room temperature"]}'
),

('poke_bowl_salmon',168,'lunch','🍱',
'{"es":"Poke bowl de salmón y arroz","en":"Salmon and rice poke bowl","fr":"Poke bowl saumon-riz","it":"Poke bowl salmone e riso"}',
'{"es":"El bowl hawaiano de moda: salmón marinado, arroz y verduras frescas","en":"The trendy Hawaiian bowl: marinated salmon, rice and fresh vegetables"}',
15,12,490,30,52,14,5,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['fish','soy','sesame'],
'medium','20_40','high',
'{"es":["150g salmón fresco en dados","80g arroz de sushi cocido","1/2 aguacate","Edamame, pepino, zanahoria","Salsa: 2 cdas tamari, 1 cdta aceite de sésamo, 1 cdta mirin","Sésamo, algas nori en tiras"],"en":["150g fresh salmon diced","80g cooked sushi rice","1/2 avocado","Edamame, cucumber, carrot","Sauce: 2 tbsp tamari, 1 tsp sesame oil, 1 tsp mirin","Sesame, nori strips"]}',
'{"es":["Marina el salmón en tamari, sésamo y mirin 10 min","Cuece el arroz y déjalo templar","Monta el bol: arroz, salmón, aguacate, verduras","Añade la salsa restante, sésamo y algas"],"en":["Marinate salmon in tamari, sesame and mirin 10 min","Cook rice and let it cool slightly","Assemble bowl: rice, salmon, avocado, vegetables","Add remaining sauce, sesame and nori"]}'
),

('gazpacho_andaluz',169,'lunch','🍅',
'{"es":"Gazpacho andaluz clásico","en":"Classic Andalusian gazpacho","fr":"Gaspacho andalou classique","it":"Gazpacho andaluso classico"}',
'{"es":"Sopa fría de tomate: refrescante, baja en calorías y llena de vitaminas","en":"Cold tomato soup: refreshing, low calorie and packed with vitamins"}',
15,0,180,4,22,8,5,
ARRAY['vegan','gluten_free','vegetarian','mediterranean','low_carb','lactose_free'],
ARRAY['ovulation','follicular'],
ARRAY['lose_weight','maintain'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["800g tomates maduros","1/2 pepino","1/2 pimiento verde","1 diente ajo","2 cdas aceite de oliva virgen extra","1 cda vinagre de jerez","Sal, agua fría","Pan del día anterior (opt, sin gluten)"],"en":["800g ripe tomatoes","1/2 cucumber","1/2 green pepper","1 garlic clove","2 tbsp extra virgin olive oil","1 tbsp sherry vinegar","Salt, cold water","Day-old bread (opt, gluten-free)"]}',
'{"es":["Tritura todos los ingredientes en batidora potente","Añade agua hasta conseguir la consistencia deseada","Cuela si quieres textura fina","Refrigera mínimo 2h antes de servir"],"en":["Blend all ingredients in a powerful blender","Add water to reach desired consistency","Strain for finer texture if desired","Refrigerate at least 2h before serving"]}'
),

('fajitas_pollo_sin_gluten',170,'lunch','🌮',
'{"es":"Fajitas de pollo sin gluten","en":"Gluten-free chicken fajitas","fr":"Fajitas de poulet sans gluten","it":"Fajitas di pollo senza glutine"}',
'{"es":"Fajitas en tortillas de maíz: mexicano clásico sin gluten","en":"Fajitas in corn tortillas: classic Mexican gluten-free"}',
10,15,420,32,42,10,6,
ARRAY['gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["250g pechuga de pollo en tiras","1 pimiento rojo, 1 verde en tiras","1/2 cebolla en juliana","4 tortillas de maíz","1 cdta comino, pimentón, orégano","Aceite de oliva, sal","Guacamole, pico de gallo (opt)"],"en":["250g chicken breast in strips","1 red, 1 green pepper in strips","1/2 onion in julienne","4 corn tortillas","1 tsp cumin, paprika, oregano","Olive oil, salt","Guacamole, pico de gallo (opt)"]}',
'{"es":["Sazona el pollo con especias","Saltea pollo en aceite 5-6 min hasta dorado","Añade pimientos y cebolla, cocina 5 min más","Calienta las tortillas y sirve con los rellenos"],"en":["Season chicken with spices","Sauté chicken in oil 5-6 min until golden","Add peppers and onion, cook 5 more min","Warm tortillas and serve with fillings"]}'
),

('lentejas_salmon_espinacas',171,'lunch','🫘',
'{"es":"Lentejas con salmón y espinacas","en":"Lentils with salmon and spinach","fr":"Lentilles au saumon et épinards","it":"Lenticchie con salmone e spinaci"}',
'{"es":"Combinación de hierro vegetal + omega-3 ideal para la fase menstrual","en":"Plant iron + omega-3 combination ideal for the menstrual phase"}',
5,20,440,34,36,12,10,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['energy','maintain'],
ARRAY['anemia','fatigue','cramps'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["240g lentejas cocidas (lata)","150g salmón en conserva al natural","100g espinacas baby","1/2 cebolla roja","Vinagreta: aceite de oliva, limón, mostaza","Sal, pimienta"],"en":["240g cooked lentils (can)","150g canned salmon in water","100g baby spinach","1/2 red onion","Dressing: olive oil, lemon, mustard","Salt, pepper"]}',
'{"es":["Calienta levemente las lentejas en una sartén","Retira del fuego y añade espinacas — se marchitarán con el calor residual","Desmenuza el salmón y añade junto con la cebolla roja","Aliña y sirve templado o frío"],"en":["Warm lentils briefly in a pan","Remove from heat and add spinach — it wilts with residual heat","Flake salmon and add with red onion","Dress and serve warm or cold"]}'
),

('musaka_ligera',172,'lunch','🫙',
'{"es":"Musaka ligera de berenjenas","en":"Light aubergine moussaka","fr":"Moussaka légère aux aubergines","it":"Moussaka leggera di melanzane"}',
'{"es":"Musaka griega aligerada: cordero + berenjena + bechamel de yogur","en":"Lightened Greek moussaka: lamb + aubergine + yogurt béchamel"}',
20,35,420,28,28,20,8,
ARRAY['gluten_free','high_protein','mediterranean'],
ARRAY['luteal','follicular'],
ARRAY['maintain','muscle'],
ARRAY[]::text[],
ARRAY['dairy','eggs'],
'medium','40_60','medium',
'{"es":["2 berenjenas","300g carne picada de cordero o ternera","400g tomate triturado","1/2 cebolla, 2 dientes ajo","Canela, comino, sal","Bechamel light: 200g yogur griego, 2 huevos, pizca nuez moscada"],"en":["2 aubergines","300g minced lamb or beef","400g crushed tomatoes","1/2 onion, 2 garlic cloves","Cinnamon, cumin, salt","Light béchamel: 200g Greek yogurt, 2 eggs, pinch nutmeg"]}',
'{"es":["Corta berenjenas en rodajas y hornea 15 min a 200°C","Sofríe carne con cebolla y ajo, añade tomate y especias, cocina 15 min","Mezcla yogur con huevos y nuez moscada para la bechamel","Monta: berenjena, carne, berenjena, bechamel","Hornea 20 min más"],"en":["Slice aubergines and bake 15 min at 200°C","Brown meat with onion and garlic, add tomatoes and spices, cook 15 min","Mix yogurt with eggs and nutmeg for béchamel","Layer: aubergine, meat, aubergine, béchamel","Bake 20 more min"]}'
),

-- ── CENAS ─────────────────────────────────────────────────────────────────────

('bacalao_tomate_aceitunas',173,'dinner','🐟',
'{"es":"Bacalao al horno con tomate y aceitunas","en":"Baked cod with tomato and olives","fr":"Cabillaud au four, tomate-olives","it":"Merluzzo al forno con pomodoro e olive"}',
'{"es":"Pescado blanco con salsa mediterránea: bajo en grasa y muy sabroso","en":"White fish with Mediterranean sauce: low fat and very flavourful"}',
5,20,290,34,10,10,3,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb','mediterranean'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['lose_weight','muscle'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["2 lomos de bacalao fresco (150g c/u)","300g tomate cherry","60g aceitunas negras sin hueso","2 dientes ajo","2 cdas aceite de oliva","Tomillo, orégano, sal, pimienta","Perejil fresco"],"en":["2 fresh cod loins (150g each)","300g cherry tomatoes","60g pitted black olives","2 garlic cloves","2 tbsp olive oil","Thyme, oregano, salt, pepper","Fresh parsley"]}',
'{"es":["Precalienta horno a 200°C","Coloca el bacalao en bandeja y rodea con tomates y aceitunas","Añade ajo laminado, hierbas, aceite, sal y pimienta","Hornea 18-20 min hasta que el pescado se desmenuce fácilmente"],"en":["Preheat oven to 200°C","Place cod in baking dish surrounded by tomatoes and olives","Add sliced garlic, herbs, oil, salt and pepper","Bake 18-20 min until fish flakes easily"]}'
),

('estofado_ternera_boniato',174,'dinner','🥩',
'{"es":"Estofado de ternera con boniato","en":"Beef and sweet potato stew","fr":"Ragoût de bœuf à la patate douce","it":"Stufato di manzo con patata dolce"}',
'{"es":"Estofado reconfortante rico en hierro y vitamina A, ideal en fase lútea","en":"Comforting stew rich in iron and vitamin A, ideal for luteal phase"}',
15,45,460,36,38,12,7,
ARRAY['gluten_free','lactose_free','high_protein','paleo'],
ARRAY['luteal','menstrual'],
ARRAY['maintain','muscle'],
ARRAY['anemia','fatigue','cramps'],
ARRAY[]::text[],
'medium','40_60','medium',
'{"es":["350g ternera para estofar en dados","1 boniato grande en cubos","2 zanahorias en rodajas","1 cebolla","400g tomate triturado","300ml caldo de carne","Tomillo, romero, sal, pimienta","Aceite de oliva"],"en":["350g diced stewing beef","1 large sweet potato cubed","2 sliced carrots","1 onion","400g crushed tomatoes","300ml beef broth","Thyme, rosemary, salt, pepper","Olive oil"]}',
'{"es":["Dora la ternera en aceite 4-5 min, reserva","Sofríe cebolla 3 min, añade zanahorias y boniato","Devuelve la ternera, añade tomate, caldo y hierbas","Hierve, baja fuego y cocina tapado 40-45 min"],"en":["Brown beef in oil 4-5 min, set aside","Sauté onion 3 min, add carrots and sweet potato","Return beef, add tomatoes, broth and herbs","Boil, reduce heat and cook covered 40-45 min"]}'
),

('gambas_ajillo',175,'dinner','🦐',
'{"es":"Gambas al ajillo","en":"Garlic prawns","fr":"Crevettes à l\'ail","it":"Gamberi all\'aglio"}',
'{"es":"Clásico español de 10 minutos: proteína pura con aceite de oliva y ajo","en":"Spanish classic in 10 minutes: pure protein with olive oil and garlic"}',
5,8,280,28,4,16,0,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','keto','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["300g gambas peladas","4 dientes ajo laminados","1 chile seco en aros (o cayena)","3 cdas aceite de oliva","Sal, perejil fresco","Pan sin gluten para acompañar (opt)"],"en":["300g peeled prawns","4 garlic cloves sliced","1 dried chilli in rings (or cayenne)","3 tbsp olive oil","Salt, fresh parsley","Gluten-free bread to serve (opt)"]}',
'{"es":["Calienta el aceite con el ajo a fuego medio hasta que empiece a dorarse","Añade el chile y las gambas","Sube el fuego y cocina 2-3 min hasta que las gambas estén rosadas","Espolvorea perejil y sirve inmediatamente"],"en":["Heat oil with garlic on medium heat until it starts to colour","Add chilli and prawns","Increase heat and cook 2-3 min until prawns are pink","Sprinkle parsley and serve immediately"]}'
),

('pechugas_rellenas_espinacas',176,'dinner','🐓',
'{"es":"Pechugas rellenas de espinacas y queso","en":"Chicken stuffed with spinach and cheese","fr":"Blancs de poulet farcis épinards-fromage","it":"Petti di pollo ripieni di spinaci e formaggio"}',
'{"es":"Pollo jugoso relleno: más vistoso que difícil, lista en 30 min","en":"Juicy stuffed chicken: more impressive than difficult, ready in 30 min"}',
10,22,390,44,4,20,2,
ARRAY['gluten_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','20_40','medium',
'{"es":["2 pechugas de pollo grandes","100g espinacas frescas","60g queso ricotta o crema","1 diente ajo","Sal, pimienta, orégano","Palillos de cocina","1 cda aceite de oliva"],"en":["2 large chicken breasts","100g fresh spinach","60g ricotta or cream cheese","1 garlic clove","Salt, pepper, oregano","Toothpicks","1 tbsp olive oil"]}',
'{"es":["Saltea espinacas con ajo hasta que se marchiten. Escurre bien","Mezcla con ricotta, sal y pimienta","Abre las pechugas en libro con un cuchillo","Rellena con la mezcla y cierra con palillos","Salpimenta y dora en sartén 3 min por lado, luego hornea 18 min a 180°C"],"en":["Sauté spinach with garlic until wilted. Drain well","Mix with ricotta, salt and pepper","Butterfly chicken breasts with a knife","Fill with mixture and close with toothpicks","Season and sear in pan 3 min per side, then bake 18 min at 180°C"]}'
),

('trucha_almendras',177,'dinner','🐟',
'{"es":"Trucha con almendras tostadas","en":"Trout with toasted almonds","fr":"Truite aux amandes grillées","it":"Trota con mandorle tostate"}',
'{"es":"Clásico francés convertido en cena saludable y antiinflamatoria","en":"French classic turned into a healthy anti-inflammatory dinner"}',
5,12,380,34,6,24,2,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation','menstrual'],
ARRAY['muscle','energy'],
ARRAY['inflammation'],
ARRAY['fish','nuts'],
'easy','20_40','medium',
'{"es":["2 filetes de trucha (150g c/u)","40g almendras laminadas","1 cda mantequilla o aceite de oliva","Zumo de 1 limón","Perejil fresco","Sal, pimienta"],"en":["2 trout fillets (150g each)","40g flaked almonds","1 tbsp butter or olive oil","Juice of 1 lemon","Fresh parsley","Salt, pepper"]}',
'{"es":["Salpimenta la trucha y dórala en aceite 3-4 min por lado","Reserva y en la misma sartén tuesta las almendras 2 min","Añade zumo de limón y mezcla","Sirve la trucha con las almendras tostadas y el jugo encima"],"en":["Season trout and brown in oil 3-4 min per side","Set aside and in the same pan toast almonds 2 min","Add lemon juice and stir","Serve trout with toasted almonds and pan juices"]}'
),

('pasta_integral_bolognesa_vegana',178,'dinner','🍝',
'{"es":"Pasta integral con boloñesa vegana de lentejas","en":"Wholewheat pasta with vegan lentil bolognese","fr":"Pâtes complètes à la bolognaise de lentilles","it":"Pasta integrale con ragù vegano di lenticchie"}',
'{"es":"Boloñesa de lentejas: misma textura que la carne, más fibra y menos grasa","en":"Lentil bolognese: same texture as meat, more fibre and less fat"}',
10,25,490,20,72,10,14,
ARRAY['vegan','vegetarian','high_protein','anti_inflammatory'],
ARRAY['luteal','menstrual','follicular'],
ARRAY['maintain','energy'],
ARRAY['anemia'],
ARRAY['gluten'],
'easy','20_40','low',
'{"es":["150g pasta integral","200g lentejas verdes cocidas","400g tomate triturado","1/2 cebolla, 2 dientes ajo","1 zanahoria en daditos","1 rama apio","Vino tinto (opt)","Orégano, laurel, sal, aceite de oliva"],"en":["150g wholewheat pasta","200g cooked green lentils","400g crushed tomatoes","1/2 onion, 2 garlic cloves","1 carrot diced","1 celery stalk","Red wine (opt)","Oregano, bay leaf, salt, olive oil"]}',
'{"es":["Sofríe cebolla, ajo, zanahoria y apio en aceite 5 min","Añade lentejas y rehoga 2 min","Añade vino (opt) y evapora. Incorpora tomate y hierbas","Cocina 20 min a fuego lento. Cuece la pasta y mezcla"],"en":["Sauté onion, garlic, carrot and celery in oil 5 min","Add lentils and stir 2 min","Add wine (opt) and evaporate. Add tomatoes and herbs","Simmer 20 min. Cook pasta and combine"]}'
),

('pulpo_gallega',179,'dinner','🐙',
'{"es":"Pulpo a la gallega","en":"Galician-style octopus","fr":"Pieuvre à la galicienne","it":"Polpo alla galiziana"}',
'{"es":"Receta española icónica: pulpo cocido con aceite, pimentón y patata","en":"Iconic Spanish recipe: boiled octopus with oil, paprika and potato"}',
5,40,310,28,24,8,3,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['shellfish'],
'medium','40_60','high',
'{"es":["600g pulpo cocido (comprado listo)","300g patatas cocidas en rodajas","Pimentón dulce y picante","3 cdas aceite de oliva virgen extra","Sal gruesa","Perejil fresco (opt)"],"en":["600g cooked octopus (ready-cooked)","300g boiled potatoes sliced","Sweet and smoked paprika","3 tbsp extra virgin olive oil","Coarse salt","Fresh parsley (opt)"]}',
'{"es":["Calienta el pulpo ya cocido en agua caliente 5 min","Coloca las patatas en rodajas en una tabla de madera","Trocea el pulpo con tijeras sobre las patatas","Aliña con aceite, pimentón al gusto y sal gruesa"],"en":["Heat pre-cooked octopus in hot water 5 min","Arrange potato slices on a wooden board","Scissors-cut octopus over potatoes","Dress with olive oil, paprika to taste and coarse salt"]}'
),

('tortitas_avena_arándanos',180,'breakfast','🫐',
'{"es":"Tortitas de avena y arándanos","en":"Oat and blueberry pancakes","fr":"Pancakes avoine-myrtilles","it":"Pancake avena e mirtilli"}',
'{"es":"Tortitas esponjosas de avena con antioxidantes de los arándanos","en":"Fluffy oat pancakes with antioxidants from blueberries"}',
5,10,340,14,48,10,6,
ARRAY['vegetarian'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY['inflammation'],
ARRAY['gluten','eggs','dairy'],
'easy','under_20','low',
'{"es":["80g copos de avena","1 plátano maduro","2 huevos","100ml leche","100g arándanos frescos o congelados","1 cdta levadura","Aceite de coco para la sartén"],"en":["80g rolled oats","1 ripe banana","2 eggs","100ml milk","100g fresh or frozen blueberries","1 tsp baking powder","Coconut oil for pan"]}',
'{"es":["Tritura la avena hasta harina fina","Mezcla con plátano aplastado, huevos, leche y levadura","Incorpora los arándanos con suavidad","Cocina en sartén con aceite a fuego medio 2-3 min por lado"],"en":["Blend oats to fine flour","Mix with mashed banana, eggs, milk and baking powder","Fold in blueberries gently","Cook in oiled pan on medium heat 2-3 min per side"]}'
),

-- ── SNACKS EXTRA ──────────────────────────────────────────────────────────────

('queso_feta_sandía',181,'afternoon_snack','🍉',
'{"es":"Sandia con feta y menta","en":"Watermelon with feta and mint","fr":"Pastèque feta-menthe","it":"Anguria con feta e menta"}',
'{"es":"Combinación griega clásica: dulce, salado y refrescante en verano","en":"Classic Greek combination: sweet, salty and refreshing in summer"}',
5,0,160,6,20,7,1,
ARRAY['vegetarian','gluten_free'],
ARRAY['ovulation','follicular'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['dairy'],
'easy','under_20','low',
'{"es":["200g sandía en cubos","50g queso feta desmenuzado","Menta fresca","Zumo de limón","Pimienta negra (opt)"],"en":["200g watermelon cubed","50g crumbled feta","Fresh mint","Lemon juice","Black pepper (opt)"]}',
'{"es":["Coloca la sandía en un bol o plato","Desmenuza el feta por encima","Añade las hojas de menta y un chorrito de limón"],"en":["Place watermelon in a bowl or plate","Crumble feta over the top","Add mint leaves and a squeeze of lemon"]}'
),

('galletas_mantequilla_almendras',182,'afternoon_snack','🍪',
'{"es":"Galletas de mantequilla de almendras sin gluten","en":"Almond butter cookies gluten-free","fr":"Biscuits au beurre d\'amandes sans gluten","it":"Biscotti al burro di mandorle senza glutine"}',
'{"es":"3 ingredientes: mantequilla de almendras, huevo y miel — listas en 12 min","en":"3 ingredients: almond butter, egg and honey — ready in 12 minutes"}',
5,12,220,7,16,14,2,
ARRAY['gluten_free','vegetarian','paleo','low_carb'],
ARRAY['luteal','follicular'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['eggs','nuts'],
'easy','under_20','low',
'{"es":["100g mantequilla de almendras natural","1 huevo","1 cda miel o sirope de arce","1 pizca sal","1 pizca canela"],"en":["100g natural almond butter","1 egg","1 tbsp honey or maple syrup","1 pinch salt","1 pinch cinnamon"]}',
'{"es":["Mezcla todos los ingredientes hasta masa homogénea","Forma bolitas y aplánalas en bandeja con papel vegetal","Hornea 10-12 min a 175°C hasta que los bordes estén dorados","Deja enfriar — se endurecen al enfriar"],"en":["Mix all ingredients to homogeneous dough","Roll into balls and flatten on lined baking tray","Bake 10-12 min at 175°C until edges are golden","Cool completely — they firm up as they cool"]}'
),

-- ── ALMUERZOS ADICIONALES ─────────────────────────────────────────────────────

('arroz_frito_verduras_huevo',183,'lunch','🍳',
'{"es":"Arroz frito con verduras y huevo","en":"Fried rice with vegetables and egg","fr":"Riz sauté aux légumes et oeuf","it":"Riso fritto con verdure e uovo"}',
'{"es":"Aprovecha el arroz del día anterior: receta anticidesperdicio y sabrosa","en":"Use yesterday's rice: anti-waste and delicious recipe"}',
5,10,420,14,56,14,5,
ARRAY['vegetarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['energy','maintain'],
ARRAY[]::text[],
ARRAY['eggs','soy'],
'easy','under_20','low',
'{"es":["200g arroz cocido (del día anterior, frío)","2 huevos","1 zanahoria en daditos","100g guisantes","2 cebolletas","2 cdas tamari o salsa de soja","1 cdta aceite de sésamo","Jengibre rallado, aceite de coco"],"en":["200g cooked rice (previous day, cold)","2 eggs","1 carrot diced","100g peas","2 spring onions","2 tbsp tamari or soy sauce","1 tsp sesame oil","Grated ginger, coconut oil"]}',
'{"es":["Saltea zanahoria y guisantes en aceite 3 min","Añade el arroz frío y rompe los grumos","Haz un hueco, rompe los huevos y revuelve en el centro","Mezcla todo y añade tamari, aceite de sésamo y jengibre"],"en":["Sauté carrot and peas in oil 3 min","Add cold rice and break up clumps","Make a well, crack in eggs and scramble in centre","Mix everything and add tamari, sesame oil and ginger"]}'
),

('ensalada_garbanzos_espinacas',184,'lunch','🫘',
'{"es":"Ensalada de garbanzos y espinacas","en":"Chickpea and spinach salad","fr":"Salade de pois chiches aux épinards","it":"Insalata di ceci e spinaci"}',
'{"es":"Ensalada saciante de proteína vegetal, hierro y vitamina C","en":"Filling salad of plant protein, iron and vitamin C"}',
10,0,380,16,44,14,12,
ARRAY['vegan','gluten_free','vegetarian','high_protein','mediterranean','anti_inflammatory'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy'],
ARRAY['anemia','fatigue'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["240g garbanzos cocidos (lata)","80g espinacas baby","1/2 pimiento rojo asado","1/4 cebolla roja","10 tomates cherry","Vinagreta: aceite oliva, zumo limón, comino, sal"],"en":["240g cooked chickpeas (can)","80g baby spinach","1/2 roasted red pepper","1/4 red onion","10 cherry tomatoes","Dressing: olive oil, lemon juice, cumin, salt"]}',
'{"es":["Escurre y aclara los garbanzos","Mezcla todos los ingredientes en ensaladera","Prepara la vinagreta y aliña justo antes de servir"],"en":["Drain and rinse chickpeas","Mix all ingredients in salad bowl","Make dressing and dress just before serving"]}'
),

('sushi_casero_california',185,'lunch','🍱',
'{"es":"California rolls caseros","en":"Homemade California rolls","fr":"California rolls maison","it":"California rolls fatti in casa"}',
'{"es":"Sushi de aguacate y cangrejo hecho en casa, más fácil de lo que parece","en":"Homemade avocado and crab sushi, easier than it looks"}',
30,12,420,14,62,14,4,
ARRAY['pescatarian','gluten_free','lactose_free'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['shellfish','sesame','soy'],
'medium','20_40','medium',
'{"es":["200g arroz de sushi","250ml agua","3 cdas vinagre de arroz, 1 cdta azúcar, 1/2 cdta sal","4 hojas alga nori","1 aguacate","100g palitos de cangrejo o cangrejo real","1 pepino","Semillas sésamo, tamari para dipear"],"en":["200g sushi rice","250ml water","3 tbsp rice vinegar, 1 tsp sugar, 1/2 tsp salt","4 nori sheets","1 avocado","100g crab sticks or real crab","1 cucumber","Sesame seeds, tamari for dipping"]}',
'{"es":["Cuece el arroz, mezcla caliente con vinagre-azúcar-sal, deja templar","Coloca nori sobre esterilla, extiende arroz dejando 2cm libre","Coloca relleno en el centro","Enrolla apretando con la esterilla, humedece el borde para sellar","Corta en 8 piezas con cuchillo mojado"],"en":["Cook rice, mix warm with vinegar-sugar-salt, cool to room temp","Place nori on mat, spread rice leaving 2cm edge free","Place fillings in centre","Roll tightly with mat, wet edge to seal","Cut into 8 pieces with a wet knife"]}'
),

-- ── CENAS ADICIONALES ─────────────────────────────────────────────────────────

('muslos_pollo_naranja',186,'dinner','🍊',
'{"es":"Muslos de pollo al horno con naranja","en":"Oven-baked chicken thighs with orange","fr":"Cuisses de poulet à l\'orange au four","it":"Cosce di pollo al forno con arancia"}',
'{"es":"Pollo jugoso marinado en naranja: dulce, cítrico y muy sencillo","en":"Juicy orange-marinated chicken: sweet, citrusy and very simple"}',
5,35,420,34,14,24,1,
ARRAY['gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY[]::text[],
'easy','40_60','low',
'{"es":["4 muslos de pollo con hueso y piel","Zumo de 2 naranjas y la ralladura de 1","2 cdas aceite de oliva","2 dientes ajo picados","1 cdta miel","Romero, sal, pimienta"],"en":["4 chicken thighs bone-in skin-on","Juice of 2 oranges and zest of 1","2 tbsp olive oil","2 garlic cloves minced","1 tsp honey","Rosemary, salt, pepper"]}',
'{"es":["Marina los muslos en naranja, aceite, ajo, miel, sal y pimienta 15 min","Coloca en bandeja con la marinada","Hornea 35-40 min a 200°C, bañando con los jugos a mitad"],"en":["Marinate thighs in orange, oil, garlic, honey, salt and pepper 15 min","Place in baking dish with the marinade","Bake 35-40 min at 200°C, basting with juices halfway"]}'
),

('tacos_pescado',187,'dinner','🌮',
'{"es":"Tacos de pescado con ensalada de col","en":"Fish tacos with coleslaw","fr":"Tacos de poisson et chou","it":"Tacos di pesce con insalata di cavolo"}',
'{"es":"Tacos baja en tortillas de maíz con merluza a la plancha y slaw crujiente","en":"Baja-style tacos in corn tortillas with grilled hake and crunchy slaw"}',
15,8,400,30,44,12,7,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["300g merluza o tilapia en dados","Especias: comino, pimentón, ajo en polvo, sal","4 tortillas de maíz","Slaw: 1/4 col, zanahoria, zumo lima, cilantro, sal","1 aguacate en rodajas","Salsa picante (opt)"],"en":["300g hake or tilapia diced","Spices: cumin, paprika, garlic powder, salt","4 corn tortillas","Slaw: 1/4 cabbage, carrot, lime juice, coriander, salt","1 avocado sliced","Hot sauce (opt)"]}',
'{"es":["Sazona el pescado y hazlo a la plancha o en sartén 3-4 min","Prepara el slaw mezclando la col con zanahoria, lima y cilantro","Calienta las tortillas","Monta los tacos con pescado, slaw y aguacate"],"en":["Season fish and cook on griddle or pan 3-4 min","Make slaw by combining cabbage with carrot, lime and coriander","Warm the tortillas","Assemble tacos with fish, slaw and avocado"]}'
),

('pastel_coliflor_jamon',188,'dinner','🥦',
'{"es":"Pastel de coliflor y jamón serrano","en":"Cauliflower and serrano ham bake","fr":"Gratin de chou-fleur au jambon de Bayonne","it":"Sformato di cavolfiore e prosciutto crudo"}',
'{"es":"Versión sin gluten del gratén: coliflor, huevo y jamón en 30 minutos","en":"Gluten-free gratin: cauliflower, egg and ham in 30 minutes"}',
10,25,310,24,14,16,5,
ARRAY['gluten_free','high_protein','low_carb','keto'],
ARRAY['luteal','follicular'],
ARRAY['muscle','lose_weight'],
ARRAY[]::text[],
ARRAY['eggs','dairy'],
'easy','20_40','low',
'{"es":["1 coliflor mediana en flores","80g jamón serrano en tiras","3 huevos","100ml leche o nata para cocinar","50g queso rallado","Sal, pimienta, nuez moscada","Aceite de oliva"],"en":["1 medium cauliflower in florets","80g serrano ham in strips","3 eggs","100ml milk or cooking cream","50g grated cheese","Salt, pepper, nutmeg","Olive oil"]}',
'{"es":["Cuece la coliflor al vapor 8 min hasta tierna","Bate huevos con leche, sal, pimienta y nuez moscada","Mezcla con coliflor y jamón","Vierte en molde engrasado, espolvorea queso","Hornea 20-25 min a 180°C hasta dorado"],"en":["Steam cauliflower 8 min until tender","Whisk eggs with milk, salt, pepper and nutmeg","Mix with cauliflower and ham","Pour into greased dish, sprinkle cheese","Bake 20-25 min at 180°C until golden"]}'
),

('risotto_setas_parmesano',189,'dinner','🍄',
'{"es":"Risotto de setas y parmesano","en":"Mushroom and parmesan risotto","fr":"Risotto aux champignons et parmesan","it":"Risotto ai funghi e parmigiano"}',
'{"es":"El risotto perfecto: cremoso, umami y reconfortante — vale la pena el proceso","en":"The perfect risotto: creamy, umami and comforting — worth the process"}',
10,30,460,16,62,14,4,
ARRAY['vegetarian','mediterranean'],
ARRAY['luteal','follicular','menstrual'],
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY['dairy'],
'medium','20_40','medium',
'{"es":["160g arroz carnaroli o arborio","300g setas mixtas","1L caldo de verduras caliente","1/2 cebolla","1 diente ajo","100ml vino blanco (opt)","50g parmesano rallado","2 cdas mantequilla","Aceite de oliva, sal, pimienta, perejil"],"en":["160g carnaroli or arborio rice","300g mixed mushrooms","1L hot vegetable broth","1/2 onion","1 garlic clove","100ml white wine (opt)","50g grated parmesan","2 tbsp butter","Olive oil, salt, pepper, parsley"]}',
'{"es":["Sofríe cebolla y ajo en aceite 3 min","Añade setas y saltea 5 min hasta dorar","Añade arroz y tuesta 1 min. Vierte vino y evapora","Añade caldo cazo a cazo, removiendo constantemente 18-20 min","Fuera del fuego añade mantequilla y parmesano, remueve hasta cremoso"],"en":["Sauté onion and garlic in oil 3 min","Add mushrooms and cook 5 min until golden","Add rice and toast 1 min. Pour wine and evaporate","Add broth ladle by ladle, stirring constantly 18-20 min","Off heat add butter and parmesan, stir until creamy"]}'
),

('hamburguesa_atun_casera',190,'dinner','🍔',
'{"es":"Hamburguesa de atún casera","en":"Homemade tuna burger","fr":"Burger de thon maison","it":"Hamburger di tonno fatto in casa"}',
'{"es":"Hamburguesa alta en proteína con atún fresco: diferente y deliciosa","en":"High-protein burger with fresh tuna: different and delicious"}',
10,8,380,34,18,18,4,
ARRAY['pescatarian','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['muscle','maintain'],
ARRAY[]::text[],
ARRAY['fish','eggs'],
'easy','under_20','medium',
'{"es":["250g atún fresco picado","1 huevo","2 cdas pan rallado sin gluten","1 cdta soja o tamari","Jengibre rallado, ajo en polvo","Sal, pimienta","Para servir: lechuga, tomate, aguacate, pan sin gluten"],"en":["250g fresh tuna minced","1 egg","2 tbsp gluten-free breadcrumbs","1 tsp soy or tamari","Grated ginger, garlic powder","Salt, pepper","To serve: lettuce, tomato, avocado, gluten-free bun"]}',
'{"es":["Mezcla atún con huevo, pan rallado, tamari, jengibre y especias","Forma 2 hamburguesas","Cocina en plancha caliente 3-4 min por lado","Sirve en pan (o sin pan) con lechuga, tomate y aguacate"],"en":["Mix tuna with egg, breadcrumbs, tamari, ginger and spices","Shape into 2 patties","Cook on hot griddle 3-4 min per side","Serve in bun (or bunless) with lettuce, tomato and avocado"]}'
);
