-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Recetas LOTE 12 (15) — display_order 356-370
-- Enfocado en: low_fodmap (cierre definitivo → ~100 recetas)
-- Ejecutar en Supabase SQL Editor DESPUÉS del lote 11
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO recipes (id,display_order,meal_type,emoji,title,description,prep_time_min,cook_time_min,kcal,protein_g,carbs_g,fat_g,fiber_g,diets,phases,goals,good_for,contains_allergens,difficulty,cooking_bucket,budget,ingredients,steps) VALUES

('arroz_pollo_azafrán_fodmap',356,'dinner','🌿',
'{"es":"Arroz con pollo y azafrán (low FODMAP)","en":"Saffron chicken rice (low FODMAP)","fr":"Riz au poulet et safran (low FODMAP)","it":"Riso con pollo e zafferano (low FODMAP)"}',
'{"es":"Arroz sabroso y reconfortante sin cebolla ni ajo: pollo, azafrán y caldo suave","en":"Flavourful comforting rice without onion or garlic: chicken, saffron and gentle stock"}',
8,28,460,32,54,10,3,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["300g muslo de pollo deshuesado en dados","200g arroz","Unas hebras de azafrán","1L caldo de pollo sin cebolla ni ajo","2 cdas aceite de ajo infusionado","1 pimiento rojo en dados","Sal, pimienta","Cebollino verde picado","Perejil fresco"],"en":["300g boneless chicken thigh diced","200g rice","A few saffron threads","1L chicken stock no onion or garlic","2 tbsp garlic-infused oil","1 red pepper diced","Salt, pepper","Chopped green chives","Fresh parsley"]}',
'{"es":["Dora el pollo en el aceite infusionado a fuego alto 5 min, reserva","Sofríe el pimiento 3 min en el mismo aceite","Añade el arroz y tuesta 1 min","Disuelve el azafrán en un poco de caldo caliente y añade todo el caldo","Cuece a fuego medio 18-20 min sin remover","Sirve con cebollino y perejil fresco"],"en":["Brown chicken in infused oil over high heat 5 min, set aside","Sauté pepper 3 min in same oil","Add rice and toast 1 min","Dissolve saffron in a little hot stock and add all the stock","Cook over medium heat 18-20 min without stirring","Serve with green chives and fresh parsley"]}'
),

('tortilla_patata_fodmap',357,'lunch','🥚',
'{"es":"Tortilla de patata sin cebolla (low FODMAP)","en":"Potato omelette without onion (low FODMAP)","fr":"Tortilla de pommes de terre sans oignon (low FODMAP)","it":"Tortilla di patate senza cipolla (low FODMAP)"}',
'{"es":"La tortilla española adaptada low FODMAP: solo patata, huevo y aceite de oliva — igual de sabrosa","en":"Low FODMAP Spanish omelette: just potato, egg and olive oil — just as delicious"}',
10,20,380,18,34,18,3,
ARRAY['low_fodmap','gluten_free','lactose_free','vegetarian','high_protein'],
ARRAY['follicular','luteal','menstrual'],
ARRAY['maintain','energy'],
ARRAY['sibo','ibs'],
ARRAY['eggs'],
'medium','20_40','low',
'{"es":["4 huevos","2 patatas medianas peladas en rodajas finas","3 cdas aceite de oliva","Sal","Cebollino verde picado (solo la parte verde)","Perejil fresco"],"en":["4 eggs","2 medium potatoes peeled and thinly sliced","3 tbsp olive oil","Salt","Chopped green chives (green part only)","Fresh parsley"]}',
'{"es":["Cuece las patatas en aceite a fuego muy bajo 12-15 min hasta tiernas, sin dorar","Bate los huevos con sal","Escurre el exceso de aceite de las patatas y mezcla con los huevos","Vierte en sartén antiadherente a fuego medio-bajo","Cuaja 5 min, da la vuelta con un plato y cuaja 3 min más","Sirve con cebollino y perejil"],"en":["Cook potatoes in oil over very low heat 12-15 min until tender, without browning","Beat eggs with salt","Drain excess oil from potatoes and mix with eggs","Pour into non-stick pan over medium-low heat","Set 5 min, flip with a plate and set 3 min more","Serve with chives and parsley"]}'
),

('gambas_limón_fodmap',358,'dinner','🦐',
'{"es":"Gambas al limón con aceite de ajo infusionado","en":"Lemon prawns with garlic-infused oil","fr":"Crevettes citron a l''huile d''ail infusee","it":"Gamberi al limone con olio all''aglio"}',
'{"es":"Gambas jugosas low FODMAP: sin ajo real, el aceite infusionado da todo el sabor","en":"Juicy low FODMAP prawns: no real garlic, the infused oil gives all the flavour"}',
5,6,300,28,4,18,1,
ARRAY['low_fodmap','gluten_free','lactose_free','pescatarian','keto','low_carb','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['sibo','ibs'],
ARRAY['shellfish'],
'easy','under_20','medium',
'{"es":["300g gambas peladas","3 cdas aceite de ajo infusionado","Zumo de 1 limón","Ralladura de 1/2 limón","1 cdta pimentón","Guindilla en copos (opcional)","Cebollino verde picado","Sal, pimienta","Perejil fresco"],"en":["300g peeled prawns","3 tbsp garlic-infused oil","Juice of 1 lemon","Zest of 1/2 lemon","1 tsp paprika","Chilli flakes (optional)","Chopped green chives","Salt, pepper","Fresh parsley"]}',
'{"es":["Calienta el aceite infusionado en sartén a fuego alto","Añade las gambas, el pimentón y la guindilla","Saltea 2-3 min hasta que las gambas estén rosadas","Exprime el limón, añade la ralladura y el cebollino","Sazona y sirve inmediatamente con perejil fresco"],"en":["Heat infused oil in pan over high heat","Add prawns, paprika and chilli","Sauté 2-3 min until prawns are pink","Squeeze lemon, add zest and chives","Season and serve immediately with fresh parsley"]}'
),

('sopa_miso_verduras_fodmap',359,'dinner','🍜',
'{"es":"Sopa de miso con verduras toleradas (low FODMAP)","en":"Miso soup with low-FODMAP vegetables","fr":"Soupe miso aux legumes toleres (low FODMAP)","it":"Zuppa di miso con verdure tollerate (low FODMAP)"}',
'{"es":"Sopa miso reconfortante y digestiva con verduras toleradas: zanahoria, espinacas y calabacín","en":"Comforting and digestive miso soup with tolerated vegetables: carrot, spinach and courgette"}',
5,10,180,10,18,6,4,
ARRAY['low_fodmap','vegan','vegetarian','gluten_free','lactose_free'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','reduce_symptoms','energy'],
ARRAY['sibo','ibs'],
ARRAY['soy'],
'easy','under_20','low',
'{"es":["2 cdas pasta de miso blanca","700ml agua","1 zanahoria en rodajas finas","100g espinacas baby","1 calabacín en dados pequeños","100g tofu firme en dados (opcional)","Cebollino verde en rodajas finas","1 cdta aceite de sésamo","Semillas de sésamo"],"en":["2 tbsp white miso paste","700ml water","1 carrot thinly sliced","100g baby spinach","1 courgette in small dice","100g firm tofu diced (optional)","Spring onion green part finely sliced","1 tsp sesame oil","Sesame seeds"]}',
'{"es":["Cuece la zanahoria y el calabacín en agua 5-6 min hasta tiernos","Baja el fuego, disuelve el miso en un poco del caldo y añade al resto","No dejes hervir el caldo con el miso","Añade las espinacas y el tofu, calienta 2 min","Sirve con cebollino, aceite de sésamo y sésamo"],"en":["Cook carrot and courgette in water 5-6 min until tender","Lower heat, dissolve miso in a little broth and add to the rest","Do not boil the broth with the miso","Add spinach and tofu, heat 2 min","Serve with spring onion, sesame oil and sesame seeds"]}'
),

('pechuga_ensalada_fodmap',360,'lunch','🥗',
'{"es":"Ensalada de pechuga con pepino, zanahoria y vinagreta de mostaza","en":"Chicken breast salad with cucumber, carrot and mustard dressing","fr":"Salade de blanc de poulet concombre carotte et vinaigrette moutarde","it":"Insalata di petto di pollo con cetriolo carota e vinaigrette alla senape"}',
'{"es":"Ensalada low FODMAP saciante: pollo, pepino, zanahoria y vinagreta de mostaza y limón","en":"Satisfying low FODMAP salad: chicken, cucumber, carrot and mustard lemon dressing"}',
10,0,360,34,12,18,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','low_carb','keto'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','lose_weight'],
ARRAY['sibo','ibs'],
ARRAY['mustard','eggs'],
'easy','under_20','low',
'{"es":["250g pechuga de pollo cocida o asada en tiras","1 pepino en rodajas","2 zanahorias ralladas","Hojas de lechuga romana","Cebollino verde picado","Para la vinagreta: 2 cdas aceite de oliva, 1 cda zumo de limón, 1 cdta mostaza de Dijon, sal, pimienta"],"en":["250g cooked or roasted chicken breast in strips","1 cucumber sliced","2 grated carrots","Romaine lettuce leaves","Chopped green chives","For dressing: 2 tbsp olive oil, 1 tbsp lemon juice, 1 tsp Dijon mustard, salt, pepper"]}',
'{"es":["Prepara la vinagreta mezclando todos sus ingredientes","Coloca la lechuga en el fondo de un bol","Añade el pollo, el pepino, la zanahoria y el cebollino","Riega con la vinagreta justo antes de servir"],"en":["Prepare dressing by mixing all ingredients","Place lettuce in the bottom of a bowl","Add chicken, cucumber, carrot and chives","Drizzle with dressing just before serving"]}'
),

('pasta_arroz_pollo_verduras_fodmap',361,'dinner','🍝',
'{"es":"Pasta de arroz con pollo y verduras salteadas","en":"Rice pasta with chicken and sautéed vegetables","fr":"Pates de riz poulet et legumes sautes","it":"Pasta di riso con pollo e verdure saltate"}',
'{"es":"Pasta sin gluten low FODMAP con pollo tierno, pimiento, calabacín y aceite infusionado","en":"Gluten-free low FODMAP pasta with tender chicken, pepper, courgette and infused oil"}',
8,18,480,32,56,10,5,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','energy','muscle'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','20_40','low',
'{"es":["150g pasta de arroz","200g pechuga de pollo en tiras","1 calabacín en dados","1 pimiento rojo en tiras","2 cdas aceite de ajo infusionado","1 cda tamari sin gluten","1 cdta pimentón","Sal, pimienta","Cebollino verde, perejil"],"en":["150g rice pasta","200g chicken breast in strips","1 courgette diced","1 red pepper in strips","2 tbsp garlic-infused oil","1 tbsp gluten-free tamari","1 tsp paprika","Salt, pepper","Green chives, parsley"]}',
'{"es":["Cuece la pasta de arroz según instrucciones, escurre","Dora el pollo en el aceite infusionado 5-6 min, reserva","En el mismo aceite saltea el calabacín y el pimiento 4 min","Devuelve el pollo, añade el tamari, el pimentón y la pasta","Mezcla bien 1 min a fuego alto","Sirve con cebollino y perejil"],"en":["Cook rice pasta according to instructions, drain","Brown chicken in infused oil 5-6 min, set aside","In same oil sauté courgette and pepper 4 min","Return chicken, add tamari, paprika and pasta","Toss well 1 min over high heat","Serve with chives and parsley"]}'
),

('tortitas_avena_arándanos_fodmap',362,'breakfast','🫐',
'{"es":"Tortitas de avena y arándanos (low FODMAP)","en":"Oat and blueberry pancakes (low FODMAP)","fr":"Pancakes avoine et myrtilles (low FODMAP)","it":"Pancakes di avena e mirtilli (low FODMAP)"}',
'{"es":"Tortitas esponjosas low FODMAP: avena sin gluten, arándanos y leche de almendra","en":"Fluffy low FODMAP pancakes: gluten-free oats, blueberries and almond milk"}',
5,10,360,10,58,10,5,
ARRAY['low_fodmap','gluten_free','lactose_free','vegetarian'],
ARRAY['follicular','luteal'],
ARRAY['maintain','energy'],
ARRAY['sibo','ibs'],
ARRAY['eggs','nuts'],
'easy','under_20','low',
'{"es":["80g copos de avena sin gluten molidos fino (o harina de avena)","1 huevo","150ml leche de almendra sin azúcar","1 cdta levadura sin gluten","1 cdta extracto de vainilla","1 cdta canela","Pizca de sal","100g arándanos frescos","Aceite de coco para cocinar","Sirope de arce para servir"],"en":["80g finely ground gluten-free oats (or oat flour)","1 egg","150ml unsweetened almond milk","1 tsp gluten-free baking powder","1 tsp vanilla extract","1 tsp cinnamon","Pinch of salt","100g fresh blueberries","Coconut oil for cooking","Maple syrup to serve"]}',
'{"es":["Mezcla la harina de avena, la levadura, la canela y la sal","Añade el huevo, la leche de almendra y la vainilla, mezcla hasta obtener una masa homogénea","Incorpora los arándanos suavemente","Calienta la sartén con aceite de coco a fuego medio","Vierte cucharones de masa y cocina 2-3 min por lado hasta doradas","Sirve con sirope de arce"],"en":["Mix oat flour, baking powder, cinnamon and salt","Add egg, almond milk and vanilla, mix until smooth batter","Fold in blueberries gently","Heat pan with coconut oil over medium heat","Pour ladlefuls of batter and cook 2-3 min per side until golden","Serve with maple syrup"]}'
),

('ternera_zanahoria_arroz_fodmap',363,'dinner','🥩',
'{"es":"Ternera salteada con zanahoria y arroz (low FODMAP)","en":"Stir-fried beef with carrot and rice (low FODMAP)","fr":"Boeuf saute carotte et riz (low FODMAP)","it":"Manzo saltato con carote e riso (low FODMAP)"}',
'{"es":"Salteado rápido low FODMAP de ternera tierna con zanahoria, jengibre y tamari","en":"Quick low FODMAP stir-fry of tender beef with carrot, ginger and tamari"}',
10,12,460,32,54,10,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation'],
ARRAY['maintain','muscle','energy'],
ARRAY['sibo','ibs'],
ARRAY['soy'],
'easy','20_40','low',
'{"es":["250g filete de ternera en tiras finas","150g arroz basmati","2 zanahorias en juliana","1 cdta jengibre fresco rallado","2 cdas tamari sin gluten","1 cda aceite de sésamo","1 cda aceite de oliva","Cebollino verde picado","Semillas de sésamo","Sal, pimienta"],"en":["250g beef steak in thin strips","150g basmati rice","2 carrots julienned","1 tsp fresh grated ginger","2 tbsp gluten-free tamari","1 tbsp sesame oil","1 tbsp olive oil","Chopped green chives","Sesame seeds","Salt, pepper"]}',
'{"es":["Cuece el arroz basmati según instrucciones","Calienta el aceite de oliva en wok a fuego muy alto","Saltea la ternera 2-3 min hasta dorada, reserva","En el mismo wok saltea la zanahoria 3 min","Devuelve la ternera, añade el jengibre, el tamari y el aceite de sésamo","Cocina 1 min mezclando bien","Sirve sobre el arroz con cebollino y sésamo"],"en":["Cook basmati rice according to instructions","Heat olive oil in wok over very high heat","Stir-fry beef 2-3 min until browned, set aside","In same wok stir-fry carrot 3 min","Return beef, add ginger, tamari and sesame oil","Cook 1 min tossing well","Serve over rice with chives and sesame"]}'
),

('creps_espinacas_ricotta_fodmap',364,'lunch','🥞',
'{"es":"Creps de trigo sarraceno con espinacas y ricotta","en":"Buckwheat crêpes with spinach and ricotta","fr":"Crepes de sarrasin epinards et ricotta","it":"Crepes di grano saraceno con spinaci e ricotta"}',
'{"es":"Creps sin gluten low FODMAP rellenas de espinacas y ricotta fresca con cebollino","en":"Gluten-free low FODMAP crêpes filled with spinach and fresh ricotta with chives"}',
10,15,380,18,42,14,4,
ARRAY['low_fodmap','gluten_free','vegetarian','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','energy','muscle'],
ARRAY['sibo','ibs'],
ARRAY['eggs','dairy'],
'medium','20_40','low',
'{"es":["Para las creps: 100g harina de trigo sarraceno, 1 huevo, 200ml leche sin lactosa, pizca de sal, aceite para cocinar","Para el relleno: 150g ricotta, 150g espinacas baby salteadas, cebollino verde picado, sal, pimienta, nuez moscada","Parmesano rallado para gratinar (opcional)"],"en":["For crêpes: 100g buckwheat flour, 1 egg, 200ml lactose-free milk, pinch of salt, oil for cooking","For filling: 150g ricotta, 150g sautéed baby spinach, chopped green chives, salt, pepper, nutmeg","Grated parmesan to gratinate (optional)"]}',
'{"es":["Mezcla la harina, el huevo, la leche y la sal hasta obtener una masa fina, reposa 10 min","Cocina creps finas en sartén ligeramente engrasada a fuego medio, 1-2 min por lado","Mezcla la ricotta con las espinacas salteadas, el cebollino, sal, pimienta y nuez moscada","Rellena cada crep y dobla en cuatro","Sirve solas o gratina con parmesano 5 min a 180°C"],"en":["Mix flour, egg, milk and salt into a thin batter, rest 10 min","Cook thin crêpes in a lightly greased pan over medium heat, 1-2 min per side","Mix ricotta with sautéed spinach, chives, salt, pepper and nutmeg","Fill each crêpe and fold into quarters","Serve as is or gratinate with parmesan 5 min at 180°C"]}'
),

('pavo_verduras_vapor_fodmap',365,'dinner','🫕',
'{"es":"Pavo al vapor con verduras y salsa de jengibre","en":"Steamed turkey with vegetables and ginger sauce","fr":"Dinde vapeur legumes sauce gingembre","it":"Tacchino al vapore con verdure e salsa allo zenzero"}',
'{"es":"Plato digestivo y ligero: pavo al vapor con calabacín y zanahoria, salsa suave de jengibre","en":"Digestive and light dish: steamed turkey with courgette and carrot, gentle ginger sauce"}',
8,20,340,36,16,10,4,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein','low_carb'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['soy'],
'easy','20_40','low',
'{"es":["300g filete de pavo en filetes finos","2 zanahorias en bastones","1 calabacín en bastones","Para la salsa: 2 cdas tamari sin gluten, 1 cdta jengibre rallado, 1 cdta aceite de sésamo, zumo de 1/2 limón, 1 cdta sirope de arce","Cebollino verde, sésamo tostado"],"en":["300g turkey fillet in thin slices","2 carrots in batons","1 courgette in batons","For sauce: 2 tbsp gluten-free tamari, 1 tsp grated ginger, 1 tsp sesame oil, juice of 1/2 lemon, 1 tsp maple syrup","Green chives, toasted sesame"]}',
'{"es":["Coloca el pavo y las verduras en la cesta del vapor","Cuece al vapor 18-20 min hasta que el pavo esté hecho","Prepara la salsa mezclando todos sus ingredientes","Sirve el pavo y las verduras con la salsa por encima, cebollino y sésamo tostado"],"en":["Place turkey and vegetables in the steamer basket","Steam 18-20 min until turkey is cooked","Prepare sauce by mixing all ingredients","Serve turkey and vegetables with sauce drizzled on top, chives and toasted sesame"]}'
),

('quinoa_salmón_limón_fodmap',366,'lunch','🐟',
'{"es":"Quinoa templada con salmón y limón (low FODMAP)","en":"Warm quinoa with salmon and lemon (low FODMAP)","fr":"Quinoa tiede saumon et citron (low FODMAP)","it":"Quinoa tiepida con salmone e limone (low FODMAP)"}',
'{"es":"Bol nutritivo low FODMAP: quinoa, salmón al horno, pepino y vinagreta de limón y eneldo","en":"Nutritious low FODMAP bowl: quinoa, baked salmon, cucumber and lemon dill dressing"}',
8,15,480,34,46,14,5,
ARRAY['low_fodmap','gluten_free','lactose_free','pescatarian','high_protein','anti_inflammatory'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs','endometriosis'],
ARRAY['fish'],
'easy','20_40','medium',
'{"es":["160g quinoa","2 filetes de salmón","1/2 pepino en dados","Hojas de espinacas baby","Para la vinagreta: 2 cdas aceite de oliva, zumo de 1 limón, eneldo fresco picado, sal, pimienta","Cebollino verde picado"],"en":["160g quinoa","2 salmon fillets","1/2 cucumber diced","Baby spinach leaves","For dressing: 2 tbsp olive oil, juice of 1 lemon, chopped fresh dill, salt, pepper","Chopped green chives"]}',
'{"es":["Cuece la quinoa, deja templar","Hornea el salmón a 200°C 14-15 min con aceite, sal y pimienta","Prepara la vinagreta mezclando todos sus ingredientes","Monta el bol con la quinoa, las espinacas, el pepino y el cebollino","Coloca el salmón encima y riega con la vinagreta de eneldo"],"en":["Cook quinoa, let cool slightly","Bake salmon at 200°C 14-15 min with oil, salt and pepper","Prepare dressing by mixing all ingredients","Build bowl with quinoa, spinach, cucumber and chives","Place salmon on top and drizzle with dill dressing"]}'
),

('porridge_arroz_canela_fodmap',367,'breakfast','🍚',
'{"es":"Porridge de arroz con canela y plátano (low FODMAP)","en":"Rice porridge with cinnamon and banana (low FODMAP)","fr":"Porridge de riz a la cannelle et banane (low FODMAP)","it":"Porridge di riso con cannella e banana (low FODMAP)"}',
'{"es":"Desayuno reconfortante low FODMAP: arroz cocido cremoso con leche de avena, canela y plátano","en":"Comforting low FODMAP breakfast: creamy cooked rice with oat milk, cinnamon and banana"}',
3,15,360,7,68,6,3,
ARRAY['low_fodmap','gluten_free','lactose_free','vegan','vegetarian'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY[]::text[],
'easy','under_20','low',
'{"es":["100g arroz de grano corto o arborio","300ml leche de avena sin gluten","100ml agua","1 cdta canela","1 cdta extracto de vainilla","1 plátano maduro en rodajas (porción de 100g, tolerable en low FODMAP)","1 cda sirope de arce","Pizca de sal","Semillas de chía (opcional)"],"en":["100g short grain or arborio rice","300ml gluten-free oat milk","100ml water","1 tsp cinnamon","1 tsp vanilla extract","1 ripe banana sliced (100g serving, tolerable in low FODMAP)","1 tbsp maple syrup","Pinch of salt","Chia seeds (optional)"]}',
'{"es":["Lleva la leche y el agua a ebullición suave","Añade el arroz, la canela, la vainilla y la sal","Cuece a fuego bajo 13-15 min removiendo con frecuencia hasta obtener consistencia cremosa","Sirve en bol con el plátano en rodajas, el sirope de arce y las semillas de chía"],"en":["Bring milk and water to a gentle boil","Add rice, cinnamon, vanilla and salt","Cook over low heat 13-15 min stirring frequently until creamy","Serve in bowl with sliced banana, maple syrup and chia seeds"]}'
),

('merluza_zanahoria_vapor_fodmap',368,'dinner','🐟',
'{"es":"Merluza al vapor con zanahoria y patata","en":"Steamed hake with carrot and potato","fr":"Merlu vapeur carotte et pomme de terre","it":"Nasello al vapore con carote e patate"}',
'{"es":"Plato digestivo low FODMAP muy suave: merluza, zanahoria y patata al vapor con aceite y limón","en":"Very gentle low FODMAP digestive dish: steamed hake, carrot and potato with oil and lemon"}',
8,22,360,30,32,10,5,
ARRAY['low_fodmap','gluten_free','lactose_free','pescatarian','high_protein'],
ARRAY['menstrual','luteal'],
ARRAY['maintain','muscle','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['fish'],
'easy','20_40','low',
'{"es":["2 filetes de merluza","2 zanahorias en rodajas","1 patata mediana en rodajas","2 cdas aceite de oliva","Zumo de 1 limón","Eneldo o perejil fresco","Sal, pimienta blanca","Cebollino verde picado"],"en":["2 hake fillets","2 carrots sliced","1 medium potato sliced","2 tbsp olive oil","Juice of 1 lemon","Fresh dill or parsley","Salt, white pepper","Chopped green chives"]}',
'{"es":["Coloca la patata y la zanahoria en la cesta del vapor más abajo (tardan más)","Cuece 8 min, luego coloca la merluza encima","Cuece 12-14 min más hasta que la merluza esté tierna","Sirve con aceite de oliva, zumo de limón, eneldo y cebollino"],"en":["Place potato and carrot in the lower steamer basket (they take longer)","Steam 8 min, then place hake on top","Steam 12-14 min more until hake is tender","Serve with olive oil, lemon juice, dill and chives"]}'
),

('bol_pavo_zanahoria_jengibre_fodmap',369,'lunch','🥕',
'{"es":"Bol de pavo, zanahoria y jengibre con arroz integral","en":"Turkey, carrot and ginger bowl with brown rice","fr":"Bowl dinde carotte gingembre et riz complet","it":"Bowl di tacchino carota e zenzero con riso integrale"}',
'{"es":"Bol nutritivo y digestivo: pavo magro, zanahoria y jengibre con arroz integral — low FODMAP completo","en":"Nutritious and digestive bowl: lean turkey, carrot and ginger with brown rice — complete low FODMAP"}',
8,30,460,32,54,10,6,
ARRAY['low_fodmap','gluten_free','lactose_free','high_protein'],
ARRAY['follicular','ovulation','luteal'],
ARRAY['maintain','muscle','energy'],
ARRAY['sibo','ibs'],
ARRAY['soy'],
'easy','20_40','low',
'{"es":["200g filete de pavo en dados","160g arroz integral","2 zanahorias en rodajas","1 cdta jengibre fresco rallado","2 cdas aceite de ajo infusionado","1 cda tamari sin gluten","1 cda aceite de sésamo","Cebollino verde, sésamo, perejil"],"en":["200g turkey fillet diced","160g brown rice","2 carrots sliced","1 tsp fresh grated ginger","2 tbsp garlic-infused oil","1 tbsp gluten-free tamari","1 tbsp sesame oil","Green chives, sesame, parsley"]}',
'{"es":["Cuece el arroz integral (unos 25-28 min)","Dora el pavo en el aceite infusionado 5-6 min","Añade la zanahoria y cocina 5 min más","Incorpora el jengibre, el tamari y el aceite de sésamo, mezcla bien","Sirve sobre el arroz integral con cebollino verde, sésamo y perejil"],"en":["Cook brown rice (about 25-28 min)","Brown turkey in infused oil 5-6 min","Add carrot and cook 5 min more","Add ginger, tamari and sesame oil, mix well","Serve over brown rice with green chives, sesame and parsley"]}'
),

('batido_fresa_avena_fodmap',370,'breakfast','🍓',
'{"es":"Batido de fresa y avena (low FODMAP)","en":"Strawberry and oat smoothie (low FODMAP)","fr":"Smoothie fraise et avoine (low FODMAP)","it":"Smoothie di fragola e avena (low FODMAP)"}',
'{"es":"Batido energético low FODMAP: fresa, avena sin gluten, leche de almendra y semillas de chía","en":"Energising low FODMAP smoothie: strawberry, gluten-free oats, almond milk and chia seeds"}',
5,0,300,9,50,8,6,
ARRAY['low_fodmap','gluten_free','lactose_free','vegan','vegetarian'],
ARRAY['menstrual','follicular','luteal'],
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['sibo','ibs'],
ARRAY['nuts'],
'easy','under_20','low',
'{"es":["150g fresas frescas o congeladas","40g copos de avena sin gluten","250ml leche de almendra sin azúcar","1 cda semillas de chía","1 cdta extracto de vainilla","1 cdta canela","1 cda sirope de arce o agave","Cubitos de hielo"],"en":["150g fresh or frozen strawberries","40g gluten-free oat flakes","250ml unsweetened almond milk","1 tbsp chia seeds","1 tsp vanilla extract","1 tsp cinnamon","1 tbsp maple or agave syrup","Ice cubes"]}',
'{"es":["Coloca todos los ingredientes en la batidora","Bate a velocidad alta 60 seg hasta que esté completamente suave","Si es muy espeso añade un poco más de leche de almendra","Bebe inmediatamente"],"en":["Place all ingredients in the blender","Blend on high for 60 sec until completely smooth","If too thick add a little more almond milk","Drink immediately"]}'
)

ON CONFLICT (id) DO NOTHING;
