-- ═══════════════════════════════════════════════════════════════════════════
-- MEIRINS · Tabla diets — ejecutar en Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS diets (
  id                   TEXT        PRIMARY KEY,
  display_order        INT         NOT NULL,
  icon                 TEXT,
  category             TEXT        NOT NULL,
  name                 JSONB       NOT NULL,
  description          JSONB,
  allowed_foods        JSONB,
  forbidden_foods      JSONB,
  limited_foods        JSONB,
  macros               JSONB,
  calories_note        JSONB,
  benefits             JSONB,
  warnings             JSONB,
  compatible_goals     TEXT[]      DEFAULT '{}',
  good_for_conditions  TEXT[]      DEFAULT '{}',
  avoid_for_conditions TEXT[]      DEFAULT '{}',
  allergen_free        TEXT[]      DEFAULT '{}',
  fasting_window       JSONB,
  sample_day           JSONB,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS diets_category_idx   ON diets (category);
CREATE INDEX IF NOT EXISTS diets_goals_idx      ON diets USING gin (compatible_goals);
CREATE INDEX IF NOT EXISTS diets_cond_idx       ON diets USING gin (good_for_conditions);
CREATE INDEX IF NOT EXISTS diets_allerg_idx     ON diets USING gin (allergen_free);

ALTER TABLE diets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "diets_public_read" ON diets;
CREATE POLICY "diets_public_read" ON diets FOR SELECT USING (true);

-- ── 1. ESTÁNDAR ──────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'standard',1,'🍽️','standard',
'{"es":"Estándar","en":"Standard","fr":"Standard","it":"Standard"}',
'{"es":"Dieta equilibrada y variada sin restricciones específicas. Incluye todos los grupos alimentarios en proporciones adecuadas.","en":"Balanced and varied diet with no specific restrictions. Includes all food groups in adequate proportions.","fr":"Alimentation équilibrée et variée sans restrictions spécifiques. Inclut tous les groupes alimentaires.","it":"Dieta equilibrata e varia senza restrizioni specifiche. Include tutti i gruppi alimentari."}',
'{"es":["Carnes magras y pescados","Frutas y verduras de temporada","Cereales integrales","Legumbres","Lácteos","Huevos","Frutos secos","Aceite de oliva"],"en":["Lean meats and fish","Seasonal fruits and vegetables","Whole grains","Legumes","Dairy","Eggs","Nuts","Olive oil"],"fr":["Viandes maigres et poissons","Fruits et légumes de saison","Céréales complètes","Légumineuses","Produits laitiers","Œufs","Noix","Huile d''olive"],"it":["Carni magre e pesce","Frutta e verdura di stagione","Cereali integrali","Legumi","Latticini","Uova","Frutta secca","Olio d''oliva"]}',
'{"es":["Ultraprocesados","Azúcar añadida en exceso","Alcohol en exceso","Grasas trans"],"en":["Ultra-processed foods","Excess added sugar","Excess alcohol","Trans fats"],"fr":["Ultra-transformés","Excès de sucre ajouté","Excès d''alcool","Graisses trans"],"it":["Ultra-processati","Zuccheri aggiunti in eccesso","Alcol in eccesso","Grassi trans"]}',
'{"es":["Carnes rojas (máx. 2×/semana)","Sal","Dulces"],"en":["Red meat (max 2×/week)","Salt","Sweets"],"fr":["Viande rouge (max 2×/semaine)","Sel","Sucreries"],"it":["Carne rossa (max 2×/settimana)","Sale","Dolci"]}',
'{"carbs_pct":50,"protein_pct":20,"fat_pct":30}',
'{"es":["Fácil de seguir en contextos sociales","Cubre todas las necesidades nutricionales","Flexible y sostenible a largo plazo"],"en":["Easy to follow in social settings","Covers all nutritional needs","Flexible and sustainable long-term"],"fr":["Facile à suivre en contexte social","Couvre tous les besoins nutritionnels","Flexible et durable"],"it":["Facile da seguire in contesti sociali","Copre tutti i fabbisogni nutrizionali","Flessibile e sostenibile"]}',
'{"es":["Requiere variedad activa para evitar déficits","Sin guía puede incluir demasiados procesados"],"en":["Requires active variety to avoid deficits","Without guidance may include too many processed foods"],"fr":["Nécessite de la variété pour éviter les carences","Sans guide peut inclure trop d''aliments transformés"],"it":["Richiede varietà per evitare carenze","Senza guida può includere troppi alimenti trasformati"]}',
ARRAY['lose_weight','maintain','gain_muscle','energy'],
ARRAY['anemia','hypothyroid'],
ARRAY[]::text[],
'{"es":{"breakfast":["Tostada integral con tomate y aceite","Yogur con fruta","Café o té"],"lunch":["Pollo a la plancha con verduras","Arroz integral","Fruta"],"dinner":["Salmón al horno","Ensalada verde","Pan integral"],"snacks":["Puñado de nueces","Fruta de temporada"]},"en":{"breakfast":["Wholegrain toast with tomato and oil","Yoghurt with fruit","Coffee or tea"],"lunch":["Grilled chicken with vegetables","Brown rice","Fruit"],"dinner":["Baked salmon","Green salad","Wholegrain bread"],"snacks":["Handful of nuts","Seasonal fruit"]}}'
);

-- ── 2. VEGETARIANA ───────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'vegetarian',2,'🥦','plant-based',
'{"es":"Vegetariana","en":"Vegetarian","fr":"Végétarienne","it":"Vegetariana"}',
'{"es":"Excluye carnes y pescados pero incluye huevos y lácteos. Rica en fibra, antioxidantes y fitoquímicos.","en":"Excludes meat and fish but includes eggs and dairy. Rich in fibre, antioxidants and phytochemicals.","fr":"Exclut viandes et poissons mais inclut œufs et produits laitiers. Riche en fibres et antioxydants.","it":"Esclude carne e pesce ma include uova e latticini. Ricca di fibre, antiossidanti e fitochimica."}',
'{"es":["Huevos","Lácteos","Legumbres","Tofu y tempeh","Frutas y verduras","Cereales integrales","Frutos secos y semillas","Aceite de oliva"],"en":["Eggs","Dairy","Legumes","Tofu and tempeh","Fruits and vegetables","Whole grains","Nuts and seeds","Olive oil"],"fr":["Œufs","Produits laitiers","Légumineuses","Tofu et tempeh","Fruits et légumes","Céréales complètes","Noix et graines","Huile d''olive"],"it":["Uova","Latticini","Legumi","Tofu e tempeh","Frutta e verdura","Cereali integrali","Frutta secca e semi","Olio d''oliva"]}',
'{"es":["Carne de res, cerdo, pollo, cordero","Pescados y mariscos","Gelatina animal","Caldos de carne"],"en":["Beef, pork, chicken, lamb","Fish and seafood","Animal gelatine","Meat stocks"],"fr":["Bœuf, porc, poulet, agneau","Poissons et fruits de mer","Gélatine animale","Bouillons de viande"],"it":["Manzo, maiale, pollo, agnello","Pesce e frutti di mare","Gelatina animale","Brodi di carne"]}',
'{"es":["Huevos (máx. 4-6/semana)","Quesos curados","Dulces con gelatina"],"en":["Eggs (max 4-6/week)","Aged cheeses","Sweets with gelatine"],"fr":["Œufs (max 4-6/semaine)","Fromages affinés","Confiseries avec gélatine"],"it":["Uova (max 4-6/settimana)","Formaggi stagionati","Dolci con gelatina"]}',
'{"carbs_pct":55,"protein_pct":18,"fat_pct":27}',
'{"es":["Reduce riesgo cardiovascular","Alta en fibra y antioxidantes","Menor huella ecológica","Beneficiosa en endometriosis y PCOS"],"en":["Reduces cardiovascular risk","High in fibre and antioxidants","Lower ecological footprint","Beneficial in endometriosis and PCOS"],"fr":["Réduit le risque cardiovasculaire","Riche en fibres et antioxydants","Empreinte écologique réduite","Bénéfique pour l''endométriose et le SOPK"],"it":["Riduce il rischio cardiovascolare","Alta in fibre e antiossidanti","Minore impronta ecologica","Benefica per endometriosi e PCOS"]}',
'{"es":["Riesgo de déficit de B12, hierro y zinc","Requiere planificación para proteína completa"],"en":["Risk of B12, iron and zinc deficiency","Requires planning for complete protein"],"fr":["Risque de carence en B12, fer et zinc","Nécessite une planification pour les protéines complètes"],"it":["Rischio di carenza di B12, ferro e zinco","Richiede pianificazione per proteine complete"]}',
ARRAY['lose_weight','maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos'],
ARRAY[]::text[],
'{"es":{"breakfast":["Tortilla de espinacas y queso","Tostada integral","Zumo de naranja"],"lunch":["Lentejas con verduras","Arroz integral","Yogur"],"dinner":["Revuelto de tofu con pimientos","Pan integral"],"snacks":["Hummus con zanahoria","Fruta"]},"en":{"breakfast":["Spinach and cheese omelette","Wholegrain toast","Orange juice"],"lunch":["Lentils with vegetables","Brown rice","Yoghurt"],"dinner":["Tofu scramble with peppers","Wholegrain bread"],"snacks":["Hummus with carrots","Fruit"]}}'
);

-- ── 3. VEGANA ────────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'vegan',3,'🌱','plant-based',
'{"es":"Vegana","en":"Vegan","fr":"Végane","it":"Vegana"}',
'{"es":"Excluye todos los productos de origen animal. Basada íntegramente en plantas, requiere suplementación de B12.","en":"Excludes all animal products. Entirely plant-based, requires B12 supplementation.","fr":"Exclut tous les produits d''origine animale. Entièrement végétale, nécessite une supplémentation en B12.","it":"Esclude tutti i prodotti di origine animale. Interamente a base vegetale, richiede integrazione di B12."}',
'{"es":["Legumbres (lentejas, garbanzos, soja)","Tofu, tempeh, seitán","Frutas y verduras","Cereales integrales","Frutos secos y semillas","Bebidas vegetales","Algas","Levadura nutricional"],"en":["Legumes (lentils, chickpeas, soy)","Tofu, tempeh, seitan","Fruits and vegetables","Whole grains","Nuts and seeds","Plant milks","Seaweed","Nutritional yeast"],"fr":["Légumineuses (lentilles, pois chiches, soja)","Tofu, tempeh, seitan","Fruits et légumes","Céréales complètes","Noix et graines","Boissons végétales","Algues","Levure nutritionnelle"],"it":["Legumi (lenticchie, ceci, soia)","Tofu, tempeh, seitan","Frutta e verdura","Cereali integrali","Frutta secca e semi","Bevande vegetali","Alghe","Lievito alimentare"]}',
'{"es":["Carne, pescado, mariscos","Huevos y lácteos","Miel","Gelatina, caseína, suero de leche"],"en":["Meat, fish, seafood","Eggs and dairy","Honey","Gelatine, casein, whey"],"fr":["Viande, poisson, fruits de mer","Œufs et produits laitiers","Miel","Gélatine, caséine, lactosérum"],"it":["Carne, pesce, frutti di mare","Uova e latticini","Miele","Gelatina, caseina, siero di latte"]}',
'{"es":["Aceites vegetales procesados","Azúcares refinados (verificar proceso)"],"en":["Processed vegetable oils","Refined sugars (check processing)"],"fr":["Huiles végétales transformées","Sucres raffinés (vérifier le procédé)"],"it":["Oli vegetali raffinati","Zuccheri raffinati (verificare il processo)"]}',
'{"carbs_pct":60,"protein_pct":15,"fat_pct":25}',
'{"es":["Muy beneficiosa para endometriosis (reduce estrógeno circulante)","Reduce inflamación sistémica","Beneficios cardiovasculares","Menor riesgo de diabetes tipo 2"],"en":["Very beneficial for endometriosis (reduces circulating oestrogen)","Reduces systemic inflammation","Cardiovascular benefits","Lower risk of type 2 diabetes"],"fr":["Très bénéfique pour l''endométriose (réduit les œstrogènes)","Réduit l''inflammation systémique","Bénéfices cardiovasculaires","Risque réduit de diabète type 2"],"it":["Molto benefica per l''endometriosi (riduce gli estrogeni circolanti)","Riduce l''infiammazione sistemica","Benefici cardiovascolari","Ridotto rischio di diabete tipo 2"]}',
'{"es":["Déficit de B12 (suplementación obligatoria)","Riesgo de déficit de hierro, calcio, D3, omega-3 y zinc","Requiere planificación cuidadosa"],"en":["B12 deficiency (supplementation mandatory)","Risk of iron, calcium, D3, omega-3 and zinc deficiency","Requires careful planning"],"fr":["Carence en B12 (supplémentation obligatoire)","Risque de carence en fer, calcium, D3, oméga-3 et zinc","Nécessite une planification soigneuse"],"it":["Carenza di B12 (integrazione obbligatoria)","Rischio di carenza di ferro, calcio, D3, omega-3 e zinco","Richiede pianificazione attenta"]}',
ARRAY['lose_weight','maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos','type2_diabetes'],
ARRAY[]::text[],
'{"es":{"breakfast":["Smoothie de plátano, espinacas y leche de avena","Tostada con aguacate y semillas de cáñamo"],"lunch":["Bowl de garbanzos, quinoa y verduras asadas","Tahini y limón"],"dinner":["Curry de lentejas rojas con arroz basmati"],"snacks":["Edamame","Frutos secos y dátiles"]},"en":{"breakfast":["Banana, spinach and oat milk smoothie","Toast with avocado and hemp seeds"],"lunch":["Chickpea, quinoa and roasted vegetable bowl","Tahini and lemon"],"dinner":["Red lentil curry with basmati rice"],"snacks":["Edamame","Nuts and dates"]}}'
);

-- ── 4. PESCETARIANA ──────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'pescatarian',4,'🐟','plant-based',
'{"es":"Pescetariana","en":"Pescatarian","fr":"Pescétarienne","it":"Pescetariana"}',
'{"es":"Dieta vegetariana que incluye pescado y mariscos. Excelente fuente de omega-3 y proteína de calidad.","en":"Vegetarian diet that includes fish and seafood. Excellent source of omega-3 and quality protein.","fr":"Régime végétarien incluant poisson et fruits de mer. Excellente source d''oméga-3 et de protéines.","it":"Dieta vegetariana che include pesce e frutti di mare. Ottima fonte di omega-3 e proteine di qualità."}',
'{"es":["Pescados (salmón, sardinas, caballa, atún)","Mariscos","Huevos","Lácteos","Legumbres","Tofu y tempeh","Frutas, verduras","Cereales integrales"],"en":["Fish (salmon, sardines, mackerel, tuna)","Seafood","Eggs","Dairy","Legumes","Tofu and tempeh","Fruits, vegetables","Whole grains"],"fr":["Poissons (saumon, sardines, maquereau, thon)","Fruits de mer","Œufs","Produits laitiers","Légumineuses","Tofu et tempeh","Fruits, légumes","Céréales complètes"],"it":["Pesci (salmone, sardine, sgombro, tonno)","Frutti di mare","Uova","Latticini","Legumi","Tofu e tempeh","Frutta, verdura","Cereali integrali"]}',
'{"es":["Carne roja","Aves de corral","Embutidos","Caldo de carne"],"en":["Red meat","Poultry","Cold cuts","Meat stock"],"fr":["Viande rouge","Volaille","Charcuterie","Bouillon de viande"],"it":["Carne rossa","Pollame","Salumi","Brodo di carne"]}',
'{"es":["Pescados grandes (atún, pez espada) — mercurio","Mariscos (máx. 2×/semana)"],"en":["Large fish (tuna, swordfish) — mercury","Shellfish (max 2×/week)"],"fr":["Grands poissons (thon, espadon) — mercure","Crustacés (max 2×/semaine)"],"it":["Pesci grandi (tonno, pesce spada) — mercurio","Molluschi (max 2×/settimana)"]}',
'{"carbs_pct":50,"protein_pct":22,"fat_pct":28}',
'{"es":["Rica en omega-3 antiinflamatorios","Excelente para la salud cardiovascular","Buena fuente de hierro hemo","Beneficiosa en endometriosis y SOP"],"en":["Rich in anti-inflammatory omega-3","Excellent for cardiovascular health","Good source of haem iron","Beneficial in endometriosis and PCOS"],"fr":["Riche en oméga-3 anti-inflammatoires","Excellente pour la santé cardiovasculaire","Bonne source de fer héminique","Bénéfique pour l''endométriose et le SOPK"],"it":["Ricca di omega-3 antinfiammatori","Eccellente per la salute cardiovascolare","Buona fonte di ferro eme","Benefica per endometriosi e PCOS"]}',
'{"es":["Atención al mercurio en embarazo","Verificar alérgenos a mariscos"],"en":["Watch mercury content during pregnancy","Check for shellfish allergies"],"fr":["Attention au mercure pendant la grossesse","Vérifier les allergies aux crustacés"],"it":["Attenzione al mercurio in gravidanza","Verificare allergie ai crostacei"]}',
ARRAY['lose_weight','maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos','anemia'],
ARRAY[]::text[],
'{"es":{"breakfast":["Yogur griego con frutos rojos","Tostada con salmón ahumado"],"lunch":["Salmón al horno con quinoa y espinacas","Vinagreta de limón"],"dinner":["Merluza al vapor con brócoli y patata"],"snacks":["Sardinas en conserva","Fruta"]},"en":{"breakfast":["Greek yoghurt with berries","Toast with smoked salmon"],"lunch":["Baked salmon with quinoa and spinach","Lemon dressing"],"dinner":["Steamed hake with broccoli and potato"],"snacks":["Tinned sardines","Fruit"]}}'
);

-- ── 5. SIN LACTOSA ───────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'lactose_free',5,'🥛','intolerance',
'{"es":"Sin lactosa","en":"Lactose-free","fr":"Sans lactose","it":"Senza lattosio"}',
'{"es":"Elimina la lactosa para personas con intolerancia. No es una dieta restrictiva en cuanto a macros, solo evita el azúcar de la leche.","en":"Eliminates lactose for intolerant individuals. Not restrictive in macros, only avoids milk sugar.","fr":"Élimine le lactose pour les personnes intolérantes. Non restrictive en macros, évite uniquement le sucre du lait.","it":"Elimina il lattosio per le persone intolleranti. Non restrittiva nei macros, evita solo lo zucchero del latte."}',
'{"es":["Bebidas vegetales (avena, almendra, soja)","Quesos curados (muy bajo en lactosa)","Yogures sin lactosa","Leche sin lactosa","Carnes, pescados, huevos","Frutas, verduras","Cereales, legumbres"],"en":["Plant milks (oat, almond, soy)","Aged cheeses (very low lactose)","Lactose-free yoghurts","Lactose-free milk","Meat, fish, eggs","Fruits, vegetables","Grains, legumes"],"fr":["Boissons végétales (avoine, amande, soja)","Fromages affinés (très faible en lactose)","Yaourts sans lactose","Lait sans lactose","Viandes, poissons, œufs","Fruits, légumes","Céréales, légumineuses"],"it":["Bevande vegetali (avena, mandorla, soia)","Formaggi stagionati (pochissimo lattosio)","Yogurt senza lattosio","Latte senza lattosio","Carne, pesce, uova","Frutta, verdura","Cereali, legumi"]}',
'{"es":["Leche de vaca, cabra, oveja","Nata, mantequilla","Quesos frescos (ricotta, mozzarella fresca)","Helados convencionales","Salsas con nata"],"en":["Cow, goat, sheep milk","Cream, butter","Fresh cheeses (ricotta, fresh mozzarella)","Conventional ice cream","Cream-based sauces"],"fr":["Lait de vache, chèvre, brebis","Crème, beurre","Fromages frais (ricotta, mozzarella fraîche)","Glaces conventionnelles","Sauces à la crème"],"it":["Latte di mucca, capra, pecora","Panna, burro","Formaggi freschi (ricotta, mozzarella fresca)","Gelati convenzionali","Salse con panna"]}',
'{"es":["Chocolate con leche (verificar etiqueta)","Algunos medicamentos (excipiente lactosa)"],"en":["Milk chocolate (check label)","Some medications (lactose excipient)"],"fr":["Chocolat au lait (vérifier l''étiquette)","Certains médicaments (excipient lactose)"],"it":["Cioccolato al latte (verificare etichetta)","Alcuni farmaci (eccipiente lattosio)"]}',
'{"carbs_pct":50,"protein_pct":20,"fat_pct":30}',
'{"es":["Elimina síntomas digestivos (gases, hinchazón)","No supone restricción nutricional significativa","Fácil de adaptar"],"en":["Eliminates digestive symptoms (gas, bloating)","No significant nutritional restriction","Easy to adapt"],"fr":["Élimine les symptômes digestifs (gaz, ballonnements)","Pas de restriction nutritionnelle significative","Facile à adapter"],"it":["Elimina i sintomi digestivi (gas, gonfiore)","Nessuna restrizione nutrizionale significativa","Facile da adattare"]}',
'{"es":["Vigilar el calcio: compensar con bebidas vegetales enriquecidas","Leer etiquetas: la lactosa está en muchos procesados"],"en":["Monitor calcium: compensate with enriched plant milks","Read labels: lactose is in many processed foods"],"fr":["Surveiller le calcium: compenser avec des boissons végétales enrichies","Lire les étiquettes: le lactose est dans de nombreux produits transformés"],"it":["Monitorare il calcio: compensare con bevande vegetali arricchite","Leggere le etichette: il lattosio è in molti prodotti trasformati"]}',
ARRAY['lose_weight','maintain','gain_muscle','energy'],
ARRAY[]::text[],
ARRAY['lactose'],
'{"es":{"breakfast":["Leche de avena con copos de avena","Fruta fresca"],"lunch":["Pollo al horno con patatas y verduras"],"dinner":["Merluza a la plancha con arroz"],"snacks":["Yogur sin lactosa","Frutos secos"]},"en":{"breakfast":["Oat milk with oat flakes","Fresh fruit"],"lunch":["Oven chicken with potatoes and vegetables"],"dinner":["Grilled hake with rice"],"snacks":["Lactose-free yoghurt","Nuts"]}}'
);

-- ── 6. SIN GLUTEN ────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'gluten_free',6,'🌾','intolerance',
'{"es":"Sin gluten","en":"Gluten-free","fr":"Sans gluten","it":"Senza glutine"}',
'{"es":"Elimina el gluten para personas con celiaquía o sensibilidad. Imprescindible en celiaquía, opcional en sensibilidad no celiaca.","en":"Eliminates gluten for coeliac or sensitive individuals. Essential in coeliac disease, optional in non-coeliac sensitivity.","fr":"Élimine le gluten pour les personnes cœliaques ou sensibles. Indispensable en cas de maladie cœliaque.","it":"Elimina il glutine per persone celiache o sensibili. Indispensabile nella celiachia, opzionale nella sensibilità."}',
'{"es":["Arroz y harina de arroz","Maíz y maicena","Quinoa, mijo, amaranto, teff","Patatas","Carnes, pescados, huevos","Frutas y verduras","Legumbres","Lácteos","Avena certificada sin gluten"],"en":["Rice and rice flour","Corn and cornstarch","Quinoa, millet, amaranth, teff","Potatoes","Meat, fish, eggs","Fruits and vegetables","Legumes","Dairy","Certified gluten-free oats"],"fr":["Riz et farine de riz","Maïs et fécule de maïs","Quinoa, millet, amarante, teff","Pommes de terre","Viandes, poissons, œufs","Fruits et légumes","Légumineuses","Produits laitiers","Avoine certifiée sans gluten"],"it":["Riso e farina di riso","Mais e amido di mais","Quinoa, miglio, amaranto, teff","Patate","Carne, pesce, uova","Frutta e verdura","Legumi","Latticini","Avena certificata senza glutine"]}',
'{"es":["Trigo, cebada, centeno, espelta","Pan, pasta, cuscús convencionales","Cerveza","Salsas de soja estándar","Productos horneados convencionales"],"en":["Wheat, barley, rye, spelt","Conventional bread, pasta, couscous","Beer","Standard soy sauce","Conventional baked goods"],"fr":["Blé, orge, seigle, épeautre","Pain, pâtes, couscous conventionnels","Bière","Sauce soja standard","Produits de boulangerie conventionnels"],"it":["Frumento, orzo, segale, farro","Pane, pasta, couscous convenzionali","Birra","Salsa di soia standard","Prodotti da forno convenzionali"]}',
'{"es":["Avena (contaminación cruzada posible)","Productos procesados etiquetados «puede contener gluten»"],"en":["Oats (possible cross-contamination)","Processed products labelled ''may contain gluten''"],"fr":["Avoine (contamination croisée possible)","Produits transformés étiquetés ''peut contenir du gluten''"],"it":["Avena (possibile contaminazione crociata)","Prodotti trasformati etichettati ''può contenere glutine''"]}',
'{"carbs_pct":50,"protein_pct":20,"fat_pct":30}',
'{"es":["Elimina síntomas en celíacos (dolor abdominal, diarrea)","Mejora absorción de nutrientes en celiaquía","Reduce inflamación intestinal"],"en":["Eliminates symptoms in coeliac patients (abdominal pain, diarrhoea)","Improves nutrient absorption in coeliac disease","Reduces intestinal inflammation"],"fr":["Élimine les symptômes chez les cœliaques","Améliore l''absorption des nutriments","Réduit l''inflammation intestinale"],"it":["Elimina i sintomi nei celiaci","Migliora l''assorbimento dei nutrienti","Riduce l''infiammazione intestinale"]}',
'{"es":["Los sustitutos sin gluten suelen tener más azúcar y menos fibra","Riesgo de déficit de fibra, B1, B2, folato","Vigilar contaminación cruzada en restaurantes"],"en":["Gluten-free substitutes often have more sugar and less fibre","Risk of fibre, B1, B2, folate deficiency","Watch cross-contamination in restaurants"],"fr":["Les substituts sans gluten ont souvent plus de sucre et moins de fibres","Risque de carence en fibres, B1, B2, folate","Surveiller la contamination croisée au restaurant"],"it":["I sostituti senza glutine hanno spesso più zucchero e meno fibre","Rischio di carenza di fibre, B1, B2, folato","Attenzione alla contaminazione crociata"]}',
ARRAY['lose_weight','maintain','energy'],
ARRAY[]::text[],
ARRAY['gluten'],
'{"es":{"breakfast":["Copos de arroz con leche","Fruta","Café"],"lunch":["Arroz integral con pollo y verduras","Ensalada"],"dinner":["Merluza al horno con patatas"],"snacks":["Tortitas de maíz con aguacate","Fruta"]},"en":{"breakfast":["Rice flakes with milk","Fruit","Coffee"],"lunch":["Brown rice with chicken and vegetables","Salad"],"dinner":["Baked hake with potatoes"],"snacks":["Corn cakes with avocado","Fruit"]}}'
);

-- ── 7. LOW FODMAP ────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'low_fodmap',7,'🫙','therapeutic',
'{"es":"Low FODMAP","en":"Low FODMAP","fr":"Low FODMAP","it":"Low FODMAP"}',
'{"es":"Reduce los carbohidratos fermentables para aliviar el síndrome de intestino irritable. Se hace en 3 fases: eliminación, reintroducción y personalización.","en":"Reduces fermentable carbohydrates to relieve irritable bowel syndrome. Done in 3 phases: elimination, reintroduction and personalisation.","fr":"Réduit les glucides fermentescibles pour soulager le syndrome de l''intestin irritable. Se fait en 3 phases.","it":"Riduce i carboidrati fermentabili per alleviare la sindrome dell''intestino irritabile. Si svolge in 3 fasi."}',
'{"es":["Arroz, quinoa, avena (porción controlada)","Pollo, pavo, pescados, huevos","Lactosa reducida: quesos curados, leche sin lactosa","Verduras bajas en FODMAP: zanahoria, pepino, tomate, espinacas","Frutas: kiwi, naranja, fresa, arándanos","Frutos secos (nueces, nueces de macadamia, en pequeñas cantidades)"],"en":["Rice, quinoa, oats (controlled portion)","Chicken, turkey, fish, eggs","Low-lactose: aged cheeses, lactose-free milk","Low-FODMAP vegetables: carrot, cucumber, tomato, spinach","Fruits: kiwi, orange, strawberry, blueberries","Nuts (walnuts, macadamia, in small amounts)"],"fr":["Riz, quinoa, avoine (portion contrôlée)","Poulet, dinde, poissons, œufs","Faible en lactose: fromages affinés, lait sans lactose","Légumes faibles en FODMAP: carotte, concombre, tomate, épinards","Fruits: kiwi, orange, fraise, myrtilles","Noix (noix, macadamia, en petites quantités)"],"it":["Riso, quinoa, avena (porzione controllata)","Pollo, tacchino, pesce, uova","Basso lattosio: formaggi stagionati, latte senza lattosio","Verdure low-FODMAP: carota, cetriolo, pomodoro, spinaci","Frutti: kiwi, arancia, fragola, mirtilli","Frutta secca (noci, macadamia, piccole quantità)"]}',
'{"es":["Ajo y cebolla (altos en fructanos)","Manzana, pera, mango (alta fructosa)","Legumbres (judías, lentejas en fase inicial)","Trigo y centeno","Leche y yogur convencionales","Coliflor, alcachofas, espárragos"],"en":["Garlic and onion (high fructans)","Apple, pear, mango (high fructose)","Legumes (beans, lentils in initial phase)","Wheat and rye","Conventional milk and yoghurt","Cauliflower, artichokes, asparagus"],"fr":["Ail et oignon (riches en fructanes)","Pomme, poire, mangue (fructose élevé)","Légumineuses (haricots, lentilles en phase initiale)","Blé et seigle","Lait et yaourt conventionnels","Chou-fleur, artichauts, asperges"],"it":["Aglio e cipolla (ricchi di fruttani)","Mela, pera, mango (alto fruttosio)","Legumi (fagioli, lenticchie in fase iniziale)","Frumento e segale","Latte e yogurt convenzionali","Cavolfiore, carciofi, asparagi"]}',
'{"es":["Avena (en porción pequeña, max 52g)","Nueces de cajú y pistachos (porción pequeña)"],"en":["Oats (small portion, max 52g)","Cashews and pistachios (small portion)"],"fr":["Avoine (petite portion, max 52g)","Noix de cajou et pistaches (petite portion)"],"it":["Avena (piccola porzione, max 52g)","Anacardi e pistacchi (piccola porzione)"]}',
'{"carbs_pct":48,"protein_pct":25,"fat_pct":27}',
'{"es":["Alivia síntomas de SII (hinchazón, dolor, diarrea)","Mejora calidad de vida en trastornos digestivos funcionales","Evidencia científica sólida"],"en":["Relieves IBS symptoms (bloating, pain, diarrhoea)","Improves quality of life in functional digestive disorders","Solid scientific evidence"],"fr":["Soulage les symptômes du SII (ballonnements, douleurs, diarrhée)","Améliore la qualité de vie dans les troubles digestifs fonctionnels","Preuves scientifiques solides"],"it":["Allevia i sintomi dell''IBS (gonfiore, dolore, diarrea)","Migliora la qualità della vita nei disturbi digestivi funzionali","Solide evidenze scientifiche"]}',
'{"es":["Debe hacerse idealmente con dietista especializada","La fase de eliminación no debe durar más de 6-8 semanas","No apta para embarazadas sin supervisión"],"en":["Should ideally be done with a specialist dietitian","Elimination phase should not exceed 6-8 weeks","Not suitable for pregnant women without supervision"],"fr":["Devrait idéalement être réalisée avec une diététicienne spécialisée","La phase d''élimination ne doit pas dépasser 6-8 semaines","Non adaptée aux femmes enceintes sans suivi"],"it":["Va seguita idealmente con una dietista specializzata","La fase di eliminazione non deve superare le 6-8 settimane","Non adatta alle donne incinte senza supervisione"]}',
ARRAY['maintain','energy','reduce_symptoms'],
ARRAY['ibs'],
ARRAY[]::text[],
'{"es":{"breakfast":["Copos de avena (52g) con leche sin lactosa","Fresas y kiwi","Café negro"],"lunch":["Pollo a la plancha con arroz","Zanahorias y pepino al vapor"],"dinner":["Salmón al horno con patatas y espinacas"],"snacks":["Queso cheddar curado","Arándanos"]},"en":{"breakfast":["Oat flakes (52g) with lactose-free milk","Strawberries and kiwi","Black coffee"],"lunch":["Grilled chicken with rice","Steamed carrots and cucumber"],"dinner":["Baked salmon with potato and spinach"],"snacks":["Aged cheddar","Blueberries"]}}'
);

-- ── 8. MEDITERRÁNEA ──────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'mediterranean',8,'🫒','standard',
'{"es":"Mediterránea","en":"Mediterranean","fr":"Méditerranéenne","it":"Mediterranea"}',
'{"es":"Patrón alimentario del mediterráneo: aceite de oliva, pescado, legumbres, verduras, frutas y cereales. Una de las dietas más estudiadas y con mayor evidencia científica.","en":"Mediterranean eating pattern: olive oil, fish, legumes, vegetables, fruits and grains. One of the most studied diets with the strongest scientific evidence.","fr":"Modèle alimentaire méditerranéen: huile d''olive, poisson, légumineuses, légumes, fruits et céréales. L''une des plus étudiées.","it":"Modello alimentare mediterraneo: olio d''oliva, pesce, legumi, verdura, frutta e cereali. Una delle diete più studiate."}',
'{"es":["Aceite de oliva virgen extra (pilar central)","Pescado azul 2-3×/semana","Legumbres 3-4×/semana","Verduras abundantes en cada comida","Frutas frescas de temporada","Cereales integrales","Frutos secos","Vino tinto con moderación (opcional)"],"en":["Extra virgin olive oil (central pillar)","Oily fish 2-3×/week","Legumes 3-4×/week","Abundant vegetables at every meal","Fresh seasonal fruit","Whole grains","Nuts","Red wine in moderation (optional)"],"fr":["Huile d''olive vierge extra (pilier central)","Poissons gras 2-3×/semaine","Légumineuses 3-4×/semaine","Légumes abondants à chaque repas","Fruits frais de saison","Céréales complètes","Noix","Vin rouge avec modération (optionnel)"],"it":["Olio extravergine di oliva (pilastro centrale)","Pesce azzurro 2-3×/settimana","Legumi 3-4×/settimana","Verdure abbondanti ad ogni pasto","Frutta fresca di stagione","Cereali integrali","Frutta secca","Vino rosso con moderazione (opzionale)"]}',
'{"es":["Ultraprocesados","Carnes procesadas (embutidos)","Azúcares refinados","Grasas trans","Comida rápida"],"en":["Ultra-processed foods","Processed meats (cold cuts)","Refined sugars","Trans fats","Fast food"],"fr":["Ultra-transformés","Viandes transformées (charcuterie)","Sucres raffinés","Graisses trans","Restauration rapide"],"it":["Ultra-processati","Carni trasformate (salumi)","Zuccheri raffinati","Grassi trans","Fast food"]}',
'{"es":["Carne roja (máx. 1-2×/semana)","Carnes blancas (máx. 3-4×/semana)","Lácteos (preferir yogur y queso)"],"en":["Red meat (max 1-2×/week)","White meat (max 3-4×/week)","Dairy (prefer yoghurt and cheese)"],"fr":["Viande rouge (max 1-2×/semaine)","Viandes blanches (max 3-4×/semaine)","Produits laitiers (préférer yaourt et fromage)"],"it":["Carne rossa (max 1-2×/settimana)","Carni bianche (max 3-4×/settimana)","Latticini (preferire yogurt e formaggio)"]}',
'{"carbs_pct":45,"protein_pct":20,"fat_pct":35}',
'{"es":["Reduce riesgo cardiovascular en un 30%","Protege contra diabetes tipo 2","Antiinflamatoria por naturaleza","Mejora síntomas de endometriosis y SOP","Beneficiosa en todas las fases del ciclo","Longevidad demostrada"],"en":["Reduces cardiovascular risk by 30%","Protects against type 2 diabetes","Naturally anti-inflammatory","Improves endometriosis and PCOS symptoms","Beneficial in all cycle phases","Demonstrated longevity benefits"],"fr":["Réduit le risque cardiovasculaire de 30%","Protège contre le diabète type 2","Naturellement anti-inflammatoire","Améliore les symptômes d''endométriose et SOPK","Longévité démontrée"],"it":["Riduce il rischio cardiovascolare del 30%","Protegge dal diabete tipo 2","Naturalmente antinfiammatoria","Migliora i sintomi di endometriosi e PCOS","Longevità dimostrata"]}',
'{"es":["No recomendable si hay alergia a frutos secos o pescado","El aceite de oliva aporta muchas calorías: dosificar"],"en":["Not recommended with nut or fish allergies","Olive oil is calorie-dense: portion carefully"],"fr":["Non recommandée en cas d''allergie aux noix ou au poisson","L''huile d''olive est calorique: doser avec soin"],"it":["Non raccomandata in caso di allergie a frutta secca o pesce","L''olio di oliva è calorico: dosare con attenzione"]}',
ARRAY['lose_weight','maintain','energy','reduce_symptoms','performance'],
ARRAY['endometriosis','pcos','type2_diabetes','hypertension','anemia'],
ARRAY[]::text[],
'{"es":{"breakfast":["Tostada de pan integral con aceite de oliva y tomate","Nueces","Café"],"lunch":["Lentejas estofadas con verduras","Pan integral","Naranja"],"dinner":["Sardinas a la plancha con ensalada","Pan con aceite"],"snacks":["Frutos secos","Fruta de temporada"]},"en":{"breakfast":["Wholegrain toast with olive oil and tomato","Walnuts","Coffee"],"lunch":["Stewed lentils with vegetables","Wholegrain bread","Orange"],"dinner":["Grilled sardines with salad","Bread with oil"],"snacks":["Nuts","Seasonal fruit"]}}'
);

-- ── 9. ANTIINFLAMATORIA ──────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'anti_inflammatory',9,'🫐','therapeutic',
'{"es":"Antiinflamatoria","en":"Anti-inflammatory","fr":"Anti-inflammatoire","it":"Antinfiammatoria"}',
'{"es":"Prioriza alimentos que reducen la inflamación sistémica. Especialmente útil en endometriosis, SOP, artritis y enfermedades autoinmunes.","en":"Prioritises foods that reduce systemic inflammation. Especially useful in endometriosis, PCOS, arthritis and autoimmune diseases.","fr":"Privilégie les aliments qui réduisent l''inflammation systémique. Particulièrement utile dans l''endométriose, le SOPK, l''arthrite.","it":"Privilegia gli alimenti che riducono l''infiammazione sistemica. Particolarmente utile nell''endometriosi, PCOS, artrite."}',
'{"es":["Pescado azul rico en omega-3 (salmón, sardinas, caballa)","Frutos rojos (arándanos, fresas, cerezas)","Cúrcuma y jengibre","Verduras de hoja verde (espinacas, kale)","Aceite de oliva virgen extra","Nueces y semillas de lino","Brócoli y crucíferas","Té verde"],"en":["Oily fish rich in omega-3 (salmon, sardines, mackerel)","Berries (blueberries, strawberries, cherries)","Turmeric and ginger","Dark leafy greens (spinach, kale)","Extra virgin olive oil","Walnuts and flaxseeds","Broccoli and cruciferous vegetables","Green tea"],"fr":["Poissons gras riches en oméga-3 (saumon, sardines, maquereau)","Fruits rouges (myrtilles, fraises, cerises)","Curcuma et gingembre","Légumes à feuilles vertes (épinards, kale)","Huile d''olive vierge extra","Noix et graines de lin","Brocoli et crucifères","Thé vert"],"it":["Pesce azzurro ricco di omega-3 (salmone, sardine, sgombro)","Frutti di bosco (mirtilli, fragole, ciliegie)","Curcuma e zenzero","Verdure a foglia verde (spinaci, kale)","Olio extravergine di oliva","Noci e semi di lino","Broccoli e crucifere","Tè verde"]}',
'{"es":["Azúcar refinado","Aceites vegetales refinados (maíz, girasol, soja)","Carnes rojas y procesadas","Alcohol","Ultraprocesados","Trans fats","Gluten (en casos de sensibilidad)","Lácteos convencionales (en algunos casos)"],"en":["Refined sugar","Refined vegetable oils (corn, sunflower, soy)","Red and processed meats","Alcohol","Ultra-processed foods","Trans fats","Gluten (in sensitivity cases)","Conventional dairy (in some cases)"],"fr":["Sucre raffiné","Huiles végétales raffinées (maïs, tournesol, soja)","Viandes rouges et transformées","Alcool","Ultra-transformés","Graisses trans","Gluten (en cas de sensibilité)","Produits laitiers conventionnels (dans certains cas)"],"it":["Zucchero raffinato","Oli vegetali raffinati (mais, girasole, soia)","Carni rosse e trasformate","Alcol","Ultra-processati","Grassi trans","Glutine (nei casi di sensibilità)","Latticini convenzionali (in alcuni casi)"]}',
'{"es":["Cereales integrales (porción controlada)","Frutas dulces (mango, uva, plátano)"],"en":["Whole grains (controlled portion)","Sweet fruits (mango, grape, banana)"],"fr":["Céréales complètes (portion contrôlée)","Fruits sucrés (mangue, raisin, banane)"],"it":["Cereali integrali (porzione controllata)","Frutta dolce (mango, uva, banana)"]}',
'{"carbs_pct":40,"protein_pct":25,"fat_pct":35}',
'{"es":["Reduce marcadores inflamatorios (PCR, IL-6)","Alivia dolor en endometriosis","Mejora síntomas de SOP","Beneficiosa en artritis y enfermedades autoinmunes","Mejora la calidad del sueño"],"en":["Reduces inflammatory markers (CRP, IL-6)","Relieves pain in endometriosis","Improves PCOS symptoms","Beneficial in arthritis and autoimmune diseases","Improves sleep quality"],"fr":["Réduit les marqueurs inflammatoires (CRP, IL-6)","Soulage la douleur dans l''endométriose","Améliore les symptômes du SOPK","Bénéfique dans l''arthrite et les maladies auto-immunes","Améliore la qualité du sommeil"],"it":["Riduce i marcatori infiammatori (PCR, IL-6)","Allevia il dolore nell''endometriosi","Migliora i sintomi del PCOS","Benefica nell''artrite e nelle malattie autoimmuni","Migliora la qualità del sonno"]}',
'{"es":["Más restrictiva: requiere planificación","Puede ser costosa (pescado fresco, frutos rojos)","No es sustituto del tratamiento médico"],"en":["More restrictive: requires planning","Can be costly (fresh fish, berries)","Not a substitute for medical treatment"],"fr":["Plus restrictive: nécessite une planification","Peut être coûteuse (poisson frais, fruits rouges)","Ne remplace pas le traitement médical"],"it":["Più restrittiva: richiede pianificazione","Può essere costosa (pesce fresco, frutti di bosco)","Non sostituisce il trattamento medico"]}',
ARRAY['lose_weight','maintain','energy','reduce_symptoms'],
ARRAY['endometriosis','pcos','hypertension','anemia'],
ARRAY[]::text[],
'{"es":{"breakfast":["Smoothie de arándanos, espinacas y semillas de lino","Nueces","Té verde"],"lunch":["Salmón al horno con brócoli y quinoa","Aderezo de cúrcuma y jengibre"],"dinner":["Sardinas con ensalada de rúcula, tomate y aceite de oliva"],"snacks":["Frutos rojos","Chocolate negro 85%"]},"en":{"breakfast":["Blueberry, spinach and flaxseed smoothie","Walnuts","Green tea"],"lunch":["Baked salmon with broccoli and quinoa","Turmeric and ginger dressing"],"dinner":["Sardines with rocket, tomato and olive oil salad"],"snacks":["Berries","85% dark chocolate"]}}'
);

-- ── 10. PALEO ────────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'paleo',10,'🥩','ancestral',
'{"es":"Paleo","en":"Paleo","fr":"Paléo","it":"Paleo"}',
'{"es":"Imita la dieta del paleolítico: carnes, pescados, huevos, verduras, frutas y frutos secos. Sin cereales, legumbres ni lácteos.","en":"Mimics the palaeolithic diet: meats, fish, eggs, vegetables, fruits and nuts. No grains, legumes or dairy.","fr":"Imite le régime paléolithique: viandes, poissons, œufs, légumes, fruits et noix. Sans céréales, légumineuses ni produits laitiers.","it":"Imita la dieta paleolitica: carni, pesce, uova, verdura, frutta e frutta secca. Senza cereali, legumi né latticini."}',
'{"es":["Carnes magras y de pasto","Pescados y mariscos","Huevos","Verduras (excepto patata en versión estricta)","Frutas de bajo índice glucémico","Frutos secos y semillas","Aceites naturales (oliva, coco)","Especias y hierbas"],"en":["Lean and grass-fed meats","Fish and seafood","Eggs","Vegetables (except potato in strict version)","Low-glycaemic fruits","Nuts and seeds","Natural oils (olive, coconut)","Spices and herbs"],"fr":["Viandes maigres et de pâturage","Poissons et fruits de mer","Œufs","Légumes (sauf pomme de terre en version stricte)","Fruits à faible index glycémique","Noix et graines","Huiles naturelles (olive, coco)","Épices et herbes"],"it":["Carni magre e al pascolo","Pesce e frutti di mare","Uova","Verdura (tranne patate nella versione rigorosa)","Frutta a basso indice glicemico","Frutta secca e semi","Oli naturali (oliva, cocco)","Spezie ed erbe"]}',
'{"es":["Cereales (trigo, arroz, avena, maíz)","Legumbres (judías, lentejas, garbanzos)","Lácteos","Azúcar refinado y miel","Sal en exceso","Aceites vegetales refinados","Patatas (versión estricta)"],"en":["Grains (wheat, rice, oats, corn)","Legumes (beans, lentils, chickpeas)","Dairy","Refined sugar and honey","Excess salt","Refined vegetable oils","Potatoes (strict version)"],"fr":["Céréales (blé, riz, avoine, maïs)","Légumineuses (haricots, lentilles, pois chiches)","Produits laitiers","Sucre raffiné et miel","Excès de sel","Huiles végétales raffinées","Pommes de terre (version stricte)"],"it":["Cereali (frumento, riso, avena, mais)","Legumi (fagioli, lenticchie, ceci)","Latticini","Zucchero raffinato e miele","Sale in eccesso","Oli vegetali raffinati","Patate (versione rigorosa)"]}',
'{"es":["Patata y boniato (paleo flexible)","Fruta muy dulce (plátano, uva)","Miel y sirope de arce"],"en":["Potato and sweet potato (flexible paleo)","Very sweet fruit (banana, grapes)","Honey and maple syrup"],"fr":["Pomme de terre et patate douce (paléo flexible)","Fruits très sucrés (banane, raisin)","Miel et sirop d''érable"],"it":["Patata e patata dolce (paleo flessibile)","Frutta molto dolce (banana, uva)","Miele e sciroppo d''acero"]}',
'{"carbs_pct":25,"protein_pct":30,"fat_pct":45}',
'{"es":["Mejora sensibilidad a la insulina","Reduce inflamación","Pérdida de peso eficaz a corto plazo","Sin gluten ni lácteos por naturaleza"],"en":["Improves insulin sensitivity","Reduces inflammation","Effective short-term weight loss","Naturally gluten and dairy-free"],"fr":["Améliore la sensibilité à l''insuline","Réduit l''inflammation","Perte de poids efficace à court terme","Naturellement sans gluten ni produits laitiers"],"it":["Migliora la sensibilità all''insulina","Riduce l''infiammazione","Perdita di peso efficace a breve termine","Naturalmente senza glutine e latticini"]}',
'{"es":["Baja en calcio (sin lácteos)","Difícil de mantener a largo plazo","Cara (carne de pasto)","Puede ser baja en fibra si no se consumen muchas verduras"],"en":["Low in calcium (no dairy)","Hard to maintain long-term","Expensive (grass-fed meat)","Can be low in fibre without abundant vegetables"],"fr":["Pauvre en calcium (sans produits laitiers)","Difficile à maintenir à long terme","Coûteuse (viande de pâturage)","Peut être pauvre en fibres sans beaucoup de légumes"],"it":["Bassa in calcio (senza latticini)","Difficile da mantenere a lungo termine","Costosa (carne al pascolo)","Può essere povera di fibre senza molta verdura"]}',
ARRAY['lose_weight','energy'],
ARRAY['type2_diabetes','pcos'],
ARRAY['gluten','lactose'],
'{"es":{"breakfast":["Huevos revueltos con espinacas y aguacate","Fruta fresca"],"lunch":["Pollo al horno con boniato y brócoli","Aceite de oliva"],"dinner":["Salmón a la plancha con espárragos y cebolla"],"snacks":["Frutos secos","Fruta"]},"en":{"breakfast":["Scrambled eggs with spinach and avocado","Fresh fruit"],"lunch":["Oven chicken with sweet potato and broccoli","Olive oil"],"dinner":["Grilled salmon with asparagus and onion"],"snacks":["Nuts","Fruit"]}}'
);

-- ── 11. CETOGÉNICA (KETO) ────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,avoid_for_conditions,allergen_free,sample_day)
VALUES (
'keto',11,'🥑','low-carb',
'{"es":"Cetogénica (Keto)","en":"Ketogenic (Keto)","fr":"Cétogène (Keto)","it":"Chetogenica (Keto)"}',
'{"es":"Dieta muy baja en carbohidratos (max. 20-50g/día) y alta en grasas. Induce cetosis: el cuerpo quema grasa en lugar de glucosa como fuente de energía.","en":"Very low carbohydrate (max 20-50g/day) and high fat diet. Induces ketosis: the body burns fat instead of glucose for energy.","fr":"Régime très pauvre en glucides (max 20-50g/jour) et riche en graisses. Induit la cétose: le corps brûle les graisses plutôt que le glucose.","it":"Dieta molto povera di carboidrati (max 20-50g/giorno) e ricca di grassi. Induce la chetosi: il corpo brucia grassi invece di glucosio."}',
'{"es":["Carnes grasas (ternera, cerdo, cordero)","Pescados grasos (salmón, caballa)","Huevos","Quesos grasos (cheddar, gouda, brie)","Aguacate","Aceite de oliva y mantequilla","Frutos secos (nueces, almendras, pecanas)","Verduras de hoja verde y crucíferas"],"en":["Fatty meats (beef, pork, lamb)","Fatty fish (salmon, mackerel)","Eggs","Full-fat cheeses (cheddar, gouda, brie)","Avocado","Olive oil and butter","Nuts (walnuts, almonds, pecans)","Leafy greens and cruciferous vegetables"],"fr":["Viandes grasses (bœuf, porc, agneau)","Poissons gras (saumon, maquereau)","Œufs","Fromages gras (cheddar, gouda, brie)","Avocat","Huile d''olive et beurre","Noix (noix, amandes, pacanes)","Légumes à feuilles vertes et crucifères"],"it":["Carni grasse (manzo, maiale, agnello)","Pesce grasso (salmone, sgombro)","Uova","Formaggi grassi (cheddar, gouda, brie)","Avocado","Olio d''oliva e burro","Frutta secca (noci, mandorle, pecan)","Verdure a foglia verde e crucifere"]}',
'{"es":["Cereales y harinas","Azúcar y dulces","Frutas (excepto frutos rojos pequeñas cantidades)","Legumbres","Patata, boniato, maíz","Bebidas azucaradas","Alcohol (mayormente)"],"en":["Grains and flours","Sugar and sweets","Fruits (except small amounts of berries)","Legumes","Potato, sweet potato, corn","Sugary drinks","Alcohol (mostly)"],"fr":["Céréales et farines","Sucre et sucreries","Fruits (sauf petites quantités de baies)","Légumineuses","Pomme de terre, patate douce, maïs","Boissons sucrées","Alcool (principalement)"],"it":["Cereali e farine","Zucchero e dolci","Frutta (tranne piccole quantità di frutti di bosco)","Legumi","Patata, patata dolce, mais","Bevande zuccherate","Alcol (principalmente)"]}',
'{"es":["Frutos rojos (max. 50g/día)","Nata y mantequilla (ricas en grasa buena pero calorías)"],"en":["Berries (max 50g/day)","Cream and butter (good fat but calorie-dense)"],"fr":["Baies (max 50g/jour)","Crème et beurre (bonne graisse mais caloriques)"],"it":["Frutti di bosco (max 50g/giorno)","Panna e burro (grassi buoni ma calorici)"]}',
'{"carbs_pct":5,"protein_pct":25,"fat_pct":70}',
'{"es":["Pérdida de peso rápida (inicial)","Mejora de resistencia a la insulina","Útil en diabetes tipo 2 bajo supervisión","Reduce triglicéridos","Eficaz en epilepsia refractaria"],"en":["Rapid initial weight loss","Improves insulin resistance","Useful in type 2 diabetes under supervision","Reduces triglycerides","Effective in refractory epilepsy"],"fr":["Perte de poids rapide (initiale)","Améliore la résistance à l''insuline","Utile dans le diabète type 2 sous surveillance","Réduit les triglycérides","Efficace dans l''épilepsie réfractaire"],"it":["Rapida perdita di peso iniziale","Migliora la resistenza all''insulina","Utile nel diabete tipo 2 sotto supervisione","Riduce i trigliceridi","Efficace nell''epilessia refrattaria"]}',
'{"es":["Gripe keto las primeras 2 semanas","Puede alterar el ciclo menstrual si es muy restrictiva","No recomendable en embarazo ni lactancia","Riesgo de déficit de fibra, magnesio, potasio","Difícil de mantener socialmente"],"en":["Keto flu in the first 2 weeks","Can disrupt menstrual cycle if too restrictive","Not recommended during pregnancy or breastfeeding","Risk of fibre, magnesium, potassium deficiency","Socially difficult to maintain"],"fr":["Grippe keto les 2 premières semaines","Peut perturber le cycle menstruel si très restrictif","Non recommandé pendant la grossesse ou l''allaitement","Risque de carence en fibres, magnésium, potassium","Difficile à maintenir socialement"],"it":["Influenza keto nelle prime 2 settimane","Può alterare il ciclo mestruale se molto restrittiva","Non raccomandata in gravidanza o allattamento","Rischio di carenza di fibre, magnesio, potassio","Difficile da mantenere socialmente"]}',
ARRAY['lose_weight'],
ARRAY['type2_diabetes','pcos'],
ARRAY['pregnant','postpartum'],
ARRAY['gluten'],
'{"es":{"breakfast":["Huevos revueltos con mantequilla y queso","Aguacate","Café con nata"],"lunch":["Ensalada cesar con pollo y parmesano","Aceite de oliva"],"dinner":["Salmón a la plancha con espinacas salteadas en mantequilla"],"snacks":["Nueces","Queso gouda"]},"en":{"breakfast":["Scrambled eggs with butter and cheese","Avocado","Coffee with cream"],"lunch":["Caesar salad with chicken and parmesan","Olive oil"],"dinner":["Grilled salmon with spinach sautéed in butter"],"snacks":["Walnuts","Gouda cheese"]}}'
);

-- ── 12. LOW CARB ─────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'low_carb',12,'🥩','low-carb',
'{"es":"Low Carb","en":"Low Carb","fr":"Faible en glucides","it":"Low Carb"}',
'{"es":"Reduce los carbohidratos a 50-130g/día (frente a los 200-300g de una dieta estándar). Más flexible que la keto, sin inducir cetosis necesariamente.","en":"Reduces carbohydrates to 50-130g/day (vs 200-300g in a standard diet). More flexible than keto, without necessarily inducing ketosis.","fr":"Réduit les glucides à 50-130g/jour (contre 200-300g dans une alimentation standard). Plus flexible que le keto.","it":"Riduce i carboidrati a 50-130g/giorno (rispetto ai 200-300g di una dieta standard). Più flessibile della keto."}',
'{"es":["Carnes y pescados","Huevos","Verduras de bajo índice glucémico","Frutos rojos","Frutos secos","Aceite de oliva","Aguacate","Lácteos enteros"],"en":["Meat and fish","Eggs","Low-glycaemic vegetables","Berries","Nuts","Olive oil","Avocado","Full-fat dairy"],"fr":["Viandes et poissons","Œufs","Légumes à faible index glycémique","Baies","Noix","Huile d''olive","Avocat","Produits laitiers entiers"],"it":["Carne e pesce","Uova","Verdure a basso indice glicemico","Frutti di bosco","Frutta secca","Olio d''oliva","Avocado","Latticini interi"]}',
'{"es":["Pan, pasta, arroz en grandes cantidades","Azúcar y dulces","Zumos y bebidas azucaradas","Patatas fritas","Cereales de desayuno azucarados"],"en":["Large amounts of bread, pasta, rice","Sugar and sweets","Fruit juices and sugary drinks","Chips","Sugary breakfast cereals"],"fr":["Pain, pâtes, riz en grandes quantités","Sucre et sucreries","Jus et boissons sucrées","Chips","Céréales de petit-déjeuner sucrées"],"it":["Pane, pasta, riso in grandi quantità","Zucchero e dolci","Succhi e bevande zuccherate","Patatine","Cereali da colazione zuccherati"]}',
'{"es":["Cereales integrales (porción pequeña)","Frutas (max 2 raciones/día)","Legumbres (porción moderada)"],"en":["Whole grains (small portion)","Fruit (max 2 servings/day)","Legumes (moderate portion)"],"fr":["Céréales complètes (petite portion)","Fruits (max 2 portions/jour)","Légumineuses (portion modérée)"],"it":["Cereali integrali (piccola porzione)","Frutta (max 2 porzioni/giorno)","Legumi (porzione moderata)"]}',
'{"carbs_pct":25,"protein_pct":30,"fat_pct":45}',
'{"es":["Pérdida de peso sostenida","Mejora glucemia y resistencia insulínica","Reduce triglicéridos","Más fácil de seguir que la keto"],"en":["Sustained weight loss","Improves blood sugar and insulin resistance","Reduces triglycerides","Easier to follow than keto"],"fr":["Perte de poids soutenue","Améliore la glycémie et la résistance à l''insuline","Réduit les triglycérides","Plus facile à suivre que le keto"],"it":["Perdita di peso sostenuta","Migliora la glicemia e la resistenza insulinica","Riduce i trigliceridi","Più facile da seguire della keto"]}',
'{"es":["Puede causar fatiga inicial","Monitorizar fibra y micronutrientes"],"en":["May cause initial fatigue","Monitor fibre and micronutrients"],"fr":["Peut causer de la fatigue initiale","Surveiller fibres et micronutriments"],"it":["Può causare stanchezza iniziale","Monitorare fibre e micronutrienti"]}',
ARRAY['lose_weight','maintain'],
ARRAY['type2_diabetes','pcos'],
ARRAY[]::text[],
'{"es":{"breakfast":["Huevos con aguacate y salmón ahumado"],"lunch":["Pollo a la plancha con ensalada verde y aceite de oliva"],"dinner":["Merluza con judías verdes y zanahoria"],"snacks":["Nueces y frutos rojos"]},"en":{"breakfast":["Eggs with avocado and smoked salmon"],"lunch":["Grilled chicken with green salad and olive oil"],"dinner":["Hake with green beans and carrot"],"snacks":["Nuts and berries"]}}'
);

-- ── 13. ALTA EN PROTEÍNA ─────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'high_protein',13,'💪','performance',
'{"es":"Alta en proteína","en":"High protein","fr":"Riche en protéines","it":"Alta in proteine"}',
'{"es":"Incrementa la ingesta proteica al 25-40% de las calorías. Preserva masa muscular, aumenta saciedad y favorece la composición corporal.","en":"Increases protein intake to 25-40% of calories. Preserves muscle mass, increases satiety and improves body composition.","fr":"Augmente l''apport en protéines à 25-40% des calories. Préserve la masse musculaire, augmente la satiété.","it":"Aumenta l''apporto proteico al 25-40% delle calorie. Preserva la massa muscolare, aumenta la sazietà."}',
'{"es":["Pechuga de pollo y pavo","Claras de huevo y huevos enteros","Proteínas vegetales: tofu, tempeh, edamame","Pescados y mariscos","Lácteos altos en proteína: queso fresco 0%, yogur griego, queso cottage","Legumbres","Carne magra de ternera"],"en":["Chicken and turkey breast","Egg whites and whole eggs","Plant proteins: tofu, tempeh, edamame","Fish and seafood","High-protein dairy: 0% cottage cheese, Greek yoghurt, cottage cheese","Legumes","Lean beef"],"fr":["Blanc de poulet et dinde","Blancs d''œufs et œufs entiers","Protéines végétales: tofu, tempeh, edamame","Poissons et fruits de mer","Produits laitiers riches en protéines: fromage blanc 0%, yaourt grec","Légumineuses","Bœuf maigre"],"it":["Petto di pollo e tacchino","Albumi e uova intere","Proteine vegetali: tofu, tempeh, edamame","Pesce e frutti di mare","Latticini ad alto contenuto proteico: ricotta 0%, yogurt greco","Legumi","Manzo magro"]}',
'{"es":["Ultraprocesados","Grasas saturadas en exceso","Azúcares refinados"],"en":["Ultra-processed foods","Excess saturated fats","Refined sugars"],"fr":["Ultra-transformés","Excès de graisses saturées","Sucres raffinés"],"it":["Ultra-processati","Grassi saturi in eccesso","Zuccheri raffinati"]}',
'{"es":["Carbohidratos simples","Grasas totales (mantener moderadas)"],"en":["Simple carbohydrates","Total fat (keep moderate)"],"fr":["Glucides simples","Graisses totales (garder modérées)"],"it":["Carboidrati semplici","Grassi totali (mantenere moderati)"]}',
'{"carbs_pct":35,"protein_pct":40,"fat_pct":25}',
'{"es":["Preserva y aumenta masa muscular","Alta saciedad — reduce el hambre","Aumenta la termogénesis (quemas más calorías)","Favorece la pérdida de grasa preservando músculo"],"en":["Preserves and builds muscle mass","High satiety — reduces hunger","Increases thermogenesis (burns more calories)","Promotes fat loss while preserving muscle"],"fr":["Préserve et développe la masse musculaire","Satiété élevée — réduit la faim","Augmente la thermogenèse","Favorise la perte de graisse en préservant le muscle"],"it":["Preserva e aumenta la massa muscolare","Alta sazietà — riduce la fame","Aumenta la termogenesi","Favorisce la perdita di grasso preservando il muscolo"]}',
'{"es":["No recomendable con enfermedad renal","Puede aumentar la carga renal a largo plazo","Asegurar hidratación adecuada"],"en":["Not recommended with kidney disease","May increase renal load long-term","Ensure adequate hydration"],"fr":["Non recommandée en cas de maladie rénale","Peut augmenter la charge rénale à long terme","Assurer une hydratation adéquate"],"it":["Non raccomandata in caso di malattia renale","Può aumentare il carico renale a lungo termine","Assicurare un''adeguata idratazione"]}',
ARRAY['lose_weight','gain_muscle','maintain','performance'],
ARRAY['anemia','hypothyroid'],
ARRAY[]::text[],
'{"es":{"breakfast":["Tortilla de 3 huevos con claras y espinacas","Yogur griego 0% con frutos rojos"],"lunch":["150g pechuga de pollo a la plancha","Quinoa con verduras","Yogur"],"dinner":["150g merluza al horno con brócoli al vapor"],"snacks":["Queso fresco 0%","Puñado de edamame"]},"en":{"breakfast":["3-egg omelette with egg whites and spinach","0% Greek yoghurt with berries"],"lunch":["150g grilled chicken breast","Quinoa with vegetables","Yoghurt"],"dinner":["150g baked hake with steamed broccoli"],"snacks":["0% cottage cheese","Handful of edamame"]}}'
);

-- ── 14. DASH ─────────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'dash',14,'❤️','therapeutic',
'{"es":"DASH","en":"DASH","fr":"DASH","it":"DASH"}',
'{"es":"Dietary Approaches to Stop Hypertension. Diseñada para reducir la presión arterial. Rica en potasio, magnesio, calcio y baja en sodio.","en":"Dietary Approaches to Stop Hypertension. Designed to lower blood pressure. Rich in potassium, magnesium, calcium and low in sodium.","fr":"Dietary Approaches to Stop Hypertension. Conçue pour réduire la pression artérielle. Riche en potassium, magnésium, calcium et faible en sodium.","it":"Dietary Approaches to Stop Hypertension. Progettata per ridurre la pressione arteriosa. Ricca di potassio, magnesio, calcio e povera di sodio."}',
'{"es":["Frutas y verduras (8-10 raciones/día)","Cereales integrales","Lácteos desnatados o semidesnatados","Proteínas magras: pollo, pavo, pescado","Legumbres y frutos secos","Aceite de oliva","Hierbas aromáticas en lugar de sal"],"en":["Fruits and vegetables (8-10 servings/day)","Whole grains","Skimmed or semi-skimmed dairy","Lean proteins: chicken, turkey, fish","Legumes and nuts","Olive oil","Aromatic herbs instead of salt"],"fr":["Fruits et légumes (8-10 portions/jour)","Céréales complètes","Produits laitiers écrémés ou demi-écrémés","Protéines maigres: poulet, dinde, poisson","Légumineuses et noix","Huile d''olive","Herbes aromatiques à la place du sel"],"it":["Frutta e verdura (8-10 porzioni/giorno)","Cereali integrali","Latticini scremati o semi-scremati","Proteine magre: pollo, tacchino, pesce","Legumi e frutta secca","Olio d''oliva","Erbe aromatiche al posto del sale"]}',
'{"es":["Sal (máx. 1.5-2.3g sodio/día)","Carnes rojas y procesadas","Grasas saturadas y trans","Dulces y bebidas azucaradas","Alcohol"],"en":["Salt (max 1.5-2.3g sodium/day)","Red and processed meats","Saturated and trans fats","Sweets and sugary drinks","Alcohol"],"fr":["Sel (max 1,5-2,3g sodium/jour)","Viandes rouges et transformées","Graisses saturées et trans","Sucreries et boissons sucrées","Alcool"],"it":["Sale (max 1,5-2,3g sodio/giorno)","Carni rosse e trasformate","Grassi saturi e trans","Dolci e bevande zuccherate","Alcol"]}',
'{"es":["Carnes rojas (máx. 1×/semana)","Cafeína (monitorizar efecto en tensión)"],"en":["Red meat (max 1×/week)","Caffeine (monitor effect on blood pressure)"],"fr":["Viande rouge (max 1×/semaine)","Caféine (surveiller l''effet sur la tension)"],"it":["Carne rossa (max 1×/settimana)","Caffeina (monitorare l''effetto sulla pressione)"]}',
'{"carbs_pct":55,"protein_pct":18,"fat_pct":27}',
'{"es":["Reduce la presión sistólica hasta 11 mmHg","Reduce riesgo de ACV y enfermedades cardíacas","Mejora perfil lipídico","Puede ayudar en diabetes tipo 2"],"en":["Reduces systolic blood pressure by up to 11 mmHg","Reduces risk of stroke and heart disease","Improves lipid profile","May help in type 2 diabetes"],"fr":["Réduit la pression systolique jusqu''à 11 mmHg","Réduit le risque d''AVC et de maladies cardiaques","Améliore le profil lipidique","Peut aider dans le diabète type 2"],"it":["Riduce la pressione sistolica fino a 11 mmHg","Riduce il rischio di ictus e malattie cardiache","Migliora il profilo lipidico","Può aiutare nel diabete tipo 2"]}',
'{"es":["Puede ser difícil con dietas altas en sodio previas","Requiere etiquetar y medir el sodio inicialmente"],"en":["Can be difficult after high-sodium diets","Requires labelling and measuring sodium initially"],"fr":["Peut être difficile après des régimes riches en sodium","Nécessite de vérifier et mesurer le sodium initialement"],"it":["Può essere difficile dopo diete ricche di sodio","Richiede di controllare e misurare il sodio inizialmente"]}',
ARRAY['lose_weight','maintain','energy'],
ARRAY['hypertension','type2_diabetes'],
ARRAY[]::text[],
'{"es":{"breakfast":["Avena con leche desnatada y frutos rojos","Zumo de naranja natural"],"lunch":["Pechuga de pollo con arroz integral y brócoli","Aliñado con aceite y limón (sin sal)"],"dinner":["Merluza al vapor con patata y ensalada verde"],"snacks":["Yogur desnatado","Fruta"]},"en":{"breakfast":["Oats with skimmed milk and berries","Fresh orange juice"],"lunch":["Chicken breast with brown rice and broccoli","Dressed with oil and lemon (no salt)"],"dinner":["Steamed hake with potato and green salad"],"snacks":["Low-fat yoghurt","Fruit"]}}'
);

-- ── 15-18. AYUNOS ────────────────────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,avoid_for_conditions,allergen_free,fasting_window,sample_day)
VALUES
(
'fasting_16_8',15,'⏰','fasting',
'{"es":"Ayuno 16:8","en":"16:8 Fasting","fr":"Jeûne 16:8","it":"Digiuno 16:8"}',
'{"es":"Ayuno intermitente donde se come en una ventana de 8 horas y se ayuna 16 horas. El protocolo más popular y el más fácil de mantener.","en":"Intermittent fasting with an 8-hour eating window and 16-hour fast. The most popular and easiest to maintain.","fr":"Jeûne intermittent avec une fenêtre alimentaire de 8 heures et un jeûne de 16 heures. Le protocole le plus populaire.","it":"Digiuno intermittente con finestra alimentare di 8 ore e digiuno di 16 ore. Il protocollo più popolare."}',
'{"es":["Cualquier alimento equilibrado durante la ventana","Agua, café y té sin azúcar (durante el ayuno)","Comidas nutritivas y saciantes"],"en":["Any balanced food during the window","Water, coffee and unsweetened tea (during fast)","Nutritious and satiating meals"],"fr":["Tout aliment équilibré pendant la fenêtre","Eau, café et thé sans sucre (pendant le jeûne)","Repas nutritifs et rassasiants"],"it":["Qualsiasi alimento equilibrato durante la finestra","Acqua, caffè e tè senza zucchero (durante il digiuno)","Pasti nutrienti e sazianti"]}',
'{"es":["Alimentos durante las horas de ayuno","Bebidas calóricas en el ayuno (batidos, zumos)"],"en":["Food during fasting hours","Caloric drinks during fast (smoothies, juices)"],"fr":["Nourriture pendant les heures de jeûne","Boissons caloriques pendant le jeûne"],"it":["Cibo durante le ore di digiuno","Bevande caloriche durante il digiuno"]}',
'{"es":["Cafeína en exceso (puede aumentar cortisol)"],"en":["Excess caffeine (may raise cortisol)"],"fr":["Excès de caféine (peut augmenter le cortisol)"],"it":["Caffeina in eccesso (può aumentare il cortisolo)"]}',
'{"carbs_pct":45,"protein_pct":25,"fat_pct":30}',
'{"es":["Facilita déficit calórico de forma natural","Mejora sensibilidad a la insulina","Autofagia celular (limpieza celular)","Simplicidad: sin contar calorías"],"en":["Facilitates natural caloric deficit","Improves insulin sensitivity","Cellular autophagy (cellular cleaning)","Simplicity: no calorie counting"],"fr":["Facilite un déficit calorique naturel","Améliore la sensibilité à l''insuline","Autophagie cellulaire (nettoyage cellulaire)","Simplicité: pas de comptage de calories"],"it":["Facilita un deficit calorico naturale","Migliora la sensibilità all''insulina","Autofagia cellulare (pulizia cellulare)","Semplicità: senza contare le calorie"]}',
'{"es":["Puede alterar el ciclo menstrual si es muy restrictivo","No recomendable en embarazo, lactancia o TCA","Posible irritabilidad y fatiga inicial","Evitar en fase menstrual (si hay síntomas)"],"en":["Can disrupt menstrual cycle if too restrictive","Not recommended during pregnancy, breastfeeding or eating disorders","Possible irritability and initial fatigue","Avoid during menstrual phase (if symptomatic)"],"fr":["Peut perturber le cycle menstruel si très restrictif","Non recommandé pendant la grossesse, l''allaitement ou TCA","Irritabilité et fatigue initiales possibles","Éviter en phase menstruelle (si symptomatique)"],"it":["Può alterare il ciclo mestruale se molto restrittivo","Non raccomandato in gravidanza, allattamento o DCA","Possibile irritabilità e stanchezza iniziale","Evitare in fase mestruale (se sintomatica)"]}',
ARRAY['lose_weight','maintain'],ARRAY['type2_diabetes','pcos'],ARRAY['pregnant','postpartum'],ARRAY[]::text[],
'{"eating_hours":8,"fasting_hours":16,"example_window":"12:00-20:00"}',
'{"es":{"breakfast":["(Se omite o se toma solo café/té)"],"lunch":["Primera comida a las 12:00: bowl de proteína con verduras y arroz integral"],"dinner":["Última comida antes de las 20:00: salmón con ensalada"],"snacks":["Fruta o frutos secos dentro de la ventana"]},"en":{"breakfast":["(Skipped or coffee/tea only)"],"lunch":["First meal at 12:00: protein bowl with vegetables and brown rice"],"dinner":["Last meal before 20:00: salmon with salad"],"snacks":["Fruit or nuts within the window"]}}'
),
(
'fasting_18_6',16,'⏱️','fasting',
'{"es":"Ayuno 18:6","en":"18:6 Fasting","fr":"Jeûne 18:6","it":"Digiuno 18:6"}',
'{"es":"Variante más estricta del ayuno intermitente: 18 horas de ayuno y 6 horas de ventana alimentaria. Mayor efecto sobre la autofagia.","en":"Stricter variant of intermittent fasting: 18 hours fasting and 6-hour eating window. Greater effect on autophagy.","fr":"Variante plus stricte du jeûne intermittent: 18 heures de jeûne et fenêtre de 6 heures. Plus grand effet sur l''autophagie.","it":"Variante più rigorosa del digiuno intermittente: 18 ore di digiuno e finestra di 6 ore. Maggiore effetto sull''autofagia."}',
'{"es":["Cualquier alimento nutritivo durante las 6 horas","Agua, café y té sin azúcar en el ayuno","Electrolitos (sodio, potasio, magnesio)"],"en":["Any nutritious food during the 6 hours","Water, coffee and unsweetened tea during fast","Electrolytes (sodium, potassium, magnesium)"],"fr":["Tout aliment nutritif pendant les 6 heures","Eau, café et thé sans sucre pendant le jeûne","Électrolytes (sodium, potassium, magnésium)"],"it":["Qualsiasi alimento nutriente durante le 6 ore","Acqua, caffè e tè senza zucchero durante il digiuno","Elettroliti (sodio, potassio, magnesio)"]}',
'{"es":["Comida fuera de la ventana","Bebidas calóricas en el ayuno"],"en":["Food outside the window","Caloric drinks during fast"],"fr":["Nourriture hors de la fenêtre","Boissons caloriques pendant le jeûne"],"it":["Cibo fuori dalla finestra","Bevande caloriche durante il digiuno"]}',
'{"es":["Cafeína en exceso"],"en":["Excess caffeine"],"fr":["Excès de caféine"],"it":["Caffeina in eccesso"]}',
'{"carbs_pct":40,"protein_pct":30,"fat_pct":30}',
'{"es":["Mayor autofagia que el 16:8","Más eficaz para pérdida de grasa","Mejora sensibilidad insulínica marcada"],"en":["Greater autophagy than 16:8","More effective for fat loss","Marked insulin sensitivity improvement"],"fr":["Plus d''autophagie que le 16:8","Plus efficace pour la perte de graisse","Amélioration marquée de la sensibilité à l''insuline"],"it":["Maggiore autofagia del 16:8","Più efficace per la perdita di grasso","Marcato miglioramento della sensibilità insulinica"]}',
'{"es":["Mayor riesgo de alterar el ciclo menstrual","Difícil de mantener socialmente","No recomendable más de 3 días/semana para mujeres activas"],"en":["Higher risk of disrupting menstrual cycle","Difficult to maintain socially","Not recommended more than 3 days/week for active women"],"fr":["Risque plus élevé de perturber le cycle menstruel","Difficile à maintenir socialement","Non recommandé plus de 3 jours/semaine pour les femmes actives"],"it":["Rischio più elevato di alterare il ciclo mestruale","Difficile da mantenere socialmente","Non raccomandato più di 3 giorni/settimana per le donne attive"]}',
ARRAY['lose_weight'],ARRAY['pcos','type2_diabetes'],ARRAY['pregnant','postpartum'],ARRAY[]::text[],
'{"eating_hours":6,"fasting_hours":18,"example_window":"13:00-19:00"}',
'{"es":{"breakfast":["(Ayuno: solo agua, café o té)"],"lunch":["Primera comida 13:00: ensalada de pollo, aguacate y quinoa"],"dinner":["Última comida 19:00: merluza con verduras al vapor"],"snacks":["Frutos secos o yogur griego dentro de la ventana"]},"en":{"breakfast":["(Fasting: water, coffee or tea only)"],"lunch":["First meal 13:00: chicken, avocado and quinoa salad"],"dinner":["Last meal 19:00: hake with steamed vegetables"],"snacks":["Nuts or Greek yoghurt within the window"]}}'
),
(
'fasting_5_2',17,'📅','fasting',
'{"es":"Ayuno 5:2","en":"5:2 Fasting","fr":"Jeûne 5:2","it":"Digiuno 5:2"}',
'{"es":"5 días con alimentación normal y 2 días no consecutivos con ingesta muy reducida (500 kcal mujeres / 600 kcal hombres).","en":"5 days of normal eating and 2 non-consecutive days with very reduced intake (500 kcal women / 600 kcal men).","fr":"5 jours d''alimentation normale et 2 jours non consécutifs avec une ingestion très réduite (500 kcal femmes).","it":"5 giorni di alimentazione normale e 2 giorni non consecutivi con apporto molto ridotto (500 kcal donne)."}',
'{"es":["Días normales: cualquier alimento equilibrado","Días de ayuno: proteínas magras, verduras, caldos","Agua, café y té sin límite"],"en":["Normal days: any balanced food","Fast days: lean proteins, vegetables, broths","Water, coffee and tea unlimited"],"fr":["Jours normaux: tout aliment équilibré","Jours de jeûne: protéines maigres, légumes, bouillons","Eau, café et thé à volonté"],"it":["Giorni normali: qualsiasi alimento equilibrato","Giorni di digiuno: proteine magre, verdura, brodi","Acqua, caffè e tè illimitati"]}',
'{"es":["Más de 500 kcal en días de ayuno","Alimentos muy calóricos en días de ayuno"],"en":["More than 500 kcal on fast days","Very calorie-dense foods on fast days"],"fr":["Plus de 500 kcal les jours de jeûne","Aliments très caloriques les jours de jeûne"],"it":["Più di 500 kcal nei giorni di digiuno","Alimenti molto calorici nei giorni di digiuno"]}',
'{"es":["Alcohol (especialmente días de ayuno)"],"en":["Alcohol (especially on fast days)"],"fr":["Alcool (surtout les jours de jeûne)"],"it":["Alcol (soprattutto nei giorni di digiuno)"]}',
'{"carbs_pct":45,"protein_pct":25,"fat_pct":30}',
'{"es":["Eficaz para pérdida de peso a largo plazo","Mayor flexibilidad que el ayuno diario","Beneficios metabólicos sin ayuno diario"],"en":["Effective for long-term weight loss","Greater flexibility than daily fasting","Metabolic benefits without daily fasting"],"fr":["Efficace pour la perte de poids à long terme","Plus de flexibilité que le jeûne quotidien","Bénéfices métaboliques sans jeûne quotidien"],"it":["Efficace per la perdita di peso a lungo termine","Maggiore flessibilità del digiuno quotidiano","Benefici metabolici senza digiuno quotidiano"]}',
'{"es":["Los 2 días de ayuno pueden coincidir con fases difíciles del ciclo","Evitar en fase menstrual o lútea tardía","No apto para embarazo ni TCA"],"en":["The 2 fast days may coincide with difficult cycle phases","Avoid during menstrual or late luteal phase","Not suitable for pregnancy or eating disorders"],"fr":["Les 2 jours de jeûne peuvent coïncider avec des phases difficiles du cycle","Éviter pendant la phase menstruelle ou lutéale tardive","Non adapté à la grossesse ou aux TCA"],"it":["I 2 giorni di digiuno possono coincidere con fasi difficili del ciclo","Evitare in fase mestruale o lutea tardiva","Non adatto alla gravidanza o ai DCA"]}',
ARRAY['lose_weight','maintain'],ARRAY['type2_diabetes'],ARRAY['pregnant','postpartum'],ARRAY[]::text[],
'{"eating_days":5,"fast_days":2,"fast_day_kcal_women":500,"fast_day_kcal_men":600}',
'{"es":{"breakfast":["Día normal: yogur con fruta y avena","Día ayuno: café solo o té"],"lunch":["Día normal: menú completo equilibrado","Día ayuno: sopa de verduras (150 kcal) + pechuga de pollo (200 kcal)"],"dinner":["Día normal: cena completa","Día ayuno: ensalada con huevo cocido (150 kcal)"],"snacks":["Día normal: fruta o frutos secos","Día ayuno: ninguno"]},"en":{"breakfast":["Normal day: yoghurt with fruit and oats","Fast day: black coffee or tea"],"lunch":["Normal day: full balanced meal","Fast day: vegetable soup (150 kcal) + chicken breast (200 kcal)"],"dinner":["Normal day: full dinner","Fast day: salad with boiled egg (150 kcal)"],"snacks":["Normal day: fruit or nuts","Fast day: none"]}}'
),
(
'omad',18,'🍽️','fasting',
'{"es":"OMAD (1 comida al día)","en":"OMAD (one meal a day)","fr":"OMAD (un repas par jour)","it":"OMAD (un pasto al giorno)"}',
'{"es":"Ayuno extremo: se consume toda la ingesta calórica del día en una única comida. Ventana de ayuno de ~23 horas.","en":"Extreme fasting: all daily caloric intake consumed in one single meal. ~23-hour fasting window.","fr":"Jeûne extrême: tout l''apport calorique quotidien est consommé en un seul repas. Fenêtre de jeûne de ~23 heures.","it":"Digiuno estremo: tutto l''apporto calorico giornaliero viene consumato in un unico pasto. Finestra di digiuno di ~23 ore."}',
'{"es":["Una comida completa y densa en nutrientes","Agua, electrolitos, café y té en el ayuno","Caldo de huesos (permitido por algunos)"],"en":["One complete and nutrient-dense meal","Water, electrolytes, coffee and tea during fast","Bone broth (allowed by some)"],"fr":["Un repas complet et dense en nutriments","Eau, électrolytes, café et thé pendant le jeûne","Bouillon d''os (autorisé par certains)"],"it":["Un pasto completo e denso di nutrienti","Acqua, elettroliti, caffè e tè durante il digiuno","Brodo di ossa (consentito da alcuni)"]}',
'{"es":["Cualquier alimento fuera de la comida única"],"en":["Any food outside the single meal"],"fr":["Tout aliment en dehors du repas unique"],"it":["Qualsiasi alimento fuori dal pasto unico"]}',
'{"es":["No aplica (toda la comida en una sola vez)"],"en":["Not applicable (all food in one sitting)"],"fr":["Non applicable (tout en un repas)"],"it":["Non applicabile (tutto in un unico pasto)"]}',
'{"carbs_pct":40,"protein_pct":30,"fat_pct":30}',
'{"es":["Máxima simplicidad","Posible pérdida de peso acelerada","Mayor autofagia"],"en":["Maximum simplicity","Possible accelerated weight loss","Greater autophagy"],"fr":["Simplicité maximale","Perte de poids potentiellement accélérée","Autophagie accrue"],"it":["Massima semplicità","Possibile rapida perdita di peso","Maggiore autofagia"]}',
'{"es":["Alto riesgo de alterar el ciclo menstrual","No recomendable para mujeres en general sin supervisión médica","Difícil cubrir necesidades nutricionales","Puede provocar TCA","No apto para deportistas"],"en":["High risk of disrupting menstrual cycle","Not recommended for women in general without medical supervision","Difficult to meet nutritional needs","Can trigger eating disorders","Not suitable for athletes"],"fr":["Risque élevé de perturber le cycle menstruel","Non recommandé pour les femmes en général sans suivi médical","Difficile de couvrir les besoins nutritionnels","Peut déclencher des TCA","Non adapté aux sportives"],"it":["Alto rischio di alterare il ciclo mestruale","Non raccomandato per le donne in generale senza supervisione medica","Difficile coprire i fabbisogni nutrizionali","Può provocare DCA","Non adatto alle sportive"]}',
ARRAY['lose_weight'],ARRAY[]::text[],ARRAY['pregnant','postpartum','teen','perimenopause'],ARRAY[]::text[],
'{"eating_hours":1,"fasting_hours":23}',
'{"es":{"breakfast":["(Ayuno total)"],"lunch":["(Ayuno total)"],"dinner":["Única comida del día: 200g carne o pescado + 2 tazas de verduras + 1 ración de carbohidrato complejo + grasa saludable + fruta"],"snacks":["(No aplica)"]},"en":{"breakfast":["(Total fast)"],"lunch":["(Total fast)"],"dinner":["Single daily meal: 200g meat or fish + 2 cups vegetables + 1 serving complex carb + healthy fat + fruit"],"snacks":["(Not applicable)"]}}'
);

-- ── 19. ALIMENTACIÓN INTUITIVA ───────────────────────────────────────────────
INSERT INTO diets (id,display_order,icon,category,name,description,allowed_foods,forbidden_foods,limited_foods,macros,benefits,warnings,compatible_goals,good_for_conditions,allergen_free,sample_day)
VALUES (
'intuitive_eating',19,'🧠','mindful',
'{"es":"Alimentación intuitiva","en":"Intuitive eating","fr":"Alimentation intuitive","it":"Alimentazione intuitiva"}',
'{"es":"Enfoque no restrictivo basado en escuchar las señales de hambre y saciedad del cuerpo. Rechaza la cultura de las dietas. Basado en 10 principios desarrollados por Tribole y Resch.","en":"Non-restrictive approach based on listening to the body''s hunger and satiety signals. Rejects diet culture. Based on 10 principles by Tribole and Resch.","fr":"Approche non restrictive basée sur l''écoute des signaux de faim et de satiété du corps. Rejette la culture des régimes.","it":"Approccio non restrittivo basato sull''ascolto dei segnali di fame e sazietà del corpo. Rifiuta la cultura delle diete."}',
'{"es":["Todos los alimentos sin restricciones","Comer cuando se tiene hambre, parar al saciarse","Honrar el cuerpo con nutrición","No clasificar alimentos como ''buenos'' o ''malos''","Movimiento intuitivo (disfrutar el ejercicio)"],"en":["All foods without restrictions","Eat when hungry, stop when satisfied","Honour body with nutrition","Do not classify foods as ''good'' or ''bad''","Intuitive movement (enjoy exercise)"],"fr":["Tous les aliments sans restrictions","Manger quand on a faim, s''arrêter quand on est rassasiée","Honorer le corps avec la nutrition","Ne pas classer les aliments comme ''bons'' ou ''mauvais''","Mouvement intuitif (apprécier l''exercice)"],"it":["Tutti gli alimenti senza restrizioni","Mangiare quando si ha fame, fermarsi alla sazietà","Onorare il corpo con la nutrizione","Non classificare i cibi come ''buoni'' o ''cattivi''","Movimento intuitivo (godere dell''esercizio)"]}',
'{"es":["Ningún alimento está prohibido (ese es el principio)"],"en":["No food is forbidden (that is the principle)"],"fr":["Aucun aliment n''est interdit (c''est le principe)"],"it":["Nessun alimento è vietato (questo è il principio)"]}',
'{"es":["No aplica — no hay restricciones ni límites"],"en":["Not applicable — no restrictions or limits"],"fr":["Non applicable — pas de restrictions ni de limites"],"it":["Non applicabile — nessuna restrizione o limite"]}',
NULL,
'{"es":["Mejora la relación con la comida","Reduce comportamientos de atracón","Disminuye el estrés relacionado con comer","Mejora la autoestima y la imagen corporal","Evidencia creciente en salud mental y metabólica"],"en":["Improves relationship with food","Reduces binge-eating behaviours","Decreases eating-related stress","Improves self-esteem and body image","Growing evidence in mental and metabolic health"],"fr":["Améliore la relation à la nourriture","Réduit les comportements de frénésie alimentaire","Diminue le stress lié à l''alimentation","Améliore l''estime de soi et l''image corporelle","Preuves croissantes en santé mentale et métabolique"],"it":["Migliora il rapporto con il cibo","Riduce i comportamenti di abbuffata","Diminuisce lo stress legato al cibo","Migliora l''autostima e l''immagine corporea","Evidenze crescenti in salute mentale e metabolica"]}',
'{"es":["No es adecuada si hay objetivos de rendimiento deportivo específicos","Requiere trabajo interno con un profesional de salud mental","Puede no ser adecuada en diabetes donde hay que contar carbohidratos"],"en":["Not suitable if there are specific sports performance goals","Requires internal work with a mental health professional","May not be suitable in diabetes where carbohydrate counting is necessary"],"fr":["Non adaptée si des objectifs de performance sportive spécifiques sont visés","Nécessite un travail interne avec un professionnel de santé mentale","Peut ne pas convenir au diabète où le comptage des glucides est nécessaire"],"it":["Non adatta se ci sono obiettivi specifici di performance sportiva","Richiede lavoro interno con un professionista della salute mentale","Potrebbe non essere adatta nel diabete dove è necessario contare i carboidrati"]}',
ARRAY['maintain','energy'],
ARRAY[]::text[],
ARRAY[]::text[],
NULL
);

-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFICACIÓN FINAL
-- ═══════════════════════════════════════════════════════════════════════════
SELECT id, display_order, icon, category, name->>'es' AS nombre_es,
       array_length(compatible_goals,1) AS n_goals,
       array_length(good_for_conditions,1) AS n_conditions
FROM diets
ORDER BY display_order;
